### ISSUE TITLE
FR: implement popen / pclose

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#102]
As documented for [`_popen`][1] / [popen][2] I've included `<stdio.h>` and used the `popen` function.
Compilation is fine - linking raises an error (both with and without `#define popen _popen`): 

~~~
;============ Linking ============
Error: Undefined External DllMain in module .\c0dpe.nas
Error: Undefined External pclose in module C:\dev\gnucobol\libcob\termio.c
Error: Undefined External popen in module C:\dev\gnucobol\libcob\termio.c
~~~

Are `popen`/`pclose` not implemented (yet)?
Should I add an additional library to link stage (both docs say the definition is found in the standard libraries)?

Additional question: How can I remove the try to link against `DllMain`?

[1]:https://msdn.microsoft.com/en-us/library/96ayss4b.aspx
[2]:https://linux.die.net/man/3/popen

**Comment by LADSoft** [comment]
the fact that Orange C didn't have these has actually annoyed me from time to time, now you've given me an excuse to implement :)

**Comment by LADSoft** [comment]
oh the DllMain thing, you've used a compiler or linker switch that invokes it I guess.   In reference to another of your comments the compiler already uses /W to figure out which assemblies to use, and which version of the runtime library.   The default is /Wc (console with static libs) but I guess you have a makefile that specifies /Wd, which would mean create a dll.

**Comment by GitMensch** [comment]
Please directly change the internal version number (leading to a new testable __ORANGEC__ number) when implementing popen/pclose.

**Comment by LADSoft** [comment]
the next push will have popen/pclose.   I've bumped the build # to '2'

**Comment by GitMensch** [comment]
I currently cannot test the resulting binaries, but at least popen can be compiled (header) and referenced (linker). As it is included in the changelist for the last version I'm close this.

**Comment by GitMensch** [comment]
@LADSoft seems the definition in stdio.h is missing.

**Comment by LADSoft** [comment]
I'm not sure what happened here.   I've added it back to the headers.

**Comment by GitMensch** [comment]
I see it in the headers now, do you have an idea why "browse to definition" works on fwrite but not on pclose?

**Comment by GitMensch** [comment]
I had done a "Build->Rebuild all..." - shouldn't this be enough?

**Comment by GitMensch** [comment]
... actually I remember that on a rebuild the warning #179 occurred - I guess there may be some cleanup steps not done correctly ?!?

**Comment by LADSoft** [comment]
yeah if obrc cannot process the files it won't update...  I'm not sure why it can't process the files though, I've never seen that.   Will see if I can duplicate later..

**Comment by GitMensch** [comment]
The point was: "rebuild all" should first do a "cleanup" of all projects (which I actually miss under "Build" menu and context menu of the projects) and build afterwards - there should no reason that anything is still there...
