### ISSUE TITLE
IDE program not properly installed in new install of v67.3.1 on Windows 10 as current user

### ISSUE THREAD

**Issue by wesinator** [LADSoft/OrangeC#1020]
I installed a new install as a user install on Windows 10 x64 22H2 from `WindowsInstaller6738.exe`.

It seems the install did not correctly install `ocide.exe`
When run the IDE was checked on the installer, it showed this error.
![install 6738 windows 10 error](https://github.com/LADSoft/OrangeC/assets/5124946/7bb50d5e-7165-40b8-9ab9-f21d3f750001)

the start shortcuts are dead, because `ocide.exe` is missing from `bin/` directory.

**Workaround:** manually extract the prog from https://github.com/LADSoft/OCIDE

**Comment by GitMensch** [comment]
Are those shortcuts new? As OCIDE is "archaic" and was explicit split out of OrangeC (both in the repository and in the binaries), it is expected that it isn't there.
It would be an error if the installer still creates a shortcut.

**Comment by wesinator** [comment]
yes, the installer creates the shortcut and start menu entry for ocide

**Comment by GitMensch** [comment]
Hm, which commit dropped OCIDE from the installer?
