### ISSUE TITLE
Segfault during Lua compilation

### ISSUE THREAD

**Issue by alvoskov** [LADSoft/OrangeC#1025]
Attempt to compile Lua 5.4.4 by OCC compiler 6.73.8 failed:
https://www.lua.org/ftp/lua-5.4.4.tar.gz

<code>
C:\C_PROG\lua_occ>occ lcode.c -c -o lcode.obj
occ (OrangeC) Version 6.73.8
Copyright (C) LADSoft 2006-2021

Access Violation:(c:\c_prog\occ\bin\occopt.exe)
CS:EIP 0023:0049AEC5  SS:ESP 002B:0019F9E0
EAX: 00000748  EBX: 02D30FC0  ECX: 00CBE0B8  EDX: 0019FBB4  flags: 00010206
EBP: 0019FA2C  ESI: 02D30FE4  EDI: 0019FBB4
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

CS:EIP  89 08 C7 45 CC 01 00 00 00 64 8B 0D 00 00 00 00

Stack trace:
                        49aec5
                        499b56
                        499066
                        40140b
                        45c077
</code>

**Comment by LADSoft** [comment]
thanks for the bug report.    I will check in a fix for this later tonite.
