### ISSUE TITLE
Please fix your read the docs site

### ISSUE THREAD

**Issue by iahunq2** [LADSoft/OrangeC#1036]
- The navbar is too big and overlaps with the content of the page.
- Clicking on any link will redirect to a 404 not found page.

This is not the fault of read the docs. There are beautiful read the docs sites. For example:

https://pybind11.readthedocs.io/en/stable/

**Comment by GitMensch** [comment]
Please send a pull request to fix that.

Am 19. Mai 2024 10:21:27 MESZ schrieb iahunq2 ***@***.***>:

**Comment by LADSoft** [comment]
it is more broken than just a bad header.    Needs/has needed new configuration files to even be building....   I'll check it in in a bit...

**Comment by LADSoft** [comment]
the webhook was broken too...    it still isn't building, it gives some error code.   Says wait a while and try again so I guess I will come back to this tomorrow....
