### ISSUE TITLE
[Feature request]  Dlang frontend support

### ISSUE THREAD

**Issue by fithisux** [LADSoft/OrangeC#1052]
Wishful thinking for an OrangeD compiler.

**Comment by chuggafan** [comment]
If someone wants to contribute one (and maintain it), I don't think I would
personally say no, but me and @LADSoft adding one? A definitive no.
I'd be more than happy to help with someone who wants to
contribute/maintain for sure however, esp. since I'm taking less work on
this project than I should be right now and I need to bring myself back
into the working on the compiler mindset.

**Comment by LADSoft** [comment]
@fithisux - 

i'm guessing a D frontend might not be much of a problem given we already have full C/C++ support, but, based on basically no knowledge I'm guessing that D has a large amount of runtime support.    It was kinda difficult getting a C runtime up and running, and I didn't even try writing a C++ runtime but rather resorted to using things available on the web.   But honestly, given that I don't have experience in D the chances of me writing an adequate runtime are small, even if I had time to do it...

I need to agree with @chuggafan, there is enough work to do on Orange C and it is going very slowly as is.   It has taken us a year to work out the support for the C++17 release and we still aren't quite there yet.    So I don't want to branch off into more frontends at this time....   but if you want to contribute your time we could certainly work with you to figure out the best way to leverage the C/C++ frontend to turn it into a D one....

**Comment by chuggafan** [comment]
I would assume what is being asked is closer to the way gcc and llvm do it:
Ignore us providing custom runtime support or even implementing the
frontend, the way all of the major non-DMD D compilers function is
basically take the DMD frontend, port it from using the Digital Mars C/C++
compiler backend and target it towards whatever compiler you're gluing it
to.
I still think that's a lot of effort when I'm still trying to figure out
what in the universe posix_spawn actually is demanding of me to use it.

**Comment by fithisux** [comment]
Thank you very much for the comments. I do not plan to take it up. Just asking in case it was something "easy".

**Comment by GitMensch** [comment]
Please re-close as unplanned, not as completed :-)
