### ISSUE TITLE
ORC cannot create an output file.

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#1057]
In order to output a file in orc, the following logic is run in rcMain.cpp:
```cpp
    auto files = ToolChain::StandardToolStartup(SwitchParser, argc, argv, usageText, helpText);
    if (files.size() < 2)
        ToolChain::Usage(usageText);
#ifndef HAVE_UNISTD_H
    int language = LANG_ENGLISH + (SUBLANG_ENGLISH_US << 10);
#else
    int language = 0;
#endif
    if (files.size() > 1 && !OutputFile.GetValue().empty())
        Utils::Fatal("Cannot specify output file for multiple input files");
```
If you notice: files.size() cannot *both* be less than 2, *AND* be equal to 1, meaning it is *literally* impossible to do:
`orc <file> /o<different_location_file.res>`
This is actually part of #603 because orc wasn't added as a resource compiler at the time, turns out, it's actually relatively simple to add too!
(Just need to set `CMAKE_RC_COMPILER` to `orc` and `enable_language(RC)` in the Windows-OrangeC.cmake section, then give a "compile object" command of `CMAKE_RC_COMPILE_OBJECT` in a file called `Windows-orc.cmake`, simple!)

**Comment by LADSoft** [comment]
oops will look at it soon....

I will write another issue about CMAKE, we need to update it anyway whenever the C++17 support is released....
