### ISSUE TITLE
ocide: FR to allow setting of working directory via file property window

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#106]
As noted in #79 the current working directory for the compiler is the project's folder.
It would be nice to be able to change this setting in the project's (or even file) property window.

**Comment by GitMensch** [comment]
This is already available on project level (General Properties->Configuration) and *may* or may not be added on the file property, too.

**Comment by LADSoft** [comment]
this feature is available both at the project level and at the workarea level.   I'm not sure what you mean by 'file' level though.

**Comment by LADSoft** [comment]
the property in the file window is meant for debugging support not compiling support...  I'm not sure if it would be confusing to use it for both...

**Comment by GitMensch** [comment]
This is what I see on file level:

![grafik](https://user-images.githubusercontent.com/6699539/40589677-0a8e2b76-61f2-11e8-8f27-6255e18a6972.png)

I don't see anything that is about "debugging support", there but I think you meant "the working directory in the property is for running the debugger and therefore only on project level" (which is reasonable).

So... yes: I asked for the option to change the compiler working directory (on all levels: cwa, project, file) and yes, using one for both is not only confusing but actually wrong so this is about "include a *new* property 'compiler working directory'".

Side note: you may recognize the strange display (the first "panel" seems to be missing, I've seen it before but it is gone since some versions (or in CI builds in general)?

**Comment by LADSoft** [comment]
I'm mulling over the best way to do this and LADSoft/OCIDE#19.   Probably, I need another tab associated with individual files to put stuff on, that is divorced from specific file extensions.   That might also help with LADSoft/OCIDE#18.
