### ISSUE TITLE
errors with '/9' when using <math.h>

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#11]
Hello!
On the same project I'm working (as reference in issue 10), I step upon errors stating that these functions are not defined: sinf cosf fabsf
After some searching, I could find these are defined for C99. So I recompiled the complaining files with '/9' and got other errors:
Error    C:\apps\OrangeC\include\stdlib.h(421):  Syntax error: ; expected
Error    C:\apps\OrangeC\include\stdlib.h(446):  Syntax error: ; expected
Error    C:\apps\OrangeC\include\math.h(657):  Undefined symbol 'complex'
Error    C:\apps\OrangeC\include\math.h(658):  Undefined symbol '_complexl'

**Comment by LADSoft** [comment]
Hi lionfaith,

is this definitely a C program (not C++).  And what version of the 
compiler are you using?

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Source files are .cpp, but it's all written in C-style (no class, no templates, ...). Same errors arise with occ 5.24.0.1, occ 5.23.0.1 and occ 5.20.0.1.

**Comment by LADSoft** [comment]
Hi lionfaith,

The headers were ok when parsed in C mode, but there were some problems when the compiler was put in C++ mode.   I released a new version which should fix it.

David

**Comment by lionfaith** [comment]
Hi!
I've downloaded the new version and it compiles without complaining now.
Big thanks!
