### ISSUE TITLE
typedef'ed enums not considered integer expression

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#12]
Hello!
Sorry, yet another little bug. Or I suppose it is. AFAIK, in C, typedef'ing simply acts as aliasing. It show up with OCC 5.25, 5.24 and 5.23, both in .cpp and .c files.

This code compiles with /DSIMPLE, it doesn't otherwise.
```C
#include <stdio.h>

typedef enum {
	ENUM_TEST = 0,
	ENUM_LAST
} MyEnum;

int main( int* argc, char** argv ) {
	char keystate[350];
	
#if defined( SIMPLE )
	keystate[ENUM_TEST] = 1;
#else
	MyEnum e = ENUM_TEST;
	keystate[e] = 1; /* works if e is cast into int */
#endif

	printf( "%d", keystate[ENUM_TEST] );
    return 0;
}
```

**Comment by LADSoft** [comment]
hi lionfaith,

are you using the install package or compiling the compiler out of github?

Thanks,

David

**Comment by lionfaith** [comment]
Hello,
I use the zipped version, always.

**Comment by LADSoft** [comment]
Hi lionfaith,

I was able to duplicate the problem but won't have a release for a 
couple more days.

David
lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
no problem, you're so fast already! :)

Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

well I used to do one day turnarounds...   I've gotten a little more 
laid back!   I put up a new version...

David
lionfaith wrote:

**Comment by lionfaith** [comment]
It's working fine now, thanks!
