### ISSUE TITLE
FR ocide: allow to view the full build

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#121]
Currently there is a build output, but this only shows the result - not the tools and command line options called.

This FR is about adding these for being able to inspect them (maybe as "Select information to view: Complete Build").

**Comment by GitMensch** [comment]
It looks like Detailbuild is not available in the GUI part - is it?

**Comment by LADSoft** [comment]
at one point I lost a couple of changes...   I thought I had gotten everything back but apparently this is missing still.   I will reopen...

**Comment by LADSoft** [comment]
it seems to be there, here is a screen shot:
![detail](https://user-images.githubusercontent.com/4514849/40264961-c2f952c8-5afc-11e8-95af-6184a2de7763.png)

please verify if you don't see it.  I will leave this open in the meantime.

**Comment by GitMensch** [comment]
OK, I see it, obviously searched in the wrong place.

But I'd still recommend to remove this from the project settings and add it as the third "information to view" in the dropdown instead:
![grafik](https://user-images.githubusercontent.com/6699539/40272973-0c551d74-5bb8-11e8-9483-1d903f48a175.png)

**Comment by GitMensch** [comment]
Another issue: with the current "full details":
![grafik](https://user-images.githubusercontent.com/6699539/40278650-7b7cb450-5c35-11e8-9c05-c378ad878ac1.png)
and a click on the first compiler warning of the file, the file cannot be opened:
![grafik](https://user-images.githubusercontent.com/6699539/40278652-98736f72-5c35-11e8-97a2-4a4931e2ac02.png)

It looks like OCIDE includes the include path from the command line, the second compiler message per file is in a separate line and can be opened as expected.

**Comment by LADSoft** [comment]
after I thought about this for a while I kinda liked it so I'm implementing.

BTW I appreciate you looking at the IDE especially, as I get little feedback on that.   But I like the issues you are raising in general!

**Comment by GitMensch** [comment]
Works fine, too.
