### ISSUE TITLE
issues with ocide + creating DLL

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#122]
~~~
;============ Building Project libcob ============
;============ Linking ============

Usage: dlpe [options] relfile

/f     remove underscore from exports
/mxxx          Set output file type
/oxxx          Set output file name
/sxxx          Set stub file name
/V, --version  Show version and date
/!             No logo

Available output file types:
   CON - Windows console (default)
   GUI - Windows GUI
   DLL - Windows DLL

Time: 20:31:18  Date: May  9 2018;============ Creating Browse information ============

Compile done.  Errors: 0,  Warnings: 0
~~~

.... I assume some setting is wrong?
The only settings I've set were the "Additional Libraries" I've added (before doing so I got the knows missing external references)

Expected result: output file (libcob.dll) and import library in output directory (none found)

**Comment by GitMensch** [comment]
Still getting the same note with current CI build :-(

libcob.dll is created.

[orangec_project_files.zip](https://github.com/LADSoft/OrangeC/files/2016026/orangec_project_files.zip) - intended to be placed under build_windows of GnuCOBOL 3.0 RC1, just in case you want to test this...

**Comment by LADSoft** [comment]
the problem was it was treating the .DEF files in the project as module definition files when they aren't.   I'm adding an explicit setting for module definition files...
