### ISSUE TITLE
implib/linking issues

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#123]
Steps to reproduce:

* download and unpack [binaries and sources (174 KB)](https://github.com/LADSoft/OrangeC/files/1998753/mpir_dll_gmp_l_sources.zip)
* use `oimplib /C gmp.l mpir.dll`
* compile the attached source with `occ -! -o conftest.exe conftest.c` --> expected result "Error: Undefined External __gmp_version"
* compile the attached source with `occ -! -o conftest.exe conftest.c -lgmp` --> expected result: conftest.exe created
* run conftest.exe: Windows error message: entry point "__gmp_version" not found in DLL conftest.exe" (expected result: nothing happens the version only should be printed when called with an argument like "conftest.exe test")

* if I rename mpir.dll Windows complains about the missing MPIR.DLL (= the dependency in general is in)
* checked with [depends](http://www.dependencywalker.com): mpir.dll has `__gmp_version`, but conftest.exe has it in the link to MPIR.DLL on ordinal 0000 where it isn't found
* gmp.l includes `CO201,023N,00E___gmp_version,000,008mpir.dll.` looks possibly correct

**Comment by LADSoft** [comment]
hm, strangely enough it is fine when I compile with another compiler, but you are right the version built with itself is broken.    I will fix it soon...

**Comment by LADSoft** [comment]
This did get fixed but it wasn't properly tagged.   The fix is here: a4add2f64e9465505981ec477fbc6cfe0881927f in the 'cpplookup.c' file.   Issue was the compiler was choosing a move constructor instead of a copy constructor in one place, which resulted in a string becoming empty prematurely.

**Comment by GitMensch** [comment]
@LADSoft Please reopen (or just point me to an error ;-).

I've checked with the test sample attached to the first post - works fine now (this uses a gmp 5.0.2 compatible mpir version from 2014, likely build with VC11).

Doing the same with a fresh compiled MPIR version (VC 2017) the oimplib part works, compiling and linking works, but the executable chrashes:

~~~
Access Violation:(X:\gnucobol\build_orange\mpir.exe)
CS:EIP 0023:004045A1  SS:ESP 002B:0019ED50
EAX: 00000005  EBX: 00000000  ECX: 6CEC4D34  EDX: 80808000  flags: 00010286
EBP: 0019FEE8  ESI: 6CEC4D34  EDI: 00000000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

[gmpver_test.zip](https://github.com/LADSoft/OrangeC/files/2022967/gmpver_test.zip)

**Comment by LADSoft** [comment]
i will get to this in a couple of days..
