### ISSUE TITLE
ocide: access violation when opening project properties

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#124]
~~~
---------------------------
Access Violation
---------------------------

Access Violation:(C:\dev\orangec\bin\ocide.exe)
CS:EIP 0023:004D3FD4  SS:ESP 002B:0019EF78
EAX: 00000000  EBX: 02D9E9E8  ECX: 0000002E  EDX: 08DFD0D4  flags: 00010246
EBP: 05386EC0  ESI: 00000000  EDI: 08DFCFB8
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

---------------------------
OK   
---------------------------
~~~

Happened after re-creating a complete work area with multiple projects - none saved :-(

**Comment by GitMensch** [comment]
The previous one was on a project, this time on the cwa (I was at least so "clever" to save the workarea first...)

~~~
---------------------------
Access Violation
---------------------------

Access Violation:(C:\dev\orangec\bin\ocide.exe)
CS:EIP 0023:004D3FD4  SS:ESP 002B:0019EF5C
EAX: 00000000  EBX: 02DCE9E8  ECX: 0000002E  EDX: 09CFD644  flags: 00010246
EBP: 09BCBA50  ESI: 00000000  EDI: 09CFD528
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

---------------------------
OK   
---------------------------
~~~

... and now on opening OCIDE (with default.cwa loaded first):

~~~
---------------------------
Access Violation
---------------------------

Access Violation:(C:\dev\orangec\bin\ocide.exe)
CS:EIP 0023:004D3FD4  SS:ESP 002B:0019E8C8
EAX: 00000000  EBX: 027BE9E8  ECX: 0000002E  EDX: 0802D554  flags: 00010246
EBP: 0019E980  ESI: 00000000  EDI: 0802D438
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

---------------------------
OK   
---------------------------
~~~

**Comment by LADSoft** [comment]
I found a problem that seems to fit the crash dump you gave; basically if you put a file in the project that doesn't have any extension, then try to open the properties window, it will crash.   Most likely saving such a project then reloading it will also cause a crash.   Before I mark this as completed I wanted to see if that is something you might have done?   So I know whether to go looking further...

**Comment by GitMensch** [comment]
I've placed a ChangeLog file into all projects and bision + flex (which will need external tools to generate C files first) into one.

**Comment by GitMensch** [comment]
Just to leave these here, that is the current version (may not be complete, can't check because of the crashing issue) of the project files, intended to be placed in a GnuCOBOL 3.0 RC1 windows source distribution under "build_windows\orangec" [orangec_project_files.zip](https://github.com/LADSoft/OrangeC/files/2012071/orangec_project_files.zip) with the following used as "[build_windows\config.h](https://github.com/LADSoft/OrangeC/files/2012084/config.h.txt)"
