### ISSUE TITLE
ocide: add command line options and documenting these

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#127]
To work around #124 I wanted to start using another cwa - but just starting `ocide.exe X:\path\to.cwa` did not load the file instead of default.cwa.

I've seen the version switch being implemented but other than that nothing.
Command line options for the following parts would be good:

* path to cwa: start with this, instead of default.cwa
* path to file: open this file after loading the cwa
* `/?` / `--help` some useful message where to find help - or opening it
* option to start with an empty workspace, maybe `--empty-workspace`?

Possible command line to process:
`ocide.exe x:\path\to\some.cwa y:\path\to\file1.c "y:\path to file2.h"`

**Comment by LADSoft** [comment]
:)   I will get to this soon but meanwhile if you specify a file (or a list of files) it will open them.   There are also two switches, '/p' opens a project and '/w' opens a workspace.   Good idea to have a 'create workspace' option and a help option and of course will update the docs...
