### ISSUE TITLE
compiling .exe from another directory doesn't work

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#13]
Having an arborescence:
```
project
project\app
project\src
project\src\test.c
```
Going to project\app and launching occ (v5.27, zipped) from there:
```Batchfile
C:\dev\project\app> occ ..\src\test.c
```
Gives the error:
```Batchfile
occ Version 5.27.0.1 Copyright (C) LADSoft 2006-2015

olink Version 5.27.0.1 Copyright (C) LADSoft 2006-2015
Error: Input file '..\src\\test.O' does not exist.
Error: Undefined External main in module .\c0xpe.nas
        2 Errors, 0 Warnings
        Errors encountered, not creating output file
```

But if I compile project\src\test.c directly in its directory:
```Batchfile
C:\dev\project\src> occ test.c
```
(it obviously works well) and then rebuild as above:
```Batchfile
C:\dev\project\app> occ ..\src\test.c
```
It now works excepted that:
the new test.o is in project\app and the old one in project\src is not updated, and the new test.exe, test.rel, test.map are all in project\src replacing the old ones.

**Comment by LADSoft** [comment]
Hi lionfaith,

I think the the usual behavior would be to put both the .o and .exe file 
in the current directory instead of in the path you get the source 
from....   I will fix it.

David

**Comment by LADSoft** [comment]
Hi lionfaith,

I put up a new version which fixes it.

David

**Comment by lionfaith** [comment]
It now works!
Big thanks,
Lionel
