### ISSUE TITLE
Library updates

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#130]
As part of #85 it was determined that there is some problem somewhere probably in the libraries, that can cause a file set to 'binary' mode to strip CR values nonetheless.   It happens on my computer but not the CI build.

As part of #116 it was determined that the 'access' function needs some work:   under certain interesting conditions 'access' is specified to set 'errno' to ENOENT but currently it doesn't do that.

**Comment by GitMensch** [comment]
Seems to be fixed and should be closed in this case.

Note: the "correct" commit message in this case may would have been something along `fix #130 access not setting errno`

**Comment by LADSoft** [comment]
I haven't closed it because there were actually two issues needing to be addressed.   the 'access' problem seems fixed like you say...  

but the build of bzip2 test does NOT work on my computer.   It builds ok but when it runs, something is stripping carriage returns, but only on one of the three tests that are run.  The CI builds seem fine...   I do need to look at it.

As of today this was coming to the top of the list though.   Should be able to do something within a few days.

I'll try to be more careful with my commit messages.   Well at least I'm not just doing 'fix a bug'!   Mostly :)

**Comment by LADSoft** [comment]
I'm closing this now.  Problem was that test files had only LF on my computer but were forced to CR/LF on the checkout at the CI computer.

**Comment by GitMensch** [comment]
>  Problem was that test files had only LF on my computer but were forced to CR/LF on the checkout at the CI computer.

Should be reopened in this case, isn't this what `.gitattributes` is for?

**Comment by LADSoft** [comment]
examination shows that the final versions of the files in question only had 'lf' in them.
