### ISSUE TITLE
FR: provide help in PDF format

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#132]
The currently used chm doesn't even render in Windows 10 and cannot be read online.
I don't know where exactly the sources for the chm are - if I knew I could check for a possible conversation.

**Comment by LADSoft** [comment]
the chm is done with a program called 'helpscribble' sources are in orangec\src\help (the .hsc files)

helpscribble can be found here: http://www.helpscribble.com/download.html  it should work if anyone wants to look at it but it annotates your pages with a note reminding you to buy if you don't buy the non-free version.

The version I have doesn't seem to export to PDF but I think I might be able to make a 'flat' HTML page out of it.

As far as the chm files not displaying they seem to display on my windows 10, however, there is some possibility that the version of HHC used to compile them was too old.  I switched to a newer one when fixing LADSoft/OrangeC#126 so I wonder if you could test again after I push the flat html page?

**Comment by LADSoft** [comment]
I ended up converting CHM to HTML and then to PDF.   will be in the next push.

**Comment by GitMensch** [comment]
Thanks for https://github.com/LADSoft/OrangeC/blob/master/doc/ocide.pdf
