### ISSUE TITLE
minor: warning 36 should be splitted into two warnings

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#133]
This is a minor one which can stay open for long time, I'm just adding it to not forget about this issue.

The following test compilation:

~~~
 occ -! -DHAVE_CONFIG_H -I. -I../../libcob -I.. -I../.. -IC:\\dev\\gnucobol-merge-in\\build_windows -Dtimezone=_timezone -D__GMP_LIBGMP_DLL=1 -c ../../libcob/common.c  -DDLL_EXPORT -DPIC -o .libs/common.o
Warning( 36)  ../../libcob/common.c(70):  Redefinition of macro '__GMP_LIBGMP_DLL' changes value
Warning( 39)  COMMAND LINE(1):  Previous declaration of '__GMP_LIBGMP_DLL' here
Warning( 36)  ../..\libcob/common.h(375):  Redefinition of macro 'timezone' changes value in function dcnpgettext_expr
Warning( 39)  COMMAND LINE(1):  Previous declaration of 'timezone' here
~~~

Shows that the warning 36/39 are raised in general when a redefinition occurs and that the command line definitions are handled correct, too.

The only thing that is not correct is the warning 36 as it says "changes value" which is not true for the two defines (they define the same value that the command line defines).

Feature request:

* change warning 36 to "Redefinition of macro '%s'"
* then check if the value is identical to the old one, if not raise a new warning "Redefinition changes value"
* then output warning 39

**Comment by LADSoft** [comment]
If it evaluates to the 'same' value after stripping spaces off the ends the intention is that no warning whatsoever is given (as it may be deliberately defined in multiple headers).  So that is the change I will make...

**Comment by GitMensch** [comment]
@LADSoft I suggest to add a testcase for both warnings (or in the medium-term - all warnings, with all parts where there were raised and shouldn't in the past).
