### ISSUE TITLE
FR (RTL / header): add regex support

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#138]
I've tried to compile [Flex - The Fast Lexical Analyzer](https://github.com/westes/flex) with OrangeC.

It is currently not possible to build a working version as regex is strictly required (note: the 2.6.3 release doesn't check for this during `configure` and will simply fail during build, newer versions check this during configure).

Needed: `<regex.h>`, and support for functions `regcomp()`, `regexec()` and `regerror()`.

I drop the HOWTO here, just in case anyone wants to build flex with OrangeC (from a posix-compatible shell):

* get release tarball of flex, unpack
* if version 2.6.3 or older is used: change src/flexdef.h (newer versions don't have this include any more)
```diff
-#include <libgen.h> /* for XPG version of basename(3) */`
```
* `mkdir _build && cd _build`
* `../configure CC='occ -!' MAKE='omake -!' LD='olink -!' CPP='ocpp -!' CXX='occ -!' CXXCPP='ocpp -!' GREP=ogrep EGREP=ogrep NM='onm -!'`
* adjust _build/libtool (**two times**) to use `olib.exe`
```diff
-old_archive_cmds="lib -OUT:\$oldlib\$oldobjs\$old_deplibs"
+old_archive_cmds="olib.exe \$oldlib\$oldobjs\$old_deplibs"
```
* `make` (omake doesn't work currently, see #56)

**Comment by LADSoft** [comment]
FWIW I'm currently fighting with autoconf so i can make a configure script so I can try to tackle #56 more robustly...   problem right now is perl doesn't want to work for me.

**Comment by GitMensch** [comment]
I may can help. What configure script do you want to create and which environment do you use for this?

**Comment by LADSoft** [comment]
I was trying to do basically what you showed in #56 (and again above) to run the configure script to get a makefile to test orange C with.    But there was no configure script included with flex and from what I could tell I was supposed to run autoconf to turn configure.ac into one.

So I downloaded autoconf...   and some other stuff....   then I fought with autoconf and friends for a couple of hours before I ran out of time..

Really all I need though is the end result (the make file) so I can test orange C and get omake working...   

I've been doing all this with msys...

**Comment by chuggafan** [comment]
The end result is fairly easy to get, I got it by first getting libtool (If you're using msys2/mingw64 doing pacman -S libtool and downloading the autoconf deps aswell) first you should do ./autogen.sh but I can't give more help than that as I don't have some other things ready on hand, but that strategy seems to have worked for me, afterwords following the instructions and running
```bash
mkdir _build && cd _build
../configure "CC=occ -!" "MAKE=omake -!" "LD=olink -!" "CPP=ocpp -!" "CXX=occ -!" "CXXCPP=ocpp -!" GREP=ogrep EGREP=ogrep```

Should get everything together to run properly

**Comment by GitMensch** [comment]
@LADSoft - the easiest way in this case is to just use the [latest flex release](https://github.com/westes/flex/releases) and do the steps I've outlined above (minimal parts to fix).

**Comment by LADSoft** [comment]
hi, just downloading the package doesn't get me a "configure" script.   I am trying to get one?

Thanks for the hint to use msys2 and pacman, but after downloading half a dozen packages I still get a problem running ./autogen.sh:

![autopoint](https://user-images.githubusercontent.com/4514849/40276326-2110a61c-5bd5-11e8-9210-d06d261a94ae.png)

I tried downloading gettext explicitly with pacman but it didn't change anything...

**Comment by LADSoft** [comment]
i added regex.h, will add the functionality later...

**Comment by GitMensch** [comment]
> hi, just downloading the package doesn't get me a "configure" script. I am trying to get one?

![grafik](https://user-images.githubusercontent.com/6699539/40279036-2bb8b598-5c3c-11e8-9bd3-23bf604202cc.png)

The "Source code" (marked with red) is just a snapshot of the git repo from this tag --> doesn't contain maintainer files.
The other "Assets" are the ones that are uploaded by the maintainer. The ones marked with blue are the release tarballs (in this case likely produced by running `./autogen.sh && make && make distcheck`) - these should need no additional tools installed (and they contain the configure script, the Makefiles, translations, ...). Finally there are the ones marked with black - these are the signatures which allow you to verify if the release tarball was tampered.

**Comment by LADSoft** [comment]
ok thank you that was what I needed to progress.

The configure script chugs through for a while then I get this at the end:

**configure:15382: error: in `/c/dev/flex-2.6.4/_build':
configure:15384: error: no acceptable C compiler found in $PATH**

and then doesn't generate any output.   The only thing I could find that outright failed was something related to 'nm.exe'.   I tried using onm.exe instead and the script seemed to accept the change, but still failed at the point of using it (apparently onm.exe isn't sufficiently compatible with nm.exe).  How did you get past this point?

**Comment by GitMensch** [comment]
I've just tried to run the commands on another system (which didn't accepted the configure options, tweaked and edited appropriate) with flex 2.6.4 and was prompted with:

~~~
checking for sys/wait.h... no
configure: error: required header not found on your system
~~~

I've cheated by creating an empty orangec/include/sys/wait.h and now got to the expected missing function:

~~~
checking for regcomp... no
configure: error: required library function not found on your system
~~~

Note: I've checked the nm part in configure.log, seems to work:

~~~
configure:3945: checking for BSD- or MS-compatible name lister (nm)
configure:3999: result: onm -!
configure:4129: checking the name lister (onm -!) interface
configure:4136: occ -! -c   conftest.c >&5
configure:4139: onm -! "conftest.o"
configure:4142: output
conftest.c:
    0 D _some_variable
    0 S data
configure:4149: result: MS dumpbin
~~~

**Comment by LADSoft** [comment]
I apologize for seeming so clueless, but i'm really having trouble with this.

I wasn't sure if the result of 'MS dumpbin' was correct for onm...

On my system it doesn't seem to check either for sys\wait.h or for the regcomp function.   It did have a problem with dlfcn.h which I fixed by making an empty one...   but that didn't change anything.   I'm attaching the log file, maybe you can get some clue from it?

[config.log](https://github.com/LADSoft/OrangeC/files/2022423/config.log)

**Comment by GitMensch** [comment]
> On my system it doesn't seem to check either for sys\wait.h or for the regcomp function

These are checked later in the script.

As far as I understood this, the configure script for flex searches for a "build" compiler and a "system" compiler, using gcc for one of those - which you don't seem to have installed.

If you want me to, I can file an issue on the flex page...

**Comment by LADSoft** [comment]
That helped.   Thank you very much!

With all this I've actually been trying to get to the point of checking out #56 but it looks like the regexp problem is in the way now.   I'm wondering...   do you know if the 'posix' modes of the C++ regular expression handling are equivalent to the regular expression handling in C?   Not from an API standpoint, from the standpoint of the expressions themselves?    Because it would be incredible if I could just make a patch around C++11 regex header and have this solved :)

**Comment by GitMensch** [comment]
> do you know if the 'posix' modes of the C++ regular expression handling are equivalent to the regular expression handling in C?

No, I don't know.

**Comment by LADSoft** [comment]
i believe the C++ regex can be coerced to perform the functions of regex.h, with a little handholding.   As part of that I tried compiling the C++ regex header and failed...  and that turned into a big can of worms...   almost got it working again though.

Will be a few days before I get back to tackling issues, but, good news is I'll be on holiday for a few days after that and hope to make some headway :)
