### ISSUE TITLE
in &(expr), side effects in expr are not executed

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#14]
Hello David,
I'm still hacking project:starfighter and found where lied one of the bug I had. In this game, there is a moving starfield and the code which update each star is like:
```C
wrapFloat(&(star[i].x += (engine.ssx * star[i].speed)), 0, 799);
wrapFloat(&(star[i].y += (engine.ssy * star[i].speed)), 0, 599);
```
wrapFloat is declared this way:
```C
static inline void wrapFloat(float *in, float low, float high)
{
    if (*in < low)
        *in = high;
    if (*in > high)
        *in = low;
}
```
And the bug was that stars were not moving at all meaning that it was like the following parts were not executed at all:
```C
star[i].x += (engine.ssx * star[i].speed)
star[i].y += (engine.ssy * star[i].speed)
```
Replacing the wrapFloat lines with the following completely removed the bug:
```C
star[i].x += engine.ssx * star[i].speed;
star[i].x = star[i].x < 0 ? 799 : star[i].x > 799 ? 0 : star[i].x;
star[i].y += engine.ssy * star[i].speed;
star[i].y = star[i].y < 0 ? 599 : star[i].y > 599 ? 0 : star[i].y;
```

Here it is, I hope I've given you enough informations.

Lionel

**Comment by LADSoft** [comment]
Hi Lionfaith!

Thank you for your detailed bug report, it helps when so much detailed 
information is given!

I fixed this bug in the new release I put up this afternoon.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
So fast! I tested the unchanged code with occ 5.34 and starfield moves exactly like it has to. Big thanks! :)

Lionel
