### ISSUE TITLE
FR for ocide: File->Close all

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#142]
It would be nice to be able to close all files currently open in the editor (not the cwa/project files).
Especially when searching for something or investigate definitions (which will work again #108) one may open many editor windows. I currently found no other way to close all than pressing [ALT]+[F]+[C] multiple times (as this workaround exists I'd consider this as very low priority, although I guess the implementation, maybe with a popup window asking if this really should be done [only if more than one file is open] would be easy to implement).

**Comment by LADSoft** [comment]
on the window menu, select 'Close All'.

**Comment by GitMensch** [comment]
I see. I think it is a little confusing to have both File->Close and Window->Close (which seem identical), the same for File/Window->Save All.

I suggest to remove the duplicates (... and also move the Close All next to Save All).

**Comment by LADSoft** [comment]
the save had been moved; other stuff left the same.
