### ISSUE TITLE
oimplib - is it reasonable to keep paths?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#145]
`oimplib -C test.l ../sub/path/test.dll` results in test.l containing the paths.
On runtime the dll is still searched relative (the final results where placed in ../othersub/path, the dll files where copied there, too - but on startup an error occurs complaining that ../sub/path/test.dll is not found).

**Comment by LADSoft** [comment]
another case where there was a difference in how '/' and '\' were treated...  I'm fixing several related issues in other projects as well.
