### ISSUE TITLE
Add Appveyor builds with clang32 and clang64

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#148]
Both seem to be supported by both the OrnageC code base and Appveyor.
To verify that the code actually can be compiled and run this way it would be good to include them in the CI-build.

**Comment by LADSoft** [comment]
according to the appveyor build environments page, only CLANG-64 is supported.   Since #170 already added support for it I'm closing this issue.

**Comment by GitMensch** [comment]
Thank you for clarifying.
