### ISSUE TITLE
linker should fail on missing input files

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#149]
The current behavior is to just raise a warning.
The preprocessor and compiler fail in this case and all other linkers I'm aware of fail in this case, too.

Is there any reason to just raise a warning for this?

Note: This behavior also breaks configure scripts as they try to find existing libraries by specifying them as input files and check the return code afterwards. If you really have a reason to keep this behavior then please add a switch like `-fatal-missing` (which may also be passed with -Wl...)

**Comment by LADSoft** [comment]
there is no reason for one way over the other; will fix in the next push.

**Comment by GitMensch** [comment]
@LADSoft - There seems to be a mistake (possible with slashes) in the library lookup:

```sh
$ occ -! -o .libs/cobc.exe cobc.o ppparse.o pplex.o parser.o scanner.o config.o reserved.o error.o tree.o field.o typeck.o codegen.o codeoptim.o ../lib/libsupport.l  ../libcob/.libs/libcob.l -lgmp

Error: Library 'libsupport.l' does not exist
Error: Library 'libcob.l' does not exist
```

both exist at specified path...
