### ISSUE TITLE
implicit cast of -3 into float making wrong value

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#15]
I'm still debugging Project:Starfighter and in some places, there is such following code:

```C
math_limitFloat(&engine.ssx, -3, 3);
math_limitFloat(&engine.ssy, -3, 3);
```

And the declaration of the function is the following:

```C
static inline void math_limitFloat(float *in, float low, float high)
{
    if (*in < low)
        *in = low;
    if (*in > high)
        *in = high;
}
```

And the bug is that engine.ssx and engine.ssy were systematically set to +3.0 forcing a constant diagonal move to the player.

Calling the same functions this way remove the bug:

```C
math_limitFloat(&engine.ssx, -3.0, 3.0);
math_limitFloat(&engine.ssy, -3.0, 3.0);
```

Obviously, the implicit casting doesn't work properly.

I made further investigation this way:
```C
static inline void math_limitFloat(float *in, float low, float high)
{
    printf( "DEBUG: *in: %f low: %f high: %f\n", *in, low, high );
    if (*in < low)
        *in = low;
    if (*in > high)
        *in = high;
}
```
It showed that `-3`, once casted into float, became the huge value of `18446744073709552000.000000`, while `3`, once casted, simply became `3.0`. `*in` being lower than `low`, it was set to it, then `*in` being obviously higher than `high`, it was set to it, resulting in `*in` being equal to `3.0`, each time.

I hope this is clear enough. There are a lot of such implicit cast in Project:Starfighter, if you squeeze this one, it shalls squeeze a lot others.

Regards,
Lionel

**Comment by lionfaith** [comment]
I forgot to say that it both bugs in occ 5.34 and 5.35.

**Comment by LADSoft** [comment]
Hi Lionel,

Thanks again for the detailed report of exactly what went wrong, you 
really make my life easy :)

it was a silly mistake...   the -3 was being converted to unsigned long 
long before being converted to float.

I'll have a new version for you over the weekend :)

David

**Comment by LADSoft** [comment]
Hi Lionel,

I put up a new version.

David

**Comment by lionfaith** [comment]
occ 5.36 tested and it is working.

Big thanks,
Lionel
