### ISSUE TITLE
occ doesn't produce object files for assembler sources

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#150]
I've tried to do a configure with mpir 3.0.0 again, therefore this may be seen as follow-up to #77...

`occ -c conftest.s -yy` doesn't produce an object file with the following sources but returns zero and no output to stdout/stderr.

```asm
	.text
dummy
Lgurkmacka

```

Same for:

```asm
	.data
	.byte 0

```

I'd assume there's one of the following issues:

* the source is valid -> occ should produce an object file
* the source is invalid -> occ should complain and return non-zero

Will do more checks with MPIR on MSYS when this is solved.

**Comment by LADSoft** [comment]
problem is the assembler isn't run if you specify -c.

**Comment by GitMensch** [comment]
Interesting. Do you consider this a bug, a possible missing documentation, or do we need to use a different command line (note: the current command line is kind-of hard wired into configure scripts)?
