### ISSUE TITLE
FR: implement nanosleep

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#153]
[nanosleep, defined in time.h](https://linux.die.net/man/3/nanosleep) seems to actually be referenced in some sources in the repository, but isn't implemented yet.

This issue has no priority for me at all, but it may be relative easy to implement.

Note (to quote the manpage):

> The `nanosleep()` function shall return a value of `0` on success and `-1` on failure or if interrupted. This latter case is different from `sleep()`. This was done because the remaining time is returned via an argument structure pointer, `rmtp`, instead of as the return value.

**Comment by GitMensch** [comment]
As `nanosleep` is mostly (?) referenced in libcxx tests I think it would be reasonable to move this to the 3.5 milestone.

**Comment by GitMensch** [comment]
Just checked again: time.h defines _nanosleep - but neither that nor the non-underscore version is part of the runtime library.

**Comment by LADSoft** [comment]
I've been adding library funcitons today, this is on the list of things to yet do...
