### ISSUE TITLE
FR: Is there any option to use .a and .lib as alias names?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#154]
The current behavior seems to be "read .a and .lib as normal C files", which is obviously a bad idea (if these are not expected C source file names), isn't it?

I suggest to handle them as static (.a) or dynamic (import .lib) library (both when specified as input and when specified as output names).
As both are processed by the linker we automagically get the warning (or hopefully error) about a wrong format if this is a file not produced by OrangeC.

The reason for this FR is that

* existing Makefiles originally not written for OrangeC may use these
* Makefiles produced by automake and libtool use these (which seems to make it impossible to build any software with MSYS/Cygwin + OrangeC that consists of a library and programs using it)

**Comment by GitMensch** [comment]
Something seems broken as occ complains about not existing files (which exist in the file system):

~~~
/bin/sh ../libtool  --tag=CC   --mode=link occ --nologo     -o cobc.exe cobc.o ppparse.o pplex.o parser.o scanner.o config.o reserved.o error.o tree.o field.o typeck.o codegen.o codeoptim.o  ../libcob/libcob.la ../lib/libsupport.a
libtool: link: occ --nologo -o .libs/cobc.exe cobc.o ppparse.o pplex.o parser.o scanner.o config.o reserved.o error.o tree.o field.o typeck.o codegen.o codeoptim.o ../lib/libsupport.a  ../libcob/.libs/libcob.lib -lvbisam -lgmp -lpdcurses
Error: Library 'libsupport.a' does not exist
Error: Library 'libcob.lib' does not exist
~~~

Note: this is the #168 from MSYS in _build_orangec

**Comment by LADSoft** [comment]
there doesn't *seem* to be an issue...   problem here is that olink can't create libraries so you have to specifically call olib (by setting AR=OLIB -nologo when generating the config file).   But there will have to be an update to olib as well as when you do that libtools passes 'cru' as the first argument, to tell ar what to do...  I'm handling it as part of #56.

**Comment by LADSoft** [comment]
well in addition to the above this was broken so I'm doing a new checkin.
