### ISSUE TITLE
Creating a code format for the repo

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#157]
One of the most annoying things I keep ramming myself into is the fact that there is always a ton of code formatting that just doesn't make sense or the formatting is just randomly changing from good to bad, from the example of ```count  =0 ;``` to the amazing c.h's formatting for keywords, there is a very big inconsistency of the quality and style of the formatting, I recomend that something such as clang-format or   Uncrustify and creating rules for consistent formatting, and auto-formatting that makes code less readable (such as where the keywords are) the formatting could be turned off for that block, it should definitely help with the inconsistent formatting I've seen, I've also been working on getting some terseness back to the compiler, replacing short if statements that I know would return with a ternary operator, etc.

**Comment by GitMensch** [comment]
Note: flex uses GNU indent (which is also available for plain win32) to handle this:

* the [indent rules are shipped in source tree](https://github.com/westes/flex/blob/b22b8fdb973e8b540dd6bac4910d5f0d3a78f717/.indent.pro):
* the [makefile has an extra indent rule](https://github.com/westes/flex/blob/6a6e69af761801aedeab0264246772cf60810246/src/Makefile.am) that is manually run by the devs before they commit any file

Adding something like this and running the rule once + commit helps for a cleaner code base *and* better diffs.

In general: the hardest part is to define the actual rules...

**Comment by LADSoft** [comment]
hehehe...  yeah I need a code format and I also need to start thinking more seriously about what I choose for variable names...

**Comment by chuggafan** [comment]
Yhea, I've personally been working on getting through first declcpp.c in the compiler itsself, which has the biggest formatting issues, such as replacing calls to ```object->sym->table[0]``` with a macro that would expand to that with a descriptive name (SYMTABBEGIN), and replacing while loops for for loop constructs when they literally do the purpose of a for loop in some extra lines. There's an if statement that checked greater than return true else return false that I compressed into a ternary operator, several other things that  I'm working on, a big thing that I think is causing issues is that 100% of the classes are derived using externs and extracting all methods from a single header file, meaning every import polluts each file and starts to make it more difficult to tell where everything comes from, it's hard work, but I'm getting somewhere on it (slowly). One of the issues i've seen as well is... https://github.com/LADSoft/OrangeC/blob/master/src/occ/parse/declcpp.c#L266 which actually looks like a perfect case for a GOTO of some sort, somehow, but definitely needs refactoring in huge ways.

**Comment by LADSoft** [comment]
since this hasn't gone anywhere I'm probably going to try to make a style this weekend...   at least we can get the code looking a little better :)

**Comment by LADSoft** [comment]
the declcpp line 266 thing is probably best fixed by setting a flag in the 'success' path, then checking the flag upon subroutine exit to see if it succeeded or not.   I really do *try* not to use gotos any more lol!

**Comment by GitMensch** [comment]
> since this hasn't gone anywhere I'm probably going to try to make a style this weekend... 

I suggest to have a look at the GNU Coding Standards (people do debate on some specific parts but in general it is a quite reasonable set), especially [5.1 through 5.4](https://www.gnu.org/prep/standards/standards.html#Formatting).

**Comment by chuggafan** [comment]
GNU Coding standards, specifically the braces, reek of poor looks.

**Comment by GitMensch** [comment]
@chuggafan "something is bad" won't help here. Providing something like "this is a sample of the current mess", "this is the same sample with GCS applied - better but the braces don't look nice" and "this is what I suggest" would help. Can you provide this, please? Otherwise at least I can't get a clue what you like and why... Samples would provide a ground for discussion :-)

**Comment by chuggafan** [comment]
Specifically the bracing style:

```cpp

do
    {
        x;
    }
while(1);
```
vs
```cpp
do
{
x;
} while(1);
```
Looks ugly. https://zed0.co.uk/clang-format-configurator/ with Allman style braces sounds good, and this website is good for seeing how a code piece would look without messing around too much.

**Comment by GitMensch** [comment]
The first one looks much more clearer to me. while I'd place the braces for non-functions in the same line:

```c
do {
    x;
} while (1);
```

**Comment by LADSoft** [comment]
personally I don't like the extra indent on the braces but think the statement inside the braces should be indented.   But I'm not much of a fan of the K&R brace style either... 

I've modified the llvm format file generated by clang-format and checked it in here: 5a8924cd838372c83f328b1af507fc017d032e62.   I ran it on a few sources and it seems ok in the present incarnation...   This is a proposal and I'm open to suggestions...

**Comment by chuggafan** [comment]
Looking at what you chose, I like it! Only issue I think needs to be done in further regards is taking certain areas of the code and creating "unformattible" sections that clang-format can't go, such as the e_kw enum in c.h would otherwise become many more lines and not be nearly as formatted as the way you have.

**Comment by LADSoft** [comment]
I went ahead and bracketed most of the enums in the compiler proper, plus some of the enums in other projects.   If you are good with it I'll apply the formatting once I take a look at your pull request.

**Comment by chuggafan** [comment]
Yhea, looks great! I think it (sometimes) annihilates arrays (I do not personally like the ends of arrays being hugged by the ending brace, but IDK how to fix that itsself in clang-format's stuff), but you got most of the enums and problem areas (I think, I don't have time to check much atm, but will later)

**Comment by LADSoft** [comment]
I updated all the sources now.   The renovation found a couple of bugs; one in OCIDE (which I've fixed) and another problem I wrote up in #238.

I did manage to crash clang-format at one point lol!   it doesn't like the microsoft targetver.h files :)

**Comment by chuggafan** [comment]
One question: how are we supposed to run clang-format through the makefile?

**Comment by GitMensch** [comment]
I still vote for `omake indent` :-)

**Comment by LADSoft** [comment]
I had broken the makefile because there was a collision with the build, so I commented it out before committing.   I've restored it so it works now though; you can just type 'omake format' either in a subdirectory or at the root.
