### ISSUE TITLE
FR: output stack trace on access violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#159]
The current behavior is:

~~~
Access Violation:(full-path-to-executable)
CS:EIP 0023:026C6244  SS:ESP 002B:0019FEEC
EAX: 026CEDE8  EBX: 02720044  ECX: 00000005  EDX: 00000014  flags: 00010212
EBP: 0019FF78  ESI: 00000001  EDI: 003B0000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

The executable name is good, the register output is likely helpful for the OrangeC programmer, but the programmer using OrangeC is likely lost.

A helpful approach would be to output the call stack (I guess more useful output when compiled with +v)

**Comment by GitMensch** [comment]
Just a question of understanding, as it isn't clear to me from looking at the documentation: How can I see which exact line the error comes from?

I see the following issue at least twice when running the testsuite:

~~~
+Access Violation:(C:\dev\gnucobol\build_windows\ocide\WIN32\Debug\cobc.exe)
+CS:EIP 0023:0040360F  SS:ESP 002B:0019F590
+EAX: FFC1A600  EBX: 772B8484  ECX: FFFFFFFC  EDX: 0019FD6E  flags: 00010246
+EBP: 0019F590  ESI: 00000000  EDI: 003A3000
+ DS:     002B   ES:     002B   FS:     0053   GS:     002B
+
+Stack trace:
+	40360f: is_screen_field + 0x6
+	412df6: yyparse + 0xefb9
+	43768a: process_translate + 0xbc
+	438c6c: process_file + 0x1af
+	439138: main + 0x381
+	47b70b: __startup + 0x1c7
~~~

As expected the stack trace is  only shown when compiled with debugging (in this case from IDE), but how do I see (or get to know by manually calculating) the exact line?

**Comment by LADSoft** [comment]
Hm didnt think of that.  reopening to have it calculate the line number for you...

**Comment by GitMensch** [comment]
@LADSoft - Just to verify my guess:

A stack trace (last working CI build) like the following:

~~~
CS:EIP 0023:0040FD1F  SS:ESP 002B:0019F278
EAX: 00000000  EBX: 029A8A1B  ECX: 00000003  EDX: 00412975  flags: 00010202
EBP: 0019FF24  ESI: 00000002  EDI: 0033D000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

Stack trace:
        40fd1f
        4010a9
        401095
        4098e3
~~~

Means that the module was compiled with debug, but the error is in a library that wasn't compiled with debug. Is this assumption correct?
Shouldn't the stack should at least have one entry for the module?

Checked with linking against a debug library:

~~~
Stack trace:
        40fd1f: memcmp + 0x13
        4010a9: NC132A + 0xa  module: nc132a.c, line: 48
        401095: main + 0x18  module: nc132a.c, line: 36
        4098e3: __startup + 0x1c7
~~~

Obviously only memcmp was part of a non-debug library ?!?

Another suggestion for the stack trace:
Can you output the library name at stack in this case? Something like:

~~~
Stack trace:
        testlib2.dll at 40fd1f
        testlib1.dll at 4010a9
        NC132A.exe at 401095
        NC132A.exe at 4098e3
~~~

note: You may (or not) reproduce this stack trace executing the file created by `occ.exe NC132A.c  libcob.l` with the given test program [NC132A](https://github.com/LADSoft/OrangeC/files/2108554/NC132A.zip)

**Comment by LADSoft** [comment]
the problem is that once something isn't compiled for DEBUG, the contents of the base register (EBP) become meaningless for purposes of tracing through the stack.   Because the 'release' versions agressively reuse EBP as general purpose storage.   So once it encounters a module that isn't compiled for debug it can't really go any further...   AFAIK Microsoft resolved this by having lookaside tables that enabled them to trace the stack anyway but I haven't really done that.

So if you aren't getting symbols it doesn't really tell you much about what was compiled and how, just that whatever is at the bottom of the stack wasn't compiled for debug.

I will see if there is any way to get the name of the module/dll.   That could be difficult though (reopened)

**Comment by LADSoft** [comment]
at some point I made a modification to the library compiles so that the libraries are always compiled using EBP as a base register, specifically to support stack unwinds with this DLL.   Still need to compile the application properly to get full symbol info and stack unwinds from the app itself.  (there is a command line switch to enable EBP as a base pointer without also making it a 'debug' build).

**Comment by GitMensch** [comment]
What are the side effects of enabling EBP?
How can we do this on the command line / in ocide?

**Comment by LADSoft** [comment]
It just leaves one less register to use for optimization...   other than that no big deal.   The code might be just a tiny bit more compact though as it doesn't use ESP based addressing when you do that...

To enable EBP as a base pointer use the '/C-E' compiler switch.

**Comment by GitMensch** [comment]
@LADSoft I've just retested this the first time since you've closed the issue.
I assume the backtrace is broken and request re-opening this issue.

[no_stacktrace.zip](https://github.com/LADSoft/OrangeC/files/2569345/no_stacktrace.zip)

~~~
occ --nologo prog.c cob.l gmp.l pdcurses.l -DCOB_WITHOUT_DECIMAL -DCOB_WITHOUT_EXCEPTIONS -o prog.exe
prog.exe

Access Violation:(c:\dev\gnucobol-stuff\_build_occ\tests\no_stacktrace\prog.exe)
CS:EIP 0023:FF4CC481  SS:ESP 002B:0019FF30
 EAX: 00000001  EBX: 77C08484  ECX: 02200088  EDX: 00454BB6  flags: 00010203
 EBP: 0019FF78  ESI: 00000000  EDI: 0027A000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

occ --nologo prog.c cob.l gmp.l pdcurses.l -DCOB_WITHOUT_DECIMAL -DCOB_WITHOUT_EXCEPTIONS -C-E -o prog.exe
prog.exe   -> hang, CPU core not hogged

occ --nologo prog.c cob.l gmp.l pdcurses.l -DCOB_WITHOUT_DECIMAL -DCOB_WITHOUT_EXCEPTIONS +v -o prog.exe
prog.exe   -> hang, CPU core not hogged
~~~

**Comment by LADSoft** [comment]
the stack trace worked as of last night.    But it currently relies on EBP-based stack frames.   To get EBP-based stack frames use the command line switch /C-E, or compile for debug with /v.    If you compile for debug you also get function name, file, and line number information.

**Comment by GitMensch** [comment]
Just rechecked with the given sample on a different machine:

* last release worked as expected (no trace without `+v`, trace with `+v`)
* current release behaves as noted above: `+v` hangs
* most current artifact (8 hours ago): `+v` hangs

@LADSoft Please reopen.

**Comment by LADSoft** [comment]
ok I duplicated it and verified that the stack trace is broken.   Hopefully can fix it tomorrow...

I also cleaned up most of the .NAS files in the library so they have EBP-based stack frames for this...  will check that part in soon...
