### ISSUE TITLE
access violation in olink.exe

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#165]
I've moved to current CI build and did a "rebuild all", seems this doesn't was a good idea...

~~~
Access Violation:(d:\dev\orangec\bin\olink.exe)
CS:EIP 0023:0041EC6E  SS:ESP 002B:0019EEF4
EAX: 00000000  EBX: 00000113  ECX: 0019F160  EDX: 0019EE5C  flags: 00010246
EBP: 06F9A4E0  ESI: 00000001  EDI: 072BA7E8
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

Note: just did another Make afterwards and the link phase passes (and the new generated executable at least starts)...

**Comment by LADSoft** [comment]
i assumed you were trying to build the compiler package so I snagged the CI version and did a build.   Seemed ok...   is this something you can duplicate?  If so can you tell me exactly which version of the CI build you got so I can investigate further?
