### ISSUE TITLE
Adding support to ignore #pragma region

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#167]
https://docs.microsoft.com/en-us/cpp/preprocessor/region-endregion Literally I want this so that I can fold code in VScode that happens to be similar, yet don't want to see, in theory ide support would also be awesome for it, but I currently use VSCode as my main editor (Visual Studio intellisense with clang-format and is infinitely less bulky with better support for certain features? that's my kind of dealio!), so I wouldn't particularly know if it is in there at all. This is low priority but is just a nice feature for code folding in editors that support it.

**Comment by LADSoft** [comment]
compilers are supposed to ignore #pragma directives they don't know about, so you should be able to use this now if you have an editor that supports it????

**Comment by chuggafan** [comment]
Ah, because I was looking into the preprocessor and had thought that it would crash if it had run into it, I'll test that now (after I make a bug report for something entirely unrelated)

**Comment by chuggafan** [comment]
Yep, seems to ignore the pragma, didn't realize that.
