### ISSUE TITLE
Assembler: add "common" option to specify to emit a data byte

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#171]
MPIR's configure checks multiple ways of defining multitude things for the assembler. This breaks now (which is good) with the implementation of #164 :

~~~
checking how to switch to text section... .text
checking how to switch to data section... .data
checking for assembler label suffix...
checking for assembler global directive... .globl
checking for assembler global directive attribute...
checking if globals are prefixed by underscore... yes
checking how to switch to read-only data section... .data
checking for assembler .type directive... .type $1,@$2
checking for assembler .size directive...
checking for assembler local label prefix... L
checking for assembler byte directive... configure: error: Cannot determine how to emit a data byte
~~~

The two sources that are checked by the configure script (because these are "common") are:
* `.byte`:
```asm
	.data
	.byte	0
```
* `data1`:
```asm
	.data
	data1	0
```

Both of these compile with "Error (0): identifier expected".

This FR is about adding one (or both) of these.

**Comment by GitMensch** [comment]
@LADSoft I'm not sure, but do you think it is reasonable to add `.byte` as possible substitute for `data1` and `.long` as substitute for `data4`?

**Comment by LADSoft** [comment]
also adding .word
