### ISSUE TITLE
FR: occ.exe - generate assembler sources with -S

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#172]
Different software written primarily against GCC uses `-S` to generate assembler sources.
occ complains about wrong command line (it looks like the correct one would be -Sasm;dbg).

Can we add `-S`?

**Comment by GitMensch** [comment]
@LADSoft I may was too quick on my request to have `-S` be an alias of `-Sasm;dbg`.
Makefiles that use `-S` normally expects the files to end with ".s"...

Question: Should there be a separate flag to adjust the default extensions or should `-S` use ".s" while `-Sasm;dbg` use ".asm"?

**Comment by LADSoft** [comment]
-S generally works although it would generate a .asm file extension.    Maybe the build you tested with was broken?   There would have to be a separate switch to adjust the extension because the extension to the -S switch has a different meaning...

**Comment by GitMensch** [comment]
We're nearly there:

> Makefiles that use `-S` normally expects the files to end with ".s"...

So my request, now that we do have `/a` to change the assembly language file extension: please make `-S` an alias for `-Sasm;dbg -As`.
