### ISSUE TITLE
Question: How to change generation of DLL entry points?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#181]
The following source

```c
__declspec(dllexport) int		testfunc (void);
static int		testfunc_ (const int);

int
testfunc ()
{
  return testfunc_ (0);
}

static int
testfunc_ (const int entry)
{
  return 0;
}
```

compiled with `occ.exe /! /Wd -o "testfunc.dll" "testfunc.c"` leads to an entry point ´_testfunc`,
compiled with `gcc.exe -shared -o "testfunc2.dll" "testfunc2.c" leads to an entry point ´testfunc`.

What is the correct way to achieve the same result as with gcc?

Background: Currently I need (only with OrangeC) to pass `_testfunc` instead of `testfunc` to get the function pointer when calling `GetProcAddress`.

**Comment by LADSoft** [comment]
The way we handled this with the MSVC compilers at an old job was to use .DEF files to alias the mangled C name to one without an underscore.   I think though that the MSVC compiler or linker might have a command-line option to strip the underscore from the exported name...   another possibility is to use the __stdcall calling convention (which is available in various #defines in the windows headers) which also strips the underscore, however, that also changes the code generation...

**Comment by LADSoft** [comment]
I tested and the microsoft linker strips the leading underscore...  so I'm doing the same...

**Comment by LADSoft** [comment]
oops...   now it broke the import library.   Will fix soon.
