### ISSUE TITLE
ocide: change default colors for editor windows

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#182]
The current default has white background with yellow and orange items, which I think are quite hard to read:

![grafik](https://user-images.githubusercontent.com/6699539/40710627-6edc2e6c-63f9-11e8-8185-7692b50a74ca.png)

**Comment by GitMensch** [comment]
Also note that the orange underscore is not visible at all:
![grafik](https://user-images.githubusercontent.com/6699539/40715140-e3638392-6404-11e8-97cf-68152e364a25.png)

The second line is

```c
statement_start = curr_pos;
```

**Comment by LADSoft** [comment]
I made some changes that seem to improve it, however, I wanted an opinion as to whether they are too garish so I left this open

**Comment by GitMensch** [comment]
It is much better now (but color preferences are a very personal view in general).
We could create a low-priority issue about providing color schemes but in this case it would likely be a better idea to replace the GUI completely with a GUI framework that also provides these and lots of other features, for example Qt or GTK or whatever VSCode uses...

Something like:
![grafik](https://user-images.githubusercontent.com/6699539/40772350-0440c4f6-64c0-11e8-92c1-913523b2eaac.png)

**Comment by GitMensch** [comment]
... parts written in italic still tend to don't show the underline:

![grafik](https://user-images.githubusercontent.com/6699539/40772704-10b31594-64c1-11e8-9b6b-33addc0eb198.png)

**Comment by LADSoft** [comment]
hm i explicitly looked at that.   Will look again...

The last time I looked into rewriting the IDE with a real windowing framework I concluded that it would really balloon in size...   it was an issue for me then but may not be now.   OTOH I've got a lot I want to do and I'm not sure a rewrite of OCIDE would make it in any time in the near future

**Comment by LADSoft** [comment]
ouch!   on my computer it depends on the font settings...

**Comment by GitMensch** [comment]
> OTOH I've got a lot I want to do and I'm not sure a rewrite of OCIDE would make it in any time in the near future.

I'm sure it wouldn't be a good thing to do this in the near future, the point was that it is likely more reasonable to do this "some time in the future" using a wide used (and portable) framework than to *add* features that will get in "for free" when using the frameworks.
