### ISSUE TITLE
debugger: show content of const char * in called functions

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#183]
Shown in the caller (defined as `static char *`, only pointer value shown)::

![grafik](https://user-images.githubusercontent.com/6699539/40711277-0f43cd50-63fb-11e8-94aa-9643c10d7ca1.png)

not shown in the function (defined as `char *`, only pointer value shown):

![grafik](https://user-images.githubusercontent.com/6699539/40711158-cb9433b0-63fa-11e8-9206-f8af1f81905a.png)

**Comment by LADSoft** [comment]
I wasn't able to duplicate this with a simple test program...   can you tell me what arguments you used to 'cobcrun' to be able to get the program to this point?

**Comment by GitMensch** [comment]
The only option used was "testfunc". To actually being able to get there:

`cobc -v testfunc.c` found in LADSoft/OrangeC#181 - should produce testfunc.dll with calling `occ` (if not: compile with `occ` directly).
`cobcrun testfunc`

**Comment by LADSoft** [comment]
ok i tried this and it seemed to work for me.   Can you tell me anything about what you were doing?  In particular i noted that the two pointers in your example were different addresses...   and I wasn't sure what was going on with that.   Even though I think it should have display some string in the second one, if only an empty one...

**Comment by GitMensch** [comment]
I've came back to recheck some debugger parts.

The possibly easiest thing is a program (in my case cobc.exe) that is compiled against lscrtl.dll and looking at `argv` value (the common `char **argv`) which currently only views its pointer (I've expected it to at least show as "ARRAY: 0x...." (and I still haven't found how to inspect these arrays in the debugger).

I've then did go on to the line `conf_ret |= cb_load_std ("default.conf");` and one step into
```c
int
cb_load_std (const char *name)
{
	return cb_load_conf (name, CB_INCLUDE_MANDATORY);
}
```
with no information about "name"; trying to set a watchpoint to "name" leads to 

~~~
---------------------------
Invalid Expression
---------------------------
Undefined symbol
---------------------------
OK   
---------------------------

---------------------------
Error
---------------------------
Symbol does not exist in this scope
---------------------------
OK   
---------------------------
~~~

Is this expected?
BTW: Should displaying items below a struct (referenced as `someStruct->item`) work currently?

**Comment by GitMensch** [comment]
> Are you using the 'release' or one of the appveyor builds? 

I was using the MSVC based 32bit artifact from statically linking.

Actually I did not see the watch window at all...

**Comment by LADSoft** [comment]
the problem being that when you step into a function it initially stops before the stack frame is set up.   After single-stepping past the first bracket it works.   I'll fix it.

if the watch window isn't visible you can get to it by selecting the DEBUG menu item, then selecting WINDOWS and then selecting WATCH.   You can have up to four watch windows :)

**Comment by GitMensch** [comment]
The debugger doesn't show 

```c
int
main (int argc, char **argv)
```

used some lines below

```c
	cb_saveargc = argc;
	cb_saveargv = argv;
```

After those lines the both left variables (source-file scope) show their values, but `argc`/`argv` do not. That isn't intended, is it?


Going on with debugging:
![grafik](https://user-images.githubusercontent.com/6699539/48727046-6b25eb80-ec31-11e8-9388-f3cfd23f7953.png)

None of the function parameters are shown, all are "undefined symbols".

```c
#define	COBC_ADD_STR(v,x,y,z)	cobc_add_str (&v, &v##_size, x, y, z);
		COBC_ADD_STR (cobc_cflags,  " --nologo", NULL, NULL);
```

All variables are shown in the calling line...
Can you reproduce things like this?

**Comment by LADSoft** [comment]
ok will look at it again in a couple of days :)

**Comment by LADSoft** [comment]
this was next up on my list...   but right now I can't compile a working version of the cobol testbed sigh.   I'll look into it this weekend...

**Comment by LADSoft** [comment]
I was able to duplicate this and will push a fix later on tonite.   I'm going to leave the issue open though pending whether you can find anything else :)
