### ISSUE TITLE
Weird typedef issue

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#184]
This issue has been preventing me from actually working on the new threading support stuff because it's just that stupid, here's an example program that reproduces the issue in the newest CI:

```cpp
#include <windows.h>
#include <stdbool.h>
typedef CRITICAL_SECTION __libcpp_recursive_mutex_t;
bool __libcpp_recursive_mutex_trylock(__libcpp_recursive_mutex_t *__m)
{
  return TryEnterCriticalSection(__m) != 0;
}
```

Literally that's it. Nothing else to it. No idea WHY this doesn't work, but it doesn't.

(edit): for the error it's saying that it's "Not an allowed type in function" for the line of which is giving both the wrong function and should list the type not allowed and the type you're trying to actually enter", this should probably go hand in hand with more enhanced error messages.

**Comment by LADSoft** [comment]
yeah the OCC error messages leave something to be desired...   I thought I had fixed that one to be more descriptive though.   I think it is complaining because it thinks something is type 'void'...   I will look at this shortly.

**Comment by LADSoft** [comment]
TryEnterCriticalSection was defined wrong in the headers...
