### ISSUE TITLE
FR: add wait/waitid/waitpid and sys/wait.h

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#187]
Used in flex (checked in its configure script since 2.6.4).

It seems to be referenced in this repo in [src/clibs/cpp/libcxx/include/condition_variable](https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/clibs/cpp/libcxx/include/condition_variable), too ?!?

Documentation: https://linux.die.net/man/2/wait

**Comment by chuggafan** [comment]
waitpid seems to not exist on windows, so it'd be probably difficult to implement without implementing pthreads, I'll look into updating the ENTIRE libcxx library after I update threading to work

**Comment by GitMensch** [comment]
This is what GnuCOBOL does for `_WIN32`, using `OpenProcess()` + `WaitForSingleObject()` (+ `GetExitCodeProcess()`, when the C compiler does not support `waitpid()` (+ `WEXITSTATUS()`):

```c
	int	pid, status;
	HANDLE process = NULL;
	DWORD ret;

	COB_UNUSED (p_id);

	status = 0;
	if (COB_MODULE_PTR->cob_procedure_params[0]) {
		pid = cob_get_int (COB_MODULE_PTR->cob_procedure_params[0]);
		if (pid == cob_sys_getpid ()) {
			status = 0 - ERROR_INVALID_DATA;
			return status;
		}
		/* get process handle with least necessary rights
		   PROCESS_QUERY_LIMITED_INFORMATION is available since OS-version Vista / Server 2008
		                                     and always leads to ERROR_ACCESS_DENIED on older systems
		   PROCESS_QUERY_INFORMATION         needs more rights
		   SYNCHRONIZE                       necessary for WaitForSingleObject
		*/
#if defined (PROCESS_QUERY_LIMITED_INFORMATION)
		process = OpenProcess (SYNCHRONIZE | PROCESS_QUERY_LIMITED_INFORMATION, FALSE, pid);
#if !defined (_MSC_VER) || !COB_USE_VC2012_OR_GREATER /* only try a higher level if we possibly compile on XP/2003 */
		/* TODO: check what happens on WinXP / 2003 as PROCESS_QUERY_LIMITED_INFORMATION isn't available there */
		if (!process && GetLastError () == ERROR_ACCESS_DENIED) {
			process = OpenProcess (SYNCHRONIZE | PROCESS_QUERY_INFORMATION, FALSE, pid);
		}
#endif
#else
		process = OpenProcess (SYNCHRONIZE | PROCESS_QUERY_INFORMATION, FALSE, pid);
#endif
		/* if we don't get access to query the process' exit status try to get at least
			access to the process end (needed for WaitForSingleObject)
		*/
		if (!process && GetLastError () == ERROR_ACCESS_DENIED) {
			process = OpenProcess (SYNCHRONIZE, FALSE, pid);
			status = -2;
		}
		if (process) {
			/* wait until process exit */
			ret = WaitForSingleObject (process, INFINITE);
			if (ret == WAIT_FAILED) {
				status = 0 - GetLastError ();
			/* get exit code, if possible */
			} else if (status != -2) {
				if (!GetExitCodeProcess (process, &ret)) {
					status = 0 - GetLastError ();
				} else {
					status = (int) ret;
				}
			}
			CloseHandle (process);
		} else {
			status = 0 - GetLastError ();
		}
	} else {
		status = 0 - ERROR_INVALID_DATA;
	}
	return status;
```

**Comment by chuggafan** [comment]
Hmm, considering normal threading support for C11 threads is in here and I can now work on getting c++11 (and c++14 stuff) in from libcxx this seems moreso obsoleted, if really neccessary I guess using libwinpthread instead could always work

**Comment by GitMensch** [comment]
ping @chuggafan any update on this?
If not: @LADSoft what do you think about implementing it using the GPL'd code I've provided as workaround above?

**Comment by LADSoft** [comment]
I'll look at this tomorrow...

**Comment by LADSoft** [comment]
i didn't think wait/fork had anything to do with threading (they rather seem to have to do with processes?)   I mean you could implement a sort of thread but not really a thread since the process data starts diverging?

But I guess I don't really know, I'm not so familiar with unix :)

**Comment by chuggafan** [comment]
fork/wait technically are process related, but are used often as a method to dispatch and run pseudo-threads, I was being dumb on what exactly I was saying yesterday, but the real essence is that the address spacing requirements means a whole UNIX compatability layer is needed (Cygwin or otherwise). https://en.wikipedia.org/wiki/Fork_%28system_call%29 And Cygwin has real problems with it: https://stackoverflow.com/questions/985281/what-is-the-closest-thing-windows-has-to-fork/985525#985525 and https://stackoverflow.com/questions/985281/what-is-the-closest-thing-windows-has-to-fork detail it well on why it's so difficult and why it's not something I would think would be good to add.

**Comment by GitMensch** [comment]
The implementation of this feature with e1525847b0e78efd30e488ccd7ed7d19014f0720 looks nice and reasonable enough to add.

> But then I looked and as it turns out flex uses fork()... so implementing wait() is only a partial fix for the problems posed by flex... what is your idea for resolving the fork() part of the problem?

My idea is to never use `fork()` on native windows as long as there is no kernel call for it like on more mature OS ;-)
Concerning flex: there's a patched version in the WinFlexBison repo that is slower but don't use fork, I *may* come back to this some day creating a PR to remove the need, depending on a define, see https://github.com/westes/flex/issues/367.
The configure script of flex should detect working wait + header and missing fork, I'll try to check next week with the updated OrangeC.

@chuggafan: did you suggest to directly integrate WinPthreads into OrangeC? In this case it should be tracked in a new issue.

**Comment by chuggafan** [comment]
I actually did not mean to suggest adding WinPThreads, I was just being stupid and thought fork() was implemented on that. The thing I was saying is that adding all of it might as well be equivalent to that, and that it is much more than just any random thing and is not simple to implement.

**Comment by LADSoft** [comment]
good....   like chuggafan said fork() would be unreliable no matter how we did it lol!   I don't have any intention of adding pthreads BTW, the idea is that between the C99 threading mechanism and the C++ threading mechanism (which I realize is TBD) that should be enough lol!

CI was a mess for a while, changes I made broke things in a big way.   Just as well I made them though to find out what the issues were :)

**Comment by GitMensch** [comment]
Please reopen adding (likely as macro) `WEXITSTATUS` and `WIFEXITED` (I've did not checked the others for implementation) as noted in the referenced manpage. Those macros are considered to be available if sys/wait.h and waitpid are available (for example in flex, which I personally would like to see building with the sole exception of `fork()`).

**Comment by LADSoft** [comment]
hi, WEXITSTATUS and WIFEXITED were defined.   Although I'm not sure the definitions were appropriate and will be updating them soon...   are you sure sys/wait.h is included at the point of use?

**Comment by LADSoft** [comment]
this seems resolved so i'm closing it.
