### ISSUE TITLE
Question (or bug?) for invocation of olib

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#188]
To build libtoolized programs with mingw I've applied the following change to the generated libtool, as this knowns about "windows linkers" but not about "olib":

```diff
-old_archive_cmds="lib -OUT:\$oldlib\$oldobjs\$old_deplibs"
+old_archive_cmds="olib --nologo -o\$oldlib\$oldobjs\$old_deplibs"
```

The resulting command line is (sample GnuCOBOL's libcob):

```
olib --nologo -o.libs/libcob.lib  common.o move.o numeric.o strings.o fileio.o call.o intrinsic.o termio.o screenio.o reportio.o cobgetopt.o
```

This *looks* fine to me but doesn't result in .libs/libcob.lib but a common.o.l file.
Is this a bug in the command line handling of olib? If not: what would be the correct command line to use?

**Comment by LADSoft** [comment]
I think it is broken.  Will look tomorrow...
