### ISSUE TITLE
C++11 decltype return specifier not made

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#200]
Ran into this issue attempting to compile a newer version of __functional_base:

```cpp
template <>
struct _LIBCPP_TYPE_VIS_ONLY less<void>
{
    template <class _T1, class _T2> 
    _LIBCPP_CONSTEXPR_AFTER_CXX11 _LIBCPP_INLINE_VISIBILITY
    auto operator()(_T1&& __t, _T2&& __u) const
    _NOEXCEPT_(noexcept(_VSTD::forward<_T1>(__t) < _VSTD::forward<_T2>(__u)))
    -> decltype        (_VSTD::forward<_T1>(__t) < _VSTD::forward<_T2>(__u))
        { return        _VSTD::forward<_T1>(__t) < _VSTD::forward<_T2>(__u); }
    typedef void is_transparent;
};
```

WWas the code, the full decltype stuff could be looked at here: https://en.cppreference.com/w/cpp/language/decltype

**Comment by chuggafan** [comment]
It appears I broke something on my end and it was working fine? I'm heavily confusde, I'll close this for now and reopen if I refind it

**Comment by chuggafan** [comment]
Ayup, as it turns out some stuff I did removed the newer version of __functional_base while I was trying to update all of libcxx to something c++14 compliant, turns out that yes this is still an issue, the exact error found is:

```
Error( 18)    C:\OrangeC\src\clibs\cpp\libcxx\include\__functional_base(73):  Undefined symbol '__t'
Error( 18)    C:\OrangeC\src\clibs\cpp\libcxx\include\__functional_base(73):  Undefined symbol '__u'
```
of which these two variables refer to the block of code originally posted. After attempting to compile certain things (cregex, algorithm) I get an Access Violation 0xC0000005, I'll add all the files I currently have to my master branch, but I have no idea why or how I keep falling into these bugs :/

(BTW, if there's no error there's no access violation, but if there's also more errors than just those two it doesn't give an access violation, I'm confused as to why and when these are appearing, but they are)

**Comment by LADSoft** [comment]
ok i fixed this one.   It immediately led to a problem with various functions in 'memory'...   another one of those problem children.   Have you vetted that one yet?   Need me to look at it?

**Comment by chuggafan** [comment]
I am doing everything sequentially, so I'll look into problems as they come up. I definitely am finding a lot of problems via upgrading to latest as much as possible though. if you want to look into it I definitely would appreciate it though

**Comment by chuggafan** [comment]
Oh wow, I see precisely what you mean when you say that memory is being a problem child, I have no idea where to even begin on trying to find the right header to get addressof when trying to pull in anything of the latest, and attempting to update the memory header gets me some weird BS with the atomics header popping up, it's annoying tbh

**Comment by LADSoft** [comment]
in your sources there is a comment in "memory" that addressof is supposed to be in __functional_base.   In mine (which are apparently not the same) there is comment it should be in type_traits.

I did put a bandaid on some of the crashes which were occurring...   I think more work needs to be done though.

**Comment by chuggafan** [comment]
I fixed memory's addressof issues in my side... but yhea to be able to get everything up to date is going to take a huge amount of band-aiding the project and working around the current limitations, I've (thankfully) mitigated the memory stuff, but in return seem to have caused (in updating <functional>) a new problem child to appear, oh well.
