### ISSUE TITLE
FR: extend ogrep with context display and "stop after"

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#202]
request for `-Anum` / `--after-context=NUM`, `-Bnum` / `--before-context=NUM`, `-Cnum` / `--context=NUM` and `-mNUM` / `--max-count=NUM`

see https://linux.die.net/man/1/grep

**Comment by GitMensch** [comment]
Just a ping on this

**Comment by GitMensch** [comment]
@LADSoft ping, ping

**Comment by LADSoft** [comment]
I guess you would like this sooner rather than later?

**Comment by GitMensch** [comment]
Just take the time you need, especially if this is "more work". I've primarily ping'd because there was no reaction before (ok, and because it's the last reason why ogrep cannot be used when building GnuCOBOL from scratch, but `omake` is much more important than this one).

**Comment by GitMensch** [comment]
I'm primarily pinging because there wasn't a reaction... and because it's the last tool from OrangeC that is not working as replacement within the GnuCOBOL make process.
Take your time with this issue, omake is more important to fix.

**Comment by GitMensch** [comment]
That mail notice got send a day to late, deleting it now...
