### ISSUE TITLE
occ doesn't pass output file name to oasm

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#204]
~~~
$ occ.exe -c --nologo -o "testme.o" "prog.s" -yy
"C:\dev\orangec\bin\oasm.exe"  -! "prog.s"
~~~

The "obvious" result: prog.o instead of testme.o

**Comment by LADSoft** [comment]
the output file name for OCC is meant to reflect the EXE file, not any of the input source files, and doesn't have any real meaning if you specify -c or -S.   How would you propose to resolve it if someone puts multiple ASM files on the command line?

**Comment by LADSoft** [comment]
never mind i'm fixing it :)

**Comment by GitMensch** [comment]
@LADSoft please reopen:

`occ -o test.o test.s` works
`occ -c test.s` doesn't work - even with "-c compile only" used the output name passed to oasm (as seen by adding `-yy` is "test.exe" - should be "test.o" when `-c` was specified.
