### ISSUE TITLE
strange output name handling (occ/olink producing multiple output files)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#206]
Using an input file name [a.o](https://github.com/LADSoft/OrangeC/files/2069023/a.zip)

Specifying neither DLL nor EXE:

~~~
$ occ.exe -o "a.out" "a.o" --nologo libcob.l -yy
"C:\dev\orangec\bin\olink.exe"  -! /c+ /T:CON32  -yy @tmp00000.$$$
with tmp00000.$$$=
c0xpe.o "a.o"  "/oa.out.dll"  "libcob.l" climp.l clwin.l Running App: "C:\dev\orangec\bin\dlpe.exe" -!  /mCON /f  "a.out.dll"
~~~

--> result a.exe with 38KB and a.out with 533KB --> expected: a.out.dll

Specifying a DLL explicit:

~~~
$ occ.exe -o "a.out.dll" "a.o" --nologo libcob.l -yy
"C:\dev\orangec\bin\olink.exe"  -! /c+ /T:CON32  -yy @tmp00000.$$$
with tmp00000.$$$=
c0xpe.o "a.o"  "/oa.out.dll"  "libcob.l" climp.l clwin.l Running App: "C:\dev\orangec\bin\dlpe.exe" -!  /mCON /f  "a.out.dll"
~~~

--> result a.out.exe with 38KB and a.out.dll with 533KB

I guess other options should be used, please advise, but in general: two output files seems wrong.

**Comment by LADSoft** [comment]
The first problem, with a.out not turning into a.out.dll, is by design.   The filename already has an extension and it isn't replaced.   As I don't know if that is a particularly useful behavior, we could maybe make this an FR for me to review the entire suite of programs to see about changing the design...

The second problem i will fix.

**Comment by LADSoft** [comment]
there are actually two output files, the linker makes an intermediate file which it passes to dlpe.   The problem is the intermediate file is misnamed, it should have a '.rel' extension.

**Comment by LADSoft** [comment]
I'm trying to figure out where you got your examples.   AFAIK OCC doesn't ever append an extension '.dll' to anything.   That is left to dlpe????????   I certainly couldn't duplicate them...

**Comment by GitMensch** [comment]
> The first problem, with a.out not turning into a.out.dll, is by design. The filename already has an extension and it isn't replaced. As I don't know if that is a particularly useful behavior, we could maybe make this an FR for me to review the entire suite of programs to see about changing the design...

It *is* a useful behavior if the specified extension is "known" to the tool actually involved (which would be the case for .dll, .exe, .l, .o, , .obj, .s, .a, .lib), otherwise it looks strange.

> I'm trying to figure out where you got your examples. 

I've got them from the GnuCOBOL test suite which also tests for compiler edge cases that were found in the last 10 years (MSVC for example needs some extra code when calling it - obviously I try to limit new compiler specific extra code to the GnuCOBOL codebase).

> I certainly couldn't duplicate them...

You can't duplicate them with the file attached to the first post using the commands specified there?

**Comment by GitMensch** [comment]
Using current CI build a simple `occ.exe -o "C:\dev\gnucobol\build_orangec\tests\cobol85\EXEC85.exe"              ".\cob2744_0.o"` results in EXEC85.exe and EXEC85.rel. Is this intended? I thought that the .rel was just an intermediate file.

**Comment by LADSoft** [comment]
yeah it is a little vague because olink can also output the results of an intermediate link (without generating and EXE) and this is also in a .rel file.   But I think I can detect when the .rel is being used as an intermediate file...

**Comment by GitMensch** [comment]
@LADSoft : please reopen.

`occ.exe -o "a.out" ".\mymain.o"`

results in a.exe.
Producing "a.out.exe" is the preferred one here, "a.out" would be not ideal but understandable, but directly *dropping* something from a command line option which was explicit specified by the user... seems wrong.
