### ISSUE TITLE
sprintf double and float precision error (misses one digit)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#220]
Given 

```c
#include <stdio.h>

int main () {
	char	wrk[48];
	sprintf (wrk, "%-.16G", 99 + (double) 1 / 3);
	printf("result: '%s'\n", wrk);
	return 0;
}
```

```cmd
C:\test>occ testme.c -nologo
testme.c
C:\test>.\testme.exe
result: '99.33333333333333'
C:\test>occ testme.c --nologo
testme.c
C:\test>.\testme.exe
result: '99.3333333333333'
```

Note: the precision error also exists when changed to (float)

**Comment by chuggafan** [comment]
http://www.jhauser.us/arithmetic/TestFloat.html seems to be a good website about testing this, it links to tybor: http://www.tybor.com/ which seems to have found a few "errors" that are slight within OCC that are there, when I last ran the check it was off by a very tiny factor, but those factors grow.

**Comment by GitMensch** [comment]
@chuggafan Thank you for the reference, I've checked the current results and created #227 as I think this issue presented here (missing precision by 1 in printf) is likely quite easy to fix (and likely also leads to better results for #227) while fixing all parts of #227 likely needs more time (I'd personally still feel uncomfortable to use occ for production with the current test results of #227 when they aren't known to be false positives).

**Comment by GitMensch** [comment]
Also seen in the output of #227 (likely printf issue with hex):

occ outputs

~~~
0X  ffffffff
0X  20
~~~

where GCC outputs

~~~
0xffffffff
0x20
~~~

**Comment by GitMensch** [comment]
@LADSoft - Ping concerning the broken precision by one.

**Comment by LADSoft** [comment]
yeah it hadn't drop totally off my radar...   the only reason I didn't fix it immediately is I was looking into the other fp issue.   Actually, it drops ALL digits after the last one it gave no matter what you set the precision to...   let me go fix it :)

**Comment by GitMensch** [comment]
Rechecked, still an issue for double (one digit missing), *may* be an issue for float (last digit different to gcc/cl):

```sh
$ occ --nologo testme.c

$> ./testme.exe
result d: '99.3333333333333'
result f: '99.33333587646487'

$> gcc testme.c -o testme

$> ./testme.exe
result d: '99.33333333333333'
result f: '99.33333587646484'

$ cl.exe --nologo testme.c 

$> ./testme.exe
result d: '99.33333333333333'
result f: '99.33333587646484'
```

**Comment by LADSoft** [comment]
it is a good thing we looked at this, the grisu3 functions I used represented some floating point values way off.   I replaced grisu3 with the dtoa library people commonly use.
