### ISSUE TITLE
Compiler crash issues

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#222]
I ran into a compiler crash when working on #128 where I was compiling cregex the compiler itself would crash, on my current master branch (https://github.com/chuggafan/OrangeC/commit/9397bd1d04c0f9327c99e4800e332930079a241b) I have run into several issues.

Type_traits for some reason doesn't work (IDK why, but it fails on line 2127)
Utility is weird (__is_swappable should be defined in type_traits, although it isn't officially part of the standard)
__tuple is being even weirder and I don't know why (The error is also duplicating the namespace it's in when printing the namespace, 2 compiler bugs, one error)
There's probably more to this but...

**Comment by chuggafan** [comment]
One of these issues I was able to reproduce:

```cpp
typedef unsigned long long int64_t;
namespace item
{
namespace itemstuff
{
    template <class _Tp> class _LIBCPP_TEMPLATE_VIS tuple_size;
template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    const _Tp,
    typename enable_if<!is_volatile<_Tp>::value>::type,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value> {};

template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    volatile _Tp,
    typename enable_if<!is_const<_Tp>::value>::type,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value> {};

template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    const volatile _Tp,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value> {};
template <typename T, typename Other>
Other item(T stuff)
{
    return static_cast<Other>(stuff);
}
} // namespace itemstuff
} // namespace item

int main()
{
    using item::itemstuff;
    if (0)
        return item::itemstuff::item<int, int64_t>(0);
    return item(0);
}
```
gets me:
```
occ Version 6.0.37.1 Copyright (C) LADSoft 2006-2018

Error( 18)    testing.cpp(10):  Undefined symbol 'is_volatile'
Internal Error - Aborting compile
```

After a fresh compile of occ, of course, the issues should ACTUALLY be:

Undefined symbol: is_volatile,
Undefined symbol: is_const,
Undefined symbol: integral_constant
Undefined symbol: enable_if

**Comment by chuggafan** [comment]
Compiler no longer crashes if you add ```#define _LIBCPP_TEMPLATE_VIS```, so it appears that it has something to do with that, after doing that (and some messing around with some code):

```cpp
typedef unsigned long long int64_t; 
#define _LIBCPP_TEMPLATE_VIS
namespace item
{
namespace itemstuff
{
template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size;
template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    const _Tp,
    typename enable_if<!is_volatile<_Tp>::value>::type,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value>
{
};

template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    volatile _Tp,
    typename enable_if<!is_const<_Tp>::value>::type,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value>
{
};

template <class _Tp>
class _LIBCPP_TEMPLATE_VIS tuple_size<__enable_if_tuple_size_imp<
    const volatile _Tp,
    integral_constant<size_t, sizeof(tuple_size<_Tp>)>>>
    : public integral_constant<size_t, tuple_size<_Tp>::value>
{
};
template <typename T, typename Other>
Other item(T stuff)
{
    return static_cast<Other>(stuff);
}
} // namespace itemstuff
} // namespace item

int main()
{
    using namespace item::itemstuff;
    if (0)
        return item::itemstuff::item<int, int64_t>(0);
    return item(0);
}
```
Gets me:

```
Error( 18)    testing.cpp(12):  Undefined symbol 'is_volatile'
Error( 18)    testing.cpp(21):  Undefined symbol 'is_const'
Error( 18)    testing.cpp(30):  Undefined symbol 'integral_constant'
Error( 18)    testing.cpp(30):  Undefined symbol 'size_t'
Error( 18)    testing.cpp(28):  Undefined symbol '__enable_if_tuple_size_imp'
Error(437)    testing.cpp(29):  Invalid use of type 'int'
Error( 11)    testing.cpp(33):  Syntax error: > expected
Error(229)    testing.cpp(46):  Qualifier 'item' is not a class or namespace in function main
Error( 18)    testing.cpp(46):  Undefined symbol 'itemstuff' in function main
Error(232)    testing.cpp(47):  Could not find a match for 'item(int)' in function main
10 Errors
```

**Comment by LADSoft** [comment]
I should have time to look at the crash issues some more tonite...

**Comment by chuggafan** [comment]
Thanks, I think I'll also go about maneuvering to reduce some of the other issues i'm running into (Notably being found when updating to the latest version of libcxx at it's master branch, which is actually semi-stable, but I just realized after literally committing 90% of it's latest master that I should probably just be using the latest stable release... oops). Should be able to attempt to reduce another crash that seems related to this one, but I'm unsure if it is or not.

**Comment by chuggafan** [comment]
I've found *ANOTHER* crash (whew, moving everything I've worked on directly to libcxx 6.0 seems to have brought out compiler crashes and other goodies, who'd have guessed?) The commit that I found the crash on (When compiling file rnew.cpp ) is https://github.com/chuggafan/OrangeC/commit/a0cdd792d1b03aecad06dfa9dc369d76dd065b9c 

Also an issue with Error 113 detection in stdexcept where things such as ```throw domain_error(__msg);``` get you:
```Error(113)    C:\OrangeC\src\clibs\cpp\libcxx\include\stdexcept(203):  Call of nonfunction in function std::__throw_domain_error(char const *)```

(P.S i'd love some help in building a new "Exception Handler" for LIBCXX so that it could be a drop in, same goes for a new "New" handler as the way new and delete are essentially implemented the same by LIBCXX (and every other library) anyways, if that's possible, then it may also be possible to get LIBCXX to accept a PR for us to be able to slowly work in ORANGEC as a compiler that is supported by LIBCXX (so long as standards conformance is an achievable goal...))

**Comment by LADSoft** [comment]
ok i'll check it out in a little while.   meanwhile I've fixed three or four crashes and a couple of compiler bugs so far....   there is another bug I'm working on :(

**Comment by LADSoft** [comment]
as you can imagine I'm just a little overwhelmed right now...   don't know if the libcxx new/delete would work or not, might have to revisit operator delete [];   right now it saves the number of array elements prior to the malloc'd block and I don't know if any other compiler does that or not...   but yeah I kinda punted on that and the exception handling, at the point I got into it I just didn't want to deal with it so I used something nonstandard!   Definitely open to cleaning that up :)

**Comment by chuggafan** [comment]
Oh yhea, I definitely understand, take as much time as you need to be able to do things at your own pace! Hopefully what could be done is that since OrangeC uses its own name mangling, etc. a preprocessor definition setup could be used in the actual, mainline libcxx so that it is released as well, meaning less work in the long run (maintaining two separate versions), Hopefully this all works out!

**Comment by LADSoft** [comment]
well amazingly enough stdexcept does compile if you configure it right...    trick is that line 739 of __config declares 

>    #define _LIBCPP_EXCEPTION_ABI __attribute__ ((__visibility__("default")))

but as per #137 occ can't handle the __attribute__ qualifiers.   I disabled that by:

> #define _LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS

up at the top where some of the other orangec-specific declarations are and it compiled...   but maybe I need to fix the __attribute__ sooner rather than later?

**Comment by chuggafan** [comment]
Well, it should have actually been giving the qualifier ```__declspec(dllimport)``` or ```__declspec(dllexport)``` instead of ```__attribute__ ((__visibility__("default")))``` due to the fact that _LIBCPP_OBJECT_FORMAT_COFF was being defined, and it in fact does, meaning that the class is being imported (presumably libcxx is attempting to import from the MSVCRT), so I'll change that section, I guess.

**Comment by chuggafan** [comment]
Yhea, when ```_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS``` is defined it seems that 90% of the errors go away and the few that are left are some that should be prioritized, I'm going to do a quick run through with it defined and see how much I can shave off in terms of errors, but it seems mostly that my issue of attention should be ```chrono``` next, oh boy.

**Comment by LADSoft** [comment]
it *looks* like most of the errors in type_traits at this point are actually compiler bugs.  I'm working down through them, it is down to the 'pack' error on line 4531 right now,  which is also bogus.

**Comment by LADSoft** [comment]
i cleaned up a bunch of bugs and while I was at it looked to see if it would crash again, hasn't crashed in a couple of days now so it seems better.   I suspect it needs more from me but for now I'm out of time.   But I also got some insight on the issue with the output files persisting and will look at that before looking at other issues.

**Comment by chuggafan** [comment]
Ok, that sounds great! I'll check out how many bugs are solved from that and see if I find any new crashes, and also see any issues that may pop up.

**Comment by LADSoft** [comment]
:)

**Comment by chuggafan** [comment]
I found *ANOTHER* crash while attempting to investigate another bug that was included in this:

```cpp
#include <type_traits>

struct __tuple_sfinae_base
{
    template <
            template <class, class...> 
                class _Trait,
        class... _LArgs, class... _RArgs>
    static auto __do_test(__tuple_types<_LArgs...>, __tuple_types<_RArgs...>)
        -> __all<typename enable_if<_Trait<_LArgs, _RArgs>::value, bool>::type{true}...>;
    template <template <class...> class>
    static auto __do_test(...) -> false_type;

    template <class _FromArgs, class _ToArgs>
    using __constructible = decltype(__do_test<is_constructible>(_ToArgs{}, _FromArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __convertible = decltype(__do_test<is_convertible>(_FromArgs{}, _ToArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __assignable = decltype(__do_test<is_assignable>(_ToArgs{}, _FromArgs{}));
};
```

Will crash the compiler (it is outputting the correct errors for the segments it's reached)

Doing:
```cpp
#include <type_traits>
template <class ..._Tp> struct __tuple_types {};
struct __tuple_sfinae_base
{
    template <
            template <class, class...> 
                class _Trait,
        class... _LArgs, class... _RArgs>
    static auto __do_test(__tuple_types<_LArgs...>, __tuple_types<_RArgs...>)
        -> __all<typename enable_if<_Trait<_LArgs, _RArgs>::value, bool>::type{true}...>;
    template <template <class...> class>
    static auto __do_test(...) -> false_type;

    template <class _FromArgs, class _ToArgs>
    using __constructible = decltype(__do_test<is_constructible>(_ToArgs{}, _FromArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __convertible = decltype(__do_test<is_convertible>(_FromArgs{}, _ToArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __assignable = decltype(__do_test<is_assignable>(_ToArgs{}, _FromArgs{}));
};
```
Will not crash the compiler (and all the correct errors are output)

This also captures the issue I was attempting to dig into:

```Error(229)    testing.cpp(10):  Qualifier '_Trait' is not a class or namespace```

This error seems to appear due to (I think?) nested templates. (Note, since I am using broken builds to get this stuff I haven't gotten type_traits included)

But this generates a lot of the issues that I think are being run into in the \<utility\> header

```cpp
#include <type_traits>
using namespace std;
template <bool ..._Preds>
struct __all_dummy;

template <bool ..._Pred>
using __all = is_same<__all_dummy<_Pred...>, __all_dummy<((void)_Pred, true)...>>;
template <class ..._Tp> struct __tuple_types {};
struct __tuple_sfinae_base
{
    template <
            template <class, class...> 
                class _Trait,
        class... _LArgs, class... _RArgs>
    static auto __do_test(__tuple_types<_LArgs...>, __tuple_types<_RArgs...>)
        -> 
        __all<
            typename enable_if<
                _Trait<_LArgs, _RArgs>::value, bool
                >::type{true}...
            >;
    template <template <class...> class>
    static auto __do_test(...) -> false_type;

    template <class _FromArgs, class _ToArgs>
    using __constructible = decltype(__do_test<is_constructible>(_ToArgs{}, _FromArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __convertible = decltype(__do_test<is_convertible>(_FromArgs{}, _ToArgs{}));
    template <class _FromArgs, class _ToArgs>
    using __assignable = decltype(__do_test<is_assignable>(_ToArgs{}, _FromArgs{}));
};
```

**Comment by chuggafan** [comment]
Since I haven't found any more crashes, I'm going to close this, but I will definitely be adding more issues that were related but not actually crashes to this as separate issues (and attempt to reduce the issues)
