### ISSUE TITLE
Exporting class issue

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#223]
Here's some code that exposes this issue, it's really simple, but probably a bit harder to parse. https://docs.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes for the docs on exactly what should happen, this is causing issues in the newer versions of libcxx (as it tries to export the definitions of standard exceptions, etc, of which I hope to work on getting the new handlers working well and getting it to be able to use the actual new.cpp from libcxx instead)
```cpp
class __declspec(dllexport) tim {
public:
int i;

}
int main()
{
return 0;
}
```

**Comment by LADSoft** [comment]
I'm thinking this won't be too difficult...   It probably needs to be done for #225 to be viable in the long term anyway :)

**Comment by LADSoft** [comment]
currently working on this one, needs more testing

**Comment by LADSoft** [comment]
Given what you said about libcxx knowing how to put declspec on classes and functions, I got this working well enough to create a dynamic library with c++ code in it and link a simple program against it, however, something I did broke the compile of the library and it crashes when you use it (both as static and dynamic).    Will fix over the next couple of days then release this... change
