### ISSUE TITLE
Adding a method to push/pop macros

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#226]
This is an idea to add a way to push/pop macros from being able to be used, it's useful for when you want to not modify macros that may come later or be in use but still use the exact same name, e.g. I did to fix string.h being weird:
```cpp
#ifdef __cplusplus
#define EXTERN_C extern "C"
#else
#define EXTERN_C
#endif
```
This conflicts with the windows headers you have (although, to be honest, I'm going to work on upgrading those as well, either, having the ability to push/pop macros from the context would be useful, as one could then do this without having to somehow do macro evading techniques that would probably require outside the preprocessor intervention, it's an extremely useful feature, the way MSVC does it is [this](https://docs.microsoft.com/en-us/cpp/preprocessor/push-macro) and the way CLANG does it is [this](https://gist.github.com/kode54/8660691) (same way). I'll look into doing this myself hopefully after I get some more work done on upgrading the library.

**Comment by GitMensch** [comment]
Also [supported by GCC](https://gcc.gnu.org/onlinedocs/gcc/Push_002fPop-Macro-Pragmas.html) "for compatibility with Microsoft Windows compilers".
