### ISSUE TITLE
occ hangs when an overloaded function call another overload of itself

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#23]
Here is the minimal code where I stepped on the problem. This is C++, and defined in a header file. It hangs only when compiling a cpp file that call the function (doesn't hang if code is just included without being called). Hang with latest version of occ, but I think it was already hanging one year ago (I did not report it because C++ was not officialy supported yet)

```C
void blit(SDL_Surface *image, int x, int y, SDL_Surface *dest)
{ ... }

void blit(SDL_Surface *image, int x, int y)
{
	blit(image, x, y, screen);
}
```
Replacing the second `blit` by `blit_on_screen` (without updating any other code) removed the hang (and generated normal errors).

**Comment by LADSoft** [comment]
Hi Lionfaith,

Which version of the SDL library are you using?

Thanks,

David

lionfaith wrote:

**Comment by lionfaith** [comment]
SDL 1.2.14

**Comment by LADSoft** [comment]
Hi Lionfaith,

I have been so far unable to duplicate your issue;  can you confirm that 
the small snippet you gave me is enough assuming I use the SDL_video.h 
file?

I also tried some simple blitting code in the body of the first blit() 
in case I could duplicate it with a function body.   I tried a couple of 
other things as well but so far no luck.

I am wondering if you had compiled this snippet as part of a larger 
program and something in the larger program was somehow affecting the 
behavior of the compiler?

And I've been assuming this is the compiler that has been hanging, not 
the linker?

Also are there any special #defines you use for compiling the SDL 
code?   I figured out you probably use /D__WIN32__ but I don't know if 
there is anything else.

Thanks,

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Sorry, my fault. Gone to conclusions too quickly, I made a bad diagnostic.
I still have a file on which occ either hangs or is incredibly long to complete.
I'm still working on this.

**Comment by lionfaith** [comment]
There is one specific file I'm compiling which take a tremendous long time to compile: 41 seconds. It was completely unexpected and I thought occ was hanging. And in this specific file, it's one specific function which is responsible for a great part of it.
Here is what it looks like:
```C++
void createOptions(SDL_Surface *optionsSurface)
{
	SDL_FillRect(optionsSurface, NULL, graphics.black);
	
	
	graphics.blevelRect(optionsSurface, 0, 0, optionsSurface->w - 2, optionsSurface->h - 2, 0x00, 0x00, 0x44);
	
	
	graphics.drawString("++ OPTIONS ++", 105, 8, FONT_WHITE, optionsSurface);
	
	graphics.blevelRect(optionsSurface, 190, 45, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 250, 45, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 20, 45, 150, 22, 0x00, 0x00, 0x00);
	if (currentGame.useSound)
		graphics.blevelRect(optionsSurface, 190, 45, 50, 22, 0xff, 0x00, 0x00);
	else
		graphics.blevelRect(optionsSurface, 250, 45, 50, 22, 0xff, 0x00, 0x00);
	graphics.drawString("ON", 207, 50, FONT_WHITE, optionsSurface);
	graphics.drawString("OFF", 263, 50, FONT_WHITE, optionsSurface);
	graphics.drawString("SOUND", 30, 50, FONT_WHITE, optionsSurface);
	
	graphics.blevelRect(optionsSurface, 190, 95, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 250, 95, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 20, 95, 150, 22, 0x00, 0x00, 0x00);
	if (currentGame.useMusic)
		graphics.blevelRect(optionsSurface, 190, 95, 50, 22, 0xff, 0x00, 0x00);
	else
		graphics.blevelRect(optionsSurface, 250, 95, 50, 22, 0xff, 0x00, 0x00);
	graphics.drawString("ON", 207, 100, FONT_WHITE, optionsSurface);
	graphics.drawString("OFF", 263, 100, FONT_WHITE, optionsSurface);
	graphics.drawString("MUSIC", 30, 100, FONT_WHITE, optionsSurface);

 	graphics.blevelRect(optionsSurface, 190, 145, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 250, 145, 50, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 20, 145, 150, 22, 0x00, 0x00, 0x00);
	if (currentGame.fullScreen)
		graphics.blevelRect(optionsSurface, 190, 145, 50, 22, 0xff, 0x00, 0x00);
	else
		graphics.blevelRect(optionsSurface, 250, 145, 50, 22, 0xff, 0x00, 0x00);
	graphics.drawString("ON", 207, 150, FONT_WHITE, optionsSurface);
	graphics.drawString("OFF", 263, 150, FONT_WHITE, optionsSurface);
	graphics.drawString("FULLSCREEN", 30, 150, FONT_WHITE, optionsSurface);

	graphics.blevelRect(optionsSurface, 20, 195, 150, 22, 0x00, 0x00, 0x00);
	graphics.blevelRect(optionsSurface, 190, 195, 110, 22, 0x00, 0x00, 0x00);
	if (currentGame.autoSaveSlot == -1)
	{
		graphics.drawString("NONE", 225, 200, FONT_WHITE, optionsSurface);
	}
	else
	{
		char string[] = "Slot %d";
		sprintf(string, "Slot %d", currentGame.autoSaveSlot + 1);
		graphics.blevelRect(optionsSurface, 190, 195, 110, 22, 0xff, 0x00, 0x00);
		graphics.drawString(string, 225, 200, FONT_WHITE, optionsSurface);
	}
	graphics.drawString("AUTOSAVE SLOT", 30, 200, FONT_WHITE, optionsSurface);
}
```
blevelRect and drawString calls easily adds to the compilation time one second each. The "ifs" generally adds 5 seconds. The cause being blevelRect and drawString are part of Graphics class, declared in it, and as so, they are inlined. I have de-inlined those two specific methods and compile time reduced from 41 seconds to 5 seconds.

Ok... so, it's not a bug then... may I ask you if there is room to make occ compile inlined methods faster?

(note: it's "occ /c", so it's not the linker. I don't use /D__WIN32__ , not yet at least. Last time, I remember I directly changed SDL include files to adapts to occ. Not sure if it's still needed.)

**Comment by LADSoft** [comment]
Hi lionfaith,

Thanks for clarifying the issue.

I think that is the optimizer...  repetative inlining ballons internal 
structures used by the optimizer and slows it down incredibly.  The fix 
is somewhat complex which is why I didn't do it immediately when I 
discovered it a few weeks ago.   Rather I tried but the solution was 
just ballooning and I didn't have a lot of time...

I will look into trying to get this fixed for good.   It may take some 
time though.   I would suggest the /O- switch but I found out today that 
for at least some C++ programs that just causes runtime issues.   I'm 
working on that too...

David

lionfaith wrote:

**Comment by lionfaith** [comment]
I can work around this problem until it's fixed. Not a big deal for me.
Thanks for your answer!
Thank you for your work.

Lionel

**Comment by LADSoft** [comment]
Hi Lionfaith,

I'm having a major release of the IDE in a few weeks mostly to fully 
support C++ but adds other new features as well.   I plan to have this 
fixed at the same time.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
That's good news!
Thanks!

**Comment by LADSoft** [comment]
Hi Lionfaith,

I've put up a new version 6.00.01 now.

I was able to speed up compiling quite a bit, but it can still be 
somewhat slow on problematic programs.   My test program went from 25 
seconds to 8 seconds...    I was wondering if you could try it on your 
test program and see if there is any improvement?

Thanks,

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Ok, I've put these two functions back to inlining... Really fast now! The offensing file now takes 1.714 seconds to compile. (timed with Measure-Command of Windows Power Shell).

Well done!
