### ISSUE TITLE
assembler question - how to define global symbols?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#231]
This is a follow-up to #173 .

Given the following code:

```asm
	.data
	.globl	foo
	data4	0
foo
	data1	0
```

oasm complains:

> Error test.s(5): Label 'foo' already exists.

Isn't the purpose of `.globl` to specify that the label `foo` should be externalized?

**Comment by LADSoft** [comment]
hm I've never heard of .globl before, probably why it isn't in there :).  the assembler accepts either 'global xxx' or [global xxx] as it stands.    But I will add it later this week...   anything else you can think of while I'm at it?

**Comment by GitMensch** [comment]
Hm, `.globl` is included in this repository at https://github.com/LADSoft/OrangeC/blob/24a72984bb1a3874a6c17d15a6b8066e88370dbb/tests/alexcs/test.cmpx - is it compiled, too?

> But I will add it later this week... anything else you can think of while I'm at it?

Despite `.file` which I didn't checked for implementation: it looks like the assembler just "skipped" the unknown `.globl` - I think it should error on unknown directives (or at least do so when a compiler switch is used, which may be a good idea in general when the behavior changes / would change otherwise).

Note: nearly *all* assembler issues I've raised are just the results of inspecting the results of the MPIR configuration script. I'll recheck after this issue is closed.

**Comment by LADSoft** [comment]
the problem is the assembler treats the '.' characters as a valid identifier prefix.   directives are actually defined with brackets [global xxx]  but macros turn them into psuedo-directives similar to what is found in other assemblers by taking advantage of the '.' in labels thing...   so 'warning' about misplaced directives isn't really viable unless I check for all the possible directives...

**Comment by LADSoft** [comment]
BTW the test program generated by alex's compiler isn't targeted for this assembler...   the point of that program was to form a C++ program to be compiled by occ.

**Comment by GitMensch** [comment]
The fix doesn't seem to work (the error message changed, but oasm still cannot process the file):

```asm
	.data
	.globl	foo
	.word	0
foo
	data1	0
```

~~~
Error conftest.s(4): identifier expected
Error (0): Undefined public 'foo'
~~~

**Comment by LADSoft** [comment]
the problem here isn't the .globl directive, it is the .word directive (which isn't known at present).   Since you've asked me to review #171 and also added #236 I'll deal with it separately from this issue.
