### ISSUE TITLE
LSCRTL - test by linking package against it

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#234]
LSCRTL supports C++ now, add a build test to the CI builds that links the package against it.

**Comment by GitMensch** [comment]
... and ideally also ein the resulted binary as the previous tests showed that linking worked but the runtime functions were borked.

**Comment by LADSoft** [comment]
yeah I was debating whether to use it as the first stage of the build (so that when linked with LSCRTL it builds everything and then goes back to normal builds) or whether to just pull the trigger and add a fourth build environment to have it build itself several times the way we do with other things :)

**Comment by GitMensch** [comment]
Marvelous, I'll likely try to rerun the GnuCOBOL testsuite to see if there are any different issues than the link against the static library (currently the MinGW Ci build fails, but the MS one works).
