### ISSUE TITLE
Issue with variadic templates

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#242]
Another one blocking me from updating the library:

```cpp
#define _LIBCPP_CONSTEXPR constexpr
#define _NOEXCEPT noexcept
template <class _Tp, _Tp __v>
struct integral_constant
{
    static _LIBCPP_CONSTEXPR const _Tp      value = __v;
    typedef _Tp               value_type;
    typedef integral_constant type;
        _LIBCPP_CONSTEXPR operator value_type() const _NOEXCEPT {return value;}
#if _LIBCPP_STD_VER > 11
         constexpr value_type operator ()() const _NOEXCEPT {return value;}
#endif
};

template <class _Tp, _Tp __v>
_LIBCPP_CONSTEXPR const _Tp integral_constant<_Tp, __v>::value;

#if _LIBCPP_STD_VER > 14
template <bool __b>
using bool_constant = integral_constant<bool, __b>;
#define _LIBCPP_BOOL_CONSTANT(__b) bool_constant<(__b)>
#else
#define _LIBCPP_BOOL_CONSTANT(__b) integral_constant<bool,(__b)>
#endif

typedef _LIBCPP_BOOL_CONSTANT(true)  true_type;
typedef _LIBCPP_BOOL_CONSTANT(false) false_type;

template <class _Tp, class _Up>
struct is_same : public false_type
{
};
template <class _Tp>
struct is_same<_Tp, _Tp> : public true_type
{
};
template <bool... _Preds>
struct __all_dummy;

template <bool... _Pred>
using __all = is_same<__all_dummy<_Pred...>, __all_dummy<((void)_Pred, true)...>>;
template <class... _Tp>
struct __lazy_all : __all<_Tp::value...>
{
};
```
Compiles fine in microsoft's CL, but gives me:
```Error( 11)    testing2.cpp(43):  Syntax error: > expected```
when I try to get OCC to compile it, I may look into it after I look at other issues that are causing problems on my attempts to update libcxx

**Comment by LADSoft** [comment]
i got deeply mired in this one...   it was easy to make it compile but isn't at all simple to get it to evaluate properly.    After fixing several bugs i'm at the point where the ((void)_Pred, true) thing is a killer...   still have some code to add to support it.   And I'm sure I'm breaking a dozen other things in the process of fixing this....    well back to it soon I guess :smile:

**Comment by LADSoft** [comment]
I'm making good progress on this now... fixed two out of three bugs that were keeping it from working.   The other bug is probably going to be easy to fix, should do it over the next couple of days.

**Comment by chuggafan** [comment]
It appears one of your changes actually made it partially worse, when attempting to compile algorithm.cpp from libcxx7, instead of displaying any error diagnostics, it actually just crashes, I'll look into this further when I'm not half asleep, but I'll attempt to pinpoint the issue at hand and see what part of your commit did this.

**Comment by chuggafan** [comment]
Whelp, I've looked into it, and it seems my NASMCHANGES did this, so I'll mention that on the PR
