### ISSUE TITLE
Recursively evaluated constexpr functions do not evaluate to constexpr

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#243]
Seems like an oddball one but this popped up into the pipeline when compiling libcxx:

```cpp

using size_t = decltype(sizeof(char));
static constexpr size_t __not_found = -1;
static constexpr size_t __ambiguous = __not_found - 1;
inline constexpr size_t __find_idx_return(size_t __curr_i, size_t __res, bool __matches)
{
    return !__matches ? __res : (__res == __not_found ? __curr_i : __ambiguous);
}
template <size_t _Nx>
inline constexpr size_t __find_idx(size_t __i, const bool (&__matches)[_Nx])
{
    return __i == _Nx ? __not_found : __find_idx_return(__i, __find_idx(__i + 1, __matches), __matches[__i]);
}
```
This shows it off (this is exactly the issue being found in libcxx)

**Comment by LADSoft** [comment]
I'm thinking about rearranging my commitments to get to the assembler possibly this week, but wondered if you needed this fixed before I do that ?

**Comment by chuggafan** [comment]
I'm currently fine with the way it is, it may be a blocking change but I also think I can modify the source to allow for 1. recursively evaluating the stuff and 2. adding a limit on recursive evaluation.

The latter should be easier, but I haven't really been focusing on this task much anyways...

**Comment by chuggafan** [comment]
Ok, so I think I figured out how to fix this and am adding a (hopefully working) regression test for this and the fix in an upcoming PR.
