### ISSUE TITLE
Re-Writing the preprocessor for better error diagnostics

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#245]
One of the brick walls of improvements I've run into recently is the fact that I want to finer grain error diagnostics (e.g. not just line, but also column location). I've currently setup how it'd be (possible) to start a foundation to allow this in my rewrite branch, however the method that all tokens, symbols, and lines are parsed absolutely disagrees with this fundamentally, since each token isn't parsed individually on a line, and lines as best as I can tell are pushed into the parser which then doesn't keep track of how far up the line it has gotten. This would require a big rewrite of how tokens are parsed, and this should probably be done at the same time as #244 to make things as simple as possible.

I sincerely hope this can get through ASAP, that way I can use those diagnostics during the re-write (although I've mostly been namspacing things and trying to figure out how I'll parse individual tokens with the pre-processor setup, I think I have most of the ideas down, just need to get more features into the pre-processor first)

**Comment by LADSoft** [comment]
I don't *think* it would be a big rewrite to get the position on a line.   For example add a 'charpos' to the INCLUDES struct and update it in getline().    Then add a 'charpos' to the LEXEME struct and make sure it gets updated with the token position right before parsing each token.   But also update it properly in all the other places it gets set...    Then I think both symbols and statement structures have line number information so add charpos there as well and make sure it gets updated any time line number info is updated.

Then we may also want to update various things like browse information and debug information but that can come a little later :)

I little involved detailwise but not a total rewrite....

**Comment by chuggafan** [comment]
Yhea, I was thinking that, it's just confusing when going through the source of how to do it, I still have to do a fix where I change it to add token lookback for the tokenizer, so I'll just store where the token start is in tokens and then parse everything from those.

**Comment by LADSoft** [comment]
I'm thinking about adding token positions early in the preprocessor, and keeping track of two sets of them; one for the original line and one for the preprocessed line.   The original line data could be used in diagnostics, debug information, browse information, etc...   whereas the preprocessed line set would be used primarily for backtracking to the original line set (e.g. you are in the middle of processing the source code for expanded macro but want to know where the original token began in the actual source line as typed).

Does this sound reasonable?

**Comment by chuggafan** [comment]
Yhea, I believe this might be what's done in other compilers but I'm not exactly sure. If we're not going that route then having a weirder setup that basically we're "internally" replacing into the macro and that each instance gets called into an internal compiler function, and if there's an error it can easily be found to be related....  We might be able to do it by having a _Pragma replacement area that marks macro expansion/end and what macro did it... (this would take a long time due to lookups, so I don't recommend it).

**Comment by GitMensch** [comment]
> Does this sound reasonable?

Yes. Actually you'd only need an "extended" token:

* file
* original line
* preprocessed line

The last entry will be filled in later (and potentially be overwritten again), the others are effectively a const variable.

**Comment by LADSoft** [comment]
the fix for this originates in the preprocessor but fills new fields in the compiler tokens with character position start and end values (relative to the original line).   It also adds a field to hold the original line data.

This issue left redundant information in the tokens, and also it seems that the line caching should be reworked to use the original line throughout instead of the preprocessed lines.   Rather than address it here I opened issue #290.
