### ISSUE TITLE
Re-work the exception handler to work better with libcxx

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#248]
The current way the exception handler and RTTI is implemented is problematic for working with libcxx, as it's able to be used for our implementations of new, delete, type_info (with minor modifications, submittable as patches to libcxx), and using initializer_list that is given by libcxx (since it doesn't have the RTL_FUNC (which I don't understand why it's in initializer_list) stuff, and it doesn't use the versioning namespace as well), being able to move all of the basic stuff off of us and our end (which is not only annoying but counterintuitive and makes us do more work overall) instead of having an ABI that they access to and then we update that instead of having to change how the library works each time, overall is better for maintaining the library section of the toolchain.

It's a lot of work but I've been silently attempting to work on it inside of the entire "Update the compiler" stuff I've been doing. I've been trying to do it in conjuction with everything else.

Speaking of which, being able to use the CMAKE defines for libcxx to give finer grain control over what we're compiling, give libcxx explicit 32 bit support and turn off their 128 size int types stuff with filesystem, however, doing this means taking the latest libcxx and then patching it a lot, (in my opinion) doing this then submitting patches to LLVM so that we can use libcxx properly as well would help us greatly.

**Comment by LADSoft** [comment]
ok, all of this sounds good to me!

**Comment by chuggafan** [comment]
Ok, so I think I hit a roadblock:

We currently do not have an implementation of exception_ptr, which is actually blocking full *c++11* support:


https://en.cppreference.com/w/cpp/error/exception_ptr

We also lack std::nested_exception:

https://en.cppreference.com/w/cpp/error/nested_exception

https://en.cppreference.com/w/cpp/header/exception for full \<exception\> header stuff

Personally, I don't understand the RTTI implementation enough to be able to extend it this far, if you could help with that it'd be great.

Another blocking thing on libcxx is that it assumes you have full \<atomic\> support, so I'll have to work on that beforehand.

Once these library issues are pushed out of the way I believe we'll be set enough we could send a patch to LLVM and see if we will stop having to make such large amounts of modifications every time they decide to change (some) defines. I'd be happy to be able to maintain the libcxx stuff over there and focus on the compiler over here. And it'll be great to actually be able to test the entire compiler each time against the library itself.

**Comment by chuggafan** [comment]
Now that we're on the milestone 3 this is the top priority issue because the current implementation of the exception handler (and all the various support tools) that are expected by libcxx to exist by way of itself just doesn't. So we should start with this issue in all honesty (atomic support we "have", just we need to add the "atomic support" found [here](https://github.com/llvm/llvm-project/blob/57b08b0944046a6a57ee9b7b479181f548a5b9b4/libcxx/src/include/atomic_support.h) so that the fallbacks compile).

There's a lot of handlers here and this is probably the most complex issue to deal with for milestone 3 so I suggest that working on this to get it out of the way first would be top priority.

I still don't understand exactly what I would have to change to get our exception system to support the libcxx stuff, so I'm going to stay away from that.

**Comment by LADSoft** [comment]
actually I was thinking maybe libcxx10 first, because I don't know if there will be changes to the abi between libcxx7 and libcxx10 and there is no point doing it twice.   At least that is the way it seems to me.

I've started working on that and made some progress last weekend, right now I'm distracted with #510 though...

yeah I haven't looked closely enough to see what kind of changes are needed...

**Comment by chuggafan** [comment]
I don't think exception "ABI" or at least what we need to implement has changed at all from 7 to 10. But yhea it's either getting compilation to actually work with us or doing this first tbh. Everything else kinda depends on these two being figured out properly.

**Comment by LADSoft** [comment]
I started researching this, seems for exception handling like we just thave to have the compiler call functions out of the ABI at the right time...   if they did what I think they might have done with 'catch' blocks it will be really nice because whar we've got now isn't very clean.    But it will cause a change to the code generation...    butwe could get rid of a lot of messy stuff out of rtti.cpp as well as some ugly things in the RTL...   and it would be another target for what is an unlikely branch lol...   here is hoping!

**Comment by LADSoft** [comment]
this is up next...  I'm taking a break from #355...

**Comment by LADSoft** [comment]
compiling libunwind and libcxxabi right now.   There are a lot of bugs but mostly easy to deal with...

**Comment by chuggafan** [comment]
We don't *necessarily* need libunwind and libcxxabi, we just need to support exception_ptr and throwing multiple exceptions. We can still roll our own exceptions other than that.

**Comment by LADSoft** [comment]
i've got this mostly worked out, there seem to be some issues with 'nested_exception' and the integer returning uncaught_exceptions, I don't match what either msvc or clang do.   I can't see how they could be right but oh well...  on those compilers uncaught_exceptions() always returns one and you can't catch things derived from nested_exception without the (...) clause...   I also was reworking the thread_local variables so you could use constructors and destructors with them.   The final issue is that the two versions of the compiler don't match during the build, presumably has something to do with thread_local variables...   will look into it soon...

**Comment by LADSoft** [comment]
i was on vacation last week which is why I got so much done...   back to my real job this week :smile:
