### ISSUE TITLE
ocide crashed at creating a new work area

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#25]
Hi!
I've got problem with OrangeC6, zip version.

ocide crash when I do:

1. click file then new work area
2. click on the three dots to choose another place
3. select a directory of mine "C:\usr\dev\starfighter\lion-0.1"
4. click ok then ocide crashes

Hope it helps,
Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

Thanks for reporting this,

this is another case where it worked with BCC32 but not the microsoft 
compiler sigh.    But it was a bug that needed to be fixed anyway...

I put up a new version 6.02 which addresses it.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Ok, ocide doesn't crash anymore.
So fast! Thank you!

Lionfaith
