### ISSUE TITLE
C11 atomics don't codegen properly

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#250]
I was looking into clang and GCC's C11 atomics for interesting reasons (I discovered that OCC (if the codegen worked) had better 32 bit Long Long codegen on CLANG!) https://godbolt.org/z/TXnhMm for more info on how the 3 major compilers implement this, GCC seems to be the best bet for any of it as they have guaranteed lockless long longs) and I was doing testing on how good the code generation was (as is reasonable, needing to see whether or not something works is a good thing) and I have discovered that there is no (good) lockless code generation for OCC's atomics, as well as that they crash often and do not work properly, and that the current OCC has a non-conformant <stdatomic.h>

First, on the stdatomic.h:
It lacks the functions:
`atomic_exchange
atomic_exchange_explicit
atomic_compare_exchange_strong
atomic_compare_exchange_strong_explicit
atomic_compare_exchange_weak
atomic_compare_exchange_weak_explicit`

Altogether, although the macros that are defined for their equivalents are there, that is non-standard.

Secondly, there is no lockless implementation of *any* of the types, while GCC on the *i386* can give lockless implementations at least some of the time, and for the *i486* only has trouble with long longs, when gcc is compiling for the pentium it can guarantee that all standard types are lock free. 

Third and most importantly:

Attempting to use atomics does not work very well, after I had made minor modifications to stdatomic.h to give it full C11 standard compatibility, I had attempted to compile and run one of GCC's c11 atomic test programs, here is the program I tested (slightly modified to give better diagnostics when run):

```c
#include <stdatomic.h>
#include <stdio.h>
extern void abort (void);
#define INCREMENT(var) printf("Iteration that works: "); printf("%u\n", (var)); (var)++;
atomic_char v;
char count, ret;

int
main ()
{
  v = 1;
  count = 1;
  printf("Beginning\n");
  if (atomic_exchange_explicit (&v, count + 1, memory_order_relaxed) != count)
    abort ();
  INCREMENT(count);

  if (atomic_exchange_explicit (&v, count + 1, memory_order_acquire) != count)
    abort ();
  INCREMENT(count);

  if (atomic_exchange_explicit (&v, count + 1, memory_order_release) != count)
    abort ();
  INCREMENT(count);

  if (atomic_exchange_explicit (&v, count + 1, memory_order_acq_rel) != count)
    abort ();
  INCREMENT(count);

  if (atomic_exchange_explicit (&v, count + 1, memory_order_seq_cst) != count)
    abort ();
  INCREMENT(count);

  INCREMENT(count);

  ret = atomic_exchange (&v, count);
  if (ret != count - 1 || v != count)
    abort ();

  return 0;
}
```

This program behaves unexpectantly, giving me the results:
```
Beginning
Iteration that works: 1

Abnormal program termination
```
when it should, in fact, run all the way through.

**Comment by LADSoft** [comment]
I'm afraid I dropped the ball on C99's atomics...   first off i implemented off of a draft rather than the actual standard which apparently wasn't the thing to do...   and second I didn't test it very well...   maybe wasn't sure how?

By the time I got to C++11 I knew I had to buy the standard if I was going to implement the language properly but back in 2011 or 2012 when I implemented C99 I wasn't thinking that way...

**Comment by chuggafan** [comment]
Well, there's actual standard drafts online for free nowadays if you need it. http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf for the C11 standard, http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf for the C17/18, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf c++14, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf c++17, all of these are not the "ISO Store" version, however all of them *ARE* the final drafts, meaning it's only minor edits and they're usable for standard implementation.

Hopefully this can get fixed, that way we can use them so that we can get atomic support for c++ via libcxx.

**Comment by chuggafan** [comment]
Question related to how I'll handle attempting to do this on my own time:

What is the minimum supported CPU for OCC and what do you want it to be?

Linux dropped support for the intel 386 back in 2012, while GCC's support of the atomic operations for it seem... iffy... at best.

I can (probably) get all of the C11 atomics to work on the i386 with a lot of ugly hacks, however this is difficult, though I do have an outline on how to implement it.

The earliest x86 processor that has the cmpxchg instruction (which makes life so much easier to implement atomics) is the i486, and the pentium is the minimum for the 64 bit version of the cmpxchg function (for i486 you'd have to use cmpxchg twice)

CLANG doesn't support anything before pentium, whereas GCC supports the i486 at a minimum it seems (I don't have a spare i386 laying around to actually test GCC with, nor do I think I'd like to see the compilation times on it). MSVC supports a minimum of pentium processors (? they're unclear on their docs).

Knowing what is vs isn't going to be supported helps with making choices on how to implement atomics.

If you want to support earlier processors than the Pentium yet don't want to do the support for atomics and you don't think I should go through the trouble, I can always make it so that the support for atomics is "officially" dropped by just getting __STDC_NO_ATOMICS__ defined and then making stdatomic.h error when it is defined.

**Comment by GitMensch** [comment]
As there's GCC for older environment and there'll be always a (possibly older) version of mingw-gcc available I'd vote to officially drop support for any processor older than 2008.

**Comment by LADSoft** [comment]
yeah that is what I was thinking, a recent Pentium version would be fine.   There is no point in trying to support architectures that existed before the turn of the century...   circa 2008 sounds good?

**Comment by GitMensch** [comment]
@chuggafan We already found that old architectures (like "P1", 1993) have enough support on Win32 via gcc-mingw32 and that we don't need to support them.

I vote for keeping the assembler code as clean as possible and not support anything before "Core" (2006) / AMD K7 (2003 as Athlon64/Opteron/Phenom).

**Comment by LADSoft** [comment]
I tend to agree with GitMensch, we are already giving up 386 and 486, might as well work with a version of the pentium that is more recent as well.

That said I already had support for CMPXCHG8B in the compiler, but the inline assembly for that and CMPXCHG was broken.   I'm fixing that in the next push....   but unless you see a good reason to support the P1 we can defer adding CMPXCHG8B in the assembler until the next round of assembly changes (which should be soon as we need to address #227 in the relatively near future)

**Comment by chuggafan** [comment]
If we're going to be working with a recent version of the pentium, the latest version the assembler supports is the pentium I, so we'd need to wait on the assembler to at the very least have MMX, hopefully SSE instructions, and for the optimizer to generate legitimately useful code in the face of branch prediction (more branches = worse code, more random branches = even worse, this holds true starting from the P5 microarch, which is the Pentium I, where speculative execution was first introduced into the Intel chip lineup) we'd have to take out even more through it all.

That being said, any hopes of getting past i486/Pentium I support atm essentially hinges on #227 

As well, the atomics support internally should at some places already requires Pentium I support for Unsigned Long Longs, specifically line 4433 in gen.c, so we already have a mandatory minimum for C11 atomics of the pentium I lineup.

**Comment by LADSoft** [comment]
I agree that the branch problem needs to be addressed for later versions HOWEVER it is not a show stopper the way #227 is.   I'm still planning on cleaning up some stuff then going back for that pretty soon...   right now I'm working on @GitMensch 's suggestion for testing the assembler with a separate build, which is also going to be essential to the success of #227...   it is coming along well should have it today or tomorrow unless there are a bunch of unforeseen issues.

Another thing that is probably going to have to happen is that the assembler core be rolled into the compiler somehow,   I've thought of that before but never gotten around to it.    But if we don't do that then all the MMX/SSE instructions we are going to implement have to be implemented twice...

**Comment by chuggafan** [comment]
I completely agree with all of that.

What we could do with the assembler parsing section is take a page from how Clang does it, https://github.com/llvm-mirror/clang/blob/master/lib/Parse/ParseStmtAsm.cpp where the MC generator has the list of instructions it can generate and the parsing of it is handed off to the ASM parser from LLVM to do it, which allows them to check if the platform they're targeting supports the instructions or not. The main issues with doing such a thing at this moment is 1, OASM is in c++ and OCC is in C, 2 OASM would need a major re-write to support such a thing (I believe), 3. OCC would need a similarly major re-write, which is heavily related to #235 (I have been making small steps on this one (though still with the same roadblock), I swear!)

**Comment by LADSoft** [comment]
The parsing/object file generate code could be ported into the compiler fairly easily, I think.   The main problem being that to actually get it to work the compiler might have to generate at least part of the text for the assembly statements, so it can be parsed out again.   Of course it would take some sort of thunks to go between the C and C++ code but that shouldn't be too bad other than being a lot of details.

But there is a way around having to generate and then reparse text.  Basically, rewrite the ADL code generator so that instead of creating a monolothic parsing/binary output module, it splits the duties.   It could tokenize the input stream and create a list of instructions similar to the one in the compiler in one pass, then generate the binary codes in another.    Long term that would give us the greatest flexibility in how to assemble instructions while allowing for some modicum of reasonable performance.

But I don't know if we should bite that off now, it could take several weeks and for the moment it seems more useful to get support for new instruction sets in than deal with that.   So I guess I'm proposing an interim solution where we use the existing compiler backend to generate text, then use the existing assembler back end to parse the text again and generate the binary output.    Not too pretty, but might work as an interim solution especially as we seem to be piling things up that can't happen until we get new instructions assembled...

**Comment by LADSoft** [comment]
I'm working on redoing the atomic code gen.   Maybe I'll have it in a couple of days...

**Comment by chuggafan** [comment]
Thank you! Sounds like we'll then be able to implement the C++11 atomics as well, right? Hopefully, at least...

**Comment by LADSoft** [comment]
I've got this implemented but haven't finished testing.   The main reason for the current push is to see if I can get traction on the appveyor build/test errors.

**Comment by LADSoft** [comment]
my current working build passes most of the tests from the GNU atomic test suite.   I need to get support for complex numbers and structures working yet though...   should have it this weekend.

**Comment by LADSoft** [comment]
on the C++11 atomics, I'm thinking add it when going to C++17 (#147).    We also need thread/mutex support which should get added at the same time.    Maybe I'll plan to do that before too much longer...   but I want to clear out some of the other issues first...

**Comment by chuggafan** [comment]
Well, I was feeling that since the atomics for C11 are directly translatable to the atomics for C++11, the only thing we'd have to do is make a wrapper for them so that libcxx accepts it. Once that's done (and all the other stuff related to making the library co-operate here) we can take our changes and submit them to libcxx to make it so that we can just use an official libcxx version directly rather than applying our own patches to it.

**Comment by LADSoft** [comment]
that sounds good.   I like your idea of getting OCC recognized natively by libcxx :)

**Comment by LADSoft** [comment]
I think this is mostly done, just waiting to fix whatever the floating point problem is in the latest build :(.   If I have to guess it has to do with complex numbers...   I will probably have that tonite but the push may be delayed as I rewrote the sources in the meantime but wasn't smart enough to do it on a separate branch.   So now I have to get it working again.   Sigh.
