### ISSUE TITLE
Unkown Subnormal minimum value

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#253]
This is related to me updating the library, as <limits> requires to know the minimum denormalized value for a number (technically subnormalized, but whatever).

https://en.cppreference.com/w/c/types/limits

C also apparently needs the macros:
```
FLT_TRUE_MIN
DBL_TRUE_MIN
LDBL_TRUE_MIN
```

Defined to be the true minimum values for a type, aka the denormalized value, of which we don't have and I do not know how to find.

**Comment by LADSoft** [comment]
we should be able to do the minimum denormal value with the 'hex' floating point format pretty easily...   that is my preferred way to make sure all the bits are right.    I will look at it later...
