### ISSUE TITLE
FR ocide: open cwa as workspace

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#258]
Doing `ocide my.cwa` opens ocide and inside my.cwa as text file. Expected behavior: ocide is open and has my.cwa as workspace loaded

**Comment by GitMensch** [comment]
Changed behavior with current dev artifact:

* cwa opens as text file
* the projects start to get loaded and each one errors with
```
---------------------------
Load Error
---------------------------
Project File my.exe Not Found
---------------------------
OK   
---------------------------
```

Note: If ocide is opened first and then the cwa is opened by Menu File->Open Work Area... everything is fine. But as it is much more easy to switch to the correct work area with a double click the FR stays open (at least for me).

**Comment by LADSoft** [comment]
in LADSoft/OrangeC#127 we added a switch for this...   but I will see about auto-detecting that it is a workspace file by checking the extension :)
