### ISSUE TITLE
FR: add all options to --help 

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#260]
`occ --help` misses some of the options mentioned in the docs. It would be nice if there would be an option to show all options, maybe `occ --help=all`?

**Comment by GitMensch** [comment]
ping @LADSoft (without rechecking if this is till an issue)

**Comment by GitMensch** [comment]
Note: this does not only apply to `occ`.

**Comment by LADSoft** [comment]
I'll push a fix to this either tonite or tomorrow, went through all the applications and made sure the help displays were up to date.

note that omake and ogrep don't show extended help by default but always had a switch '?' to allow it.   I also added --help to do the same thing on those two products; the other products do help by default with an empty command line.
