### ISSUE TITLE
olink Access Violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#262]
~~~
Access Violation:(d:\dev\orangec\bin\olink.exe)
CS:EIP 0023:0041EB49  SS:ESP 002B:0019EECC
EAX: 00000008  EBX: 00401000  ECX: 0019F0BC  EDX: 00000000  flags: 00010202
EBP: 00446178  ESI: 0019F378  EDI: FFFFFFFF
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

Happened when rebuilding a project with ocide. Note: reproducible, happens only in Build type "Debug" (no error in Release).

**Comment by LADSoft** [comment]
I can't get olink to crash despite running a lot of code through it. but did find that when compiling the entire product with itself (debug enabled) there are a lot of problems with errors in the object files generated by the compiler.   So at a minimum I'll be looking at that and at the non-working test program in conjunction with this issue.   I guess I'll also add an appveyor test case to test compiling the product with itself in debug mode...

Can you still reproduce the crash with olink?   If so can you provide instructions as to how?

FWIW this is the last issue I'm going to work on before returning to #227....

**Comment by GitMensch** [comment]
I've reproduced it two weeks ago using current release. I can retest with an appveyor artifact in the next days.

**Comment by GitMensch** [comment]
Rechecked with most recent artifact, works now.
As this was the last issue before returning to #227 I'm looking forward for an upcoming release, soon ;-)

**Comment by LADSoft** [comment]
there were too other issues found while investigating this issue (see above).   I've resolved one and hope to have the other resolved tonite.    It is about time for a release, isn't it?
