### ISSUE TITLE
error with modulo operator

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#27]
Hello David!
I stepped upon a strange behavior of modulo operator which I could reduce to this sample:
```cpp
#include <stdlib.h>
#include <stdio.h>

class Math {
	private:
		Math(){}
	public:
	static int rrand(int min, int max)
	{
		int r = min;
		max++;
		if ((max - min) == 0)
			return min;
		r += rand() % ( max - min );
		return r;
	}
};

void main(void) {
	printf( "value: %d", Math::rrand(-3,3) );
}
```
Value should be between -3 and 3, but it is as if `%` didn't work. Strangest of all is that making this change:
```cpp
int delta;
r += rand() % ( delta = max - min );
```
did remove the bug from the project I am compiling while it does not remove it from the small excerpt I gave you up above. Putting the definition of `class Math` in a header is not enough to change that fact. I just don't understand what changes the behavior.

I hope it helps,
Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith!

in some contexts, constant propagation for the modulous function was 
behaving incorrectly.   I have fixed it in the 6.04 release on my web site.

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
thanks for the work you do so fast!

It was actually a long standing bug for the game I want to compile. It seems to work pretty well now.

Lionfaith

**Comment by LADSoft** [comment]
Hi lionfaith,

you're welcome!

the vast majority of the time I end up making small tweaks to the 
compiler to fix bugs, it is rare that I have a bug that takes deep 
rework like the ones related to the compile time issue you had recently :)

I really appreciate that you dig into the issues and can usually isolate 
them to a small example;   that makes it much easier on me.

David

lionfaith wrote:
