### ISSUE TITLE
occ Extension Erorr 

### ISSUE THREAD

**Issue by EmilHalim** [LADSoft/OrangeC#273]
The next test example compiled to error asm code 

```
int cmmtest(void)
{
    _EAX = 0x03;
        return _EAX;
}
void main(void)
{
	printf("this program doesn't do anything,\n");
}

```
 the error asm code is
```
; Line 4:	    _EAX = 0x03;

	mov	00h,03h

```
Thanks.

**Comment by chuggafan** [comment]
I don't think that OrangeC extension has existed for quite some time, if you really do need it I can re-implement it, but is it necessary and are you not able to use inline assembly instead?

**Comment by EmilHalim** [comment]
actually , my favorite language was SphinxC-- , which allows using EAX,EBX,.... registers with C code.
but it stopped developing and dead.
So kindly If you de not mind , fixing it ,I will feed some Examples from SphinxC--.
thanks.

**Comment by chuggafan** [comment]
Uhhh, this isn't a SphixC-- compiler, this is a C/C++ compiler, and you're talking about an extension whose only existence being still there is in: old DOS code and the lexer itself. Do you have old legacy code which relies on this feature and you can't easily modify or is it just something you want to toy around with for fun?

**Comment by EmilHalim** [comment]
Yes , I know that it is C/C++.
the point is using those features allows you access register and code in easy way and funny.
here is an c-- function example,  
```
void	RemoveFileExt(dword lpFileName)
{
	lstrlen(lpFileName);
	EDX = lpFileName;
	WHILE (EAX)
	{
		EAX--;
		IF(DSBYTE [EDX+EAX]=='.')
		{
			DSBYTE [EDX+EAX] = 0;
			BREAK;
		}
	}
}
```
I think it's good idea to simplify  asm code by using your Extension just like sphinx--.

**Comment by chuggafan** [comment]
Uh... that'd not only be a non-standard extension, you can already do similar things with inline assembly.

OCC uses MS style assembly:
https://docs.microsoft.com/en-us/cpp/assembler/inline/inline-assembler?view=vs-2017

if you really want that kind of control inline assembly is right for you.

**Comment by EmilHalim** [comment]
Okay , thanks you very much.

**Comment by GitMensch** [comment]
In this case I vote for closing this issue. @EmilHalim could do it :-)
