### ISSUE TITLE
Question: Does occ define anything when `+v` is used? Does OCIDE define something for DEBUG builds?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#274]
Just rechecking...

**Comment by LADSoft** [comment]
occ doesn't define anything.

ocide doesn't define anything by default but you should be able to add it.

**Comment by GitMensch** [comment]
Thank you, that's clean and fine. It *may* be something to document somewhere as VC auto-defines `_DEBUG` in this case (which is generally *not* considered a good practice, so no need to change occ's behavior here).
