### ISSUE TITLE
Slow constexpr evaluation

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#280]
For fun I tried this:

```cpp
template<typename T>
constexpr T adder(T v) {
  return v;
}

template<typename T, typename... Args>
constexpr T adder(T first, Args... args) {
  return first + adder(args...);
}
int main()
{
    return adder(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
}
```
This on my machine took 66 seconds and /C+d gave me:

```Memory used:
        Global Peak 3584K
        Local peak 0K
        Template peak 0K
        Optimizer peak 128K
        Temporary peak 128K
        Alias peak 128K
        Live peak 128K
        Conflict peak 128K
Intermediate stats:
  Block peak:          6
  Temp peak:           103
  Allocation Spills:   14
  Allocation Passes:   5
  Allocation Accesses: 28
```

This really should be run through faster, CL ran through it in .8 seconds. Later today I hope to profile this and see where it's stuck on and see if I can make it faster.

**Comment by LADSoft** [comment]
were you able to get anywhere with this?

**Comment by chuggafan** [comment]
Yes and no, I did a profile of the program and went down the "remove things we don't need" rabbit hole, I discovered that a whopping 8% of program time was dedicated to memset, so I went on a "memset remove" hunt, however in doing this I have somehow made it unable to compile something else, so now I'm stuck fixing that... I might drop everything I've done and re-do the things I was doing separately:

Making intellisense happier with OrangeC (lots of unused variables, moving a lot of the iterators to their correct places, getting the CRT to stop complaining about the redefinitions of stuff by removing that, etc.)

Removing calls to memset. Everywhere. A huge amount of even the STDLIB uses memset calls to initialize non-pointers as zero, or even arrays as zero, even though you can just use the declared array initialization syntax, I assume this is a holdover from cc386, but it is a huge amount of program time... (ironically enough, with MSVC only, ```struct s = {0}``` calls memset anyways, but that's because microsoft is lazy with its optimizer it seems)

**Comment by LADSoft** [comment]
yeah I think the array/structure initializers got added in C99 is that correct?   Anyway for a long time I was trying to keep the compiler sources compatible with C89 and didn't want to use newer features.   Not an issue any more, I've started letting some C99 stuff creep in..

I looked quickly at this and it seems related to #243, the fact constexpr functions aren't being properly evaluated at compile time.   I need to think about how to do that without destroying function-related data I guess...    Anyway this program you've shown here spends a *lot* of time in the constopt.c module trying to optimize something to constant....  Pretty much the entire call stack for the most-used functions were in that module.   I didn't look any deeper than that at this point.   Other than to note that it doesn't take much time if you don't declare the templates constexpr...

**Comment by LADSoft** [comment]
I have an interim patch for this but have opened #298 to address the underlying issue that calls to constexpr functions aren't evaluated at compile time.

**Comment by chuggafan** [comment]
Hmm, your interm patch seems to be one of those functions that optimizes for both constexpr and non-const-expr functions iirc, I think you may have removed some constant folding with that, but since windows restarted and I should really be asleep (darn me and my sleep habits), I'll have to test that tomorrow

**Comment by LADSoft** [comment]
well constant folding of functions doesn't work so well anyway...   but the patch was in a section of code that checked for constexpr anyway...

**Comment by chuggafan** [comment]
Ah, ok. I was mis-remembering, thanks.
