### ISSUE TITLE
OCIDE hangs with (bad?) DOCKS entries in cwa.user files

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#282]
Opened OCIDE from current Appveyor MSVC artifact --> all fine.
Opening an existing workspace --> all edit windows are opened, then for some/all files "scanning for dependencies for source.file" is shown, then OCIDE hangs.

I've removed the entries in `<EDITWINDOWS>` and `<FILEBROWSE>`, results: those aren't opened so the "hang" is earlier...

What can I do to work around this issue / make it more easy for you to check?

**Comment by GitMensch** [comment]
Found out: deleting the cwa.user helped. Actually the problem seems to be in the `DOCKS` entries.
Attached are the broken user prefs (leading to OCIDE hanging).

[GnuCOBOL.cwa.user](https://github.com/LADSoft/OrangeC/files/2591983/GnuCOBOL.cwa.user.txt) vs. [GnuCOBOL.cwa.user (broken)](https://github.com/LADSoft/OrangeC/files/2591984/GnuCOBOL.cwa.broken.user.txt)

**Comment by LADSoft** [comment]
I've seen this but don't have any idea how to reproduce it.   At the times it has happened I've mostly been editing without moving windows around...   if you have any suggestions as to what was happening before the file got corrupted I would appreciate hearing it...

**Comment by GitMensch** [comment]
>  if you have any suggestions as to what was happening before the file got corrupted I would appreciate hearing it...

Changing the screen resolution was done, I can't say if this was the reason for the corrupted file or not.
My main point here is: Shouldn't it be possible from those two files to see "what" is broken and test for this in the IDE?

**Comment by LADSoft** [comment]
I guess I could just restore all the windows to their default positions...

**Comment by GitMensch** [comment]
> I guess I could just restore all the windows to their default positions...

That was the idea, ideally only if the positions are "broken" (for whatever reason).
