### ISSUE TITLE
OCIDE resource editor seems to have issues with defined C strings

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#285]
~~~
---------------------------
Fatal RC File error
---------------------------
Error   C:\dev\gnucobol\build_windows\config.h(534):  Identifier expected
---------------------------
OK   
---------------------------
~~~

Which is

```c
/* Version number of package */
#define VERSION "3.0-dev"
```

See [version_cobc.rc](https://github.com/LADSoft/OrangeC/files/2592242/version_cobc.rc.txt) including [config.h](https://github.com/LADSoft/OrangeC/files/2592243/config.h.txt).

**Comment by LADSoft** [comment]
the problem seems to be "VERSION" is a keyword sigh.   I'll fix it...
