### ISSUE TITLE
friend operators are only allowed to take 1 parameter

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#288]
Friend operators in OCC can only have 1 parameter, this is incorrect according to the standard, https://en.cppreference.com/w/cpp/language/friend shows that you can define a non-member operator inside of a class, and this is causing an issue with upgrading the libcxx version to libcxx7, as the iterators there require this.

**Comment by LADSoft** [comment]
can you clarify what the problem is?   I had previously fixed this because the old version of LIBCXX requires it too...   I just tried this:


    struct aa
    {
	friend int operator<<(aa&, int);
    };
    struct bb
    {
    };
    int operator<<(aa&, int)
    {
    }
    int operator<<(bb&, int)
    {
    }

and it seems to work fine???

**Comment by chuggafan** [comment]
Found it! Super simple to replicate:


```cpp
template<class T>
class thing
{
    template<class A, class B> constexpr
    friend bool operator==(const thing<A>&, const thing<B>&);
}
```
It's the fact that it's ```constexpr``` that's the cause of this rather than the actual friend operator stuff itself, libcxx7's iterators can be constexpr when not debugging which seems to have shown this.

**Comment by LADSoft** [comment]
ok thanks for tracking it down !
