### ISSUE TITLE
Add a builtin offsetof

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#289]
Currently the implementation we have for offsetof is *NOT* a builtin, unlike MSVC, Clang, and GCC, there's a good reason all three have them, and I think we should create this builtin as well, as the current macro located in stddef.h is implemented as such: ```#define offsetof( s_name, m_name )  (size_t)&(((s_name *)0)->m_name)```

This does not take into account the possibility of a user implementing their own & operator, meaning if anyone does this, this macro is broken and won't work properly.

The same thing goes for addressof, which starting in C++17 is a constexpr function https://en.cppreference.com/w/cpp/memory/addressof
Rolling our own here is mandated if it is constexpr, and is another good start to moving to the latest C++ standard.

**Comment by LADSoft** [comment]
I fixed this in 543965c21d44e509f0ee447ae2b44a51fa834cec but accidentally attributed it to #290.

**Comment by chuggafan** [comment]
I noticed the function you made had two underscores in front of it, in C/c++ those are reserved, so it seems removing them would be good to prevent macro conflicts with the STL/STDLIB of any random system...
