### ISSUE TITLE
occ crashes with the option +v 

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#29]
At my tests occ (version 6.0.20.1) when I try to compile with option **+v** to create debug informations.
This crashes:
`occ /O /1 /c +v -oWIN32\Debug\Lines_win32.o Lines_win32.c`
This works:
`occ /O /1 /c -oWIN32\Debug\Lines_win32.o Lines_win32.c`

**Comment by LADSoft** [comment]
I fixed it...
