### ISSUE TITLE
dlpe: (created) Dll file is missing or in wrong format

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#290]
Test case:
[fexists_signed.c](https://github.com/LADSoft/OrangeC/files/2596850/fexists_signed.c.txt)

~~~
occ.exe -yy -Wd -o "fexists_signed.dll" "fexists_signed.c"
occ Version 6.0.39.1 Copyright (C) LADSoft 2006-2018

"d:\dev\bin\olink.exe"   /c+ /T:DLL32  -yy @C:\Users\me\AppData\Local\Temp\s4gw.0
with C:\Users\me\AppData\Local\Temp\s4gw.0=
  c0dpe.o "fexists_signed.o"  "/ofexists_signed.dll"  climp.l clwin.l olink Version 6.0.39.1 Copyright (C) LADSoft 2006-2018
Running App: "d:\dev\bin\dlpe.exe" -!  /mDLL /f  "fexists_signed.rel"
Dll file 'fexists_signed.dll' is missing or in wrong format
~~~

What does this error message want to say?

Two additional notes:
* It looks like `-!` should not be used on dlpe call because `-yy` was used.
* The olink version number seems to be shown out-of-synch - is there a newline missing anywhere?

**Comment by LADSoft** [comment]
the confusion is that the -y switch isn't passed to dlpe...  dlpe goes on to call oimplib without telling you it is doin git and it is oimplib that fails.   Presumably due to a bug in oimplib.   I'm working on fixing all this...

**Comment by GitMensch** [comment]
The message change "is missing or in wrong format" to "is missing, unreadable, or has no exports" is good, but Is still want to ask: is be complicated to actually split those messages?

**Comment by chuggafan** [comment]
It appears you accidentally added some gmp.h files for these commits, any ideas why? I don't see them being used anywhere...

**Comment by LADSoft** [comment]
yeah i caught that.   Will be fixed on the next push...   along with the underscores in the function name :)
