### ISSUE TITLE
tgmath.h doesn't work

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#293]
As I was poking around in #292 I noticed that the tgmath.h header is filled with using the OCC keyword ```__typeid```, which in OrangeC exists, but does not do anything at all to my knowledge, so afaik the tgmath.h C header is broken (however the C++ version is not there, that's another thing I'll add). Seems like we'd have to re-implement __typeid for C99 compatibility as well.

**Comment by LADSoft** [comment]
oops!    that was in CC386 I guess and never got ported over.   Shouldn't be too hard to add...
