### ISSUE TITLE
Unable to cast types under odd circumstances

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#294]
I was fumbling around with my edits when I saw that I had created a diagnostic, one that says that it can't cast properly, and I found out what can cause and where it causes it too! I just don't know how to fix this...

```cpp
#include <string>
int main()
{
    using namespace std::literals;
    std::string temp = "Hello!"s;
    std::string temp2 = "World!!!!"s;
    // add an "s" to the end of the next line's string to get rid of the diag
    temp += (temp.size() ? temp.substr(2) : "");
}
```

This is a full reproduction of it, so essentially the "" char array is unable to be converted to an std::string despite it being a const char*. CL doesn't even warn about the conversion being deprecated according to the standard, GCC does (and I am pretty sure clang too)

**Comment by chuggafan** [comment]
Ok, I just noticed that this line here: https://github.com/LADSoft/OrangeC/blob/master/src/omake/Eval.cpp#L246 is there, but since that works, what changed? I'm confused now... the git blame [here](https://github.com/LADSoft/OrangeC/blame/master/src/omake/Eval.cpp#L246) claims that the commit to add this (which should trigger the bug) was made *FIVE MONTHS AGO*, Why is this popping up NOW? I'm terribly confused .-. I hadn't even changed anything to do with OCC on my improvements branch...

**Comment by LADSoft** [comment]
I dunno, but I've been updating make files...   have you as well?    Possibly that line didn't get executed before?    But it is definitely broken, seems to be casting the structure to a pointer...   additionally I grabbed the April release and ran OCC and it has the same problem so we didn't introduce a bug any time recently...    I'm gonna be taking a break from SSE and cleaning up various issues so I should get to it within a couple of days...

**Comment by chuggafan** [comment]
Ok, yhea, afaik I touched no makefiles, and my "PR on hold" thing to see diffs in total doesn't seem to either...

**Comment by LADSoft** [comment]
i really don't know what to say but it clearly was broken...   I went back as far as april and it was broken there too.

I'll push a fix in a little bit, fixing the deprecation error right now.
