### ISSUE TITLE
OCC accepts invalid alignas specifiers

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#296]
C11 standard, 6.2.8 Alignment of objects paragraph 4, states:

```
Alignments are represented as values of the type size_t. Valid alignments include only
those values returned by an alignof expression for fundamental types, plus an
additional implementation-defined set of values, which may be empty. Every valid
alignment value shall be a nonnegative integral power of two.
```

OCC neither generates a warning nor errors here, and seemingly accepts it fundamentaly. It also does not seem to generate the correct C11 alignment, a test program I have here shows this off:

```c
#include <stdalign.h>
#include <stddef.h>
#include <stdio.h>
#include <assert.h>
struct sse_t
{
    alignas(32) float v[4];
};
int main()
{
    static_assert(alignof(struct sse_t) == 32, "Alignment of sse_t should be 32");
}
```
Supposedly occ thinks this alignment is 8, gcc and clang both disagree, intel's compiler does as well.

**Comment by LADSoft** [comment]
thanks for pointing this out,  it isn't easy to try to get every last detail right from the spec...
