### ISSUE TITLE
Evaluate constexpr functions when possible

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#298]
constexpr functions could sometimes be evaluated at compile time to result in a constant value.

**Comment by LADSoft** [comment]
the 'constant optimizer' was  originally written to optimize subexpressions, I only later turned it into something that would reduce an entire expression to a constant.    So yes it is probably a little more involved than it needs to be...

**Comment by LADSoft** [comment]
this is a roadblock for the libcxx tests so i moved it into the current milestone.

**Comment by LADSoft** [comment]
this is coming along pretty well.    Mostly functional,  still need to clean some things up with literal classes though....   basically need to make them 'real' if something outside the constexpr functionality needs to either use the class instance or modify a class member...   took about a 4% hit on compile time though (for a file compiling in 1 sec anyway with vectors and maps) so I may have to try to optimize the code a little better...

**Comment by LADSoft** [comment]
I got the compiler to compile itself again.   I have a couple of bug fixes to the constexpr handling that I have to work out though...

**Comment by LADSoft** [comment]
this is done from a functional standpoint; leaving it open while we see if it needs speed optimizations...

**Comment by chuggafan** [comment]
Has the atomics tests been re-run? I know a few of those have failed per some of the old changes due to some of the structures having constexpr constructors.

**Comment by LADSoft** [comment]
not the libcxx ones.   I'll try that out in a minute...

**Comment by LADSoft** [comment]
1 failure.   Will get on it soon...

**Comment by LADSoft** [comment]
i did fix the failure...   over the weekend I also found the constexpr stuff needed to support returning simple structures that had been initialized with a constexpr constructor.   I'm mostly through developing that but there are a couple of minor bugs yet...

**Comment by chuggafan** [comment]
Sounds really good! I hope we can find some hard things that use a lot of constexpr evaluations so that we can do profiling on a single file to determine hotspots after this is done, as I feel that constexpr will be one of the largest features that can slow down the compile times.

**Comment by LADSoft** [comment]
yeah constexpr could conceivably slow down compile times if we had a file that used it heavily....   i ended up making a mini-interpreter for the high level statement/expression trees...   the main things I've been testing with are all the variations on std::min, std::max, std::minmax and some things with pairs out of the libcxx tests, plus I wrote a couple of tests of my own...    I'm wrapping all those tests in a single file that will get run as part of the compiler tests during the build 😄

**Comment by GitMensch** [comment]
What is the state of this issue?

**Comment by LADSoft** [comment]
it still needs a little work lol...   I was thinking about picking myself up and trying to finish it this week....

**Comment by LADSoft** [comment]
I've been working on this... slowly...  almost there...

**Comment by LADSoft** [comment]
got this to a happy place.    Whenever the appveyor builds are copacetic we'll have a release...

**Comment by chuggafan** [comment]
Woot! I'll probably be trying to break this in half and measure the constexpr performance sometime in december, at least so that there's a good look into bottlenecks because I know a huge amount of compilation elsewhere is the dual-punch of templates and constexpr.
