### ISSUE TITLE
stdnoreturn.h is using __STDBOOL_H

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#30]
The "stdnoreturn.h" header is enclosed in "#ifndef __STDBOOL_H". So you can not use "stdbool.h" at the same time
(version 6.0.21.1)

**Comment by LADSoft** [comment]
thank you for your several issues...  you've pushed into some areas that don't see much use and the feedback helps.   I've fixed this one now

**Comment by tenk-a** [comment]
Thank you for fixing
