### ISSUE TITLE
artifacts broken? occ.exe: libstdc++-6.dll not found

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#305]
I've tried to use the current CI artifacts but they don't work as occ.exe is linked against libstrdc++-6.dll which is not part of the artifact.

**Comment by chuggafan** [comment]
Don't use the clang artifacts, use the MSVC and it'll work.

**Comment by GitMensch** [comment]
I've used the MINGW64 ones :-)

**Comment by chuggafan** [comment]
The MINGW64 ones require CLANG stdlib or GCC stdlib, use the MSVC one on windows to make it work properly

**Comment by LADSoft** [comment]
hi chuggafan, do you know offhand if there is something I can do on the command line to make it prefer a non-dll version of the stdlib?

**Comment by GitMensch** [comment]
I think there is no real benefit from static linking glibc (or the CLANG one), instead just include the dll in the artifact.

But the real question is: Am I wrong that all tools are compiled with glibc/msvcrt/... first and then recompiled with itself to remove the dependencies of the original compilation set?

**Comment by chuggafan** [comment]
>But the question is: Am I wrong that all tools are compiled with glibc/msvcrt/... first and then recompiled with itself to remove the dependencies of the original compilation set?

I don't know which set is distributed, I think the *FIRSTLY MADE* ones, the ones that compile the first set of the compiler (Aka, the ones made by MSVC, MINGW64, CLANG), are the ones that get used rather than anything else... unsure of that though.... but it makes sense as an explanation

**Comment by GitMensch** [comment]
In this case it makes sense to change it to "the latest compiled set". @LADSoft ?

**Comment by LADSoft** [comment]
yeah I was thinking about it over dinner and it seems that the MINGW64 compile should have compiled with MINGW64, then recompiled with itself 3 times.   The final compile should have been what went into the artifacts, and the MINGW64 dependencies should have been lost by then.   I will research soon and see what went wrong...

**Comment by LADSoft** [comment]
the occ.exe artifact was bogus... I'm getting rid of it...   the versioned artifact seemed fine though.
