### ISSUE TITLE
Bad message during linking "Dll file '%s' is missing"

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#308]
Can also be seen when compiling with OCIDE (in case of the GnuCOBOL testbed: libcob.dll).

I've just tried to use the resulting executable but as this message is now always emitted there is no way to run the complete testbed :-(

Output of `cobc -vvv CBL_OC_DUMP.c`

~~~
executing:      occ.exe -I "D:\dev\gnucobol" -I
                "D:\dev\gnucobol\build_windows" -yy
                /Wd -o "CBL_OC_DUMP.dll"
                "C:\Users\me\AppData\Local\Temp\cob68676_0.c"
                /L"D:\dev\gnucobol\build_windows\win32\release"
                -yy libcob.l
Running App: "D:\dev\OrangeC\bin\dlpe.exe" /y  /mDLL /f  "CBL_OC_DUMP.rel"
Running: "D:\dev\OrangeC\bin\oimplib" /C "CBL_OC_DUMP.l" "CBL_OC_DUMP.dll"
Dll file 'CBL_OC_DUMP.dll' is missing
oimplib Version 6.0.39.1 Copyright (C) LADSoft 2006-2018
dlpe Version 6.0.39.1 Copyright (C) LADSoft 2006-2018
olink Version 6.0.39.1 Copyright (C) LADSoft 2006-2018
"D:\dev\OrangeC\bin\olink.exe"   /c+ /T:DLL32  -yy @C:\Users\me\AppData\Local\Temp\s23g8.1
with C:\Users\me\AppData\Local\Temp\s23g8.1=
"/LD:\dev\gnucobol\build_windows\win32\release"   c0dpe.o "cob68676_0.o"  "/oCBL_OC_DUMP.dll"  "libcob.l" climp.l clwin.l
Return code: 0
occ Version 6.0.39.1 Copyright (C) LADSoft 2006-2018
~~~

**Comment by LADSoft** [comment]
my testbed isn't finding the H files needed to compile the intermediate file (specifically libcob.h)...   the occ command line you reference looks a lot different too.    Let me see if I can massage it to get past that...

**Comment by LADSoft** [comment]
btw any clue as to why all the messages from the tools are out of order?   by design olink should have been called first, then dlpe, then oimplib...   but the messages are reversed...

**Comment by GitMensch** [comment]
> my testbed isn't finding the H files needed to compile the intermediate file (specifically libcob.h)... 

From the initiaal testbed this header would be in the main gnucobol folder while others would be in build_windows (or build_occ) subdir. And it is expected that your command line looks different as I've use a newer GnuCOBOL version (will update the testbed once I can verify what works and what not, which is hard if nearly everything fails because of the unexpected output (which itself is also shown when recompiling the testbed in OCIDE).

> btw any clue as to why all the messages from the tools are out of order? by design olink should have been called first, then dlpe, then oimplib... but the messages are reversed...

Can you reproduce this with a plain `occ.exe -I "C:\some\include" -yy /Wd -o "SOME.dll" C:\some\TEST.c" /L"C:\some\libdir" -yy some.l` (and yes: there are two `-yy` in as I was too lazy to filter it)?

**Comment by LADSoft** [comment]
as it turns out the bug should have been easily reproducible with virtually any DLL...   I got cobc working well enough to work it from that angle though.
