### ISSUE TITLE
Error occurs when _Alignas is specified

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#31]
Error occurs when "_Alignas" is specified on C11.

smp.c:
	_Alignas(8)   short  v1;
	_Alignas(int) char   v2;

> occ /1 /c smp.c

RESULT:
Error(437)    smp.c(1):  Invalid use of type 'int'
Error(437)    smp.c(2):  Invalid use of type 'int'

It is possible to specify "alignas" with c++.

**Comment by LADSoft** [comment]
I fixed it

**Comment by tenk-a** [comment]
Compiled with version 6.0.22.1
Thank you.
