### ISSUE TITLE
fix issues compiling the msil compiler

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#312]
occ has various issues compiling the msil compiler that need to be addressed

**Comment by LADSoft** [comment]
the remaining issue is illustrated as follows:

struct aa
{
	aa();
	aa(const aa&) = delete;
};
struct bb :public aa
{
	bb();
	bb(const bb&) { }
};

main()
{
	bb cc;
	bb dd(cc);
}

here in the line defining 'dd' orange C complains about the deleted copy constructor for aa instead of falling back to the default constructor.

I'll try to fix it this weekend...

**Comment by GitMensch** [comment]
> I'll try to fix it this weekend...

Sounds good. Is there any update on this? As the build seems to be working again #358 and the last release is from January it may be a good time to release a new version (and to get something extra in the GCC alignment attributes [which are parsed, but not handled, while handled when specified different] #348 may be a good candidate).

**Comment by LADSoft** [comment]
I'm not done with the build yet but I'll comment on #358.   I guess this probably is a good time to clean up a few loose ends and then have a release...    I'm getting ready to do taxes (such fun) so I'll stear in that direction later this week.

**Comment by LADSoft** [comment]
it took a while to figure out what to do but I did finally get this resolved.   Going to clean up some of the recent low hanging fruits over the next week or so then will have a release...

**Comment by GitMensch** [comment]
Is the msil compiler actually run in the testsuite and some results of it verified?

**Comment by chuggafan** [comment]
AFAIK the MSIL compiler is compiled in a separate repository located https://github.com/LADSoft/Simple-MSIL-Compiler and from there... everything happens. Doesn't seem like it's mostly integrated with the main repository if only because it'd be difficult to do so.

**Comment by LADSoft** [comment]
chuggafan is correct.   The main thrust of this issue wasn't to validate the MSIL compiler again (I'll get there.. someday) but rather to fix a bug that was found when compiling the MSIL compiler with OCC.     Basically, there was a bug in how non-defaulted copy/move constructors were handled....   this is one of the areas where I didn't fully understand nuances of how it is meant to work...

**Comment by GitMensch** [comment]
> the MSIL compiler is compiled in a separate repository

> The main thrust of this issue wasn't to validate the MSIL compiler again

I see. Is there something that prevents the MSIL repo be integrated here?
Even if it will be left out of actual validation and distribution it will at least allow this project to normally build the MSIL version showing "obvious" defects like the ones fixed now during each build.

... and yes: I'd really like that project to be shipped with the normal OrangeC releases, even it it is as "experimental only" - but this is a different issue...

**Comment by LADSoft** [comment]
well there isn't really an impediment now, actually I usually work on it out of this repo anyway and then copy it to the other repos for a release.   I wanted it to be obvious I was doing it you see :).   

Source code is [here](https://github.com/LADSoft/OrangeC/tree/master/src/occ/netil) within this repo .    

The builds are somewhat broken at the moment though...   I have to run the make files by hand...
