### ISSUE TITLE
Error message file path may be incorrect

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#32]
If the relative path is used to specify a file or directory, the file path of the compile error message may be incorrect. (occ Version 6.0.21.1)

ex)
r:\app\inc\a.h
	#error !

r:\app\src\a.c
	#include "a.h"

current directory: r:\app\src

> occ /1 /c /I..\..\app\inc ..\src\a.c
or
> occ /1 /c /I..\..\app\inc r:\app\src\a.c
or
> occ /1 /c /I..\..\app\inc r:/app/src/a.c

RESULT:
Error( 37)    R:\app\app\inc\a.h(1):  error: !

"app" will be dubbed.

There is no problem below

> occ /1 /c /I../../app/inc ../src/a.c
Error( 37)    R:\app\src\../../app/inc\a.h(1):  error: !

> occ /1 /c /I..\..\app\inc  a.c
Error( 37)    ..\..\app\inc\a.h(1):  error: !

**Comment by LADSoft** [comment]
i fixed it now

**Comment by tenk-a** [comment]
There was still something that failed.

r:\app\src\a.cpp
	#error !

current directory: r:\app\src
> occ /c ..\src\a.cpp

RESULT:
Error( 37)    R:\ap\src\a.cpp(1):  error: !

One character has been deleted.

**Comment by LADSoft** [comment]
yeah that was a general problem with my implementation...   I think I have it fixed now.

**Comment by tenk-a** [comment]
I think that it was fixed in 6.0.23.1.
Thank you
