### ISSUE TITLE
occ complains about missing functions that ocpp finds

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#331]
I have no clue why but flex' sources now fail to build with

> Undefined symbol 'INT8_MAX'
> Undefined symbol 'INT16_MAX'

I can directly reproduce it with

`occ --nologo -DHAVE_CONFIG_H -I. -I../../src -DLOCALEDIR=/usr/local/share/locale ../../src/gen.c`

but the preprocessed source obtained with

`ocpp --nologo -DHAVE_CONFIG_H -I. -I../../src -DLOCALEDIR=/usr/local/share/locale ../../src/gen.c` 

contains the constant, like `(32767)`.

Is this a bug?

**Comment by LADSoft** [comment]
this is a bug in the stdint.h header...   apparently part of my fix to #325 highlighted it...

**Comment by GitMensch** [comment]
I see, then it seems like an easy fix [actually configure generated test scripts have an option to explicit check for the "header only works for the preparser" thing, so this seems like a common issue].

Can you check all distributed headers for possible errors?

**Comment by LADSoft** [comment]
the problem was actually with what seems to be some non-standard code in the stdint.h header, to support C++.   Other compilers used this code and I guess at some point we added it to OCC as well but got the implementation wrong.    But I will skim through all the headers to see if I see anything similar :)

**Comment by LADSoft** [comment]
there weren't similar problems...   but I did clean things up a bit.  Leaving this open for a short while because I want to get rid of _lfloat.h in the library but that will apparently take some library rework.

**Comment by GitMensch** [comment]
>  Leaving this open for a short while because I want to get rid of _lfloat.h in the library but that will apparently take some library rework.

Shouldn't this be tracked separately?
