### ISSUE TITLE
realloc return issue

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#332]
Given

```c
#include <stdlib.h>

int
main ()
{
  int testme = ! realloc (0,0);
  printf("result %d", testme);
  return 0;
}
``` 

gcc and cl.exe print zero, while occ prints one.

**Comment by chuggafan** [comment]
This technically is correct https://en.cppreference.com/w/c/memory/realloc https://en.cppreference.com/w/c/memory/malloc shows that realloc(0, x) = malloc(x) and that malloc(0) is implementation defined. However, it also says that it can't be used for size checking....

**Comment by LADSoft** [comment]
fixed
