### ISSUE TITLE
Is it possible to add sigaction function (and struct)?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#334]
Just stumbled over this... https://linux.die.net/man/2/sigaction

**Comment by chuggafan** [comment]
sigaction() seems very similar to the C standard signal(), and supports many, many more signals than windows natively does, are you suggesting adding those signals & then adding sigaction...? Does it get used that much and does it really matter that much?

**Comment by LADSoft** [comment]
I'll probably add it....   but it is beyond the scope to add more signals than are already supported...

**Comment by GitMensch** [comment]
I'm fine with that
 :-)

**Comment by GitMensch** [comment]
Thank you for the commit.

>  but it is beyond the scope to add more signals than are already supported...

As far as I see we actually have a more fine grained code available than before.

**Comment by GitMensch** [comment]
I've obviously opened a can of worms and ask for reopening this again...

GnuCOBOL now sees the "working" header and calls `sigemptyset` which isn't defined and now leads to "undefined external". Can you also implement this?

Please see [`sigemptyset`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigemptyset.html#) and [signal.h posix specification](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html#tag_13_42_07), showing a bunch of missing functions (the ones with "sig" would be really good to implement=.

**Comment by LADSoft** [comment]
:)
