### ISSUE TITLE
Resulting executables just "stand still"?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#335]
Both cobc and cobcrun just "stand still" when being executed.
They were completely rebuild with the latest CI-Build (mingw64).
Both the "static" version (created with Git-Bash environment) and the version built in OCIDE (which is linked against LSCRTDLL) share the same issue: the do noting until killed. Here's the version build and run with debug in the IDE:

![grafik](https://user-images.githubusercontent.com/6699539/52153043-d439ce80-2678-11e9-949c-e99aac63d481.png)

Do you have any idea what may causing this?

**Comment by chuggafan** [comment]
Have you tried debugging and seeing where they stand still? If you can get the function/line that it is looping at or get the assembly there'd be much better information than having someone compile it and test it themselves...

**Comment by GitMensch** [comment]
It doesn't even reach the first line of code...

**Comment by LADSoft** [comment]
oops... forgot about putting the waitpid() thing in LSCRTL.DLL and the fact that c11 threading waits on a semaphore for the thread to start...   can't wait on semaphores in DLL startup sigh..   will push a fix later tonite...
