### ISSUE TITLE
add delayload option, possibly to oimplib (was: Is there something like dlltool part of OrangeC tools?)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#344]
... and if not - would it be reasonable/possible to add it?

See [binutils docs](https://sourceware.org/binutils/docs/binutils/dlltool.html):

> `dlltool` is used to create the files needed to create dynamic link libraries (DLLs) on systems which understand PE format image files such as Windows.

Note: I have no urgent need for this, just wondering because it is checked for in autoconf generated configure scripts.

**Comment by chuggafan** [comment]
Isn't there a way to natively create a DLL anyways? I personally am confused if it's really needed as I thought you could just compile into a DLL

**Comment by LADSoft** [comment]
well if all you want to do is create a DLL, try:

occ /Wd /omy_dll.dll my_dll_contents.c

where the /Wd switch is the magic.    There is a corresponding linker switch /T:DLL32 (but you also have to specify c0dpe.o) and of course DLPE does the actual work of generating the output file once the linker has created a linked image.

If you want it to work with autoconf I suppose 'dlltool' would just be a wrapper spawning occ....

**Comment by GitMensch** [comment]
How do the functions provided by dlltool (especially creating import libraries [with the super nice addition delay load import library] from *object files*) match to occ functions?

And yes, getting it working to be usable "from autoconf" would be *one* of the purposes...

**Comment by LADSoft** [comment]
hm I looked at the docs for dll tool.   Looks like you would use either olink or oimplib to get most of the functionality.  (oimplib does the conversions to and from the various file formats and olink/dlpe actually builds the DLL).    I'd only recently heard about delay load libraries and don't know much about them...

**Comment by GitMensch** [comment]
> I'd only recently heard about delay load libraries and don't know much about them...

The "normal" delay load on Windows was to LoadLibrary on the first call of a function included in a DLL and then use function pointers, filled with GetProcAddress. So if you want to go from a program that just uses functions and link against a lib to delay load you have to manually change the access to the complete library which is bad and error prone.
delayimp.lib is a wrapper library that changes this - you just need to link against this static library and tell the linker which functions it should resolve not by the real import library but with the help of delayimp which will provide those functions. There is zero change in the compilation.
This helps in different cases:
1) the startup time increases as there are less DLLs to be loaded before main is actually used
2) a program that only rarely uses functions in a DLL may also work without it shipped
3) a program may adjust PATH and by this dynamically change the actual library loaded which is not possible

You can find more about this topic at [msdn][1]. I think it would be nice to be add a -delayload option to oimplib (also passed on from occ). If you agree then it likely is a good idea to track this in a separate issue (also for the reference in the ChangeLog).

[1]:https://docs.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls

**Comment by chuggafan** [comment]
BTW While doing my COFF parsing research I encountered a section of [pecoff_v8.doc](https://web.archive.org/web/20100314154747/http://www.microsoft.com/whdc/system/platform/firmware/PECOFF.mspx) that dealt specifically with Delay-load-libraries and their format inside of an Image.

I think this will be useful when we go to implement Delay-Load-Library situations.

**Comment by LADSoft** [comment]
ok so i want to do this but it is going to take some time to research what to do, so I'm going to continue on with lower-hanging fruit for now...
