### ISSUE TITLE
POSIX functions for dll (un)loading: dlfcn.h, dlopen, dlclose, dlsym, dlerror

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#345]
Again: there's no urgent reason to implement this *now* but after thoroughly checking there aren't a bunch of functions/definitions that have to be added and as POSIX explicit specifies that `dlclose()` only *may* unload a DLL and specifies no explicit error messages that are returned by `dlopen()` I *think* adding it seems like a low-hanging fruit.

[POSIX specification for dlfcn.h](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/dlfcn.h.html) (follow links to get to the function definitions).

Minimal sample implementation (LGPL'd after GnuCOBOL libcob/call.c):

```c
static HMODULE
dlopen (const char *x, int mode)
{
	// ignoring mode here, guessed as RTLD_LAZY | RTLD_GLOBAL
	if (x == NULL) {
		return GetModuleHandle (NULL);
	}
	return LoadLibrary(x);
}

static void *
dlsym (HMODULE hmod, const char *p)
{
	union {
		FARPROC		modaddr;
		void		*voidptr;
	} modun;

	modun.modaddr = GetProcAddress(hmod, p);
	return modun.voidptr;
}

#define dlclose(x)	(int)FreeLibrary(x)

static char	errbuf[64];
static char *
dlerror (void)
{
	sprintf(errbuf, _("LoadLibrary/GetProcAddress error %d"), (int)GetLastError());
	return errbuf;
}
```

**Comment by LADSoft** [comment]
thank you for contributing code samples in some of your issues.    Every little bit helps :).

As an aside, a few weeks ago I started rewriting the tools to use the C++11 'unique_ptr' to manage pointers - I was originally just going to use it to get explicit deletes out of all the destructors but the scope creeped to where I was getting rid of deletes whenever not too inconvenient....    And then a whole bunch of compiler bugs surfaced when I got it done and tried to compile it with itself.    For a while I was trying to work on it part time and work other things in at the same time but the code has diverged in big ways on several branches.   I need to get this back under control before proceeding on the other branches...   stay tuned...

**Comment by GitMensch** [comment]
Just wondering - is there something that leads to the later milestone for this?

Without a deep check this looks like the posix header definition is linked and a sample license-compatible implementation is included in this issue so copy+paste+work [OK, obviously someone should test this somehow at least once]?

**Comment by LADSoft** [comment]
it didn't seem too needed so I just threw it in.   I can move it up if you want...

I was thinking about doing something a little more involved, there was something here on github that did a more complete implementation and I thought I could use it.   Can't find it right off the bat though...

**Comment by GitMensch** [comment]
> I was thinking about doing something a little more involve

Sounds good, then take your time.
