### ISSUE TITLE
FR (patch included): implement realpath / canonicalize_file_name

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#347]
While I was on #346 I've tried to find a fast way to implement [POSIX realpath][1] / [GNU canonicalize_file_name][2].
This is a "working" version (which does the allocation and the path resolving per definition) using Win32 [GetFullPathName][3] (just hacked the following which misses: setting errno as per definition, and to internally use something like the missing `readlink` (unistd.h) for actually reversing symbolic links like realpath does):

```c
static const char *
realpath (const char *path, char *resolved_path) {
   char int_path_lookup[MAX_PATH];
   int size = GetFullPathName (path, MAX_PATH - 1, int_path_lookup, NULL);
   if (size == 0) return NULL;
   if (size >= MAX_PATH) {
	   size = MAX_PATH - 1;
   }
   if (resolved_path == NULL) {
	   resolved_path = malloc(size);
   }
   strcpy (resolved_path, int_path_lookup);
   return resolved_path;
}

static const char *
canonicalize_file_name (const char *path) {
   realpath (path, NULL);
}
```

[1]:https://linux.die.net/man/3/realpath
[2]:https://linux.die.net/man/3/canonicalize_file_name
[3]:https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfullpathnamea

**Comment by LADSoft** [comment]
i'm going to add this, but couldn't find a way to canoncalize hard links on windows...

**Comment by GitMensch** [comment]
> couldn't find a way to canoncalize hard links on windows...

As far as [StackOverflow](https://stackoverflow.com/questions/23621778/how-to-find-target-of-symbolic-link-in-windows-c-program) enlightened me the way to go would be use CreateFile (to open the file, yay, MS super names) to get the file handle (if not explicit asked it does not give you the handle to to hard link but to the target file) and then query the filname by this handle.
The good thing - this way should work in any case, not only in the symlink case.
The bad thing - this may only work with newer versions (`CreateFile` needs XP/2008+), not sure about the query function, or the support of OrangeC for Windows 2000/98 whatever.
