### ISSUE TITLE
FR: add support for GCC variable attributes (especially the alignment)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#348]
This is similar to #96, also the [GCC variable attributes](https://gcc.gnu.org/onlinedocs/gcc/Variable-Attributes.html#Variable-Attributes) that are likely most reasonable to implement are

* https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#Common-Variable-Attributes
* https://gcc.gnu.org/onlinedocs/gcc/Microsoft-Windows-Variable-Attributes.html#Microsoft-Windows-Variable-Attributes (maybe done already, but is `shared` really available?)

I especially ask for the [aligned-variable attribute](https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-aligned-variable-attribute) as this is a feature actually supported by OrangeC (just not with this attribute).

**Comment by LADSoft** [comment]
I'm going to fix this and #352 over the next few days, then we'll have a release :)

**Comment by LADSoft** [comment]
sorry for the delays.   I've evaluated this and decided that for now I'm going to do the things in the two lists that don't require linker support, unless you have something specific you want to ask for.   I should be able to comfortably do that this weekend and have a release.

**Comment by LADSoft** [comment]
got through the implementation, been having problems compiling it with itself sigh...

**Comment by GitMensch** [comment]
Found the actual implemented attributes at https://github.com/LADSoft/OrangeC/blob/v6.0.41.1/src/occ/parse/declcpp.cpp#L3099, just to leave a trace of documentation here ;-)

* [alias](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-alias-function-attribute)
* [aligned](https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-aligned-variable-attribute)
* warn_if_not_aligned
* alloc_size
* cleanup
* [copy](https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-copy-variable-attribute)
* deprecated
* nonstring
* packed
* unused
* used
* vector_size
* dllimport
* dllexport

And as a special OrangeC extension:
* zstring

One important implementation note I did not knew about before (quoting [GCC docs, Attribute-Syntax](https://gcc.gnu.org/onlinedocs/gcc/Attribute-Syntax.html#Attribute-Syntax)):

> You may also specify attributes with ‘__’ preceding and following each keyword. This allows you to use them in header files without being concerned about a possible macro of the same name. For example, you may use `__noreturn__` instead of `noreturn`.

Note: this applies to _all_ attributes GCC supports.

Note: One additional attribute that seems to be supported by declspec declaration already is the sample above: `noreturn`.

**Comment by LADSoft** [comment]
I'll look at the '__'  versions when I get through with #366.

**Comment by GitMensch** [comment]
@LADSoft looks like the following is related:

```c
int foo (int x) __attribute__ ((const));
int
main ()
{

  ;
  return 0;
}
```

With occ complaining

> Error( 11)    conftest.c:  Syntax error: ) expected

**Comment by LADSoft** [comment]
just caught this comment.   the latest issue is still an issue so reopening.
