### ISSUE TITLE
OCC spits out wrong error when encountering certain code

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#349]
Latest master:

```cpp

template <class _Tp, _Tp __v>
struct integral_constant
{
    static constexpr const _Tp value = __v;
    typedef _Tp value_type;
    typedef integral_constant type;
    constexpr operator value_type() const noexcept { return value; }
    constexpr value_type operator()() const noexcept { return value; }
};

template <class _Tp, _Tp __v>
constexpr const _Tp integral_constant<_Tp, __v>::value;
template <bool __b>
using bool_constant = integral_constant<bool, __b>;
#define _LIBCPP_BOOL_CONSTANT(__b) bool_constant<(__b)>

typedef _LIBCPP_BOOL_CONSTANT(true) true_type;
typedef _LIBCPP_BOOL_CONSTANT(false) false_type;

template <class _Tp>
struct __libcpp_is_void : public false_type
{
};
template <>
struct __libcpp_is_void<void> : public true_type
{
};

template <class _Tp>
struct is_void : public __libcpp_is_void<typename remove_cv<_Tp>::type>
{
};
```

When I compile this, I get:

```Error( 11)    TestWrongGT.cpp(30):  Syntax error: > expected```

When it should just be complaining about remove_cv not being defined instead, when defining remove_cv properly, the error vanishes.

**Comment by LADSoft** [comment]
:)   hm...   will look at these next...

**Comment by LADSoft** [comment]
i tried this with VC and got pretty much the same result...    although the errors CL.EXE produces are slightly more verbose lol!   It still doesn't quite point directly to the actual problem with remove_cv not defined...   I don't think occ can complain about remove_cv not being defined because of the 'typename' but maybe I can make the error a little more verbose anyway...   will think about it some more...

**Comment by chuggafan** [comment]
Yhea, GCC seems to handle this poorly aswell, https://godbolt.org/z/4RMucV Clang points right to it, 

```
<source>:30:51: error: expected a qualified name after 'typename'
<source>:30:51: error: no template named 'remove_cv'
<source>:31:1: error: expected class name
```

So... it should be detectable, and saying that ">" expected is much different than a template parameter being off!

**Comment by LADSoft** [comment]
I'm improving this.   Thank you.   will upload when i finish #350.

**Comment by chuggafan** [comment]
yay :) Once these two are down the majority of compiler-errors will be gone from the latest libcxx compiles, and the rest will be 1 outlier and just repeats of the same ones...

All of the issues I've posted in the past 2 days are about libcxx, and that's just about getting it to compile, getting it to run is another game entirely unthankfully....

**Comment by LADSoft** [comment]
that sounds really good.   

FWIW when you've been giving me issues where it doesn't compile I've been trying to validate that not only is the error gone, but the underlying functionality works too.   Not a guarantee we won't have issues but should make it a teensy bit easier to navigate with it :).

As far as the other issue, it was easy to fix but then I ran into those dratted braces lol!   I never thought of using initializer lists in that context.   Going to take some rework...
