### ISSUE TITLE
endless module initialization if compiled with wrong symbol defintions

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#352]
The following correct code works with GCC, MSVC and occ:

```c
#include <libcob.h>

int callee (char *, char *);

int
main (int argc, char **argv)
{
   /* for storing COBOL return code */
   int cob_ret;

   /* initialize parameters */
   char *p1 = "A";
   char *p2 = "FROM C";

   /* initialize the COBOL run-time library */
   cob_init (argc, argv);

   /* call COBOL program */
   cob_ret = callee (p1, p2);

   /* Clean up and terminate - This does not return */
   cob_stop_run (cob_ret);
```

**Note**: both this program and callee.c are called in one invocation of the compiler and are statically linked.

If I now change the definition to `extern int callee (char *, char *);` everything is still fine.
When changing it to `__declspec(dllimport) extern int callee (char *, char *);` MSVC correctly warns:

>  warning LNK4217: local defined symbol "_callee" was imported in _main-function.

occ doesn't complain but more important: the resulting binary does not start correctly (it seems to "hang" during initialization).

**Comment by LADSoft** [comment]
yeah doing that causes a serious error that needs a diagnostic :)

**Comment by LADSoft** [comment]
this turned into a headache when I first tried it.   It isn't hard, just going to have to add a record to the object file to support that and don't know immediately if that is going to have repercussions...   I'm going to look and see where things are at for chuggafan's issues tonite then get back to what I was working on for you tomorrow...
