### ISSUE TITLE
Including complex will result in errors

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#36]
Including complex will result in errors

smp.cpp:
```
	#include <complex>
```
> occ /c smp.cpp

RESULT:
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1038):  Could not find a match for 'isinf(long double)' in function std::__1::proj(long double)
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1039):  Could not find a match for 'abs(long double)' in function std::__1::proj(long double)
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1047):  Could not find a match for 'isinf(double)' in function std::__1::proj(double)
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1048):  Could not find a match for 'abs(double)' in function std::__1::proj(double)
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1068):  Could not find a match for 'isinf(float)' in function std::__1::proj(float)
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(1069):  Could not find a match for 'abs(float)' in function std::__1::proj(float)
Error(313)    C:\Program Files (x86)\Orange C 386\include\complex(1530):  operator "" requires identifier

**Comment by LADSoft** [comment]
I defined abs() properly for C++11 and enabled various macros and functions from C99 in C++ mode.   There was a vagaray with the literal operator where it needed a space between the quotes and the ID that I also fixed.

**Comment by tenk-a** [comment]
I compiled with v 6.0.24.1.
Thank you
