### ISSUE TITLE
Build number from AppVeyor to version.h

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#362]
Would it be possible to set the build-number from AppVeyor as build-number in version.h?

**Comment by LADSoft** [comment]
this sounds like a good idea but what is likely to happen is we include the build from appveyor into the product during appveyor builds; the build won't be propagated back to github though.

If that sounds ok I'll do it later this week :)

**Comment by AlexN-114** [comment]
Sounds OK! 👍  :)

**Comment by GitMensch** [comment]
@LADSoft Just checking as this seems to be doable fast - any progress here? According to the [Appveyor environment variables documentation](https://www.appveyor.com/docs/environment-variables/) one may use `%APPVEYOR_BUILD_NUMBER%` for this case.

**Comment by LADSoft** [comment]
I'm working on this now.   The first attempt sets the appveyor version (as viewed through the appveyor gui), and my second attempt might set the version number inside the applications depending on whether I typed the commands correctly.   Tomorrow I'm going to work on reinstrumenting the build process to be able to put the appveyor version/build number in the inno setup installation file.   Then should be able to close it.

I'm probably going to let the build indexes increase from where they were on this version, may think about starting to reset them to 1 at the beginning of each new release in 6.0.43.

**Comment by GitMensch** [comment]
> I'm probably going to let the build indexes increase from where they were on this version, may think about starting to reset them to 1 at the beginning of each new release in 6.0.43.

Sounds very reasonable (although this is another manual step to do but would go together with adjusting the main version).

**Comment by LADSoft** [comment]
the following commits weren't tagged properly but go with this:

f9560bd938956876f649a33f2581720e255e28eb

2e22d31ce93f0e8d1cdfaeb200d1565a5833e84c
