### ISSUE TITLE
Namespace searching is recursive in some situations.

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#367]
In namespacesearchInternal, a namespace somehow included itself and created an infinite loop, with lst and qualified not changing, meaning that it is permanently stuck

Two different namespaces referencing eachother in a permanent loop, the code I got this to work with (I have *NO IDEA* where to begin with this kind of code-finding task...) is:

[testnewheader2.zip](https://github.com/LADSoft/OrangeC/files/3163337/testnewheader2.zip)

This is the file, and I got it from attempting to debug how my example program in #366 was not working, by taking that file, preprocessing it, then running it through c++ insights to see how the templates unfolded, then trying to compile *THAT* with the template specialization...

**Comment by chuggafan** [comment]
I've found a likely culprit here, https://github.com/LADSoft/OrangeC/blob/60fcd108fc530b1db25d02af0ee4f1e351d76348/src/occ/parse/cpplookup.cpp#L3943-L3957 if this if statement is taken, at the end of the if statement the namespace setup for the global namespace is RECURSIVE, so globalNameSpace->next is equal to globalNameSpace. There's actually more than once where this "direct" recursion occurs. 

https://github.com/LADSoft/OrangeC/blob/60fcd108fc530b1db25d02af0ee4f1e351d76348/src/occ/parse/declare.cpp#L4545-L4556

This is the other place this occurs, and THIS set of lines is the actual culprit in my scheme here, as proven by me setting a breakpoint in Visual Studio with the condition listed: ```globalNameSpace && globalNameSpace->next && globalNameSpace->next->next && globalNameSpace == globalNameSpace->next->next```

I shall do more digging into this, but this type of recursion should be identified and as much as possible, purged to stop these kinds of infinite loops that just iterate down the namespace until it "ends"

**Comment by LADSoft** [comment]
this specific form of recursion is being fixed as  part of #366.

**Comment by LADSoft** [comment]
fixed here: 1238880ef574b93fbe2ba5cddf9a8b09931a616d
