### ISSUE TITLE
Integrating the MSIL compiler

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#369]
This is a follow-up to #312. If I see it correct the maintained [source code for the msil-compiler is in this repo](https://github.com/LADSoft/OrangeC/tree/master/src/occ/netil) and has an [additional repo](https://github.com/LADSoft/Simple-MSIL-Compiler) with the same content, but outdated and no releases with binaries.

Questions part 1: Is the MSIL compiler compiled in this repo's CI with OCC and verified to at least do "something simple"?
Questions part 2: Can the MSIL compiler's code be compiled with the MSIL compiler yet? Can it be run (as .net) then, too?

Question part 3: Can the MSIL compiler `occil` be integrated into the CI artifacts and the release? If not: Where is the problem?

**Comment by LADSoft** [comment]
#1 I've only recently gotten it to compile with OCC.   The last released compile was with VS2017.   I need to validate the OCC compiled version but there are also new changes I made last year that need to finish validation.    The additional repo has the last working version (compiled with VS2017) so the two repos are currently out of sync.
#2 The MSIL compiler cannot compile itself at this time....   the problem is that it only handles C language code and the compiler/support code is in C++.

#3 I could integrate it easily enough, with the provision it only gets compiled and tested (can't recompile itself).   The limitation is #2, #1 has to be completed before I could do that though.

**Comment by GitMensch** [comment]
Please drop the additional repo, it does not serve a big purpose.
As far as I see it the things to do would be:

* copy over the README.md into a subdirectory of this repo (possibly some other files, too)
* if not too hard: re-tag the two old versions here that match the tags in the other repo (I personally wouldn't mind); if you do please add (the old) binaries to them (maybe only to the newest one)
* make a last commit there adjusting README.md stating where to find the code, mark the repo as read-only [or instead: clean cut with deletion of the repo, the only reason to not do it in my view is the minimal track of the PRs there]

Then run the tests that are available for the MSIL compiler with the compiled version (provides a minimal test bed), ideally with running them.

Close this issue and have inner peace for a cleaner world of code and more integrated tests in this repo.

**Comment by LADSoft** [comment]
hehehe...   well I'll get to it... eventually...   I AM kinda tired of copying files around to release!   gonna concentrate on C++/libcxx8 problems in the near future though...

**Comment by GitMensch** [comment]
Ping @LADSoft as a release with various C++ problems was published. I assume that most libcxx8 problems still persist, but still suggest to get rid of the additional msil repo and integrate the msil compiling binary (+whatever docs are available) to the next release.

**Comment by LADSoft** [comment]
I was thinking of prioritizing this right after #365 (which i'm working on now)

**Comment by LADSoft** [comment]
this is coming along pretty well.   The MSIL compiler works again (at least as much as it ever did).   And OCC happily compiles it.  But I am working through all the reasons OCC won't generate correct code for the sources.  Sigh.

**Comment by LADSoft** [comment]
four out of about 35 tests are failing but once I get them working I'll push.

Meanwhile the first round is going to be a little slow due to the problem outlined in #386.

**Comment by LADSoft** [comment]
I messed up on tags during all the checkins, here are the ones related to this issue:

08a3c4bb17c1e4a9f69bc9fa20b7dc096a5b141e
a97a033bd66bf4dbb772bdece57917cd2549a8d9
64f8b95a74fd664cd9e0f1412e6e1c5f82853700
06b3142ba7a74a43e39a230ed84a4456d67c34c6
ba047016e8a4820450eab24049c3f22fb7aae645
72044984f9e8240d45e97cf2a3999c492632e7ec
687e325433f16615496a68c5cb35abcba2b8bbf5
54ab2bb2f5474b3f657a8b176f8473f9d720d2a0
7fad4c04d6fccb9d7c989b86808049470b42033c
4f72361453dbf282b5d4e605e0d3ba177045d357
9aa5b96e4467dc10062bb9cbf2b25bf588d8f619
56d8b959b9c7d7c7decb5a31ef01b222e9c7658d
d7addedab6eb9304c8b35e28ee36c23eabc30af5
e61d98aa056cd88d5b34626d1799a231316d5a66
099db78f789686f4f2531a68853e2551afdfb46c
66af98140b8aa217e6656fc2f9f1871f23a8cbb4
73f0c376018d4e630415c167d73c2f3606f33075
3084330be88c5c28674950cadccfe308a168afd1
369d5a20b2253bb44888626d9e11882fd174f557

**Comment by GitMensch** [comment]
We're not there yet, but once we are the separate repository (and Appveyor CI project) should be deleted.

**Comment by LADSoft** [comment]
yeah i remembered :).
