### ISSUE TITLE
Including locale (nl_types.h) may result in errors

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#37]
Including <locale> after <cstdio> results in errors.
It succeeds if it is not <cstdio> but <stdio.h>

smp.cpp:
```
	#include <cstdio>
	#include <locale>	// <ostream> <complex> ...
```

> occ /c smp.cpp

RESULT:
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(29):  Undefined symbol 'va_list' in function snprintf_l(char*, unsigned int, void*, char const *, ...)
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(29):  Undefined symbol 'arg' in function snprintf_l(char*, unsigned int, void*, char const *, ...)
Error(113)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(30):  Call of nonfunction in function snprintf_l(char*, unsigned int, void*, char const *, ...)
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(31):  Could not find a match for 'vsnprintf(char*, unsigned int, char const *, void)' in function snprintf_l(char*, unsigned int, void*, char const *, ...)
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(39):  Undefined symbol 'va_list' in function asprintf_l(char**, void*, char const *, ...)
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(39):  Undefined symbol 'arg' in function asprintf_l(char**, void*, char const *, ...)
Error(113)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(40):  Call of nonfunction in function asprintf_l(char**, void*, char const *, ...)
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(41):  Could not find a match for 'vsnprintf(char*, int, char const *, void)' in function asprintf_l(char**, void*, char const *, ...)
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(62):  Undefined symbol 'va_list' in function sscanf_l(char const *, void*, char const *, ...)
Error( 18)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(62):  Undefined symbol 'arg' in function sscanf_l(char const *, void*, char const *, ...)
Error(113)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(63):  Call of nonfunction in function sscanf_l(char const *, void*, char const *, ...)
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(64):  Could not find a match for 'vsscanf(char const *, char const *, void)' in function sscanf_l(char const *, void*, char const *, ...)

----
Including <locale> after wctype.h(cwctype) results in errors.

smp2.cpp:  
```
	#include <wctype.h>	// <cwctype>  
	#include <locale>	// <ostream> <complex> ...  
```

> occ /c smp2.cpp

RESULT:
Error(228)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(16):  'iswctype' is not a member of 'std'
Error(228)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(17):  'iswctype' is not a member of 'std'
Error(228)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(18):  'iswctype' is not a member of 'std'
Error(228)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(19):  'iswctype' is not a member of 'std'
Error(228)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(20):  'iswctype' is not a member of 'std'

**Comment by LADSoft** [comment]
I upgraded nl_types so that it included enough headers to compile in a standalone fashion, and fixed the collision with wctype.h

**Comment by tenk-a** [comment]
It seems that there is still errors. (The error message has changed)

smp.cpp:
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(40):  Could not find a match for 'vsnprintf(char*, unsigned int, char const *, void*)' in function snprintf_l(char*, unsigned int, void*, char const *, ...)
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(50):  Could not find a match for 'vsnprintf(char*, int, char const *, void*)' in function asprintf_l(char**, void*, char const *, ...)
Error(232)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(73):  Could not find a match for 'vsscanf(char const *, char const *, void*)' in function sscanf_l(char const *, void*, char const *, ...)

smp2.cpp:
Error(229)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(104):  Qualifier 'std' is not a class or namespace in function iswcntrl_l(unsigned int, void*)
Error(229)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(108):  Qualifier 'std' is not a class or namespace in function iswgraph_l(unsigned int, void*)
Error(229)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(114):  Qualifier 'std' is not a class or namespace in function iswpunct_l(unsigned int, void*)
Error(229)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(116):  Qualifier 'std' is not a class or namespace in function iswspace_l(unsigned int, void*)
Error(229)    C:\Program Files (x86)\Orange C 386\include\nl_types.h(118):  Qualifier 'std' is not a class or namespace in function iswblank_l(unsigned int, void*)

**Comment by LADSoft** [comment]
should have read the issue on github instead of relying on the email...   works better now though.

**Comment by tenk-a** [comment]
I compiled with v 6.0.25.1.
Thank you
