### ISSUE TITLE
Change or modify libcxx so that we have atomics in C++

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#372]
Title of the issue is the main focus, we need to work on modifying libcxx or our own atomics system so that we can get atomic features in C++, this work can be done without #355 being completed in terms of compilation, however libcxx does atomics wholly differently from most c++ libs as far as I can tell and decides that clang should have C11 atomics in C++ and then uses the same semantics... don't ask me why it just does. https://github.com/llvm-mirror/clang/blob/master/docs/LanguageExtensions.rst#__c11_atomic-builtins shows what it does, which means that if we'd want to do minimal changes to libcxx just to stay compatible implementing the clang extension to determine if it's lock free would be the best way.

My guess as to why clang/libcxx for atomic_is_lock_free uses the size of the object being pointed to is because of how they implement CPU level atomics for increments decrements etc. 

Getting this done would mean we can remove, say, InterlockedIncrement and InterlockedDecrement from omake or other stuff. It's something simple and needs distinct focus from the rest of the libcxx work, including threading and mutexes. (threading is actually relatively simple in the newest libcxx comparatively, only problem is actually compiling it... which means that's a #355 issue).

**Comment by LADSoft** [comment]
so i looked into this, probably the existing C11 support will be sufficient (although it wasn't immediately clear if I'd have to add new names for  the intrinsicis).   Then add some __has_feature flags to support it...    may look at implementing __has_feature in the compiler so we don't continually have to update the config file dramatically every time we change out the lib...

**Comment by chuggafan** [comment]
Question as I've begun work on this now, for the atomic fences we don't have a separate implementation for thread and signal fences.

According to the C17 standard draft I've dug up, while similar, there is one important difference: The signal fence only will only execute ordering restraints intra-thread between the fence and a requisite signal handler (e.x. anything passed to signal() and raised by raise()).

This is important for proper signal handling for signals such as SIGTERM in multithreaded environments to handle cleaning up resources that don't get freed by the system on process termination (such as named semaphores on linux).

**Comment by LADSoft** [comment]
i don't remember enough about atomic fences to know details, but seems like at a minimum we'd have to do a minor rework to raise() so we know when we are in a signal hander, then add another RTL function to support fencing against that.   Lastly have a compiler intrinsic make a call to that function at the appropriate points....

**Comment by chuggafan** [comment]
Yhea, I've also been looking at what the <atomic> header expects, basically a small rewrite to the lexer to add a few more types of modify and exchange operations all called "__c11_atomic_foo" will get it to work, or at least, it should.

The real interesting thing I think is that it seems the compiler doesn't actually do checking on the internals to templated functions until way after it's deferred, which is why I'm seeing the __c11_atomic_thread_fence issue first before anything else.

Lastly: in order to be compatible we need to have OCC add the definitions of:

```
ATOMIC_BOOL_LOCK_FREE
ATOMIC_CHAR_LOCK_FREE
ATOMIC_CHAR16_T_LOCK_FREE
ATOMIC_CHAR32_T_LOCK_FREE
ATOMIC_WCHAR_T_LOCK_FREE
ATOMIC_SHORT_LOCK_FREE
ATOMIC_INT_LOCK_FREE
ATOMIC_LONG_LOCK_FREE
ATOMIC_LLONG_LOCK_FREE
ATOMIC_POINTER_LOCK_FREE
```

I think this should be relatively easy compared to everything else we need to do here, as we just need to do a simple change to grab the value from the chosenAssembler structure like `Optimizer::chosenAssembler->arch->type_needsLock` and just set each, I think I could do this in the next 20 minutes myself to be quite honest.

**Comment by LADSoft** [comment]
yeah i wouldn't expect expanding the atomic support to be that difficult.    As far as templates, I really really need to rewrite the whole template engine but that is kind of a big deal.   The main issue is that there is no internal representation other than tokens directly from the source code so many problem checks have to be delayed until much later, when the template is instantiated.   I would also expect having a better internal representation would speed it up...   and the code would be quite a bit cleaner...

**Comment by chuggafan** [comment]
Looking around it seems I've found that we don't actually check if we really do need an atomic lock for the char16_t type, as the code for it looks like:

```cpp
int needsAtomicLockFromType(TYPE* tp)
{
    Optimizer::ARCH_SIZING* p = Optimizer::chosenAssembler->arch->type_needsLock;
    switch (basetype(tp)->type)
    {
        case bt_char16_t:
            return 0;
        case bt_char32_t:
            return 0;
        case bt_bit:
        case bt_void:
            return 0;
```

Should I substitute it with the architecture specific "similar" types? Because not *EVERY* platform in the world even supports working on 16 bit stuff.

Other than that everything should be able to be taken care of by me.

**Comment by LADSoft** [comment]
yeah...  unfortunately the architecturally similar types aren't of guaranteed bit size.    Really what needs to happen is the ARCH_SIZING structure has to change to add the two new types, then the six places where ARCH_SIZING structures define data (three for the x86 and three for the msil) have to change to add new constants.    SIZE and ALIGNMENT constants in confx86.cpp and confmsil.cpp are in bytes, the lock constants are booleans.    You could probably do all that...   but if you are uncomfortable with it I will fix it for you tonite.

**Comment by chuggafan** [comment]
I'll probably get on that later tonight, by doing the "basics" of just defining the ATOMIC_*_LOCK_FREE stuff it instantly cuts the number of errors down from more than 100 to 13. 

These errors are:

```
Warning c:\ORANGEC\include\__config(1573): _LIBCPP_AVAILABILITY_FUTURE macro redefinition changes value
Warning c:\ORANGEC\include\__config(214): Previous definition here
Error(232)    c:\ORANGEC\include\atomic(930):  Could not find a match for '__c11_atomic_thread_fence(int)'
Error(232)    c:\ORANGEC\include\atomic(935):  Could not find a match for '__c11_atomic_signal_fence(int)'
Error(232)    c:\ORANGEC\include\atomic(976):  Could not find a match for '__c11_atomic_exchange(bool*, bool, int)'
note:         c:\ORANGEC\include\atomic(975):  Referenced in instantiation of 'std::__1::__cxx_atomic_exchange<bool>(__cxx_atomic_base_impl<bool> volatile *, bool, memory_order)'
note:         c:\ORANGEC\include\atomic(2317):  In template instantiation started here
Error(232)    c:\ORANGEC\include\atomic(981):  Could not find a match for '__c11_atomic_exchange(bool*, bool, int)'
note:         c:\ORANGEC\include\atomic(980):  Referenced in instantiation of 'std::__1::__cxx_atomic_exchange<bool>(__cxx_atomic_base_impl<bool>*, bool, memory_order)'
note:         c:\ORANGEC\include\atomic(2324):  In template instantiation started here
Error(232)    c:\ORANGEC\include\atomic(952):  Could not find a match for '__c11_atomic_store(bool*, bool, int)'
note:         c:\ORANGEC\include\atomic(951):  Referenced in instantiation of 'std::__1::__cxx_atomic_store<bool>(__cxx_atomic_base_impl<bool> volatile *, bool, memory_order)'
note:         c:\ORANGEC\include\atomic(2345):  In template instantiation started here
Error(232)    c:\ORANGEC\include\atomic(957):  Could not find a match for '__c11_atomic_store(bool*, bool, int)'
note:         c:\ORANGEC\include\atomic(956):  Referenced in instantiation of 'std::__1::__cxx_atomic_store<bool>(__cxx_atomic_base_impl<bool>*, bool, memory_order)'
note:         c:\ORANGEC\include\atomic(2352):  In template instantiation started here
Error(228)    c:\ORANGEC\include\__threading_support(255):  'tv_sec' is not a member of 'timespec'
Error(204)    c:\ORANGEC\include\__threading_support(258):  Cannot convert ' const __ts_sec' to 'rep'
Error(228)    c:\ORANGEC\include\__threading_support(260):  'tv_sec' is not a member of 'timespec'
Error(228)    c:\ORANGEC\include\__threading_support(261):  'tv_nsec' is not a member of 'timespec'
Error(228)    c:\ORANGEC\include\__threading_support(265):  'tv_sec' is not a member of 'timespec'
Error(228)    c:\ORANGEC\include\__threading_support(266):  'tv_nsec' is not a member of 'timespec'
Error(510)    c:\ORANGEC\include\__mutex_base(58):  static_assert generated: the default constructor for std::mutex must be nothrow
```

So it seems the first 6 errors are all "we need to add the __c11_*" stuff, all the rest but one are "timespec" issues, and the last is that there's an issue with nothrow on a specific default constructor, which is a big step up to be quite honest.

**Comment by chuggafan** [comment]
And checking out the actual definition of timespec shows that our timespec definition is just wrong and that I may have to locate a bunch of individual places in the build to fix it.

Fun times are about to begin 🤡

**Comment by chuggafan** [comment]
Huh, the issue only affected 2 files in the entire system apparently. Neat.

**Comment by LADSoft** [comment]
cool, I'm glad it was that easy.   Dunno what was up with me getting the wrong definition of timespec...

**Comment by chuggafan** [comment]
Other than the __c11_atomic stuff blocking as well as the mutex constructor not being nothrow, the big issue I've next encountered ahead of time is drumroll please.... #248 and our lack of exception_pointer. Figures that it'd somehow pop up immediately after this issue will be nominally "fixed".

**Comment by LADSoft** [comment]
yeah that is still on the radar for this milestone.   I've just been having so many problems with #355...   I'd probably be working on #248 now if #355 hadn't caused major timing problems with appveyor...

**Comment by chuggafan** [comment]
Small note that I found when reading CLANG's language extensions that the lock-freeness depends on the size of an actual object, not its type, same with GCC's extension. As for MSVC, they sidestep the problem entirely and rely on about 4-5 functions to do everything.

**Comment by chuggafan** [comment]
Technically #578 fixes this, however there's still plenty of related issues, notable we parse out `__c11_atomic_is_lock_free` but do nothing with it because the actual thing is based on the size of the type for libcxx.

This is a MAJOR issue and we should not release until a fix is out for this, however I don't know the appropriate way to handle it because our system is designed around type and not the size of said type.

**Comment by chuggafan** [comment]
Also we have plenty of TODOs in relation to this, so I say it'd be incredibly premature to close this now. notably on line 4799 of expr.cpp and 5055 of the same file both show glaring issues that *MUST* be discussed.


Until everything I've identified is done it'd be far premature to close this issue and make a release, it'd be before inception.

**Comment by LADSoft** [comment]
ok sure :)   I'll start looking into seeing how it should work....    I already found out there was some bug with atomic_store not returning the correct value and some other bug with not being able to tell the difference between overloaded cast operators so I kinda figured we weren't quite done with it lol!

**Comment by chuggafan** [comment]
Yhea, I suspect that in order to get everything right we'd have to move our goal of #559 from milestone 4 to 3 as it seems it'd be a good way to catch where we fall in the cracks however it'd be something at least difficult as I have no idea where to start...probably by learning the LLVM lit system and how it gets run... I'll link lit over in the related issue.

**Comment by LADSoft** [comment]
the __c11_atomic_is_lock_free seems used for non integral types...  does that sound correct?   If so the easy thing is to just return false...   but if you think it good we could also do loads/stores if the size is less <= 8.   (it would have to be configurable in the configuration structures I guess)

I'll propagate __atomic_signal_fence into the intermediate code with the intent of disabling optimizations that would reorder the code sequence.

I'm going to get rid of __atomic_cmpswp and propagate the strong/weak compare exchange to the backend, then I'll figure out if there needs to be different code gen for this processor..

if you've put in enough stub functions I may also get rid of __atomic_modify....

**Comment by chuggafan** [comment]
__c11_atomic_is_lock_free is used for all types, it just get passed a sizeof instead of a type, it is used to mark any type as "lock free" always.

The plans with __atomic_signal_fence sound good.

__atomic_cmpswp does *NOT* need to have differing strong/weak codegen on intel platforms and in fact there doesn't need to be different codegen for acquire/release semantics IIRC due to ordering on x86 processors always being sequentially consistent.

__atomic_modify I made a function so that I didn't have to do so much work with.... if you want to get rid of it it's your prerogative but the function I made to do that will have to be modified to swap our whatever with probably a LUT for what __atomic thing it needs...

**Comment by LADSoft** [comment]
ok sounds good.   i will fix so that small structures and floats can be loaded and stored atomically since that is all the support we get...   i figured that out about atomic_cmpswp but I'm going to pass the difference between strong and weak through to the backend anyway so we have it for other architectures...   i also figured out we dont currently support kill_dependency so I'm going to figure out what to do with that...

**Comment by chuggafan** [comment]
> i also figured out we dont currently support kill_dependency so I'm going to figure out what to do with that...

Libcxx seems to treat it as if it doesn't even exist and just passes it through the templated function kill_dependency... GCC does this as well... same with MSVC....

I have no idea how the magic template works or why it works only that it supposedly works...

**Comment by LADSoft** [comment]
i got most of the atomic stuff done, then I found out the GCSE optimizer is a little buggy and not doing GCSE right now....   working on this before I can add changes for atomic_signal_fence but it seems like atomic_signal_fence will be an easy thing to incorporate.

I think there is one other optimization phase that can move subexpressions around, will look at that once I get past the GCSE problems...
