### ISSUE TITLE
In resource Workshop: disabled possibility to change Dialog font

### ISSUE THREAD

**Issue by svmizin** [LADSoft/OrangeC#376]
Look at the on-screen view: any effort to change default font “MS Sans Serif” -  for ANY whole dialog box fails : we always receive error message “Illegal character. You can input only digits here” ! 
**Problem is not as small as it looks like: 
1)	OCC Workshop selected as default quite faded font.
2)	All sizes of Windows’s dialog boxes are determined precisely by their default font !
Therefore it is desirable – that this defect of OCC Workshop will corrected, and we have possibility to change font of Dialog boxes.**  
![Impossible to change Dialog font](https://user-images.githubusercontent.com/35298943/62784210-a2417300-bac6-11e9-8b93-09bc07a7b1af.jpg)

**Comment by LADSoft** [comment]
Hi Sergey.

I will look at this and your other issue early next week.   Glad you are able to debug right now though.

**Comment by LADSoft** [comment]
I'm about to push a fix for this issue; will make a release for it later today or tomorrow.

**Comment by svmizin** [comment]
Thank you very much, dear David, thank you very much again !
You keep your responsibility and quality marks of your works on highest degree !
How i understad you, as i too old programmer... 
For now i decided problem with debugger-watcher - by moving from OCC 6.037->6.041. 
And as i understand, now you will correct problem with dialog box fonts in a future...
With my best wishes, Sergey Mizin

**Comment by LADSoft** [comment]
thank you for saying so!   I put a new version of the installer up on my web site that fixes the dialog issue, i've also been putting the installer into the 'release' section of this project on github.

**Comment by svmizin** [comment]
19.8.2019
Dear David,
Unfortunately, I should report, that you did NOT correct bug/defect with font-dialog-boxes in new “fixed release” by 11.08.2019. Defect with dialog-box-font-change in new release became worse ! and became more secretive. That is in new, “corrected” OCC v.6.0.42.1 we can change dialog-box-font ONLY ONCE !!! ONCE – and FOREVER! After first changing of dialog-box-font – all next changes of it – WILL FAIL ! Any second and next changes of dialog-box-font from resource-editor of OCC 6.0.42.1 with rebuilding and any recompilations will stay dialog-box-font same with after 1-st change! I do not how it is possible, because, in text form of respective resource file, - dialog-font showed as you choose it in resource editor ! BUT, after any rebuildings number, the program will show the dialog with dialog-font AFTER FIRST CHANGING! I do not know – how it is possible, but it is really thus in new “corrected” OCC 6.0.42.1 I mean that, when I say, that problem/bug with dialog-font in new “corrected” OCC version became WORSE, that it was in non-corrected 6.0.41. There, OCC resource-editor honestly refused to change default dialog-font (MS Sans Serif) and no more. In “corrected” - new version OCC resource editor change dialog-font ONCE, and do NOT permit change it more ever, in any circumstances ! Situation will became worse, than it was.
  Now I'm in thought. Probably I will be forced to return to work on the OCC version 5.7.30.1 from 07/18/2016 on which I wrote my first successful project on Orange C. Because - in that version there really aren’t such serious errors that I observe in all releases of version 6. So, for example, in that 5th version, the dialog font is easily and always correctly changed "manually": we just print the name of the desired font - and everything is understood and works there, in version 5.7.30.1 always right.
Dear David, maybe it makes sense, given the impossibility of eliminating these defects with the resource editor - is it just to return fully its version from OCC 5.7.30.1?
Or maybe the other functionality of this version? Because, for example, I am very confused by the dozens of bad warnings produced by the compiler when building the examples you attached - in version 6. There are some very incomprehensible and bad multi-line warnings - about the stack, etc. - see the attached screen below. None of this was in version 5.7.30.1. There, all your control examples are exemplary broadcast and built with 0 errors and 0 warnings.
Dear David, perhaps - is it worth it to return as a good base - to the source code of version 5.7.30.1? I get the impression that in version 6 there is only a further accumulation of defects.

**Comment by svmizin** [comment]
19.8.2019
Dear David,
Unfortunately, I should report, that you did NOT correct bug/defect with font-dialog-boxes in new “fixed release” by 11.08.2019. Defect with dialog-box-font-change in new release became worse ! and became more secretive. That is in new, “corrected” OCC v.6.0.42.1 we can change dialog-box-font ONLY ONCE !!! ONCE – and FOREVER! After first changing of dialog-box-font – all next changes of it – WILL FAIL ! Any second and next changes of dialog-box-font from resource-editor of OCC 6.0.42.1 with rebuilding and any recompilations will stay dialog-box-font same with after 1-st change! I do not how it is possible, because, in text form of respective resource file, - dialog-font showed as you choose it in resource editor ! BUT, after any rebuildings number, the program will show the dialog with dialog-font AFTER FIRST CHANGING! I do not know – how it is possible, but it is really thus in new “corrected” OCC 6.0.42.1 I mean that, when I say, that problem/bug with dialog-font in new “corrected” OCC version became WORSE, that it was in non-corrected 6.0.41. There, OCC resource-editor honestly refused to change default dialog-font (MS Sans Serif) and no more. In “corrected” - new version OCC resource editor change dialog-font ONCE, and do NOT permit change it more ever, in any circumstances ! Situation will became worse, than it was.
  Now I'm in thought. Probably I will be forced to return to work on the OCC version 5.7.30.1 from 07/18/2016 on which I wrote my first successful project on Orange C. Because - in that version there really aren’t such serious errors that I observe in all releases of version 6. So, for example, in that 5th version, the dialog font is easily and always correctly changed "manually": we just print the name of the desired font - and everything is understood and works there, in version 5.7.30.1 always right.
Dear David, maybe it makes sense, given the impossibility of eliminating these defects with the resource editor - is it just to return fully its version from OCC 5.7.30.1?
Or maybe the other functionality of this version? Because, for example, I am very confused by the dozens of bad warnings produced by the compiler when building the examples you attached - in version 6. There are some very incomprehensible and bad multi-line warnings - about the stack, etc. - see the attached screen below. None of this was in version 5.7.30.1. There, all your control examples are exemplary broadcast and built with 0 errors and 0 warnings.
Dear David, perhaps - is it worth it to return as a good base - to the source code of version 5.7.30.1? I get the impression that in version 6 there is only a further accumulation of defects.
With my best wishes to you, Sergey Mizin

**Comment by svmizin** [comment]
19.8.2019
Dear David,
Unfortunately, I should report, that you did NOT correct bug/defect with font-dialog-boxes in new “fixed release” by 11.08.2019. Defect with dialog-box-font-change in new release became worse ! and became more secretive. That is in new, “corrected” OCC v.6.0.42.1 we can change dialog-box-font ONLY ONCE !!! ONCE – and FOREVER! After first changing of dialog-box-font – all next changes of it – WILL FAIL ! Any second and next changes of dialog-box-font from resource-editor of OCC 6.0.42.1 with rebuilding and any recompilations will stay dialog-box-font same with after 1-st change! I do not how it is possible, because, in text form of respective resource file, - dialog-font showed as you choose it in resource editor ! BUT, after any rebuildings number, the program will show the dialog with dialog-font AFTER FIRST CHANGING! I do not know – how it is possible, but it is really thus in new “corrected” OCC 6.0.42.1 I mean that, when I say, that problem/bug with dialog-font in new “corrected” OCC version became WORSE, that it was in non-corrected 6.0.41. There, OCC resource-editor honestly refused to change default dialog-font (MS Sans Serif) and no more. In “corrected” - new version OCC resource editor change dialog-font ONCE, and do NOT permit change it more ever, in any circumstances ! Situation will became worse, than it was.
  Now I'm in thought. Probably I will be forced to return to work on the OCC version 5.7.30.1 from 07/18/2016 on which I wrote my first successful project on Orange C. Because - in that version there really aren’t such serious errors that I observe in all releases of version 6. So, for example, in that 5th version, the dialog font is easily and always correctly changed "manually": we just print the name of the desired font - and everything is understood and works there, in version 5.7.30.1 always right.
Dear David, maybe it makes sense, given the impossibility of eliminating these defects with the resource editor - is it just to return fully its version from OCC 5.7.30.1?
Or maybe the other functionality of this version? Because, for example, I am very confused by the dozens of bad warnings produced by the compiler when building the examples you attached - in version 6. There are some very incomprehensible and bad multi-line warnings - about the stack, etc. - see the attached screen below. None of this was in version 5.7.30.1. There, all your control examples are exemplary broadcast and built with 0 errors and 0 warnings.
Dear David, perhaps - is it worth it to return as a good base - to the source code of version 5.7.30.1? I get the impression that in version 6 there is only a further accumulation of defects.
With my best wishes to you, Sergey Mizin.




s.v.mizin на gmail.com

From: David Lindauer
Date: 2019-08-13 05:42
To: LADSoft/OrangeC
CC: svmizin; Author
Subject: Re: [LADSoft/OrangeC] In resource Workshop: disabled possibility to change Dialog font (#376)
thank you for saying so! I put a new version of the installer up on my web site that fixes the dialog issue, i've also been putting the installer into the 'release' section of this project on github.

**Comment by svmizin** [comment]
Today, after some different efforts to find optimal working solution, i have found such
working variant. I have returned to preceeding version - OCC v6.0.41.1, which you have "corrected" 
now to current 6.0.42.1. Because, i found working variant to "detour" font defect of resource editor.
Namely : i change dialog-box-font manually, outside the resource editor. Precisely: 
i close current project in OCC, and check respective xxxx.rc file in text editor : typing proper font
in quotas instead of default font (for instanse "Arial" instead of "MS Sans serif") . 
After that, and rebuilding full project all works good. 
Therefore i suggest to you, while to return that variant for all OCC users. And you can issue respective remark
unless you will correct this hard problem in resource editor. 
For me - it is optimal variant, because earlier OCC versions have problems with debugger, and 
v 6.0.42.2 is behaving strangely after second font changing. 
With my best wishes to you, Sergey V. Mizin



s.v.mizin на gmail.com

From: David Lindauer
Date: 2019-08-13 05:42
To: LADSoft/OrangeC
CC: svmizin; Author
Subject: Re: [LADSoft/OrangeC] In resource Workshop: disabled possibility to change Dialog font (#376)
thank you for saying so! I put a new version of the installer up on my web site that fixes the dialog issue, i've also been putting the installer into the 'release' section of this project on github.

**Comment by svmizin** [comment]
Today, after some different efforts to find optimal working solution, i have found such
working variant. I have returned to preceeding version - OCC v6.0.41.1, which you have "corrected"
now to current 6.0.42.1. Because, i found working variant to "detour" font defect of resource editor.
Namely : i change dialog-box-font manually, outside the resource editor. Precisely:
i close current project in OCC, and change respective xxxx.rc file in text editor : typing proper font
in quotas instead of default font (for instanse "Arial" instead of "MS Sans serif") .
After that, and rebuilding full project all works good.
Therefore i suggest to you, while to return that variant for all OCC users. And you can issue respective remark
unless you will correct this hard problem in resource editor.
For me - it is optimal variant, because earlier OCC versions have problems with debugger, and
v 6.0.42.2 is behaving strangely wrong after second font changing.
With my best wishes to you, Sergey V. Mizin

**Comment by GitMensch** [comment]
In this case: please reopen

**Comment by LADSoft** [comment]
i just saw this.    Will look at it soon...

**Comment by LADSoft** [comment]
Hi Sergey,

it seems to work...   how are you doing the build?   Pressing one of the toolbar buttons?   if so which one?   Right click menu?   Which menu item?   Project menu?   Which menu item?   are you editing the rc file while the debugger is running?

**Comment by svmizin** [comment]
Hello, David.
As i remember,
i do NOT change resource *.rc file during debug session, and at runing program at all, I am not so beginer programmer.
Usually, now i proceed with program text in such order :
changing program text, i press button "compile" (single file), on tool bar,
then i press button "build all", 
then press buttons by my choice : "Start  debug" or Start without debug"
Essential : now i have return (from last week) on OCC 6.0.41.1 version, 
because when i find "detour way" to change default dialog font - this version
works good, but v.6.0.42.1 - after 2nd font changing behaved very  bad - hangs up, mystically fails debug session and so on...
Now i work with v.41 and its behavior is quite proper for me.
Although i sometimes observe volatile deffects in debugger, connecting also with spontaneous non-full project rebuilding in OCC.
A will describe it later in post to my issue about debugger#375.
I do not know - how you will decide with dialog font problem, but for today - i advice to you - return back OCC version 6.0.41.1 - as optimal release:
probably - less userc of OCC have need to change dialog font - as only i saw it... 
With my best wishes to you, 
Sergey Mizin




s.v.mizin на gmail.com

From: David Lindauer
Date: 2019-08-24 12:18
To: LADSoft/OrangeC
CC: svmizin; Comment
Subject: Re: [LADSoft/OrangeC] In resource Workshop: disabled possibility to change Dialog font (#376)
Hi Sergey,
it seems to work... how are you doing the build? Pressing one of the toolbar buttons? if so which one? Right click menu? Which menu item? Project menu? Which menu item? are you editing the rc file while the debugger is running?

**Comment by LADSoft** [comment]
ok thanks that may help...   I didn't realize the debug session was problematic at that point.

Can you remind me what OS you are running on?   I can't remember if was  XP or Windows 7.

**Comment by svmizin** [comment]
Windows-7-64,
for now - i am ending my responce on debugger problem, 
i will send it on issue, and will repeat it as reply to this your message !
Many thanks, Sergey Mizin




s.v.mizin на gmail.com

From: David Lindauer
Date: 2019-08-26 16:47
To: LADSoft/OrangeC
CC: svmizin; Comment
Subject: Re: [LADSoft/OrangeC] In resource Workshop: disabled possibility to change Dialog font (#376)
ok thanks that may help... I didn't realize the debug session was problematic at that point.
Can you remind me what OS you are running on? I can't remember if was XP or Windows 7.

**Comment by svmizin** [comment]
Dear comrades.
Thank you for your efforts. Now I deeply work with my new project on OCC. At that, I return to OCC v. 6.0.41.1, because of volatile fails of 42.1 version after 2nd dialog font changing.
Now, in general, debugger of OCC works good with one strange volatile fault, which I can not localize the while. It appears often if I put debugger break-down point BEFORE starting the program in debugger. In this case often, on unknown reason, the debugger do not catch this break-down point miss(omit) it. Moreover, if it already happened, even full rebuilding of the project (and work-area) do not correct the fault. In this case only one method helps : full closing of work-area, reopen it, and full re-building. After that – in OCC v.6.041.1 – all works good.
For you pleasure I should say, that in MS Visual Studio – all is MUCH MORE BAD, than in OCC !!! : ) :) :)
Really : now I CAUSED rapidly rewrite complicated device-data re-calculation program – to replace first it version, written 2-3 years ago on MS Visual Studio 2012 (bought) by another programmer. Because last month this “powerful MS-Visual Studio made” huge data re-calculation program have became fail in full on Windows-10, and even in Windows-7 computers, probably after next Windows update !!! As result - we have THE ONLY computer with this important data-treatment (about Earth radiation), the only computer – where were forbidden any update of Windows!!! Thus we saw all “advantages” of firmware MS Visual Studio!!! As result – I should fast re-write this program on OCC, at that I have no source code – that programmer with MS Visual Studio leave us…
You can decide yourself - leave this issue opened while, or close it... ?
Many thanks for your efforts...




s.v.mizin на gmail.com

From: David Lindauer
Date: 2019-08-26 16:47
To: LADSoft/OrangeC
CC: svmizin; Comment
Subject: Re: [LADSoft/OrangeC] In resource Workshop: disabled possibility to change Dialog font (#376)
ok thanks that may help... I didn't realize the debug session was problematic at that point.
Can you remind me what OS you are running on? I can't remember if was XP or Windows 7.

**Comment by LADSoft** [comment]
Going to assume that the edit window was the issue.
