### ISSUE TITLE
Using unordered_set may cause errors

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#38]
Using unordered_set may cause errors

smp.cpp:
```
#include <unordered_set>
int main() {
    std::unordered_set<int> a;
    a.insert(1);
    return 0;
}
```

cmdline> occ smp.cpp
cmdline> smp.exe

RESULT:
Access Violation

CS:EIP 0023:00412877  SS:ESP 002B:0019F9A0
EAX: 00000000  EBX: 0019FF18  ECX: 00000000  EDX: 00000000  flags: 00010202
EBP: 0019FF18  ESI: 00000000  EDI: 0019FF18
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

----
smp2.cpp:
```
#include <unordered_set>
#include <string>
int main() {
    std::unordered_set<std::string>	a;
    std::unordered_set<std::string>	b = a;
    return 0;
}
```
cmdline> occ smp2.cpp

RESULT:
Error: Undefined External std::__1::hash<basic_string<char, char_traits<char>, allocator<char>>>::operator ()( const basic_string<char, char_traits<char>, allocator<char>>&) const  in module r:\test\smp2.cpp

----
When using a type without hash, occ.exe aborts.
smp3.cpp:
```
#include <unordered_set>
struct A {
    A() {}
};
int main() {
    std::unordered_set<A>  a;
    std::unordered_set<A>  b(a);
    return 0;
}
```
cmdline> occ smp3.cpp

**Comment by LADSoft** [comment]
there was a problem with the 'hook' operator:   when one of the results was nullptr the overall type would become nullptr instead of the type of the other result.   This cascaded into an incorrect selection for the overload of unique_ptr::reset and caused the unordered set initialization process to crash.

**Comment by tenk-a** [comment]
smp.cpp was compiled with v 6.0.24.1. (smp 2, smp 3 is still)

**Comment by LADSoft** [comment]
sorry I totally missed that there were three issues.   On the second, there was a problem with declaring class member functions outside a specialization of the class.   I fixed the third as well

**Comment by tenk-a** [comment]
v 6.0.25.1, smp2.cpp can be compiled. smp3.cpp no longer abort.
Thank you
