### ISSUE TITLE
dirs.mak missing / Travis environment borked?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#381]
The [travis log](https://api.travis-ci.org/v3/job/570597652/log.txt) is full of omake? warnings (44 times referencing "dirs.mak")

> ls: cannot access [..]/dirs.mak: No such file or directory

Is this a configuration issue, something missing, or ???

**Comment by LADSoft** [comment]
i checked and dirs.mak is still there.  probably was actually complaining about the new file 'appveyorversion.bat'.   As I fell asleep last night I was like 'shoot I forgot to check that in'.

I fixed it now; if it builds this morning I will close this...

**Comment by GitMensch** [comment]
> i checked and dirs.mak is still there.

Just rechecked - the [current travis log](https://api.travis-ci.org/v3/job/571039701/log.txt) (still building) shows this error very often.

Further checking: the error is actually produced in [src/treetop.mak](https://github.com/LADSoft/OrangeC/blob/master/src/treetop.mak#L56) (and therefore at least 7 months old) - Can I suggest to replace that by a simple `test -f "$(_TARGETDIR)$(PATHEXT2)dirs.mak"`?

**Comment by LADSoft** [comment]
yeah i found out later I misread the issue...   I had like a half hour before work this morning and was in a dreadful hurry to try to finish the versioning issue...   was planning not to close it until I looked into it further.

I'll check it out tomorrow nite.

**Comment by LADSoft** [comment]
I finally got to this but travis isn't working right now.   I'm gonna let it settle for a couple of days and see if they fix something because I don;t think I changed anything on my end in the last three days since it worked...   if that doesn't happen I think you said in another issue that WIN32 support should work there now so I may see if I can do something with that to wrap up the various travis issues after doing #369

**Comment by GitMensch** [comment]
For the broken travis build #383 should work - at least [its build](https://travis-ci.org/LADSoft/OrangeC/builds/572600437) shows the dirs.mak issue (and the c++ switches used on c files warning) again; let's see what Appveyor says...

**Comment by LADSoft** [comment]
thanks.

The problem with the 'dir' warning was actually benign, it was using the unix 'ls' to test for the existance of a file, and ls printed an error when it couldn't find it.   I fixed this though, by using $(wildcard) instead.   But I had to fix a bug in the behavior of $(wildcard)

**Comment by GitMensch** [comment]
As noted above `test -f ` would have provided a fix, too - but your wildcard solution is actually cross-plattform and we got an important fix in the makefile handling, so: yay :-)
