### ISSUE TITLE
Stack trace line numbers are not shown during fullbuild

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#382]
I noticed this while attempting to figure out what is causing OCC to crash and burn for my PR #380 and the debug build [here](https://ci.appveyor.com/project/LADSoft/orangec/builds/26650493/job/8iq9h2xh0mmlm9mk) shows that when the stack trace is dumped it does not show line numbers, file names, function names, etc. meaning that somewhere there is a problem with debug builds, I don't know where but I know it's there.

**Comment by LADSoft** [comment]
the issue was that the file name for the debug file as stored in the EXE didn't have a full path...  I'll push it whenever I'm ready to do my next test of builds...
