### ISSUE TITLE
Update inno setup

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#387]
the version of inno setup previously being used crashes on windows 10 during the install.   Update build to use the latest...

**Comment by LADSoft** [comment]
0c616777ea117449a426b2a8bd00e9f0e75a26e6

**Comment by GitMensch** [comment]
So - closed?

**Comment by LADSoft** [comment]
I'm waiting for artificacts to be built on appveyor

**Comment by GitMensch** [comment]
> I'm waiting for artificacts to be built on appveyor

Currently they do not build, an issue with the Makefile or omake invocation?

~~~
path=%ORIGPATH%
cd ..\tests
omake -B
Error makefile(2): Expected rule
Command exited with code 2
~~~

**Comment by LADSoft** [comment]
there are a lot of problems with the builds.  I'm working through them slowly.   In the last round enough built that inno setup compiler could run and it seems to have been successful, so I'm closing this.
