### ISSUE TITLE
Coverity Scan, Libraries

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#392]
fix the coverity scan issues on the util, objlib, ocpp, and netlib projects

**Comment by LADSoft** [comment]
So I went to start on this last night, but the coverity server wasn't responding when I tried to go to the defects page.   Same problem again tonite.   Will ping it every so often to see if it comes back...

**Comment by LADSoft** [comment]
I still can't get in to the defect viewer after about a week.   I reviewed recent issues and people have on and off had similar problems but coverity keeps saying they've fixed it.   So I wrote them a message and asked them if there is something further I need to do on my side.

**Comment by LADSoft** [comment]
the coverity contact said there is a significant problem but they hope to have it fixed in the very near future.   Will keep polling it :smile:

**Comment by GitMensch** [comment]
Thank you for the update.

**Comment by LADSoft** [comment]
cloverity was back tonite so I worked through a couple of the libraries.   Finally making progress on this very old issue lol!

Mostly I'm just fixing stuff regardless of how trivial I think it is because most of the stuff being flagged isn't very intense in terms of how much rework is required.   But I'm deferring some stuff in the floating point handling until I work on #377 again, because I think there may need to be major rewrites there anyway.

Tomorrow nite I'll finish the 40 or so issues in DotNetPELib then revalidate the suite and upload the changes to Coverity for another sweep.

**Comment by LADSoft** [comment]
there were 642 issues, now it is down to 525 :smile:

**Comment by GitMensch** [comment]
Hm, I suggest to either create a second issue to inspect the 525 later or to re-open this one (I'd second that working on the occ parser and backend seems much more important for now and this is already part of the milestone'd plan).
Good work on the decrease, the amount is impressive.

**Comment by LADSoft** [comment]
I got through what this issue was about - which was to clean up the coverity scan on the libraries.   I think there are like six or seven issues I marked as 'ignore' but other than that I got through all the issues related to this...   there are further issues to take care of the other 525, which are in other parts of the project.   I think I have it planned to go through more of them in milestone 2.

**Comment by GitMensch** [comment]
Thank you for the explanation, this does make sense to me now ;-)
