### ISSUE TITLE
Coverity scan, various support tools

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#393]
coverity scan on assembler, linker, librarians, onm

**Comment by LADSoft** [comment]
i'm working on the upload for the scan now.

**Comment by LADSoft** [comment]
outstanding defects:874.    The latest rewrites added around 300 new issues...

**Comment by LADSoft** [comment]
there were only 77 issues in this part of the coverity scan project, but I had to do a lot of rework in olib project to resolve some of them.    Seems like it needed me to check return values from file i/o functions in the C runtime lol!   I guess I got a bit lax :)

I did a second scan which verified most of the changes but still left some open issues.   I tried fixing them again and now I'm trying to get another coverity scan run done.   But I am having problems with uploading (the upload file is 280MB so network errors often kill uploads from home) and then I decided to do it by proxy through travis.  But when I got the build on travis running properly again it didn't seem to do anything.    The travis logs show the setup working just nothing happened on the coverity site...    Waiting until tomorrow to try again in case the coverity site is ignoring my submission.   One is only allowed limited submissions per day and week.   I don't think I overdid it but don't know what else to do other than wait...

The C compiler scans are still a couple of milestones away; I may move them into milestone 3 since there are apparently a lot of issues in that part of the project...   I have some hope milestone 3 won't be too bad to complete with the current workload but we will see...

once this issue clears we'll be done with this milestone.

**Comment by GitMensch** [comment]
Sounds reasonable, thank you for the update and for the progress.

**Comment by LADSoft** [comment]
its been one disaster after another; yesterday I couldn't even get to the coverity site, too many network issues.   After this point I've got travis at least trying to build for coverity, but, the coverity upload is broken for reasons unknown.    It does the upload but only uploads a couple of files worth of data...   Unfortunately I cannot see the log file to see why...   I'm wondering if it is something stupid like I've installed a 32-bit version of g++7 or something so coverity can't hook it properly.

I've used up both scans for today, will try again tomorrow.

**Comment by LADSoft** [comment]
got the scan running on travis but don't get exactly the same results as with msvc...   lots of issues went away.    still it was good enough to verify things for purposes of this issue...   only relevant issues left are two for tainted reads from files.   I tried various things like checking the return value and checking for EOF right after the read but that isn't good enough...   I'm going to let it go for now.   Maybe I will come back to it when I do the rewrite for windows on travis in milestone 3 (issue #257)
