### ISSUE TITLE
Occ.exe aborts when using VLA

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#40]
Occ.exe aborts when using "Variable Length Array" of C99

smp.c:
```
void func(int n) {
    char buf[n];
}
int main() {
    func(1000);
    return 0;
}
````
cmdline> occ /9 smp.c

**Comment by LADSoft** [comment]
fixed.   Also fixed a problem with passing VLAs to unprototyped functions, and enabled VLAs in C++ mode

**Comment by tenk-a** [comment]
I compiled with v 6.0.24.1. (smp.c, smp.cpp)
Thank you
