### ISSUE TITLE
Update SQLITE3

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#402]
SQLITE3 component is many years out of date and needs to be updated.   Latest version right now is 3.29.

**Comment by GitMensch** [comment]
> SQLITE3 file exists in several places in the repository. I should probably try to resolve that...

Yes, please do this.

**Comment by LADSoft** [comment]
I'm working on this while I wait for coverity to come back so I can work on #392.   It was a good thing to have a separate issue, as I immediately had two problems compiling the new version (one a parser problem and one a problem in the optimizer).   And now it crashes when I run it!

so now occ can compile things like this:

char *(hello[]) = { ... };

where the parenthesis are superfluous but generated an error...
