### ISSUE TITLE
installer: image and default path

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#406]
I've just opened the Installer the very first time and somehow felt to be blinded by the chosen colors:
![grafik](https://user-images.githubusercontent.com/6699539/64562075-74ad4b00-d34c-11e9-84a0-7f11c45d4935.png)
![grafik](https://user-images.githubusercontent.com/6699539/64562150-9ad2eb00-d34c-11e9-942e-acc3de372542.png)
Can I request to adjust the image or to get rid of it?

Additional - this is the default path: `C:\Program Files (x86)\Orange C 386`,
I think it is duplicated and confusing (x86 + 386); my suggestion is to use `C:\Program Files (x86)\OrangeC`, instead.

**Comment by LADSoft** [comment]
I think microsoft recommends the opening screen shouldn't be there anyway...   I had arbitrarily put it back recently.   Will look at removing it.   And yeah we can change the path...

I have some checkins related to the latest milestone but can't get them to compile reliably... meanwhile I'm temporarily out of town on a business trip :)

**Comment by GitMensch** [comment]
Just checked NPP as one of my favorite editors - you get the install language first, then the opening screen.
I actually think it is reasonable to keep it, just... change the image (a gray-scale of the current version would already be better). On the license screen there is again a "very colorful" image which could be replaced by something else, too.
Maybe it is a good time to come up with a minimal logo for OrangeC, the simplest is likely an orange C.

**Comment by LADSoft** [comment]
I'll grayscale the images and change the path; don't really feel like making new images right now though.
