### ISSUE TITLE
add binaries to release (=zip similar to CI artifacts)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#407]
I may have requested it before, but it looks like there is no issue tracking this.

I'd prefer to have the option to just unpack the compiler+toolset somewhere (the main possible benefit of the installer would be the addition of bin to PATH and possibly the file association to OCIDE and this should be doable from within OCIDE).

So - can you please (ideally created automated when the installer is created) add an OrangeC.zip with the complete package to the artifacts?

Note: theoretically you could also add the creation of the installer to the CI build (or do you need "special software" to do this?) . Then as an additional step could auto-create the release@GitHub, if - for example - you create a tag (or a tag following a naming scheme). What do you think, is this worth another issue to be created?

**Comment by LADSoft** [comment]
there is already a file like this being generated for a zipped binaries version for this in the CI builds and elsewhere...   it just doesn't show up on the github 'release' page.   I think in the CI builds the current one is occ60431e.zip...    

The installer is also being created in the CI builds, I think the current one is occ60431.exe.  It is created with inno setup, which is available on chocolatey....

Right now I load the files into the release by hand, do you know of a way to automate it?

**Comment by chuggafan** [comment]
There's a way to set appveyor to pick up certain files for release if you make tag for a release, so if you make a git tag before a commit and then push it you'd be able to get appveyor to release it.

**Comment by GitMensch** [comment]
> the installer is also being created in the CI builds

that is good - please add it to the artifacts in this case (= would show up in each correct built version @appveyor)

As @chuggafan said - it should be able to completely automate the release via GitHub. Depending on how much time you want to spend to create a nice script you may let Appveyor push the release to GitHub (with any of the artifacts you find relevant), then edit the release later to add-in a nicely formatted Changelog (also possible by using a part of the Changelog.md [if this is nicely formatted]).

**Comment by GitMensch** [comment]
Is it possible to delete the ci-test releases?
As it is currently missing - you may want to add a script that pulls the description from a NEWS (highlights) + Changelog file, if you want to do this (saving time on every upcoming release) then it seems reasonable to create a new issue for this (and if the necessary files are "in place" I could co-work on creating the scripts, if necessary).

**Comment by LADSoft** [comment]
Originally I couldn't find a way to delete them...   went back and looked again and it was obvious.
I'm not sure how to go about pulling the description from somewhere, can you give me a hint where to look to find documentation
