### ISSUE TITLE
Use TLS variable to abort at runtime

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#41]
Use thread_local(_Thread_local) variable to abort at runtime.

smp.cpp:
```
//_Thread_local int tls_var;
thread_local int tls_var;
int main() {
    tls_var = 0;
    return tls_var;
}
```
cmdline>occ smp.cpp
cmdline>smp.exe
Access Violation

CS:EIP 0023:00401023  SS:ESP 002B:0019FF3C
EAX: 00000000  EBX: 73D78744  ECX: 0040B3C0  EDX: 005E7798  flags: 00010206
EBP: 0019FF78  ESI: 00000000  EDI: 002A3000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B

**Comment by LADSoft** [comment]
I had broken this during a code refactoring.   Fixed.

**Comment by tenk-a** [comment]
I compiled with v 6.0.24.1.
Thank you
