### ISSUE TITLE
encoding issues in the resource compiler and OCIDE "invalid resource id"

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#412]
Checked CI build of 44d04798 - result: error message

> invalid resource id

for a rc file that is ANSI encoded and includes a header that is (for whatever strange reason) encoded with UCS-2 LE BOM.

Interesting side notes:

* it does **not** happen in places where C files include this header
* OCIDE cannot display this header file (shows the BOM instead)

It *may* be reasonable to split this issue into "resource compiler" and "ocide" (ideally they use the same internal functions to read the file though),

**Comment by LADSoft** [comment]
I've gone to a lot of effort to share code in other programs in the project but OCIDE has been kind of orphaned in this respect...

**Comment by GitMensch** [comment]
Hm, I somehow question that the referenced commit also solves the resource compiler.
Despite of this - nice work on the BOM issues.

**Comment by LADSoft** [comment]
you are right it probably doesn't lol.   I'll work on it as soon as I get past LADSoft/OrangeC#407
