### ISSUE TITLE
FR: release+artifacts: add 7z format

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#415]
The current CI binaries have a size 17,1MB.
I've just unpacked it and did:

```cmd
cd ZippedBinaries && "%ProgramFiles%\7-Zip\7z.exe" a -r -mx=9 "..\ZippedBinaries.7z" *
```
Result: 7,7MB, around 45% of the size. Note: 7zip command line binary "7z.exe" is available in PATH on Appveyor.

Therefore: please add this to Appveyor (to do so: use an "on build success" script to create the 7z archive and list it (with a wild card) in the artifacts.

**Comment by LADSoft** [comment]
looks like the new artifact is being generated now...
