### ISSUE TITLE
Using complex and iostream at the same time may cause an error

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#42]
Error sometimes occurs when complex and iostream are included and used. (v6.0.25.1)
~~~
#include <complex>
#include <iostream>
int main() {
    std::cout << "123" << std::endl;
}
~~~
RESULT:
Error(232)    C:\Program Files (x86)\Orange C 386\include\complex(273):  Could not find a match for 'std::__1::ostreambuf_iterator<char, char_traits<char>>::ostreambuf_iterator<char, char_traits<char>>()' in function std::__1::__pad_and_output<char, ostreambuf_iterator<char, char_traits<char>>>(ostreambuf_iterator<char, char_traits<char>>, char const *, char const *, char const *, ios_base&, char)
Warning(436)  smp.cpp(4):  In template instantiation started here
(occ.exe abort)

Removing '#include < complex >' will compile.

**Comment by LADSoft** [comment]
I fixed a spurious error generation that did not affect the compile, also fixed it so that if a real error occurred under those conditions it would not abort.    

Thank you for finding these bugs, it is very much appreciated.

**Comment by tenk-a** [comment]
I compiled with v 6.0.26.1.
Thank you
