### ISSUE TITLE
CPP testsuite

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#422]
As ocpp was internally replaced it seems like a good time to recheck that it works as expected. The only "testsuite" I've found is the one of [mcpp](http://mcpp.sourceforge.net/) - it may be possible to verify ocpp against this.
There are likely other preprocessor testsuites available, which I'm currently not aware of. Very likely GCC and clang have tests but they may be very tightened to these compiler commands (which may also be true for mcpp...)

So short note: is anybody able to give ocpp a deeper test (other than "preprocess source x in a way that occ can handle")?

**Comment by LADSoft** [comment]
actually the older preprocessor was tested I think against mcpp's test suite at some point in the distant past.   It was some comprehensive test suite distinctively for preprocessors I remember that much.   The new one is pretty much a C++ rewrite of the older one so it should be close.   I'll see if I can dig up the test suite and see where we stand.

**Comment by GitMensch** [comment]
If I've understood it correctly you've ran the test, found some issues and fixed them, correct?
Would there be reason to add the tests to CI or are these parts adjusted too seldom and therefore the tests should just be run manually (or possibly only on a special branch/tag)?

**Comment by LADSoft** [comment]
that is correct, I still had the test setup from last time I ran them so I just ran it again and fixed the issues it found.

I think the licensing is ok and I could add the tests; my main problem when I was thinking about it is that they have heavy use of assert so if something goes wrong it is a little unmanageable right now...   but maybe I can work around that.
