### ISSUE TITLE
onm Access Violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#425]
I've tripped different access violation in different tools in the last two years - that's officially the first time for onm (using the current MINGW64 CI build results)

```text
Access Violation:(c:\dev\OrangeC\bin\onm.exe)
CS:EIP 0023:004081C5  SS:ESP 002B:0019F0D4
EAX: 00000000  EBX: 00000000  ECX: 0019F4BC  EDX: 00000004  flags: 00010213
EBP: 0019F53C  ESI: 00000000  EDI: 00000000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B


CS:EIP  8B 47 10 23 C0 7C 48 83 F8 0D 7D 43 50 8B 04 85 

Stack trace:
	                4081c5
	                403cbe
	                4013fc
	                40104a
	                419817
```

**Comment by LADSoft** [comment]
what command line did you use to cause this?

**Comment by GitMensch** [comment]
Not sure, I've just ran the MPIR configure script. If the stack trace gives you no idea I could try to get the code parts from the script (always a little bit of work if there's no direct configure-script fail).
