### ISSUE TITLE
Linker crashes when building C++ with debug infos

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#43]
When I try to compile the attached cpp file with debug info, the linker crashes.
used commandline: occ +v hallo.cpp

[hallo.zip](https://github.com/LADSoft/OrangeC/files/1409773/hallo.zip)

Without debug infos all works correct. 

Regards
Alex ;-)

PS: Version 6.0.25.1

**Comment by LADSoft** [comment]
the problem you mentioned is easy to fix, however, while I was testing I found there is something wrong with debugging complex lambda functions.   I will try to get it fixed tomorrow nite...

**Comment by LADSoft** [comment]
i fixed your issue, also fixed a handful of other issues related to the /v switch that I found while testing.
