### ISSUE TITLE
sizeof with double parenthesis around a type specification does not work.

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#432]
Not anything that needs to be rushed, just stumbled over `uint_least32_t` and [friends](https://en.cppreference.com/w/cpp/types/integer) which are typedef'd inside this repo under libcxx but aren't usable in occ yet.

**Comment by LADSoft** [comment]
could you say under what conditions they are unusable?   Because they seem to be defined in their proper place in stdint.h/cstdint and when I tested I could access them.

**Comment by GitMensch** [comment]
If you see everything is fine then feel free to close this, I think I just was confused by

```c
#include <stdint.h>
int
main ()
{
if (sizeof ((uint_least32_t)))
	    return 0;
  ;
  return 0;
}
```

producing

> occ testme.c
occ Version 6.0.43.40 Copyright (C) LADSoft 2006-2019
Error(181)    testme.c(6):  if statement needs close parenthesis in function main
1 Errors

while the parenthesis are obviously fine.

**Comment by LADSoft** [comment]
oops that is a bug...   but not with stdint.h.    occ doesn't like the double parenthesis around the type, Will fix...

**Comment by LADSoft** [comment]
ok apparently the inner parenthesis on the sizeof are supposed to be taken as indicative of an expression and types aren't allow there...   I tried it with various compilers including gcc and they all agree on that.    So this is a mal-formed program...   maybe there is an opportunity for occ to emit a more useful diagnostic...   but other than that there is no issue here.
