### ISSUE TITLE
Switch object files to binary format

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#436]
it appears mpir needs the object files to be binary so that it can parse them during the autoconfig operation.   Switch the toolchain to binary mode and add a simple program to dump the binary file into an ASCII file for viewing.

**Comment by GitMensch** [comment]
Note: we should not care about MPIR needing the binary format at all.

I think it is reasonable to have the switch to binary in any case, as long as the simple program can both dump the file to ASCII and convert the ASCII file back, too.
