### ISSUE TITLE
OCC should error when doing floating point comparisons

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#437]
```c
#define VAL 12.1
#define VAL2 12.2
int main()
{
    #if VAL < VAL2
    return 1;
    #endif
    return 0;
}
```

This file compiles and runs perfectly well on 6.0.43.1, but the C standard at 6.10.1 paragraph 4 has no mention at all of dealing with floating point numbers, in fact it seems to assume you'll only ever encounter integers. It seems the common way to deal with it is to error on the comparison (ICC, MSVC, clang, and GCC all do this), so what should probably be done instead of forcing an integer comparison (the binary returns 0) is to error. If we decide to take the floating point route we'd be doing a very undefined behavior and a very out-of-place behavior compared to all the other compiles & preprocessors.

**Comment by LADSoft** [comment]
thanks!

**Comment by LADSoft** [comment]
this was fixed here:

c846eee9bd903d644a36e216145ef421d6507ec0
