### ISSUE TITLE
mini-gmp errors: cannot modify a const object

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#440]
As MPIR has the yasm dependency (and GMP has some different code and tests) I'm going on with GMP 6.1.2 - configure works fine, But the very first file fails to compile:

~~~
Error(146)    ..\mini-gmp\mini-gmp.c(1952):  Cannot modify a const object in function mpz_abs_add
Error(146)    ..\mini-gmp\mini-gmp.c(2872):  Cannot modify a const object in function mpz_gcdext
Warning(132)  ..\mini-gmp\mini-gmp.c(3099):  Suspicious pointer conversion in function mpz_ui_pow_ui
Warning(132)  ..\mini-gmp\mini-gmp.c(3211):  Suspicious pointer conversion in function mpz_powm_ui
Warning(132)  ..\mini-gmp\mini-gmp.c(3318):  Suspicious pointer conversion in function mpn_perfect_square_p
Warning(132)  ..\mini-gmp\mini-gmp.c(3332):  Suspicious pointer conversion in function mpn_sqrtrem
Error(146)    ..\mini-gmp\mini-gmp.c(3644):  Cannot modify a const object in function mpz_and
Error(146)    ..\mini-gmp\mini-gmp.c(3716):  Cannot modify a const object in function mpz_ior
Error(146)    ..\mini-gmp\mini-gmp.c(3789):  Cannot modify a const object in function mpz_xor
~~~
[mini-gmp.zip](https://github.com/LADSoft/OrangeC/files/3708505/mini-gmp.zip)

**Comment by LADSoft** [comment]
I'll get to this and the updates to #330 within a couple of days; right now I'm interested in making inroads into #297 :smile:

**Comment by GitMensch** [comment]
That's fine. I'll come back to this not before 2019/10/21. If you've already find some time to work on this you may try GMP on your own (same setup as MPIR just [geting GMP](https://gmplib.org/#DOWNLOAD) instead (no need for yasm) and adjust the configure option to drop the yasm/static/shared part.

**Comment by LADSoft** [comment]
I fixed some stuff; now it procedes quite a way through the compiles then fails on this:

> libtool: link: occ --nologo -o .libs/libgmp-10.dll .libs/libgmp.la-2.o  --export-all-symbols --output-def .libs/libgmp-3.dll.def   `func_echo_all "" | /usr/bin/sed 's/ -lc$//'` -link -dll
> Unknown switch '--export-all-symbols'
>

**Comment by LADSoft** [comment]
this belongs here too:

a2fb56a52ec9443053078e06cbbca58e6ef33537

**Comment by GitMensch** [comment]
You may work-around the wrong command line used by GMP/libtool (I'll dive in that later) by generating the expected output manually.

Note: this does look like as `--disable-shared --enable-static` wasn't used during configure, was it? (reminder: after [re-]configure you have to manually adjust the lib command in the [re-]generated libtool script).

**Comment by LADSoft** [comment]
I used

> --disable-static --enable-shared


as that is what we ended up doing for mpir...   Is that correct?

**Comment by GitMensch** [comment]
That's the shared option which in most cases would be preferable. I _guess_ that the static one is the "simpler" to build, so this may be preferable.

The shared one should work in any case (once the build system is fixed or work-around), so please try to create the dll and link library manually and see if you can run `make check` (possibly only in the test subdirectory).

**Comment by LADSoft** [comment]
I get this:

> $ ./link
> occ Version 6.0.43.1 Copyright (C) LADSoft 2006-2019
> olink Version 6.0.43.1 Copyright (C) LADSoft 2006-2019
> len: 9
> Error: Undefined External '__gmpn_bdiv_dbm1c' in module ../compat.c
> Error: Undefined External '__gmpn_divrem_1' in module ../compat.c
> Error: Undefined External '__gmpn_popcount' in module ../primesieve.c
> Error: Undefined External '__gmpz_jacobi' in module ../compat.c
>         4 Errors, 0 Warnings
>         Errors encountered, not creating output file
> len: 9
> 

where link. calls occ to link with all the files...

briefly went searching for the __gmpz_jacobi but only found a prototype for it....   don't have time to dig deeper right now...   am trying to get the build to work.   It ONLY fails on appveyor sigh, I tried on a couple of different computers and it seems fine...

**Comment by GitMensch** [comment]
>  am trying to get the build to work. It ONLY fails on appveyor sigh, I tried on a couple of different computers and it seems fine...

I highly suggest to target the MSIL compiler part next, the build log shows multiple access violations within oasm and occ.

Once the CI builds are running again I'll continue to check GMP/MPFR.

**Comment by LADSoft** [comment]
yeah I've been trying various things to narrow down the build issues, it is taking a lot of time since it takes about 15 minutes to get results....   like I say it works fine on the other computers I have access to...  I've done complete builds 4 times in a row similar to what is going on on appveyor on multiple occassions while waiting for the appveyor to fail....   which it fails 100% the same way every time it is built lol!

anyway while waiting on that I fixed a couple of assembler bugs related to the gmp build in the 'check' part and now my problem is that libtool wants 'libgmp.la' to be a libtool archive whatever that is...   I had taken your suggestion and built it with olink...:

>         /bin/sh ../libtool --tag=CC --mode=link occ --nologo -pa--gas -o libtests.la memory.lo misc.lo refmpf.lo refmpn.lo refmpq.lo refmpz.lo spinner.lo trace.lo x86call.lo x86check.lo ../libgmp.la
> libtool:   error: '../libgmp.la' is not a valid libtool archive
> 
> Error Makefile(751): commands returned error code 1
> 

and then it goes on after failing that step and we get this:

>        C:\orangec\bin\omake.exe check-TESTS
> Error: No rule to make target 'TEST_LOGS=t-bswap.exe.log t-constants.exe.log t-count_zeros.exe.log t-hightomask.exe.log t-modlinv.exe.log t-popc.exe.log t-parity.exe.log t-sub.exe.log'
> 

can you steer me a little bit here?

**Comment by LADSoft** [comment]
we fixed the 'const' problem and several other problems compiling MPIR...   I'm going to close this since it specifically names an issue and new issues are being written around the remaining issues with compiling it...

**Comment by GitMensch** [comment]
GMP with current CI-build builds completely but the t-constants.exe tests fails, here is its output:

~~~
ULONG_MAX + 1 = 0 != 0 = 0
UINT_MAX + 1 = 0 != 0 = 0

Access Violation:(C:\dev\gmp-6.1.2\build_occ\tests\t-constants.exe)
CS:EIP 0023:004268A0  SS:ESP 002B:0019FEF4
EAX: 0019FF20  EBX: 00000001  ECX: 00000001  EDX: FFFE0000  flags: 00010246
EBP: 00000000  ESI: 0000FFFF  EDI: 003A0000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B


CS:EIP  67 66 8B 44 24 0C 67 66 8B 54 24 08 67 66 F7 74 
FAIL t-constants.exe (exit status: 1)
~~~

@LADSoft Is this a known issue already?

**Comment by LADSoft** [comment]
yes i was aware that some of the tests crash and others (often the ones related to division) fail.   I want to delay going through all the tests and fixing them, but wrote #460 to remember to address these issues.

BTW what is the make command line for running the tests?  I've been doing it by hand...

**Comment by GitMensch** [comment]
> BTW what is the make command line for running the tests? I've been doing it by hand...

In nearly all free software packages that build with autotools (and others): `make check`, also existing but much more rare are `make test`/`make tests`. (GnuCOBOL has both, `make check` is the internal suite, `make test` is the NIST ANSI COBOL85 suite and `make checkall` runs both targets in GnuCOBOL).

**Comment by LADSoft** [comment]
I was afraid of that.   Of course omake bails right after building all the tests...   something else to fix...
