### ISSUE TITLE
alloca.h missing?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#441]
Seen when trying to configure for [MPFR](https://www.mpfr.org/mpfr-current/#download) - which checks and does not find [alloca.h](http://man7.org/linux/man-pages/man3/alloca.3.html).

**Comment by chuggafan** [comment]
It's missing because it's not there, there's a custom alloca #def'd to the internal compiler __alloca in malloc.h

**Comment by GitMensch** [comment]
So... should it be added and possibly included in OrangeC's malloc.h to keep the current working parts working (and possibly also in stdlib.h to be comparable to glibc)?

**Comment by LADSoft** [comment]
I didn't realize there was a header for that.   we can add it..
