### ISSUE TITLE
constructor/destructor for shared libraries [or programs] (special gcc attributes)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#442]
That one was new to me. See [documentation](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-constructor-function-attribute) and [example](https://www.geeksforgeeks.org/__attribute__constructor-__attribute__destructor-syntaxes-c/) (which doesn't use the optional priority).

Looks useful...

**Comment by chuggafan** [comment]
Isn't this similar to what the RTL does with #pragma startup and #pragma rundown ? Just with attributes instead of pragmas?

**Comment by GitMensch** [comment]
Yes, [those pragmas](https://orangec.readthedocs.io/en/latest/occ/OCC%20Pragma%20Directives/) are similar. I *guess* the `#pragma rundown` is identical to [`#pragma exit`](http://docwiki.embarcadero.com/RADStudio/Rio/en/Pragma_exit_and_pragma_startup) so those two should be aliased (I've found no compiler but OrangeC with the rundown but some with exit).

But it is only similar as those attributes may also be used for shared objects and should be executed on dll load/unload. If you delay-load/unload a module the registered functions should be executed (possibly also multiple times). It is identical when you use the attribute in an executable (and can be seen as prefix/postfix to the `main()`). I'd argue that the use in shared objects is even much higher than in a program's main.

**Comment by LADSoft** [comment]
I looked at the documentation for #pragma exit and while it is similar to #pragma rundown, I think I may have the priorites backwards...   may have to rework that...

I think the #pragma startup/rundown should work with a DLL so it may just be a matter of implementing the __attributes__ to enter data in the table.
