### ISSUE TITLE
NAN != NAN

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#443]
```c
#include <stdio.h>
#include <math.h>
#ifndef NAN
# define NAN (0.0/0.0)
#endif
int main (void) {
  double d;
  d = NAN;
  return d != d;
}
```

MPFR's configure script warns:
> The test NAN != NAN is false. The probable reason is that your compiler optimizes floating-point expressions in an unsafe way because some option, such as -ffast-math or -fast (depending on the compiler), has been used.  You should NOT use such an option, otherwise MPFR functions such as mpfr_get_d and mpfr_set_d may return incorrect results on special FP numbers (e.g. NaN or signed zeros).

**Comment by LADSoft** [comment]
the fix for this will fix ALL comparisons involving NAN, not just equal and notequal...

**Comment by GitMensch** [comment]
Sounds good, do you have a reference for the commit hash?

**Comment by LADSoft** [comment]
didn't mean to close it.   I'll be pushing the commit later....
