### ISSUE TITLE
preparser / stdint.h broken?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#445]
```c
#include <wchar.h>
#include <stdint.h>

#if defined(WINT_MAX) && WINT_MAX < INT_MAX
typedef int    wint;
#endif

int main (void) {
  return 0;
}
```

Leads to 

~~~
$ occ test.c
occ Version 6.0.43.53 Copyright (C) LADSoft 2006-2019
Error test.c(5): Expected ')'
1 Errors
~~~

**Comment by LADSoft** [comment]
I fixed this as part of #440, problem being a type cast in a preprocessor expression.  here is the initial fix:

2f220f3fb0dd82acde73276bd4f797721205b14b

There were further bug fixes later on when I tried to compile the package with itself.
