### ISSUE TITLE
please improve static_assert

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#447]
according to [MS docs](https://docs.microsoft.com/en-us/cpp/cpp/static-assert?view=vs-2019) additional to `static_assert(condition, "message");` C++17 has `static_assert(condition);`. Using the former works with OrangeC, using the later leads to "Syntax error: ? expected in function ...".

 I assume the easiest way to achieve this is to use a macro like MPFR does. Adjusted version:

```c
#   define static_assert(c) _Static_assert((c), #c )
#   define static_assert(c,m) _Static_assert((c), m)
```

Additional, it would be useful to adjust the compiler message. Currently the text (error 212) seems to be: `%s in function %s`, I suggest to adjust this to `static assertion failed in function %s: %s`.

**Comment by LADSoft** [comment]
it was one of the things planned for sprint 4 I think...   but I can add it now :smile:

**Comment by GitMensch** [comment]
It's fine to do this in milestone 4. I just stumbled over an error message I did not understand, rechecked the code, found the assert, looked how other compiler's messages look like (all I've found include "static assert[ion]" or at least "assert") and stumbled over the C++17 syntax.

No need to rush this now.

**Comment by LADSoft** [comment]
ok.   Yeah this was one of the things I was aware was going to change, but it probably is a good idea to make the textual change you've indicated as well.

**Comment by GitMensch** [comment]
Just a ping - is there a testcase for this error (I did not found one)... or others?

**Comment by LADSoft** [comment]
I think I missed writing one.    Will leave this open and address it soon...
