### ISSUE TITLE
question/possible problem

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#448]
The following code compiles with gcc and likely with a newer cl.exe and switch to `static_assert`, but runs into the assert with OrangeC.
*Should* it compile fine?

```c
#include <stdlib.h>

typedef long  mpfr_prec_t;
typedef unsigned long  mpfr_uprec_t;
#define MPFR_PREC_MAX ((mpfr_prec_t) ((((mpfr_uprec_t) -1) >> 1) - 256))

int main (void) {
  _Static_assert(((MPFR_PREC_MAX + 7) >> 3 <= (size_t) -1), "game over");
  return 0;
}
```

**Comment by LADSoft** [comment]
I think it probably should compile ok...   I recently found a related problem with the ~ operator when used in constant evaluation though.   It would complement all 64 bits of the internally kept value even for 32-bit values and that would cause comparisons to fail...   I'll have to evaluate this.

**Comment by LADSoft** [comment]
the deal with this was, there was a comparison between 'long' and 'unsigned int'.   this was determined to be a signed comparison (since the rank of long is greater than the rank of unsigned int) but shouldn't be in this case....  so I'm changing it...
