### ISSUE TITLE
Fix destructor call bug

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#449]
consider:

        const char *env = getenv(chosenAssembler->envname);
        if (env && !switchParser.Parse(std::string(env), &ecnt, eargs))
            Utils::usage(argv[0], getUsageText());

the current version of the compiler will call the destructor for the std::string(env) even if env is null...

**Comment by chuggafan** [comment]
So it's crashing because the stl is trying to free() null memory when cleaning up the string? That sounds like a library bug not a compiler bug to me tbh. Something that might be fixed if we modified libcxx. Not sure if it was ever a problem with it though....

**Comment by LADSoft** [comment]
well the real problem was that with env being null the second part of the if never got evaluated, so the 'string' constructor in the function argument never got called on what is essentially a temporary local variable.   But, the destructor was being called anyway...   which is a bug in the code generation that led to undefined behavior.   It just so happened it worked ok when I tried it at home but failed every time on appveyor...

I'm delaying fixing the root issue for now because the fix to #297 gives me two versions of the compiler to maintain at least until #297 replaces the current version...   But I don't think it is such a big deal that I have to prioritize it to happen sooner than that...
