### ISSUE TITLE
FR: add .cc to internal lists of cxx-extensions

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#450]
The following check is is done by configure scripts to verify the C++ compiler and currently fails with `occ`:

```c
namespace foo { }
using namespace foo;

int main (void) { return 0; }
```

result:

~~~
$ occ --nologo  -g conftest.cc
Warning(482)  conftest.cc(1):  Missing type specifier for identifier 'namespace'
Error( 11)    conftest.cc(1):  Syntax error: ; expected
1 Errors
~~~

**Comment by chuggafan** [comment]
Does OCC parse .cc files as C++? Try it again with .cpp as the file extension and tell me if it works, I know it does .cxx and .cpp files just fine...

**Comment by GitMensch** [comment]
@chuggafan This was what triggered the problem, so the only question is where the extension should be added...

**Comment by GitMensch** [comment]
Adding .cc may be necessary in both the compiler/preparser (and ocide) and omake.

**Comment by LADSoft** [comment]
@chuggafan thanks for fielding this.

The compiler was supposed to know about '.cc' but there was a bug...   I'm cleaning up that region of the code...

hm... omake doesn't seem to have a 'builtins' file...   looks like there is support for builtins but it never got fully implemented...

**Comment by LADSoft** [comment]
8004c6b2b18c0e303416227affd021b1512ac243

**Comment by GitMensch** [comment]
> hm... omake doesn't seem to have a 'builtins' file... looks like there is support for builtins but it never got fully implemented...

@LADSoft I'm not sure about the details of this but suggest to create an issue for this (with some details).

Note - also concerning 804c6b - this is the default filter list of VC2019:

```xml
    <Filter Include="Source Files">
      <UniqueIdentifier>{4FC737F1-C7A5-4376-A066-2A32D752A2FF}</UniqueIdentifier>
      <Extensions>cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx</Extensions>
    </Filter>
    <Filter Include="Header Files">
      <UniqueIdentifier>{93995380-89BD-4b04-88EB-625FBE52EBFB}</UniqueIdentifier>
      <Extensions>h;hh;hpp;hxx;hm;inl;inc;xsd</Extensions>
    </Filter>
    <Filter Include="Resource Files">
      <UniqueIdentifier>{67DA6AB6-F800-4c08-8B7A-83BB121AAD01}</UniqueIdentifier>
      <Extensions>rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe;resx;tiff;tif;png;wav</Extensions>
    </Filter>
```

**Comment by LADSoft** [comment]
need to add the various extensions listed above so I reopened.

**Comment by chuggafan** [comment]
The only other c++ based extension I can think of in the rest of that list is .def which is very, verrrrry rarely used as a C++ extension.

**Comment by GitMensch** [comment]
That's a so minor issue that I want to ping @LADSoft for a minimal commit closing it.

**Comment by LADSoft** [comment]
I will do it as soon as  we get past LADSoft/OrangeC#297.

**Comment by LADSoft** [comment]
I'm not going to do the .def extension since it collides with windows linker definition files...
