### ISSUE TITLE
false-positive: 105 Function should return a value

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#452]
This warning is always raised if the function ends with an `exit()` call - and as this will end the complete program the warning should be suppressed in this case. Sample:

```c
int
test_version (void)
{
  int err = 0;
  if (0 == 0)
    {
      if (0 == 1)
        return err;
    }
  exit (1);  // warning should only be raised if this line is not active
}
```

**Comment by GitMensch** [comment]
The implementation works for this specific case, but I'd suggest to do this via handling the noreturn attribute (which the `exit()` call should have). @LADSoft what do you think about this?

**Comment by LADSoft** [comment]
that was a good idea so I made a new issue.

**Comment by GitMensch** [comment]
For reference: the new issue is #461
