### ISSUE TITLE
ocpp broken?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#454]
I wanted to recheck some headers and conditional compilation so I've issued `ocpp test.c` - but the output seems bad - first lines:

~~~
extern FILE
extern FILE
extern FILE
extern FILE
extern FILE



    extern unsigned
    FILE*
    void
    int
    int
    int
    int
    char *__attribute__((zstring))    fgets(char *__attribute__((zstring))
    int
    int
    FILE*   fopen(const char *__attribute__((zstring))  __path, const char *__attribute__((zstring))
    int   fprintf(FILE* restrict __stream, const char *__attribute__((zstring))
    int
    int   fputs(const char *__attribute__((zstring))
~~~

Shouldn't this produce the same result as `occ +i` does (which seems to show what I wanted to see)? As the help output does not mention it: how can I set the output file for the preprocessed file (currently defaults to filename without extension, I'd like to be able to send this to stdout [filename `-`], a file of my liking or at least to filename.i)?

**Comment by GitMensch** [comment]
@LADSoft:

So should ocpp produce the same result `as occ +i` does?
As the help output does not mention it: how can I set the output file for the preprocessed file (currently defaults to filename without extension, I'd like to be able to send this to stdout [filename -], a file of my liking or at least to filename.i)?

**Comment by LADSoft** [comment]
the preprocessing uses the same engine in both cases so the content *should* be the same.   Can't guarantee spacing details will match up 100% though...

will write another issue for allowing you to set the name of the preprocessed file...
