### ISSUE TITLE
unused static function needs definition

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#458]
With GCC and VS it is fine to declare a static function without defining it, as long as it isn't referenced anywhere.

OrangeC says:
> Error(481)    D:\dev\test\(0):  static function 'dummy' is undefined

Additional note: the output "(0)" looks like some information is missing.

**Comment by chuggafan** [comment]
Do you know if there's anything about this being intended behavior in the standard? https://en.cppreference.com/w/c/language/storage_duration doesn't mention anything about it at least in C. So I'm assuming this is non-conforming behavior, could you try it with -Wall -Wextra -pedantic -std=c11 for gcc?

**Comment by GitMensch** [comment]
´c11` results in "cc1plus.exe: warning: command line option '-std=c11' is valid for C/ObjC but not for C++" :-)

`gcc tests.cpp -Wall -Wextra -pedantic -std=c++11` does not raise any warning.

**Comment by LADSoft** [comment]
gcc shows a WARNING for -Wall otherwise says nothing...   I guess the occ error is too aggressive lol
