### ISSUE TITLE
FR linker: add --out-implib <file>

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#459]
This is a follow-up to #451. The help for this option with the GNU toolchain is:

    --out-implib <file>    Generate import library

Note: With the GNU toolchain this **additionally** creates the import-library. OrangeC "implies" `--out-implib dllbasename.l` which is fine, using the switch would just override the default. It _may_ be reasonable to ask for a way to _not_ create the import library, which seems be the default for the GNU toolchain.

**Comment by LADSoft** [comment]
Im going to add this as a switch, but, i don't think I can change the behavior when the switch isn't there for legacy reasons
