### ISSUE TITLE
There seems to be an error with std::function.

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#46]
There seems to be an error with std::function. (v6.0.28.1)

smp1.cpp
```
#include <functional>
int main() {
    //std::function<int(void)> fn;	// ok
    std::function<int()> fn;		// error
}
```
Error(318)    smp1.cpp(4):  Structured type 'std::__1::function<int>' not defined in function main

-----
smp2.cpp
```
#include <functional>
int fnc(void) { return 1; }
int main() {
    std::function<int(void)> fn = fnc;
}
```
Error(232)    C:\Program Files (x86)\Orange C 386\include\type_traits(3527):  Could not find a match for '__invoke((*)(*)(), void)' in function main
Warning(436)  smp2.cpp(4):  In template instantiation started here
Error(113)    C:\Program Files (x86)\Orange C 386\include\type_traits(3527):  Call of nonfunction in function main
Warning(436)  smp2.cpp(4):  In template instantiation started here
Error(232)    smp2.cpp(4):  Could not find a match for 'std::__1::function<(*)()>::function<(*)()>((*)())' in function main

----
When using std::function and std::bind, occ.exe aborted.

smp3.cpp
```
#include <functional>
int add(int a, int b) { return a + b; }
int main() {
    std::function<int(void)> fn = std::bind(add, 1, 2);
}
```
Error(232)    C:\Program Files (x86)\Orange C 386\include\functional(2079):  Could not find a match for 'std::__1::tuple<int>::tuple<int>(int, int)' in function  std::__1::__bind<(*)(int, int), int, int>::__bind<(*)(int, int), int, int>((*)(int, int)&&, int&&, int)
Warning(436)  smp3.cpp(4):  In template instantiation started here

When it is "int main() { std::bind(add, 1, 2); }", it becomes an error, but it does not abort.

**Comment by LADSoft** [comment]
hi tenk-a,

thank you as always for the report.   I apologize for the delay; the second issue was a bit of a problem to track down.   I fixed all these in 6.0.29 and did some additional testing; there was also a problem with function<int(int,...)> where there were two or more arguments and I fixed that as well.

**Comment by tenk-a** [comment]
Thank you.
Smp1.cpp and smp2.cpp were able to compile.
However, smp3.cpp seems to give an error. (occ.exe did not abort)

Error(113)    smp3.cpp(6):  Call of nonfunction in function std::__1::__tuple_impl<__tuple_indices<...unsigned int=0, unsigned int=1>, int, int>::operator =( const __tuple_impl<__tuple_indices<...unsigned int=0, unsigned int=1>, int, int>&)

**Comment by tenk-a** [comment]
smp3.cpp were able to compile (v.6.0.30.1)
Thank you.
