### ISSUE TITLE
add new option for specifying preprocessed output file

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#462]
in #454 it was indicated that there is a desire to have a switch to allow putting the preprocessed output of the compiler into a specifically named file.   Maybe something like:

> --preprocess filename

**Comment by chuggafan** [comment]
How about just tying the preprocess command to only preprocess and then specifying the output file name to be whatever it is for the output the way GCC, Clang, and MSVC do it?

**Comment by LADSoft** [comment]
hm that would work...

**Comment by LADSoft** [comment]
i made the -i switch preprocess only; then used the -o switch to specify a preprocessed output file
