### ISSUE TITLE
occil: Access Violation

### ISSUE THREAD

**Issue by berbun** [LADSoft/OrangeC#464]
I run into AV while trying to use `occil` for some reason.
The file I am trying to compile out is [`minilua.c`](https://raw.githubusercontent.com/LuaDist/luajit/master/src/host/minilua.c).

## Steps
1. Download a copy of [`minilua.c`](https://raw.githubusercontent.com/LuaDist/luajit/master/src/host/minilua.c) and save it in a folder on Desktop.
2. Make sure `occil` is accessible from command line (append `"C:\Program Files (x86)\Orange C 386\bin"` to PATH environment variable).
3. Open command prompt and navigate (`cd`) to the folder where you have saved `minilua.c`.
4. Run the following command:
    `occil /ominilua minilua.c /O- /Wd /Lkernel32;user32;gdi32 /Nmynamespace.myclass`

## Output
```
C:\Users\User\Desktop\minilua>occil /ominilua minilua.c /O- /Wd /Lkernel32;user32;gdi32 /Nmynamespace.myclass
occil Version 6.0.43.1 Copyright (C) LADSoft 2006-2019

Warning(129)  minilua.c(2491):  Nonportable pointer conversion in function auxgetinfo(lua_State*, char const *, lua_Debug*, Closure*, CallInfo*)
Optimizer error: (luaV_concat) Mismatched stack at label L_7869_11ea3355

Access Violation:(C:\Program Files (x86)\Orange C 386\bin\occil.exe)
CS:EIP 0023:005010B5  SS:ESP 002B:0019F6A4
EAX: 00000024  EBX: 00B44CF8  ECX: 00000000  EDX: 00000008  flags: 00010206
EBP: 0FF65D74  ESI: 10335C93  EDI: 004B25BE
 DS:     002B   ES:     002B   FS:     0053   GS:     002B


CS:EIP  83 78 0C 00 0F 84 3B 03 00 00 80 3D 7C 7B 66 00
```

**Comment by chuggafan** [comment]
Does occ work? Afaict minilua.c doesn't need occil to function.

**Comment by bencz** [comment]
I just did a small test... with the OCC can build the minilua.c.. about 
using the OCCIL there is a error on MSIL code generation, in some point, 
the stack size is wrong calculated...

Alexandre S. Bencz
+55 {15} 991-707-384

**Comment by LADSoft** [comment]
thanks for the report!   I'm fixing a few things.    Starting with the AV and finishing with various code generation problems that led to invalid push/pop sequences.

The fix compiles minilua, but, I noticed minilua uses setjmp/longjmp.     That isn't really supported because longjmp into managed code doesn't work very well.   That said, the setjmp seems to succeed whereas the longjmp seems to exit the current function...
 (you have to use _setjmp in the default configuration, e.g. compiling against msvcrt.dll)

**Comment by LADSoft** [comment]
hi alexandre, there were a couple of problems:

(void)((argc != 4) && (myfunc()));

got optimized wrong (I removed the related optimization from occil), and

   char c = "hello"[0];

didn't generate the load!

the AV problem was related to the latter...

**Comment by LADSoft** [comment]
hi chuggafan, I always assume that if someone wants to compile with occil they have a reason to want to, maybe just even curiosity?  :smile:

**Comment by chuggafan** [comment]
Well, true, they can compile with occil if they want to but if it works with occ but not occil that does reduce problem space nicely ;)

**Comment by LADSoft** [comment]
yeah that is true enough lol!
