### ISSUE TITLE
add posix getopt implementation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#465]
[POSIX getopt](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html) says everything works with including unistd.h. Implementation note: most but not all implementations have the getopt specific parts defined in getopt.h (and possibly always include this in unistd.h).

A license compatible implementation which may be included (and later updated) nearly unchanged can be found in glibc ([getopt.c](https://code.woboq.org/userspace/glibc/posix/getopt.c.html), [getopt.h](https://code.woboq.org/userspace/glibc/posix/getopt.h.html)) and an adjusted version (possibly not 100% posix compatible, older, increased win32 support) can be found in libcob ([cobgetopt.c](https://sourceforge.net/p/open-cobol/code/HEAD/tree/trunk/libcob/cobgetopt.c), [cobgetopt.h](https://sourceforge.net/p/open-cobol/code/HEAD/tree/trunk/libcob/cobgetopt.h)) - but there are many implementations out there.

The reason for this request that I've currently wanted to build something which needs an implementation of getopt...

**Comment by LADSoft** [comment]
will look into this tonite or possibly tomorrow nite...   need to work on code generation for the 'new' compiler for a little first...

**Comment by GitMensch** [comment]
> ... need to work on code generation for the 'new' compiler for a little first...

I totally agree that this is the useful priority for now. If you get good along with this, just finish it, if you feel that either "it will take longer" or "not feel happy/useful/whatever doing it" then commit to a branch and come back to it. Otherwise: please finish it before tackling all minor issues.

**Comment by LADSoft** [comment]
that is actually best - while I'm comfortable making the same change to multiple branches when I fix something, it always comes with a risk of making a mistake and is usually better avoided!

But this is going pretty well; the old one-file version of BZIP2 I use for testing compiles and runs at this point.  I'm currently working with the C++ program I use for basic testing; it compiles into what seems to be a structurally correct EXE but there are minor code generation problems.   Whenever I get that done I can go on to proof 'fastcall' and the inline assembler...

**Comment by GitMensch** [comment]
> [POSIX getopt](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html) says everything works with including unistd.h. Implementation note: most but not all implementations have the getopt specific parts defined in getopt.h (and possibly always include this in unistd.h).

Did I read this part wrong some months ago or shoul unistd.h be adjusted (that _is_ a question I don't know the answer to)?

**Comment by GitMensch** [comment]
... ok, had a look (possibly again), the types and function prototypes that should be provided with unistd is [documented](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/unistd.h.html). I _guess_ there may be other headers we should include there, but getopt.h is definitely a part of it.

**Comment by LADSoft** [comment]
yeah the implementation I found used getopt.c and getopt.h...   I'm still on the fence about adding unistd.h to a windows distribution though...
