### ISSUE TITLE
Problem with run time library and wide char

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#466]
As an example: This piece of code shows different results, when it is linked to static library, LSCRTL.DLL or CRTDLL.DLL, MSVCRT.DLL.

`#include <stdio.h>
int main()
{
    wprintf(L"Hello, world!\n");
    return 0;
}`

**Comment by LADSoft** [comment]
oops!   seems like the conversion to multibyte isn't being called.   Will see about fixing it tonite...

**Comment by AlexN-114** [comment]
I hope you see this as an example, not as the hole problem. ;-)

**Comment by LADSoft** [comment]
yes definitely, I'm about to push a rework of the multibyte and wide print and scan support in general.   But bear in mind occ doesn't really support locales beyond the basic one so it isn't likely to work too well beyond the 8-bit character set...
