### ISSUE TITLE
mkdir with bad definition (and wrong header)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#467]
The current definition is only in direct.h:

```c

int _RTL_FUNC _IMPORT chdir(const char *ZSTR );
char *ZSTR  _RTL_FUNC _IMPORT getcwd(char *ZSTR , int);
int _RTL_FUNC _IMPORT mkdir(const char *ZSTR );
int _RTL_FUNC _IMPORT rmdir(const char *ZSTR );

int _RTL_FUNC _IMPORT _chdir(const char *ZSTR );
char *ZSTR  _RTL_FUNC _IMPORT _getcwd(char *ZSTR , int);
int _RTL_FUNC _IMPORT _mkdir(const char *ZSTR );
int _RTL_FUNC _IMPORT _rmdir(const char *ZSTR );
```

The underscore variants are all fine, but the ones without the underscore should be moved / adjusted:

* [`chdir`][1], [`getcwd`][2], [`rmdir`][3] -> unistd.h
* [`mkdir`][4] -> sys/stat.h with a second parameter for the mode (`_mkdir` takes only one !)

related:

* [`chmod`][5]-> sys/stat.h (is currently in io.h where only `_chmod` belongs)

[1]:https://linux.die.net/man/3/chdir
[2]:https://linux.die.net/man/3/getcwd
[3]:https://linux.die.net/man/3/rmdir
[4]:https://linux.die.net/man/3/mkdir
[5]:https://linux.die.net/man/3/chmod

**Comment by chuggafan** [comment]
They should be in both because direct.h contains those definitions, albeit the non _ are deprecated according to the microsoft docs.

**Comment by GitMensch** [comment]
direct.h does not contain mkdir in my VS2019 installation, only _mkdir.

The main point is that mkdir actually has a different signature, a possible implementation will call _mkdir and if it returns with zero does a chmod with the requested mode.

**Comment by LADSoft** [comment]
I'm not too sure how to handle this...   not sure it is appropriate to use unistd.h on windows...

**Comment by GitMensch** [comment]
As the underscore variants will stay as and where there are documented at MSDN I see no problem with this - *if* you use the non-underscore variant you are likely to either include the according VC header and redefine it to the underscores or use unistd.h.

In any case the main point was `mkdir` (two parameters) vs. `_mkdir` (one parameter and in a different header).

**Comment by LADSoft** [comment]
thanks for explaining the difference in the prototypes, I didn't realize that.
