### ISSUE TITLE
alignof may return -1

### ISSUE THREAD

**Issue by tenk-a** [LADSoft/OrangeC#47]
The result of alignof of class|struct without member variable becomes -1.
(v6.0.30.1)

smp.cpp:
```
#include <stdio.h>
struct S1 {
    bool b;
};
struct S2 {
};
struct S3 {
    virtual ~S3() {}
};
int main() {
    printf("sizeof(S1)=%d  alignof(S1)=%d\n", int(sizeof(S1)), int(alignof(S1)));
    printf("sizeof(S2)=%d  alignof(S2)=%d\n", int(sizeof(S2)), int(alignof(S2)));
    printf("sizeof(S3)=%d  alignof(S3)=%d\n", int(sizeof(S3)), int(alignof(S3)));
}
```
RESULT:
sizeof(S1)=1  alignof(S1)=1
sizeof(S2)=4  alignof(S2)=-1
sizeof(S3)=4  alignof(S3)=-1

**Comment by LADSoft** [comment]
fixed

**Comment by tenk-a** [comment]
I'm sorry to be late.

Compiled with v6.0.31.1, It was fixed to 1 instead of -1.
Thank you.

However, I think the aligneof(S3) is the same as sizeof(S3)(alignof(void*)) is better.

**Comment by LADSoft** [comment]
no problem with the timing, it gave me a break :)   I agree this should be alignof(void *) because of the pointer to vtab...   I'll try to have something soon, there are a lot of problems with member functions and templates and I'm working through them, slowly.

**Comment by LADSoft** [comment]
fixed

**Comment by tenk-a** [comment]
I compiled with v 6.0.32.1.
Thank you.
