### ISSUE TITLE
Use namespaces and headers to cordon off sections of the compiler from one/another

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#473]
Essentially, this issue is to get rid of all of the externs located everywhere in the .cpp files
An example of this (in the master branch) is:

https://github.com/LADSoft/OrangeC/blob/27c1755f74c5e67efcba9f4eadfa1531634b00a9/src/occ/parse/ccerr.cpp#L38-L54

An example of this (in the split branch) is:

https://github.com/LADSoft/OrangeC/blob/0285ac70bd887b50794e5305f8863ca868484f30/src/occopt/ilstream.cpp#L40-L82

This makes it hard to know where things are defined and what section of the compiler is for what, it also means that by making a single change in one file to say, the type of one of these you have to edit another 15 files. This is a real problem in that it will not error in the parser stage but only in the linker stage when you're confused about why the compile is failing, or even worse: it will only silently fail and you'll be stuck wondering why. 

By using headers to remove these externs (and also putting prototypes for functions in headers for their respective Translation Units) we can de-clutter the start of many, maaaaaaany files. The work we do here now will make life easier in the future so that we only have one central area where things that are used are defined. 

As an addendum: dropping the "be.h pulls in be.p which defines all the prototypes" would also help with making it so that we know where everything is located, prototypes in headers would define the prototypes for their respective TU and you're not pulling in completely irrelevant prototypes for what you're trying to do. It also has the bonus effect of allowing us to look at a header to see what functions a TU is putting out for public use instead of browsing a large file and hoping that it's properly commented. 

Secondary: namespaces, something really important that we should add now while #297 is being worked on. This will allow us to further cordon off and define what section of things are where, as currently, the question of: "Is is located in the parser?" "Optimizer?" "Backend?" is a thing and by removing that question in it's entirety we (at the cost of having a lot of work) have a more obvious location for everything.

**Comment by LADSoft** [comment]
ok this sounds like a good idea!   I love to make maintenance easier when possible :smile:

**Comment by LADSoft** [comment]
@gitmensch:

in #297 you asked

> Isn't it "enough" if "be.p would group the definitions "per file" and have a comment which file the group refers to?

well it already does lol!

but I kind of agree, that partitioning everything into multiple headers is a more modern thing to do especially for C++ programs.   Ideally this would also partition everything into class objects and be more object-oriented as well but that is too much to bite off right now...

**Comment by LADSoft** [comment]
I'm pulling this in now rather than delaying to another milestone, because it seems important, and besides this IS the infrastructure milestone :)

**Comment by LADSoft** [comment]
this is next up, I will probably start on it tomorrow...

**Comment by LADSoft** [comment]
I made good progress on this and aside from a few loose ends got the rewrite done.

As usual though I tried out a new thing I hadn't tried with this compiler ('using namespace xxx;' inside a function) and it didn't work out so well.   Hope to have it fixed in a few days...

**Comment by LADSoft** [comment]
this issue is mostly complete at this point; leaving it open because there is a small amount of cleanup I may want to do this weekend :)
