### ISSUE TITLE
occparse should output named .icf files

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#484]
Currently occparse /Y outputs files that are in Intermediate Code, which is a COMPLETELY different format than the one that occopt accepts. My personal idea is that we should have the occparse output occopt usable formats (and occopt outputs occopt usable formats if I so choose) so that it's possible to test optimizations and various other things.

**Comment by chuggafan** [comment]
Turns out I'm an idiot, the issue is that occparse is outputting a .icf file that is blank. I'll fix that, but there's nothing that actually needs being done other than that

**Comment by chuggafan** [comment]
Also further: the actual physical file shouldn't be written to unless we want to dump it to play around with, I'll eventually write a words <-> Il converter using the setup functionality but at this point in time I'm not doing that. So I'll add the ability to *optionally* dump the file to an actual file or not.

**Comment by LADSoft** [comment]
I think the way I did it occparse/occopt will dump to a memory region if you run occ.exe, because occ.exe can set up the memory regions properly.    You had asked to be able to dump to a file and you can do that more or less directly now by running occparse.exe and/or occopt.exe instead of occ.exe;   when they aren't attached to a memory region by occ.exe they should dump to a file...   that was the plan anyway...

**Comment by chuggafan** [comment]
Yhea, I realized I was an idiot, the main problem atm is that it dumps a file literally just named ".icf" when it should have an actual file name there instead.

**Comment by LADSoft** [comment]
i thought i fixed that....   i'll have another look...

**Comment by LADSoft** [comment]
i have a fix for this but I'm not going to push it for a few days.    Right now I'm back to the issue I was having with executables not comparing properly to each other.   I'm trying to figure out why occ  generates different code depending on what compiler it was compiled with...   something in the optimizer....
