### ISSUE TITLE
Refactor internal source code line caching in the compiler

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#490]
the fix for #245 left redundant information in the C compiler tokens, and also there is now no requirement to have the preprocessed line propagated through the compiler.    Using the original line actually is a better solution but there wasn't access to it until now.

This issue should move the generation of LINEDATA tokens into the lexer and remove the redundant fields from the lexeme structure.

**Comment by chuggafan** [comment]
Yes, this idea sounds exactly like the manner in which clang and GCC run their internal compiler because it helps greatly with diags. Something that can come out of this is being able to pinpoint the "original" line, and the line that causes a problem inside of a macro.
