### ISSUE TITLE
fix current GCC warnings

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#507]
inspecting the recent [Travvis GCC buidl log](https://travis-ci.org/github/LADSoft/OrangeC/builds/688147740) showed some warnings that may should be inspected:

>/home/travis/build/LADSoft/OrangeC/src/../src/lib/gcc-linux/libutil.a(Utils.o): In function `Utils::TempName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
>
>Utils.cpp:(.text+0xee2): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

> g++ -c -D__MSVCRT__ -U__STRICT_ANSI__ -DHAVE_UNISTD_H=1 -DSQLITE_OS_UNIX -D_unlink=unlink -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -D_strnicmp=strncasecmp -I../util -fpermissive  -DGNUC -std=c++14 -o /home/travis/build/LADSoft/OrangeC/src/ocpp/obj/gcc-linux/ppMain.o ppMain.cpp
~~~
ppMain.cpp: In function ‘int main(int, char**)’:
ppMain.cpp:68:5: warning: exception of type ‘std::ios_base::failure’ will be caught
     catch (std::ios_base::failure)
     ^~~~~
ppMain.cpp:64:5: warning:    by earlier handler for ‘std::runtime_error’
     catch (std::runtime_error e)
     ^~~~~
~~~

> g++ -c -D__MSVCRT__ -U__STRICT_ANSI__ -DHAVE_UNISTD_H=1 -DSQLITE_OS_UNIX -D_unlink=unlink -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -D_strnicmp=strncasecmp -I../util -I../objlib -I../olib -I../olink -I../ocpp -I../exefmt -fpermissive  -DGNUC -std=c++14 -o /home/travis/build/LADSoft/OrangeC/src/oimplib/obj/gcc-linux/ImpLibMain.o ImpLibMain.cpp
~~~
ImpLibMain.cpp: In function ‘int main(int, char**)’:
ImpLibMain.cpp:51:5: warning: exception of type ‘std::ios_base::failure’ will be caught
     catch (std::ios_base::failure)
     ^~~~~
ImpLibMain.cpp:47:5: warning:    by earlier handler for ‘std::runtime_error’
     catch (std::runtime_error e)
     ^~~~~
~~~

> g++ -c -D__MSVCRT__ -U__STRICT_ANSI__ -DHAVE_UNISTD_H=1 -DSQLITE_OS_UNIX -D_unlink=unlink -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp -D_strnicmp=strncasecmp -I../util -I../objlib -I../olink -I../olib -fpermissive  -DGNUC -std=c++14 -o /home/travis/build/LADSoft/OrangeC/src/onm/obj/gcc-linux/nmMain.o nmMain.cpp
~~~
nmMain.cpp: In function ‘int main(int, char**)’:
nmMain.cpp:86:5: warning: exception of type ‘std::ios_base::failure’ will be caught
     catch (std::ios_base::failure)
     ^~~~~
nmMain.cpp:82:5: warning:    by earlier handler for ‘std::runtime_error’
     catch (std::runtime_error e)
     ^~~~~
~~~

**Comment by LADSoft** [comment]
the 'mkstemp' warning is going to be hard to fix because msvc doesn't have a viable mkstemp function...   I'm fixing the other one soon...

**Comment by GitMensch** [comment]
> the 'mkstemp' warning is going to be hard to fix because msvc doesn't have a viable mkstemp function... 

The benefit of a `mkstmp` implementation is that you can specify a file name template, which is the reason that GnuCOBOL implemented its own.
But it *looks* like you can change your use cases to `tmpfile` instead - as this is both implemented in msvc and posix + friends, so should be quite portable.

**Comment by LADSoft** [comment]
ok thanks.   I was contemplating copy the mkstemp implementaion from the RTL and conditional compiling it in under windows but if tmpfile will work that might be better...
