### ISSUE TITLE
Cannot compile global variables with occil

### ISSUE THREAD

**Issue by claunia** [LADSoft/OrangeC#509]
It just complains the variable is redefined.

```
Error: Multiple definition of coderversionError: Multiple definition of modError: Multiple definition of blocksizeError: Multiple definition of orderError: Multiple definition of verbosityError: Multiple definition of compressError: Multiple definition of recordsize
```

**Comment by chuggafan** [comment]
Do you have any samples that could cause this to reproduce this issue?

**Comment by claunia** [comment]
http://www.compressconsult.com/szip/

**Comment by LADSoft** [comment]
@claunia  thanks for the reference.    There are some things missing from types.h which I will upload after a while.   When I added them the compile went fine, but there is something wrong with occil as the resulting program doesn't work properly.   occ generates good code for it though.

I'll fix that then get back to you :)

**Comment by LADSoft** [comment]
@claunia, ok the bugs are in occ not occil.   occil works fine...   occ has problems with freopen apparently...   if the appveyor build works you can grab the latest binaries there.    I'll fix occ soon...
