### ISSUE TITLE
[Feature request] Compile macros as functions

### ISSUE THREAD

**Issue by claunia** [LADSoft/OrangeC#513]
As discussed in #510 offer the option to compile macros as if they were functions instead of replacing them directly in code by the preprocessor.

This helps when using OCCIL to make the decompiled code clearer.

**Comment by chuggafan** [comment]
We could also add something in milestone 5 such that we can take macros and make them constexpr functions a la MSVC's intellisense, having such code transforms would be impressive and if we can do it here we most certainly can do it when we're given a snippet of code to work with and make it readable.

**Comment by LADSoft** [comment]
nice idea.   I was thinking of adding a command line switch for turning function-like macros into functions just to make it generic so maybe it will just come for free!

**Comment by LADSoft** [comment]
This is of little use with respect to bzip2...   bzip2 needs state of the current function in the macros for things like return statements and case statements.   To correctly parse such things out of the macros then generate proper code would be somewhat difficult.    Much easier just to refactor bzip2 the way it is desired before running it through occil.   as per comments in #510 that is probably a requirement for this program anyway...

I'm going to leave this open as a potentially generally useful thing to be able to do,   but demote it to a later date...

**Comment by LADSoft** [comment]
i thought about this and it should be doable, if we split into potentially multiple functions at case and label boundaries.   Only difficult part is return statements, which can be handled readily by passing a phantom argument in the macro's function telling the caller to return the result of the function call...   But I'm going to put this off until next milestone at this point.
