### ISSUE TITLE
different interpretion of a printf 

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#52]
When I played around with [rswier c4](https://github.com/rswier/c4), I found that the output of this printf
`          printf("%8.4s", &"LEA ,IMM ,JMP ,JSR ,BZ  ,BNZ ,ENT ,ADJ ,LEV ,LI  ,LC  ,SI  ,SC  ,PSH ,"
                           "OR  ,XOR ,AND ,EQ  ,NE  ,LT  ,GT  ,LE  ,GE  ,SHL ,SHR ,ADD ,SUB ,MUL ,DIV ,MOD ,"
                           "OPEN,READ,CLOS,PRTF,MALC,MSET,MCMP,EXIT,"[*++le * 5]);
`
is different between a built with MSVCRT/CRTDLL or LSCRT/Static.

If you try to build this project (a single C file with four functions :-) ) you must use the parameter -d or -s to see the difference.

**Comment by LADSoft** [comment]
was also a problem for plain C programs without using a DLL for the runtime.   In version 6.0.34 I have modified the RTL and it should work more to the standard.

**Comment by AlexN-114** [comment]
Looks good!
Thank you!
