### ISSUE TITLE
FR posix api: fmemopen and friends

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#522]
see [its manpage](https://linux.die.net/man/3/fmemopen)

For now I create a temporary file and write to it, then read from it whenever I need its data (which in my case is simple as this is only the case on fclose), but I guess that's easy to implement in OrangeC.

**Comment by LADSoft** [comment]
I've been embroiled in trying to get maps in libcxx 10 to compile...   lots of issues with C++14 type aliases.... it is close now though.   It at least compiles the declaration for a map before running out of steam!  As soon as I get there I will look at doing this and some of the other 'easy' things that have made it to the list :smile:

**Comment by GitMensch** [comment]
Any update on this? Just a friendly ping; I hope you're well, only silent.

**Comment by LADSoft** [comment]
healthwise i'm ok but for a small scare that turned out to be nothing; 

i got stalled on the libcxx stuff, was going around in circles until my head was spinning and then decided to take abreak...    whenever I get around to working on occ again I'll put that on the back burner as it is on a different branch anyway.

**Comment by GitMensch** [comment]
Thank you for the update.
In this case I suggest to push that branch so others (ok, actually primary @chuggafan) may investigate this some day, I _guess_ just pushing that may allow you to let it go easier for now in any case.

**Comment by chuggafan** [comment]
I'm perfectly happy to take a look on the libcxx stuff while you work on this, might get my stuff in gear to actually fix the problems I've had with AV software and running the build tools.

**Comment by LADSoft** [comment]
I actually distilled the latest problem into a relatively simple source file...   problem is there is some internal overwriting going on in the compiler and data gets lost from one invocation of a 'using' statement and the next.   libcxx10 is much more liberal with the using statements than the previous version...    I added a bunch of code to try to get around that but I guess there is still a problem...   if you still want to look at it I will share what I've got...

**Comment by GitMensch** [comment]
>  if you still want to look at it I will share what I've got...

push branch push :-)

**Comment by LADSoft** [comment]
i pushed a branch 'libcxx' and added the simple test file I have and instructions for continuing on #355

**Comment by GitMensch** [comment]
Any update?

**Comment by LADSoft** [comment]
I've started working on this; I have the basic implementation and have it doing basic read/write, need to write some more extended tests with mixed read/write and seeks as well as test the dynamic buffer expansions before I can release it.
