### ISSUE TITLE
OCPP skips the first file path when adding it to the filepath

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#526]
When I run the command: `ocpp /Itest1;test2;test3;test4 testTotal.h` the only filepaths that the command-line handler picks up are "test2;test3;test4", the way to fix this currently is to do: `ocpp /I;test1;test2;test3;test4` since it skips to the first semicolon found in the list for some reason.

**Comment by LADSoft** [comment]
see the comment for #525, details about how the searchpath is correct but not being searched properly.

**Comment by LADSoft** [comment]
i fixed this...  on the libcxx branch.
