### ISSUE TITLE
Call FlushFileBuffers on output files.

### ISSUE THREAD

**Issue by jossk** [LADSoft/OrangeC#53]
https://randomascii.wordpress.com/2018/02/25/compiler-bug-linker-bug-windows-kernel-bug/

**Comment by svmizin** [comment]
Great !
********************

> And then, a few days shy of its first birthday, the bug started happening again. A steady drumbeat of reports came in – ten separate bugs were merged into the master bug over the next few months, representing just a fraction of the crashes.

**************************************

**Comment by LADSoft** [comment]
this only applies to memory mapped io with remarkably high I/O and only for writing PE files;   This tool chain does not use memory mapped I/O so it doesn't directly apply.   As far as applying indirectly, e.g. for programs compiled with the tool, I feel it best to let individual developers determine if they want to 'fix' their own applications, given the difficulty in reproducing the problem and the general need to do things that are way outside the language standard to even trigger it.
