### ISSUE TITLE
Add the library files to the auto-format list

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#531]
I just want the auto-format function of omake to apply to the files in the clibs, not those done in libcxx. It's been something that's been bothering me for a rather long time.

Problems: any custom in-c assembly will be borked since clang doesn't know that our style of assembly exists, a fix would be to add MSVC or GCC style inline assembly but that's a lot of effort for that.

**Comment by LADSoft** [comment]
I had sorta been thinking along the lines of adding a more 'standard' way of doing assembly such as found in GCC anyway...   I don't think it a big deal to either support that (in addition to the current syntax) or to write a program that reformats all inline assembly in the libraries appropriately...    that might make this issue work out a little better...
