### ISSUE TITLE
Investigate compilation with CLANG rev 10.0.0

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#532]
while working on #257, it was discovered that travis-ci uses CLANG rev 10.0.0 (as opposed to my local 9.0.0).    On travis, the builds were hanging while building the c runtime library.

investigate whether this is a real issue.

**Comment by chuggafan** [comment]
Clang 11 also just came out, so that should also be investigated, it may be a known regression to the clang team that has to do with their optimizer.

**Comment by LADSoft** [comment]
yeah I found that out..    Meanwhile I installed CLANG 10 and ran into issues although not an exact duplicate of what I saw on Travis-CI.    The common thread seems to be that olib sometimes hangs when compiled with CLANG 10 though.

I couldn't find a distribution of CLANG 11 yet,   I'll wait a few days and revisit this with version 11.

**Comment by chuggafan** [comment]
https://releases.llvm.org/download.html#11.0.0 should work for version 11 of clang.

**Comment by LADSoft** [comment]
some problem in occparse is causing this.  the version built with clang hangs compiling the huge SQLITE3 file.  At this point I'm assuming it a bug in occparse as #533 also seemed to happen in the compiler...
