### ISSUE TITLE
CI through Github Actions

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#534]
in #257 it was proposed a next step was to do CI through Github Actions.    I propose we do a single build with MSVC, then build the libraries, then build the tests.    Skipping the part where we rebuild the compiler with itself.   While not as involved as the tests being performed on Appveyor it would least give a basic test of the compiler.    We can catch more involved problems on Appveyor.

Part of the reason I'm proposing it this way is that we don't need five more hours of builds every time a checkin is performed, it is actually better if we can get results sooner rather than later.   Another part is that Github Actions isn't free after a certain point and those five hours of builds would anyway eat up the allotted time way too quickly.  ( on windows platform we get the equivalent of 1000 minutes a month)

**Comment by GitMensch** [comment]
Sounds like a reasonable approach!

**Comment by GitMensch** [comment]
As travis-ci.org is down and Appveyor builds for hours, it may be a good time to check the Github Actions again.

**Comment by GitMensch** [comment]
Looks like PDCursesMod just created the [related file](https://github.com/Bill-Gray/PDCursesMod/blob/master/.github/workflows/github_actions_build.yml) and [added the badge to README.md](https://github.com/Bill-Gray/PDCursesMod/commit/a96c85d5de8033cf304e31dd3de4e6f30cb07b9f); maybe that's all?

**Comment by LADSoft** [comment]
we are already way off in left field considering 3.5 is supposed to be a very small milestone just to get the libcxx tests done lol...   I'll leave the scheduled for milestone 4.

**Comment by LADSoft** [comment]
so this is another thing on my short list of things to do.

**Comment by LADSoft** [comment]
right now it builds the compiler, but I'm having a hard time getting the compiler onto the path so that I can build the runtime library/tests....   there was some security update that made the normal ways of changing environment variables not work and none of the other advertised ways of doing this seem to work either...

**Comment by LADSoft** [comment]
i got the compiler onto the path by specifying the PATH variable on the omake command line :smile: now it can't find the include files...   not sure why...

**Comment by LADSoft** [comment]
this is done now.

**Comment by GitMensch** [comment]
What about adding build artifacts like we have in slow appveyor?

**Comment by LADSoft** [comment]
i can build the artifacts; also i want to do a ubunto build just to see if it still compiles on linux.    

As discussed earlier in this topic I don't want to do multi-step because we have a limited number of free minutes per month.

**Comment by LADSoft** [comment]
I completed adding an artifact to the existing action.   And started working on a linux action.   The linux action seems viable at this point, but, there are quite a few incompatibilities at the source-code level that I'm working on.

Meanwhile, apparently i misread the documentation and there is no minutes/per/month limit for public repositories.    So after I finish the 'linux' action I'm working on I'll look into adding a third action which is to do the normal multiple-builds thing.   Not sure how viable that is going to be though unless I can figure out a way to use cmd.exe to run a step...   I don't want to make a specific build script for powershell because I don't want to be maintaining multiple build scripts...

**Comment by LADSoft** [comment]
this is working as well as it is going to, for the moment...    We have a windows action which builds it then runs tests...   I also tried adding the libcxx tests in, but, something is up with python and it is mangling the path for occ.exe in a way that it can't run.

I'm going to close this...   whenever I get bored I might add more actions...
