### ISSUE TITLE
Perform minimal likely/unlikely branch prediction optimization

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#539]
In a loop, a break statement (for example in an if block) makes the if block an unlikely path.   Look into changing the sense of the branch and moving the if block out of the loop.

**Comment by LADSoft** [comment]
this is a duplicate of #254, which has more info.    Closing.

**Comment by GitMensch** [comment]
I suggest to drop the milestone from this one (it was wrong but #254 is in the correct one already).

**Comment by LADSoft** [comment]
ok i fixed it :)
