### ISSUE TITLE
Add NEWS/Changelog entries and binaries to the releases

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#54]
please compare https://github.com/LADSoft/OrangeC/releases with https://github.com/lexxmark/winflexbison/releases

**Comment by LADSoft** [comment]
thanks for keeping me honest!   I fixed the current releases in the OrangeC project and will keep it up to date in the future.

**Comment by GitMensch** [comment]
@LADSoft These look much better now. What do you think about a NEWS file (may be considered "old-school") or HISTORY.md in the root directory containing what you've already added in a single file?

**Comment by LADSoft** [comment]
I added a very simple HISTORY.md with releases back several years.

**Comment by GitMensch** [comment]
Sorry, I've missed [HISTORY.md](https://github.com/LADSoft/OrangeC/blob/master/HISTORY.md).

Can you please revert dc4749799d745ee857007bd5f1f426f4ff6692c6? It is good to have the full information in there.
Afterwards this issue can be closed.

**Comment by LADSoft** [comment]
Instead of reverting I took the original information (release notes for version 4) and reformatted it to a nicer format.

**Comment by GitMensch** [comment]
Looks fine.
