### ISSUE TITLE
Remove unused labels from the intermediate code

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#542]
the inlining generates a lot of unneccessary labels on the off chance they may needto be used.   This interferes with optimization, so it would be helpful to remove them before starting the optimizations passes.

**Comment by LADSoft** [comment]
this had been addressed , and is even less of a problem with the recent rewrites to the inlining

**Comment by GitMensch** [comment]
Just rechecking - the user specified (written in the code) are all in when doing a debug build, no?

Most debuggers allow to list/view/jump to them, so that's an important thing to keep.

**Comment by LADSoft** [comment]
yeah shouldn't affect that.    Just effects a bunch of internal labels that used to be generated any time a function was inlined...
