### ISSUE TITLE
Invalid multiple declaration error

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#549]
in the following, we get a multiple declaration error on nn because bb has two different meanings.

```
truct bb { };
template <class bb>
int nn(bb &&)
{
}
bb xx();
int xxt(const bb & aa)
{
	nn(xx());
	return 0;
}
```

**Comment by chuggafan** [comment]
Does this code work in main or in the libcxx branch? I'm assuming neither if you're doing it like this, but I just want to check since I can restart work on thursday.

**Comment by LADSoft** [comment]
it doesn't work in either branch right now.   I'm hoping I can get far enough to merge the two branches together again this week but it is slow going...

**Comment by LADSoft** [comment]
if you decide to work on this it would be best done on the libcxx branch...  I've already done some changes to the name mangling on that branch.    I was tired of seeing weirdly formed names in the error messages!

**Comment by LADSoft** [comment]
I merged libcxx back into the master branch now...   not quite done with it but it was a good time to do the merge.
