### ISSUE TITLE
include Appveyor CI

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#55]
There's already a configuration file, if this is working the only thing left seems like either adding the webhooks manually or "installing" from the marketplace https://github.com/marketplace/appveyor

... note: AppVeyor CI currently doesn't build: https://ci.appveyor.com/project/LADSoft/OrangeC

**Comment by LADSoft** [comment]
it broke when I updated my build environment to visual studio 2017.   I've fixed it now.

**Comment by LADSoft** [comment]
hi thank you for the hint on how to add the status badge.  I've used the appveyor token now and moved the status to a more prominent place.   

To be honest someone else had set up the Appveyor for me a long time ago.   I know that it ran a CI build every time I checked something in, but beyond that it doesn't do much.   I suppose maybe I could have it move the build artifacts back to the github project?   I'm not sure what else to do with it though.   Do you have any suggestions?

**Comment by LADSoft** [comment]
I added appveyor CI to the other two projects as well; and updated the build scripts so it does an 'omake fullbuild' every time it builds.   Among other things that creates new artifacts, one of which is the installer.

**Comment by GitMensch** [comment]
>  I suppose maybe I could have it move the build artifacts back to the github project? I'm not sure what else to do with it though. Do you have any suggestions?

Yes, adding the artifacts as you did is good.

I'm not sure if you do this already but I'd suggest to create two to four environments in AppVeyor:

1. build OranceC with VC as you do already
2. build OranceC with MSYS2/mingw-w64 (this provides you with all Windows headers which I guess are needed but use GCC + GNU make to build everything) - if this environment doesn't work (yet) it would be good to be tracked with a different issue and implemented in a different branch (which would also change the appveyor.yml to additional use this environment), merge into master when working
3. build OrangeC with latest release of OrangeC - if you find something that doesn't compile with the latest release anymore it is time to do a new release ;-)
4. build OrangeC with artifacts created by step 3 (by itself) and re-build it with the resulting artifacts (ensuring that they still work)

Ideally for each of these verify that the C compilation works by running a testsuite - but I'd say step 3 and/or 4 can be seen as a good test.

**Comment by GitMensch** [comment]
It is quite impressive how fast this project makes process!
