### ISSUE TITLE
Cascading help text

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#550]
When I just compiled OCC for the first time in forever (I know) and ran /help, I couldn't help but notice that the help text is larger than the screen, what I think should be something that gets added sometime in the future is either: The ability to dig down into what type of help you need with, and/or having the ability to cascade the help page a la CL.exe

**Comment by LADSoft** [comment]
it would be farily easy to do something like what cl.exe does....    it could even be done in shared code so that other applications could take advantage of it if they need to in the future :).

**Comment by GitMensch** [comment]
I just assume that everything is fine if I `occ --help > help.txt` or `occ --help | ogrep -C4 "something"`, on windows cmd, powershell and also in shell (for example via WSL).

That is correct, isn't it?

**Comment by LADSoft** [comment]
hm, guess I should check if it is a TTY before pausing it.   Right now there would probably be a problem...   thanks for the comment, will go fix.
