### ISSUE TITLE
Include behavior discussion issue

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#563]
This is a continuation issue for #561 so that we aren't arguing an issue in a PR anymore.

**Comment by chuggafan** [comment]
Personally, my problem with the current include system and my warning is only specific to the "last included directory" portion, I do not know the history of how this functionality came to be, but I am currently saying that this *can* be a problem depending on the exact functionality desired out of #include_next and regular #includes, this is just something that I have seen while debugging the #include_next functionality, nothing more, nothing less.

**Comment by LADSoft** [comment]
but the last included directory thing is also done by GCC.    Which is why I'm arguing so much that it shouldn't be removed...   I'm not sure we should be removing a compatibility that seems so relied on that all the compilers do it in one form or another.

**Comment by chuggafan** [comment]
> but the last included directory thing is also done by GCC

Ok, this is where the confusion is then.

There are two things that are being discussed here I think and we're being passed about them. I currently am on a new setup entirely and don't have the tools immediately on hand to test if the idea of the current directory of the current included file is specifically searched vs the current include directory. 

If GCC supports the behavior your describing, I think we can emulate GCC then, as of right now after all, there's no problem, and if GCC and clang can support it, we can probably support it.

The way I was assuming GCC supports it and currently supports is that it does the "." include where it just searches in the invocation directory. These two are both supported by OCC, and only one of them is "correct" as far as GCC is concerned. I'm not well versed in either clang's or GCC's actual support for either of these and trawling through the ten thousand clang files it'd take to figure it out is not my idea of a nice afternoon, so if either of us can create a test that demonstrates one behavior over another from GCC I'll take that as gospel as far as GCC is concerned.

**Comment by GitMensch** [comment]
This may help to clear part of the question:

```
$ mkdir 1
$ mkdir 2
$ echo '#include "file.h"' > 1/test.c
$ echo '#include "file.h"' > 2/test.c
$ echo '#error "in one"' > 1/test.c
$ echo '#error "in two"' > 2/test.c
$ cd 1
$ gcc ../2/test.c
../2/test.c:1:2: error: #error "in two"
 #error "in two"
  ^~~~~
$ clang ../2/test.c
../2/test.c:1:2: error: "in two"
#error "in two"
 ^
1 error generated.


1>cl ../2/test.c
Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29334 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

test.c
../2/test.c(1): fatal error C1189: #error:  "in two"
```

So all three include in the current processed source directory first (add additional check with `<file.h>` showed the same results).

**Comment by chuggafan** [comment]
What about if you do:

```

mkdir 1
mkdir 2
echo '#include "file1.h" > 1/test.h
echo '#include file2.h" >> 1/test.h
echo '#warning "in 1"' > 1/file2.h
```

Or something similar, what you tested here is that it errors because there's no include shenanigans going on, what is really needed to be tested is whether include shenanigans are going on or not and the only way to do that is with a top-level file and include structures that jump around files including files of the same name in different directories.

**Comment by GitMensch** [comment]
Actual testing what I've previously wanted (complete output without linker errors)...

```
$ mkdir 1
$ mkdir 2
$ cd 1
$ echo '#warning "in one"' >file.h
$ echo '#include "fileB.h"' >>file.h
$ echo '#warning "in one b"' >fileB.h
$ echo '#include "file.h"' >test.c
$ cp * ../2
$ sed -i 's/one/two/' ../2/*
$ gcc ../2/test.c
In file included from ../2/test.c:1:
../2/file.h:1:2: warning: #warning "in two" [-Wcpp]
 #warning "in two"
  ^~~~~~~
In file included from ../2/file.h:2,
                 from ../2/test.c:1:
../2/fileB.h:1:2: warning: #warning "in two b" [-Wcpp]
 #warning "in two b"
  ^~~~~~~
$ clang ../2/test.c
In file included from ../2/test.c:1:
../2/file.h:1:2: warning: "in two" [-W#warnings]
#warning "in two"
 ^
In file included from ../2/test.c:1:
In file included from ../2/file.h:2:
../2/fileB.h:1:2: warning: "in two b" [-W#warnings]
#warning "in two b"
 ^
2 warnings generated.
```

for msvc changed to `#pragma warning ("in NNN")`

```
1>cl /nologo ../2/test.c
test.c
in two
in two b
```

Again: all working identically using the **directory of the file that includes** for `include "file"`.
When changed to `include <file.h>` the result is different:

```
gcc ../2/test.c
In file included from ../2/test.c:1:
./file.h:1:2: warning: #warning "in one" [-Wcpp]
 #warning "in one"
  ^~~~~~~
In file included from ./file.h:2,
                 from ../2/test.c:1:
./fileB.h:1:2: warning: #warning "in one b" [-Wcpp]
 #warning "in one b"
  ^~~~~~~
$ clang ../2/test.c
In file included from ../2/test.c:1:
./file.h:1:2: warning: "in one" [-W#warnings]
#warning "in one"
 ^
In file included from ../2/test.c:1:
In file included from ./file.h:2:
./fileB.h:1:2: warning: "in one b" [-W#warnings]
#warning "in one b"
 ^
2 warnings generated.
```

Now gcc and clang use the current directory (if "-I ../2" is used then we're back to the initial result). [they are not identical as their fallback differs, see below]

cl does not compile the sources that way

> ../2/test.c(1): fatal error C1083: File (Include) cannot be opened: "file.h": No such file or directory

the "current directory fallback" does not exist -> one has to explicit specify `-I.` to include it

And "because of course" gcc and clang differ which can be seen if we compile one level above:

* gcc's fallback is the current execution directory (it does not compile from one level above)
* clang's fallback is again the directory of the file that includes

**Comment by chuggafan** [comment]
So, can you give me a quick rundown on TL;DR? So gcc's fallback if the file cannot be found in the current include directory is to check the execution directory, whereas clang's is the directory of the file that ran the #include moniker? 

Of *COURSE* gcc and clang have to be meaningfully different. So I guess it's ok to support what we're doing now, and if we run into problems later change behavior to be easier to handle.

**Comment by GitMensch** [comment]
> So gcc's fallback if the file cannot be found in the current include directory is to check the execution directory, whereas clang's is the directory of the file that ran the #include moniker?

Not exactly. That's the fallback if the include file cannot be resolved (cl.exe has neither of those fallbacks).

For `#include 'file.h'` the include file is always searched first in the directory of the file that did the include (identical for gcc, clang, cl), for `#include <file.h>` this is not the case so the three fallbacks outlined above may kick in.

**Comment by chuggafan** [comment]
Ok, so our current structure is the way GCC, clang, and MSVC do this, at least for user-includes. I'm fine with keeping it in then, hopefully no one complains about weird include issues that could stem from it, and I'll make the system-includes start ignoring that maybe and see how things change.

**Comment by LADSoft** [comment]
thanks for clearing this up guys.
