### ISSUE TITLE
Adding the ability to time different parts of the compiler

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#565]
We should be able to see how long each process of the compiler is run, I don't mean each segment, I mean more like, how long did OCC run vs OCCOPT vs OCCPARSE, the reason I ask is that I'm thinking of tackling #541 and this is either an OCCPARSE problem (which is easy enough to profile) or an OCCOPT problem, which is a bit harder to profile.

This would be useful as a first step in identifying where problems are, after all, the rule when optimizing is always: profile first.

**Comment by GitMensch** [comment]
Did you try to compile OrangeC with `gcc -pg` and run the result with `gprof`?

I've opted to do that for GnuCOBOL to find bottlenecks both at the function level and even down to loops/instructions (we spend most time in `strcmp` and some in `strncmp` for reserved and user-defined words...).

One think to verify before the actual comparision is the check: What is traced? The OrangeC runtime components (that are used by the compiler after it is recompiled with itself) possibly have their own things to work on, so profiling the compiler using those may be a bad (or a good) thing.

**Comment by chuggafan** [comment]
I can already do timing for individual portions of the OCC compiler with Visual Studio.

The specific thing I'm referencing here is to be able to quickly distinguish if a specific set of command line arguments to occ is spending most of it's time in OCCPARSE, OCCOPT, or being translated to assembly in OCC. I've noticed far less egregiously bad Big O times in other areas of the suite than in the compiler itself, which I noticed multiple sets of recursion that grow exponentially really, really badly.

**Comment by LADSoft** [comment]
yeah I do tend to over-use recursion....    definitely a lot of stuff could use a rewrite.   And there are possibly better algorithms that could be used in at least some instances that would not have required it to begin with...

But adding timing measurements at the gross level as you've indicated is not difficult at all...   I'll go ahead and do it in a few minutes.

**Comment by LADSoft** [comment]
i added this on the libcxx branch.   Use the '/t' switch to get timing info.
