### ISSUE TITLE
Documenting ADL for future use

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#567]
Something currently barring any support for other people working on OASM is a complete lack of documentation of the currently implemented ADL functionality. IF we intend to ever autogenerate any future architectures (E.G. the plans for POWERPC in the future) we will require this functionality to be clear and usable, or else scrapped and replaced with something that fits the use cases better.

I believe that this is a necessity for future usage, whether or not this belongs in the current milestone is something of a different question entirely, however.

**Comment by LADSoft** [comment]
i've been kinda sluggish on the speedup issue; might look at this as an alternative this weekend...   it would be great to have more eyes on this stuff but yeah I realize a lot of things are undocumented...

**Comment by chuggafan** [comment]
Any news on how far this got? I would eventually like to use the ADL myself to generate other assembly types.

**Comment by LADSoft** [comment]
not very far...   I'm about at the point of getting back to work though lol...

**Comment by LADSoft** [comment]
I've been making progress on this.  I have a description of the ADL file itself, working on describing the code-level interface.   Reworking things a little as I go to make it a little cleaner.

**Comment by LADSoft** [comment]
I have a first draft at [ADL Document](../tree/master/doc/adl.md).   Later this week I'll run through it and clean up all the errors and miscommunications...

**Comment by chuggafan** [comment]
Neato, I will likely check it out in its entirety sometime next week as I'll have a whole lot more time and work on maybe even generating an ADL for a custom CPU I am thinking of designing
