### ISSUE TITLE
Getting vscode-makefile-tools to work right with omake

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#568]
Microsoft came out with a new way to get intellisense off of makefiles via https://github.com/microsoft/vscode-makefile-tools

After seeing this I of course immediately set out to try it utilizing omake, this didn't work due to a lack of 3 specific arguments: --dry-run, --keep-going, and --print-directory, 

https://www.gnu.org/software/make/manual/make.html#Instead-of-Execution gives a full list of what we need. 

Dry run in particular seems like we just need to create a long command version, --keep-going might be default behavior? But adding that as a thing that we by default have active instead of just having the option to disable seems nice, and --print-directory might need some testing based off of the GNU make, and seems useful to debug the massive near-incoherent mess that is our buildsystem.

**Comment by chuggafan** [comment]
I was able to quickly get this up and running, however I am running into an issue of where the actual command is being run, so I'll just turn this issue into "Getting vscode-makefile-tools to work right with omake" and work on this when I have more time.

**Comment by chuggafan** [comment]
7 long options have been made, however I have run into a problem where if we do not run omake inside of the src directory everything breaks due to the pathext2.mak file being treated as a rule of all things(?). I will investigate this later tonight and see if I can get everything working.

**Comment by GitMensch** [comment]
@chuggafan  I know you are involved with the libcxx - but what do you think about coming back to this one?

**Comment by chuggafan** [comment]
I forgot to mention that this can be closed because I realized that if we just did a directory based one instead (IIRC -C) it worked perfectly, it seems file-based 100% of all make programs fail but directory based we succeed.

**Comment by GitMensch** [comment]
> it seems file-based 100% of all make programs fail

Sounds like a bug in omake in which case there should be an issue. But for "file based make" remember that "omake sourcefile.c" should in most cases just say "no rule to make sourcefile.c".

**Comment by GitMensch** [comment]
The original point of missing parameters `--dry-run`, `--keep-going`, and `--print-directory` along with their short forms seems also still open (according to `omake --help`). So should we reopen this or create follow-up issues?

**Comment by chuggafan** [comment]
> Sounds like a bug in omake in which case there should be an issue.

Nah, I meant omake and gnu make both decide to barf out at the issue here so I'm not questioning it too hard to be honest.

**Comment by chuggafan** [comment]
> The original point of missing parameters --dry-run, and --print-directory along with their short forms seem also still open, similar the long form --keep-going (according to omake --help). So should we reopen this or create follow-up issues?

That's a documentation error, not actually a code error, it seems I forgot to update the docs when I made the change, at the moment I'm doing a lot of other things preventing me from programming too much, so if you want you can go fix the documentation.
