### ISSUE TITLE
OMAKE does not search current makefile path for included makefiles

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#569]
When running an out-of-tree build:

```makefile
include ./whatever.mak
```

Will not work because omake for some reason sees this as a goal, likely after failing to include the file properly wherever the actual execution is taking place, assuming that the environment starts where $(MAKE) executes.... Which is absolutely not true in out-of-tree builds.

This is what is causing #568 btw, I'm throwing this up as a separate issue as it really is very different and should be focused on separately.

**Comment by chuggafan** [comment]
Figured out why we aren't including: We don't do in-current-directory checking for the existence of the file, unlike in the compiler.... Wonders, may try to figure out how to modify it soonish.

**Comment by chuggafan** [comment]
Upon further inspection: I have absolutely no idea how I'd accomplish this without very large rewrites and structural code changes, the main thing that I think prevents me from theoretically accomplishing this task for now is that there is no way of getting the currently processed file, and even if there was, I have no idea where I'd do the check for current dir processing due to the general code structure.

**Comment by chuggafan** [comment]
Looking at this again, I think it's possible to fix this if we change it so that the preferred path of searching for new dependencies is the same path as the "goal", however I'm not sure if this will break anything else currently related as then we will have to track every goal file's fullpath. Should I attempt to bootstrap this modification on the current system using the current goals or...?

**Comment by LADSoft** [comment]
i think that would be ok...   it currently tries finding it relative to the cwd but usually the goal file is in the cwd if it is going to be including something.  (usually from using the /C switch)

**Comment by chuggafan** [comment]
Yhea the entire reason I made this issue was because this wasn't happening, my original plan was to change the cwd to whatever the file we're working on's directory is but....

I may or may not add an OS wrapper to get the fullpath of a file and utilize that as the "preferred" path. We still have to figure out linux support for omake at some point but that's a different issue entirely.

**Comment by chuggafan** [comment]
Okay so this is actually more difficult than I stated it to be, I actually made an OS::GetFileDirectory function and added Shlwapi.lib for OMAKE only (yay!) and then got slapped in the face by the thing *still not* working, so I'll have to debug why it's not finding pathext2.mak despite my efforts. ompfh.

**Comment by chuggafan** [comment]
Doing the investigation it seems that pathext2.mak was a separate goal from the makefile itself... my whole issue is that I have absolutely no idea how to determine the "controlling" file and then making each included file also be relative since goals aren't being disambiguated by anything but it being a std::string so I can't tell if it's an include goal or not...

*SIGH* this issue is way more complicated than I gave it credit for...

**Comment by chuggafan** [comment]
Got a bit further on this by deciding that the "Source target" is the first goal in the path, however this generates the abomination of:

"C:\OrangeCtreetop.mak"

And of course:

```
        copy orc.exe ..\bin
The system cannot find the file specified.
```

because of *COURSE* relative directory tasks are highly effected based off of what directory they're executed from.

I swear I thought this was simple, turns out I was just a 🤡.

**Comment by LADSoft** [comment]
i'll be pushing a fix for this in a few days.    I think the main reason you were having trouble is the include support was very buggy to begin with...
