### ISSUE TITLE
is_nothrow_constructible on constructors with no parameters is false when constructor isn't specifically marked noexcept

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#576]
When performing the check in the function `nothrowConstructible`, on line 533 of libcxx.cpp, the only check to determine if something is "nothrow" is with `return sp->sb->xcMode == xc_none;`, which will fail when the xcMode is unspecified.

In order to test this I created a file:

```cpp
#define _LIBCPP_CONSTEXPR constexpr
#define _NOEXCEPT noexcept

template <class _Tp, _Tp __v>
struct integral_constant
{
  static _LIBCPP_CONSTEXPR const _Tp      value = __v;
  typedef _Tp               value_type;
  typedef integral_constant type;
  
  _LIBCPP_CONSTEXPR operator value_type() const _NOEXCEPT {return value;}
  constexpr value_type operator ()() const _NOEXCEPT {return value;}
};

template <class _Tp, _Tp __v>
_LIBCPP_CONSTEXPR const _Tp integral_constant<_Tp, __v>::value;

#define _LIBCPP_BOOL_CONSTANT(__b) integral_constant<bool,(__b)>

typedef _LIBCPP_BOOL_CONSTANT(true)  true_type;
typedef _LIBCPP_BOOL_CONSTANT(false) false_type;
template <class _Tp, class... _Args>
struct is_nothrow_constructible
    : public integral_constant<bool, __is_nothrow_constructible(_Tp, _Args...)> {};
template <class _Tp> struct is_nothrow_default_constructible
    : public is_nothrow_constructible<_Tp>
    {};

typedef void* __libcpp_mutex_t;
#define _LIBCPP_MUTEX_INITIALIZER 0
class mutex
{
    __libcpp_mutex_t __m_ = _LIBCPP_MUTEX_INITIALIZER;

public:
    
    mutex() = default;

    mutex(const mutex&) = delete;
    mutex& operator=(const mutex&) = delete;

    ~mutex() = default;

    void lock();
    bool try_lock() _NOEXCEPT;
    void unlock() _NOEXCEPT;

    typedef __libcpp_mutex_t* native_handle_type;
    native_handle_type native_handle() {return &__m_;}
};

static_assert(is_nothrow_default_constructible<mutex>::value,
              "the default constructor for std::mutex must be nothrow");

int main()
{
    return 0;
}
```

This demonstrates the issue, whilst:

```cpp
#define _LIBCPP_CONSTEXPR constexpr
#define _NOEXCEPT noexcept

template <class _Tp, _Tp __v>
struct integral_constant
{
  static _LIBCPP_CONSTEXPR const _Tp      value = __v;
  typedef _Tp               value_type;
  typedef integral_constant type;
  
  _LIBCPP_CONSTEXPR operator value_type() const _NOEXCEPT {return value;}
  constexpr value_type operator ()() const _NOEXCEPT {return value;}
};

template <class _Tp, _Tp __v>
_LIBCPP_CONSTEXPR const _Tp integral_constant<_Tp, __v>::value;

#define _LIBCPP_BOOL_CONSTANT(__b) integral_constant<bool,(__b)>

typedef _LIBCPP_BOOL_CONSTANT(true)  true_type;
typedef _LIBCPP_BOOL_CONSTANT(false) false_type;
template <class _Tp, class... _Args>
struct is_nothrow_constructible
    : public integral_constant<bool, __is_nothrow_constructible(_Tp, _Args...)> {};
template <class _Tp> struct is_nothrow_default_constructible
    : public is_nothrow_constructible<_Tp>
    {};

typedef void* __libcpp_mutex_t;
#define _LIBCPP_MUTEX_INITIALIZER 0
class mutex
{
    __libcpp_mutex_t __m_ = _LIBCPP_MUTEX_INITIALIZER;

public:
    
    mutex() noexcept = default;

    mutex(const mutex&) = delete;
    mutex& operator=(const mutex&) = delete;

    ~mutex() = default;

    void lock();
    bool try_lock() _NOEXCEPT;
    void unlock() _NOEXCEPT;

    typedef __libcpp_mutex_t* native_handle_type;
    native_handle_type native_handle() {return &__m_;}
};

static_assert(is_nothrow_default_constructible<mutex>::value,
              "the default constructor for std::mutex must be nothrow");

int main()
{
    return 0;
}
```

This code block shows the minor change, which makes the issue go away, proving my theory in #574 that it's the fact that there's no noexcept keyword after the default mutex constructor that's causing the problem.

**Comment by LADSoft** [comment]
if you don't specify 'noexcept' and you don't specify throw with an empty list, there is no way to know that the function does indeed not throw exceptions.   You can see an example here:

[https://www.cplusplus.com/reference/type_traits/is_nothrow_constructible/](https://www.cplusplus.com/reference/type_traits/is_nothrow_constructible/)

**Comment by chuggafan** [comment]
Reading the draft for C++17 I pulled up states simply that the function `is_nothrow_constructible` has the following condition:

"`is_constructible_v<T, Args...>` is true and the variable definition for `is_constructible`, as defined below, is known not to throw any exceptions (8.5.2.7)", with the 8.5.2.7 linking to the noexcept operator, which simply states:

"The noexcept operator determines whether the evaluation of its operand, which is an unevaluated operand, can throw an exception." 

This indicates to me that `is_nothrow_constructable` evaluates the same rules as `is_constructible` and `noexcept()`, and I know for sure that `noexcept()` does not necessarily have to be false when not everything in it is marked `noexcept`.

Perhaps the wording is unclear? Should I email WG21 for clarification?

**Comment by chuggafan** [comment]
Also noted: clang and gcc both agree that marking a function as always `noexcept` whilst having it always throw is not an error but a warning. 

When looking at compound-requirements, the statement: "If the noexcept specifier is present, the expression shall not be a potentially-throwing expression", with "shall" meaning: "A keyword that indicates a mandatory requirement. Designers are required to implement all such mandatory requirements to assure interoperability with other products conforming to this standard."

Whereas in the Functions section:

```
In a declaration T D where D has the form
D1 ( parameter-declaration-clause ) cv-qualifier-seqopt
ref-qualifieropt noexcept-specifieropt attribute-specifier-seqopt
and the type of the contained declarator-id in the declaration T D1 is “derived-declarator-type-list T”, the type
of the declarator-id in D is “derived-declarator-type-list noexceptopt function of (parameter-declaration-clause)
cv-qualifier-seqopt ref-qualifieropt returning T”, where the optional noexcept is present if and only if the
exception specification (18.4) is non-throwing. The optional attribute-specifier-seq appertains to the function
type.
```

The important bit being "Where the optional noexcept is present if and only if the exception specification (18.4) is non-throwing".

Which leads me to 18.4 where I think this clarifies everything: 

```
 The predicate indicating whether a function cannot exit via an exception is called the exception specification
of the function. If the predicate is false, the function has a potentially-throwing exception specification,
otherwise it has a non-throwing exception specification. The exception specification is either defined implicitly,
or defined explicitly by using a noexcept-specifier as a suffix of a function declarator
```

I am currently reading through the rest of this document, on noexcepts, because there's *ANOTHER* portino right below in paragraph 3 that has a bunch of other information and possible footnotes.

Whooo

**Comment by LADSoft** [comment]
thanks for looking into this.

we can do the work while building default constructor trees I guess, as each constructor higher in the chain will rely on lower constructors that have already been fully evaluated.    Of course we have to go through every expression that could be evaluated, looking for constructor and function calls....   A little bit of work but not too bad...

**Comment by chuggafan** [comment]
I think your solution works, however, what will we do about conditional noexcept functions while we're at it? They still need to be evaluated at some point while we're in it, but that's the whole constexpr issue all over again.

Why do I get the feeling that this will push us over the appveyor limit again?

**Comment by LADSoft** [comment]
I think at least some of them are being evaluated at the point that the related template is fully instantiated...   yeah we still haven't gotten past the last appveyor problem and now this lol...   maybe it can be calculated along with some of the other passes already being made over structured data in conjunction with generating constructors though and not be too much of an extra hit...

**Comment by LADSoft** [comment]
i took a first stab at this; your first example seems to work ok now.   Leaving it open until you approve of it...

**Comment by chuggafan** [comment]
Seems OK so far, not entirely sure, but a different error is popping up with <regex> that I'm not quite sure existed before, saying `Error(258)    c:\ORANGEC\include\regex(5905):  'std::__1::__thread_id::__thread_id(long)' is not accessible` which is... odd... to say the least, will look into the new issue later, but for now this issue seems like it's done, last step is to make sure the perf impact isn't too bad.

**Comment by LADSoft** [comment]
i may know what is going on with that...  will make a patch in a bit.

**Comment by LADSoft** [comment]
does this look ok?

**Comment by chuggafan** [comment]
Wouldn't be able to evaluate it without a more comprehensive test suite, will test this tomorrow

**Comment by chuggafan** [comment]
Still getting the issue with the regex include, I'll check it out in detail after I sleep for a while and bring up VS as the IDE I'm using instead of VSCode so that I can actually do things, I'll likely file a separate issue as it seems separate from NoExcept entirely.

**Comment by GitMensch** [comment]
Test suite sounds good. Could this be added and therefore easily be run before a release?

Something like
  omake release-check

**Comment by chuggafan** [comment]
We already have a test-suite able to be executed with `omake` while in the tests directory, this just needs to be added to the whole thing. Also, I have confirmed that in the `tests` directory the __thread_id(long) issue also appears. All of the bugs seem to love me right now.
