### ISSUE TITLE
OCCOPT command line needs reworking and documentation

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#580]
There's a lot to say about the OCCOPT command line and it's current state, mostly that:

* Input files actually being seen as input files requires that there only be 2 arguments to the command line ????
* There is no way to actually individually test OCCOPT optimizations and passes, so there's no way to see if a specific transform causes an issue
* Some parameters that are available are not even in the OPTMAIN file but are hidden elsewhere???
* A lot of stuff in the command line completely lacks documentation re: point above, a notable one being the displaytiming parameter

OCOPT in all honesty is an absolute mess, I'd like to get it to the point that we can test specific ICF files and see the transformations that OCCOPT produces so that we can see if bad codegen is coming from OCCOPT, OCCPARSE, or OCC, but that's an entirely separate issue that first requires actual knowledge of the inner workings.

**Comment by LADSoft** [comment]
yeah i've wished I had some way to turn off individual optimizations in occopt...   for testing...   it is pretty easy to do as there are hooks in optmain.cpp::optimize, just haven't done it sigh.

**Comment by GitMensch** [comment]
>  it is pretty easy to do as there are hooks in optmain.cpp::optimize

Sounds like a near milestone ;-)
Can I suggest to have those as `-fopt-something` in the frontend OCC and possibly identical in OCCOPT? If those command line options and their help would be generated from a header file both could use the same code...

**Comment by chuggafan** [comment]
I definitely would support -fopt stuff, it'd also be nice if we can go to the optimizer and add our own custom transforms and move around transforms in an easy manner a la the way that LLVM does it, but I don't know enough about the LLVM system to be helpful in that respect.

**Comment by LADSoft** [comment]
in a couple of days I should have the libcxxabi and libunwind at least compiling, then I can take a break and work on this :)

**Comment by chuggafan** [comment]
Even with the recent changes passing in an input file to occopt does not work as it will always take the 1st input as the input file even if that input is a switch name. 

If you place too many options it also fails.

I have another issue with occopt that I will place in a different issue because I suspect it will be more difficult to pull off.

**Comment by LADSoft** [comment]
seems to work fine for me...   are you aware that SwitchParser.ParseI() removes switches that it finds from the (argc, argv) list so that all you are left with is non-switch entities when it returns?

**Comment by chuggafan** [comment]
Running the command on the latest changes: `occopt -ofile hello.icd -O2 -t occopttest.icd` gives me the usage banner which is partially what I'm basing this off of. However I did not know that the Switchparser removes the argc count, that might explain some things, however it does not change that argv[1] is the input file for OCCOPT at all times and that the command I pasted generates a usage banner for a command that in theory should just be giving me an error about invalid file formats.

**Comment by LADSoft** [comment]
well -o isn't currently supported.   I will add it lol!

**Comment by chuggafan** [comment]
Ah, that actually made the issue go away, nvm on the "too many parameters" front then, because -ofile is listed I thought that it meant -ofile {file} when it was supposed to be -o{file}.

My mistake and one that has erronerously persisted for absolutely no reason.

This also makes it so my argv[1] issue goes away, surprisingly, may explain a lot of why I was having issues before...

**Comment by LADSoft** [comment]
also your command line is a little off, to get a file to use you run occparse by itself and it produces an ICF file which combines all the files you added on the occparse command line.   the ICF file is what you specify for occopt.   so you don't need more than one input file for occopt...

**Comment by LADSoft** [comment]
where do we stand on this?

**Comment by chuggafan** [comment]
I think this is likely complete now, only complaint I have is the shared-options weirdness that makes it non-obvious where options are to be modified in OCCOPT/OCC/OCCPARSE but that's not a priority whatsoever.
