### ISSUE TITLE
In threading tests, unique pointer destructor causes error

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#582]
```
Error(112)    c:\ORANGEC\include\memory(2572):  Argument list too short in call to 'std::__1::unique_ptr<_Tp, _Dp>::reset(__pointer_type<_Tp, _Dp>::type)'
note:         c:\ORANGEC\include\memory(2572):  Referenced in instantiation of 'std::__1::unique_ptr<_Tp, _Dp>::~unique_ptr()'
note:         c:\ORANGEC\include\future(1722):  In template instantiation started here
Error( 59)    future.cpp(107):  Pointer to structure required to left of '->'
Error(232)    future.cpp(144):  Could not find a match for 'operator !=(std::exception_ptr, nullptr_t)'
3 Errors

```

I have no idea why this is happening, will attempt to boil down to the heart of the issue later, but this looks like it's going to be one heck of a headache of a debug session for figuring out why this is complaining that something with only a default parameter has insufficient parameters.

**Comment by LADSoft** [comment]
i hate these.   lol

**Comment by chuggafan** [comment]
I figured it out, somewhat, has to do with it being a defaulted parameter (That part I'm not sure about) so the function parameter list is null, making the CheckArgs function completely go ballistic, I have not been able to replicate the issue with any other default parameter case and my attempt to "boil it down" has.... gotten me a different issue to pop up?

What fun.

**Comment by chuggafan** [comment]
Investigating further, this seems to be happening because we're passing a function as an argument to a destructor call, not even sure wtf is happening with that but it looks like I have absolutely no idea how or why it is getting a destructor call like that, just that it's happening.

Ahhhhh the wonders of the world 🤡

**Comment by LADSoft** [comment]
the 'funcsp' parameters are the symbol associated with the function whose body is currently being compiled...    to get the symbol of the function that was selected via overloading use params->sp.

**Comment by LADSoft** [comment]
on looking at it again this actually may be easy...   I didn't expose operator != for exception_ptr with the second argument being nullptr...

**Comment by LADSoft** [comment]
I think I got these three bugs fixed....

**Comment by chuggafan** [comment]
`Error(232)    future.cpp(144):  Could not find a match for 'operator !=(std::exception_ptr, nullptr_t)'` is what I now see in the future.cpp compile.

**Comment by LADSoft** [comment]
i think i really fixed it now, it was having trouble disambiguating two overloads...

>

**Comment by chuggafan** [comment]
Yep, fixed.
