### ISSUE TITLE
Convert the compiler used macros to constexpr

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#583]
The specifics I'm talking about are the following:

`basetype`, `isref`, `__isref`, `__ispointer`, `ispointer`, etc.

The reason for this is sometimes we pass in functions to this, which means that due to macro expansion some functions can get called anywhere between 5-6 times for a single test of whether or not something is a pointer, which is ridiculous, I actually encountered this happening in expr.cpp line 3004.

This will probably involve moving all the macros to the bottom and just running the Visual Studio "Change this to constexpr" and "With this constexpr function fill in the actual valid types for it", I've done it before and threw the work away though so...

**Comment by LADSoft** [comment]
ok will look into this soon.    Maybe it will help compile speed lol!
