### ISSUE TITLE
Equality operator for some types gets overloaded incorrectly

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#584]
THIS is the origin of the issue we are currently facing with `__thread_id`, the test case is generator.cpp from alexcs in the tests, what's happening is an enum is being compared to a integer, and for some reason this calls the __thread_id equality operator out of some location of which I am still investigating. However, this explains why `__thread_id` and it's private constructor is coming into play: by assuming that it's the equality operator for both types it's attempting to convert them both to `__thread_id` and then compare. This is a *MAJOR* issue, as it means that some user-defined equality operators likely aren't getting compiled correctly for some custom types with defined conversion operators.

**Comment by chuggafan** [comment]
So the problem lies somewhere in a call to GetOverloadedFunction, where we are overloading a default operator on an enum and an int, into the equality between two `__thread_id`'s, presumably this has to do with a combination of the private conversion into a long of the `__thread_id` and the custom overloaded equals operator for `__thread_id`, so basically we wouldn't have found this issue unless `__thread_id` existed at all.

How specific.

**Comment by LADSoft** [comment]
this one actually was easy...   turns out operator overloading shouldn't have been applied if the left parameter of an operator is a non-structured type.

Sigh.

**Comment by chuggafan** [comment]
Double checking, we should be converting if either the right side or the left side are a structured type right? If I'm reading the standard properly we're allowed to provide *one* implicit conversion conversion function if it makes the most sense (If we have to implicitly convert it twice, it's an error, actually that should be a testcase, I'll work on that tomorrow). And I think operators are also allowed the one implicit conversion operator, but the standard is rather large and my reading of it rather short.

**Comment by LADSoft** [comment]
apparently both structures and enumerations are fair game for this.   Maybe if an enumeration is passed we shouldn't convert it to a structured type though?

**Comment by chuggafan** [comment]
Agreed, unless it's a class enum and there's a specific overload for the class. I think the rule of "Only one implicit conversion" works either way, if we can enforce that in our expression matching, we just need to find the solution to whatever expression that requires 1 or less conversions in each expression (Maybe subexpression is a better one? I make no promises to how many pages of the C++ standard I will read tomorrow to confirm this)

**Comment by LADSoft** [comment]
there is a comment somewhere that it could be up to three conversions...   but I'm thinking that for overloaded operators the 'default' behavior coded into the compiler for the operator should be considered as part of the overloaded searching process?   So that for example an overload that specifies an enum would be matched, but an overload that specifies a class would not be matched even if a constructor for the class would accept the enum...   because the 'default' function would take precedence in that case?

**Comment by chuggafan** [comment]
https://en.cppreference.com/w/cpp/language/implicit_conversion

Where the reference is getting the implicit conversion stuff is likely from a similar location I was getting the implicit conversion stuff, and theoretically there should be an "infinite" (However much we want to support) explicit conversion change before the implicit conversion.

Enums are specifically mentioned as being convertible to its underlying type and *THEN* being able to be subject to integer promotion as of c++11.

I swear trying to understand the full breadth of the C++ standard is a full time job.

**Comment by LADSoft** [comment]
i did some playing with the MSVC compiler.    It certainly seems like the function operator==(int, int);  should be considered for overload matching even though it isn't formally a function but rather a builtin operation....   if it were it would match enumerated parameters better than if a class constructor had to be called...

**Comment by chuggafan** [comment]
The rule is specifically that if both operands are of arithmetic or enumeration types, the "usual" arithmetic conversions are performed on both and then just do the relation.

So we *technically* just need to do our overload check and if both are of either an enum or an integer type we just select the "Least wide that fits both" and convert whichever is the smaller of the two to the correct size.

**Comment by LADSoft** [comment]
i'm glad we came to the same conclusion lol!   I'll have it fixed soon and then do a push...
