### ISSUE TITLE
OCC generates inefficient code for simple testcases

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#586]
```c
#include <stdlib.h>
int main()
{
    int r = rand();
    if(r & 0b1010)
    {
        return r;
    }
    return 0;
}
```
This generates code listed as:

```nasm
_main:
L_1:
; Line 4:     int r = rand(); 
        call    _rand
; Line 5:     if(r & 0b1010) 
        mov     ecx,eax
        and     ecx,byte 0ah
        je      L_4
; Line 6:     { 
; Line 7:         return r; 
        jmp     L_2
; Line 8:     } 
L_4:
; Line 9:     return 0; 
        xor     eax,eax
; Line 10: } 
L_2:
        ret
```

when I'd expect a code generated as:

```nasm
_main:
L_1:
; Line 4:     int r = rand(); 
        call    _rand
; Line 5:     if(r & 0b1010) 
        test    eax,byte 0ah
        je      L_4
; Line 6:     { 
; Line 7:         return r; 
        jmp     L_2
; Line 8:     } 
L_4:
; Line 9:     return 0; 
        xor     eax,eax
; Line 10: } 
L_2:
        ret
```

This partially stems from the ICD found here:
```
... excess ...
	GOSUB	#_rand:PC.UI
	PARMADJ	#0.N
	T1.I =   RV.T0.I
	_r:LINK(0).I =   T1.I
	DBG BLOCK START
; Line 5:	    if(r & 0b1010) 

	T2.I =   _r:LINK(0).I
	T3.I = T2.I & #A.I <-------------------- issue
	CONDGO	L_4:PC ; T3.I == #0.I
... excess ...
```
which the current OCC (because OCCOPT does not support the TEST instruction) does not meaningfully recognize as a classic use case for the TEST instruction. This means that we should add cases where TEST and similar instructions can be meaningfully useful such as this, I think this belongs in milestone 5 as that's where our "optimizer" work is and the code being generated is still technically correct if inefficient.

(Note: I was inspired to make this test case from the long standing comment in peep.cpp noting:
```
        /* just for fun change it to an AND instruction... */
        ip->opcode = op_and;
```
I haven't actually found anything from this because the actual case that the TEST gets converted to an AND isn't this one)

**Comment by GitMensch** [comment]
@chuggafan: You may want to recheck if this is still the case after the changes during the last months.

**Comment by LADSoft** [comment]
this is probably still a problem... the issue being that the 'test' instruction is a special case.   you would need the same code gen if the if statement looked like this for example:

if (a ^ 0b1010)
     return a;

so this is probably handled best as just a processor-specific modification to the peep handler (occ\peep.cpp)

**Comment by chuggafan** [comment]
Surprisingly my testcase actually got optimized, I have *NO* idea when this happened and it presumably happened really recently.

```
;File test.s
;Compiler version OCC Version 6.0.51.1
        section code align=2        use32
        section data align=8        use32
        section bss  align=8        use32
        section const  align=8        use32
        section string  align=2        use32
        section tls  align=8 use32
        section cstartup align=2 use32
        section crundown align=2 use32
        section tstartup align=2 use32
        section trundown align=2 use32
section code
[global _main]
; main
_main:
L_1:
; Line 4:     int r = rand(); 
        call    _rand ; rand
; Line 5:     if(r & 0b1010) 
        test    eax,0ah
        je      L_4
; Line 6:     { 
; Line 7:         return r; 
        jmp     L_2
; Line 8:     } 
L_4:
; Line 9:     return 0; 
        xor     eax,eax
; Line 10: } 
L_2:
        ret
section data
section code
section data
section const

[extern _rand]
```
I'll say that this testcase is solved but that I need to do a deeper dive, it'll probably be awhile before that deep dive happens though.

**Comment by LADSoft** [comment]
well that is good!   but the branches could still be optimized..

**Comment by chuggafan** [comment]
Theoretically, depending on the architecture the two jumps might be nanoseconds faster than 2 rets on some Intel platforms IIRC from that manual, the ideal here would probably be to invert the je and then have it jump to L_2 instead of L_4 but that's some much more advanced things...

**Comment by LADSoft** [comment]
i retested and the original issue is fixed, closing.
