### ISSUE TITLE
Adding __atomic_thing_fetch builtins

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#587]
This is related to PR #578 where this should be the "final frontier" of the issues preventing compiles in general. 

I have no idea how to implement this in the logicatomic section of occ as it handles both long-long and non-long long and I'm not sure how we should handle them differently at an instruction level.

(Edit: This is related to the file atomic_support.h in the include directory of the source directory of libcxx, __atomic_*_fetch has a semantic difference from __atomic_fetch_* which is why this is cropping up)

**Comment by LADSoft** [comment]
i guess it isn't clear to me what the difference is between atomic_add and __atomic_add (for example) that would require a rewrite to the backend.    Can you clarify?

**Comment by chuggafan** [comment]
atomic_fetch_add and atomic_add_fetch return either the item before the add or after the add, respectively IIRC.

**Comment by chuggafan** [comment]
https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html re-read this and reconfirmed that my memory was right, the `__atomic_fetch_*` returns the value from before the operation and the `__atomic_*_fetch` returns the value after the operation, an important distinction.

This actually is required in a few places so that we can get full support for things such as the <memory> header in multithreaded environments.

**Comment by LADSoft** [comment]
yeah once you said that I looked it up and found you were right....   I'll evaluate how hard it will be to add this support this evening.   I'm hoping that maybe we can make a minor tweak to the atomic_modify code gen.... 😄

**Comment by chuggafan** [comment]
I believe I've added everything we *absolutely* needed, there's a few things we could do for GCC support but we'd have to modify our own systems to do so and I'm not enthused at that because I don't think the non-n versions are particularly useful in the first place relative to the other systems we could bolt onto the compiler at this point in time.
