### ISSUE TITLE
Change build system to remove redundant compiles

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#590]
I noticed while doing single-threaded builds that we build the libcxx c++ files and a bunch of the platform support files twice erroneously, I have no idea why this is being done or identifying where in the makefile system this is being caused, and I suspect that we can get appveyor builds running again if we fix this issue as it should definitely cut out compile times significantly by fixing this.

A way to verify:

Go into the appveyor builds, go to the full build, and ctrl+f something from the libcxx c++ files, you'll note that you'll have 6 hits, two for every stage of the triple "Build me to build myself" chain. 

And upon further inspection this is happening due to the difference between building LSCRTL DLL and not, but this change also is going to be removed once #578 goes through as we already are defining _LIBCPP_BUILDING_LIBRARY and the LSCRTL library will no longer affect visibility annotations causing them to be removed entirely (Why this was the case in the first place is lost on me)

The removal of the LSCRTL special-casing makes sense because libcxx maintainers who place visibility attributes know when/where their compilations should be either imported or exported for consumption due to CLANG builds, and if we are having our own issues I'd rather make us mimic MSVC's behavior as dllexporting is entirely their thing.

As for the __BUILDING_LSCRTL_DLL flag itself: I see it mostly used to define the same dllimport/dllexport shenanigans that LIBCXX does.

I may be completely off with this issue and the intents may be different than what I though since I'm not the biggest expert in the field of the linker but I suspect that this is actually a possible issue rather than not.

**Comment by LADSoft** [comment]
this is a good idea.   But somehow we have to get the export table into lscrtl.dll...   either through a .def file or through some linker shenanigans...

**Comment by chuggafan** [comment]
_LIBCPP_BUILDING_LIBRARY dllexports so it should work on its own...

**Comment by LADSoft** [comment]
oh my, of course you are right, no reason we can't use object files with exports in them to generate both versions of the library.   Well duh...    This seems like an easy fix then...  probably just a change to the make files...   but not tonite...

**Comment by LADSoft** [comment]
that reminds me, the compiler is being compiled multiple times per pass too.    Mostly because there are #defines that make the compiles different between occ and occpr....    guess I will look into that as well :)

**Comment by chuggafan** [comment]
I do happen to know that there are supposed to be differences between occ and occpr however the compiler.h header always defining IS_PARSER has seemingly killed them to the best of my knowledge. There's plenty of spots in the code where there's a semantic difference.

**Comment by LADSoft** [comment]
The thing that makes the difference in this case is the PARSER_ONLY macro, which is only defined as a compiler switch during builds.   But that brings up a good point about the ISPARSER definition...   I should look into whether that is really necessary and clean it up if not...   this sounds like a good time!

**Comment by GitMensch** [comment]
Cool! Has someone already deep-verified that all redundant compiles are gone?

In the meanwhile, here is the nice...

# result #

## before ##
Configuration | Duration
--------------- | ----------
MINGW64 THEN WITH STATIC LIB| 49 min 24 sec
CLANG THEN WITH STATIC LIB | 50 min 38 sec
MSVC THEN WITH STATIC LIB | 48 min 33 sec
MSVC THEN WITH LSCRTL | 47 min 52 sec
MSVC THEN VIA ASSEMBLY | timeout; > 1h
MSVC THEN WITH DEBUG | timeout; > 1h
CODE ANALYZER TEST | 14 min 47 sec
MSIL COMPILER |30 min 4 sec
MS WITH PDB | 22 min 41 sec

## after ##
Configuration | Duration
--------------- | ----------
MINGW64 THEN WITH STATIC LIB| 45 min 13 sec
CLANG THEN WITH STATIC LIB |44 min 38 sec
MSVC THEN WITH STATIC LIB |43 min 48 sec
MSVC THEN WITH LSCRTL | 41 min 27 sec
MSVC THEN VIA ASSEMBLY |56 min 58 sec
MSVC THEN WITH DEBUG | 57 min 45 sec
CODE ANALYZER TEST |12 min 39 sec
MSIL COMPILER |23 min 2 sec
MS WITH PDB | 16 min 48 sec

**Comment by LADSoft** [comment]
i verified that the RTL is only being compiled once per pass and removed the only redundancy I know about from the compiler compiles...

**Comment by chuggafan** [comment]
> Cool! Has someone already deep-verified that all redundant compiles are gone?
> 
> In the meanwhile, here is the nice result (10-20% compile time, cpu-cycles and energy saved):
> 
> Configuration	Duration before	Duration after
> MINGW64 THEN WITH STATIC LIB	49 min 24 sec	45 min 13 sec
> CLANG THEN WITH STATIC LIB	50 min 38 sec	44 min 38 sec
> MSVC THEN WITH STATIC LIB	48 min 33 sec	43 min 48 sec
> MSVC THEN WITH LSCRTL	47 min 52 sec	41 min 27 sec
> MSVC THEN VIA ASSEMBLY	timeout > 1h	56 min 58 sec
> MSVC THEN WITH DEBUG	timeout > 1h	57 min 45 sec
> CODE ANALYZER TEST	14 min 47 sec	12 min 39 sec
> MSIL COMPILER	30 min 4 sec	23 min 2 sec
> MS WITH PDB	22 min 41 sec	16 min 48 sec

Nice, 5-6 minute improvements across the board except for the analyzer.

My single-threaded builds should be significantly faster when I'm doing rebuilds then
