### ISSUE TITLE
ensure function overload matching can disambiguate properly

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#596]
it was brought up in PR#578 that the function overload mechanism can't disambiguate between std::to_string(int) and std::to_string(unsigned) when an enum is involved...

**Comment by LADSoft** [comment]
this simple example works, so I have to debug.   Maybe tomorrow...

```c++
enum xx { r, s, t };

int aa(int);
int aa(unsigned);

main()
{
	xx b;
	aa(b);    
}
```

**Comment by chuggafan** [comment]
Is this in C mode or C++ mode? That may or may not make a difference

**Comment by LADSoft** [comment]
hehehe...   yeah i run into issues like this all the time, where a simple test works but if you put it in a larger contect it sometimes fails.   Will debug as soon as I figure out what I did wrong with the exclude_from_explicit_instantiation attribute implementation I made :)

**Comment by LADSoft** [comment]
what file were you compiling when you ran into this?

**Comment by chuggafan** [comment]
osutil on the AtomicHeaderSupport pull.
