### ISSUE TITLE
Evaluate preprocessor - speed up fputc implementation

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#600]
dig out the old C language version of the preprocessor, and perform performance comparisons against ocpp.

**Comment by LADSoft** [comment]
@chuggafan I was wondering, if I resurrect the old preprocessor code would you be willing to do some side by side comparisons just to see where we stand on this?

**Comment by chuggafan** [comment]
If you can theoretically do it with occparse... I tried out VTune the other day on some parts of the compiler (it immediately BSOD'd me when doing memory effeciency on OCCOPT though when trying to see why it took so long on sqlite3 (it's the liveOut function taking up a lot of time)).

Should be two measuring sticks of timing via simply running them through a test gauntlet and seeing how they differ...

**Comment by LADSoft** [comment]
well i was thinking, we have the standalone preprocessor, and we have the old standalone preprocessor (at least I'm pretty sure I can dig it up)...   for these tests it might be good enough just to measure the standalone preprocessors and see how they compare, without dragging in the compiler proper...   anyway good to know that about liveOut lol...

**Comment by chuggafan** [comment]
Yhea, that sounds good. (BTW that liveOut test was conducted in MSVC debug mode, might majorly affect throughput there, because the main killer seemed to be a common pointer dereference and assign somehow, which makes me doubt that it's a bottleneck unless liveOut is being called a *LOT*, VTune seems less intuitive than Microsoft's own tools for performance analysis but is perfect for analyzing performance of binaries compiled with our own compiler...)

**Comment by LADSoft** [comment]
well as i recall liveout does get called a lot...   i think it is one of those things where you iterate until you find a solution to a set of equations...   and data is gathered for every block in every function.    I think that maybe some of the huge functions in sqlite3 might be an issue....   I think some of the problem is that since everything is in the same file (sqlite3.c) the inlining being done is probably tremendous as we don't have sophisticated inline decision making...   and if there are a lot of conditionals especially loops that would be problematic...

another thing I am interested in is what exactly is causing the problem in ilstream.cpp and ilunstream.cpp

**Comment by chuggafan** [comment]
Preferably we want something that includes a lot of text to paste or preprocessor macros to deal with to stress-test it.

**Comment by GitMensch** [comment]
Sounds good, but in this case my test is likely not that useful.

**Comment by LADSoft** [comment]
@GitMensch I'll take you up on yoru offer for that example.    It might be easier than trying to debug sqlite3...      but that is actually a different issue than we are addressing here :)

@Chuggafan i checked in a version with the c language preprocessor.   It is in the VS solution.

**Comment by chuggafan** [comment]
I'll test the suggestion I made in #599 first, because if that can knock off 3 minutes of buildtime then this issue is invalid as the problem wasn't the preprocessor... the main issue I had IIRC was simply trying to separately test the pre/post fix with VTune in debug mode because it's treated as a library by the MSVC thing.

TBQH I think that even *IF* the old preprocessor is *faster*, the new preprocessor is more maintainable and has more features (my `__include_next` nightmares are to thank for that). 

So once I can see if the issue was enums or preprocessor in the first place we can do the checks...

**Comment by LADSoft** [comment]
im definitely not wanting to go backwards with the preprocessor.   I jsut thought if it turns out the preprocessor is an issue there may be ways to optimize it without changing its character too much :smile:

**Comment by LADSoft** [comment]
well i did a quick benchmark with a 100000 line randomized file.

The C version of the preprocessor wrote an output file in 0.29 seconds.

The C++ version of the preprocessor wrote an output file in 29.41 seconds.

Guess I will look at to find out the disparity, soon...

**Comment by LADSoft** [comment]
i may have been comparing apples to apples, the C version was compiled with MSVC whereas the C++ version was compiled with OCC.

**Comment by LADSoft** [comment]
when compiled with MSVC the preprocessors are speedy (< 1 second on a 10000 line file) but the preprocessors run 40-50 times slower when compiled with OCC.   I tracked it down to the fputc/fputs implementation, so this will become a task to optimize that.   I'm not going to address it in this milestone though.

**Comment by LADSoft** [comment]
turns out 80% of the time is used locking and unlocking.   I figured I'd try to fix it sooner rather than later.

**Comment by GitMensch** [comment]
Any updates statistics? The comparison of the times before/after this change would be quite interesting.

**Comment by LADSoft** [comment]
i used the old C preprocessor from before we switched to the C++ version, compiled with OCC.   To process a 100000 line file with random data took about 5.5 seconds with the old lock implementation.   It used windows semaphores.    The same file was processed in half a second or less when I switched the file locking to using atomics.   I didn't explicitly measure it just noted the difference.    So there is at least a ten times speedup.   Maybe I will try to get more accurate numbers later today...

**Comment by LADSoft** [comment]
prior to the change, c_preprocessor took 5.5 seconds to process my 100000 file.   After, it was down to .28 seconds, which is comparable to what an msvc-compiled version does.

I'm reopening this though as the c++ version only sped up by about 30% down from 29 to 21 seconds.   There is omething up with the fwrite implementation which is unrelated to the original problem.

**Comment by LADSoft** [comment]
turns out there was a further problem; stderr and stdout weren't buffered.   Adding a small buffer dropped the time to 1.4s.   Compare to the MSVC-compiled version at .8s.
