### ISSUE TITLE
Decltype is not same type as referenced type

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#607]
I've noticed often when doing fixes related to #559 that constructs such as `static_assert((std::is_same<decltype(std::abs((float)0)), float>::value), "");` fail often even though the decltype should be returning the correct type. This is absolutely something that should be fixed sooner rather than later, it'll definitely at least be part of milestone 3.5 though.

**Comment by chuggafan** [comment]
Further testing also indicates that there's issues when using different versions of this

Something is different between:

```cpp

#include <cstdlib>
namespace std
{
template <class _Ty, _Ty _Val>
struct integral_constant
{
    static constexpr _Ty value = _Val;

    using value_type = _Ty;
    using type = integral_constant;

    constexpr operator value_type() const noexcept { return value; }

    constexpr value_type operator()() const noexcept { return value; }
};

// ALIAS TEMPLATE bool_constant
template <bool _Val>
using bool_constant = integral_constant<bool, _Val>;

using true_type = bool_constant<true>;
using false_type = bool_constant<false>;
template <class _Tp, class _Up> struct  is_same           : public false_type {};
template <class _Tp>            struct  is_same<_Tp, _Tp> : public true_type {};
}  // namespace std

int main() { static_assert((std::is_same<decltype(std::abs((float)0)), float>::value), ""); }
```

Which doesn't work, and:

```cpp
#include <cstdlib>

namespace std
{
template <class _Ty, _Ty _Val>
struct integral_constant
{
    static constexpr _Ty value = _Val;

    using value_type = _Ty;
    using type = integral_constant;

    constexpr operator value_type() const noexcept { return value; }

    constexpr value_type operator()() const noexcept { return value; }
};

// ALIAS TEMPLATE bool_constant
template <bool _Val>
using bool_constant = integral_constant<bool, _Val>;

using true_type = bool_constant<true>;
using false_type = bool_constant<false>;
template <class, class>
constexpr bool is_same_v = false;  // determine whether arguments are the same type
template <class _Ty>
constexpr bool is_same_v<_Ty, _Ty> = true;

template <class _Ty1, class _Ty2>
struct is_same : bool_constant<is_same_v<_Ty1, _Ty2>>
{
};
inline  float abs(float __lcpp_x)  { return ::fabsf(__lcpp_x); }

inline  double abs(double __lcpp_x)  { return ::fabs(__lcpp_x); }

inline  long double abs(long double __lcpp_x)  { return ::fabsl(__lcpp_x); }
}  // namespace std

int main() { static_assert((std::is_same<decltype(std::abs((float)0)), float>::value), ""); }

```

Which *ALSO* doesn't work but uses the microsoft style but the compiler returns 1 for.

Will be on the lookout for why tomorrow.

**Comment by LADSoft** [comment]
this works lol:

```c++
#include <algorithm>
#include <cmath>
static_assert((std::is_same<decltype(std::abs((float)0)), float>::value), "hi");

main()
{
}
```
I'll look into this in a couple of days.

**Comment by LADSoft** [comment]
ok you used cstdlib and i used cmath...   your first example worked when I switched it to cmath...   didn't try the second.   is it possible that the only problem here is that floating point versions of std::abs should be in scope in cstdlib and aren't?   Or is this a more prevalent problem?

**Comment by chuggafan** [comment]
cstdlib seems to include stdlib.h which in c++ for the clang headers includes math.h which should define it...

**Comment by LADSoft** [comment]
it seems like the floating point definitions of abs() in \orangec\include\math.h aren't being compiled for whatever reason...

**Comment by LADSoft** [comment]
sorry i was so abrasive yesterday...   I have my moments...

anyway I was wondering...   in stdlib.h it does an include_next followed by an include.    Which directory would the include occur in, the original directory before the include_next or the directory the include_next happened in?   because if the wrong version of math.h is being included that could be the reason for the abs() failure...   one defines the floating point versions of abs() and the other doesn't...

**Comment by chuggafan** [comment]
I don't think so, the C++ math.h #include_next's math.h and as per the behavior I'm looking at, when doing a pure #include we first look at the directory of the system (if it's a system type path), last included file, then the local directory, then the user search, then if we haven't specified system, search system. So #include might theoretically be doing something weird but I don't think so considering this mimics behavior from other compilers, to test I just need to run the preprocessor on a file including cstdlib, right?

**Comment by LADSoft** [comment]
yeah, just include cstdlib.   I had put garbage characters at the point of defining the floating point versions of abs() in math.h, 
didn't get a compiler error so I know it wasn't reaching that point at least.   I didn't have time to go any further with it so I wasn't sure it wasn't a #if issue of some sort...

**Comment by chuggafan** [comment]
*SIGH* you're right about it being an include_next issue, one I actually cannot understand due to the fact that the include ordering should be so simple.

After the #include <cstdlib> it seems to be skipping.

I thought I finished the #include_next stuff 😢

**Comment by LADSoft** [comment]
this seems fundamental so I moved it into milestone #3

**Comment by LADSoft** [comment]
we are getting really close, just a few minor things to polish off!

**Comment by chuggafan** [comment]
Well, I discovered that the problem isn't actually my #include_next stuff, because it actually goes cstdlib -> config -> cstdlib -> stdlib.h -> c\stdlib.h -> include\stddef.h -> c\stddef.h -> _defs.h

However it seems for some reason the warnings I put in include\stddef.h aren't being included but I do see the:

`#line 96 "c:\ORANGEC\include\stdlib.h"` appear in the file.

I'm 99% sure this is a preproc problem of which I have no idea how to solve...

**Comment by LADSoft** [comment]
ok will look at it tonite...

**Comment by LADSoft** [comment]
the problem turned out to be simple...   need_malloc_and_calloc was defined by the compiler so it didn't include math.h at all.   It will be fixed in the next push...

**Comment by LADSoft** [comment]
now occ won't compile itself properly...   maybe I'll get it fixed tomorrow.
