### ISSUE TITLE
nullptr not treated as a constant

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#608]
This is another milestone 3.5 issue from the libcxx tests:

An example program for this is:

```
#include <cassert>
int main()
{
    bool b(nullptr);
    assert(!b);
}
```

nullptr should be a constant of 0 for an integral literal:

```
7.11 Pointer conversions [conv.ptr]
1 A null pointer constant is an integer literal (5.13.2) with value zero or a prvalue of type std::nullptr_t. 
```

And thus is a constant.

**Comment by LADSoft** [comment]
the type being std::nullptr_t, it can't be used anywhere a value of '0' could be used.   Because the type wouldn't be right for non-pointer contexts.   But I suppose it is legit that a pointer could be converted to a bool so the example should compile?

**Comment by chuggafan** [comment]
I think nullptr is only a std::nullptr_t when in a prvalue context, otherwise it's a 0 constant.

**Comment by LADSoft** [comment]
I'm not able to think of what context you could use it in where it wouldn't be a prvalue...    when used to initialize an object it clearly is one...  so for example:

int aa(nullptr);

shouldn't work and in fact doesn't in the popular compilers...

**Comment by chuggafan** [comment]
https://godbolt.org/z/bnac36K6K

All 3 compilers accept this for some reason but not the example you provide, and you're right that it should be a prvalue in that case.

What we could do is just mark the test that's checking for it as SKIP because it's (seemingly) noncompliant.

**Comment by LADSoft** [comment]
like I tried to say earlier (not so well I guess) I'm thinking that conversion of a pointer to a bool is allowed and that is why your example works whereas mine doesn't.
