### ISSUE TITLE
Suggestion: Move doc sources to markup

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#61]
.. or any other format that is better human-readable than the current HTML.

Markup would have the obvious benefit that it is "native" supported by GitHub.
But this would also allow to combine it with something like readthedocs.io which allows online downloads for any tagged version as HTML/EPUB/PDF...

For an example read http://opencobolide.readthedocs.io/en/latest/ (which shares the same abbreviation for the IDE ;-)

**Comment by LADSoft** [comment]
deferred to the weekend

**Comment by LADSoft** [comment]
I completed this and removed the HTML files

**Comment by GitMensch** [comment]
Looks good. I've prepared the minimal setup on readthedocs:

https://orangec.readthedocs.io/en/latest/Tools/

If you like this we can do one of the following (after you registered there and/or tell me your username there):

* I delete the project under my account and you re-add it under your account with "OrangeC" as project name (I don't know if this will result in the cased variant or not).
* I set you as the admin of the project there.

Afterwards you may add the webhook (it is a single click away when logged in as Administrator there - at least if your account has GitHub write access) - this leads to auto-build of the docs there (it is currently a manual "build now" thing) and optionally change/adjust the theme.

In general we can add the badge https://readthedocs.org/projects/orangec/badge/?version=latest to the main README.md (showing if there are any errors in the markup for example missing links) and optionally create an index.md to tweak the generation of the PDF.

**Comment by LADSoft** [comment]
That looks good.   I linked an account to my github account, the user name is LADSoft...

**Comment by GitMensch** [comment]
@LADSoft You've admin access there (and if you want to may remove my account under Admin->Maintainers).
Next step may be to [add the web-hook](https://readthedocs.org/dashboard/orangec/integrations/)

**Comment by LADSoft** [comment]
Ok I appreciate your help on this.  I've added the webhook and updated README.md with various information about this.   I've also queued some changes for my web page to talk about this, the appveyor.ci, and the recent relicense to GPL-3 but won't push that until I have the next release, which I hope to have within a week or so.

**Comment by GitMensch** [comment]
Looks like we should provide an index.md, too - see http://orangec.readthedocs.io/en/latest/
This could contain part of the README.md (in this case best to split the current version and include the common OrangeC part in both) and either link to or include https://github.com/LADSoft/OrangeC/blob/master/doc/Tools.md

**Comment by GitMensch** [comment]
Seems there is an issue on readthedocs:

https://orangec.readthedocs.io/en/latest/occ/OCC/
links to https://orangec.readthedocs.io/en/latest/occ/OCC/OCC%20Command%20Line.md instead of https://orangec.readthedocs.io/en/latest/occ/OCC Command Line

In general I'd advise against spaces in these file names (replacing them by underscores with git-mv and within the links may fix the issue on readthedocs already).
