### ISSUE TITLE
add GCC developer option --print-file-name

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#611]
> `-print-file-name=library`
>
> Print the full absolute name of the library file library that would be used when linking—and don’t do anything else. With this option, GCC does not compile or link anything; it just prints the file name.

In the meantime: is there a way to get this information currently?

**Comment by LADSoft** [comment]
no there is no way to get the RTL library file name.   But I suppose it would be different based on whether you linked to the library statically or dynamically?

**Comment by GitMensch** [comment]
No, that gives the library that would be used for linking - resolving from `LIBPATH`

**Comment by LADSoft** [comment]
there are actually two libraries - the rtl library and the win32 import library.    Would it just give whatever RTL library it is using?

**Comment by GitMensch** [comment]
The compiler does not know anything about the runtime library, I'd say the link library would be correct.

**Comment by LADSoft** [comment]
@GitMensch i did complete these three issues.   If you have no comment within a few days I will close them...

**Comment by GitMensch** [comment]
Somehting is wrong. First of all: these commands cannot output a version header as the first line is always what is parsed by scriptsm so `--nologo` must be implied.

~~~
>rem expected: full path to olink.exe, but got none
>occ --print-prog-name ld
occ Version 6.0.50.212 Copyright (C) LADSoft 2006-2020

>rem expected: as the name cannot be resolved: input name, unchanged; would be different for libcob.l
>%CC% --print-file-name a
occ Version 6.0.50.212 Copyright (C) LADSoft 2006-2020
c:\Users\me\Desktop\orangec\lib\clwin.l

>%CC% -dumpmachine
occ Version 6.0.50.212 Copyright (C) LADSoft 2006-2020
i686-w32-occ
>%CC% -dumpversion
occ Version 6.0.50.212 Copyright (C) LADSoft 2006-2020
6.0.50.212
~~~

(btw: nice variant with the machine names, I like that)

compare with gcc:

~~~
$ gcc --print-file-name libcob.so
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libcob.so
$ gcc --print-file-name dummy
dummy
$ gcc --print-prog-name collect2
/usr/lib/gcc/x86_64-linux-gnu/8/collect2
$ gcc --print-prog-name dummy
dummy
$ gcc -dumpmachine
x86_64-linux-gnu
~~~

Please adjust the output and I'll retest.
In the meanwhile I've found another part missing... #615

**Comment by GitMensch** [comment]
The latest commit is much better and --dump does not have a banner any more, but it is still there with --print:

~~~
>%CC% -dumpversion
6.0.50.216
>%CC% --print-prog-name=ld
occ Version 6.0.50.216 Copyright (C) LADSoft 2006-2020
c:\Users\me\Desktop\orangec\bin\olink.exe
~~~

**Comment by LADSoft** [comment]
oops....  i missed that --print has two dashes lol.   I'll fix these tonite...

**Comment by LADSoft** [comment]
i did fix both of these.

**Comment by GitMensch** [comment]
`--print-file-name` does not work as expected yet. Two scenarios:

1 there is an import library found in the library search path that matches the name -> print the full path to it
2 there isn't --> print output as input

**Comment by LADSoft** [comment]
i think i fixed this issue?

**Comment by GitMensch** [comment]
Getting nearer. If my glancing over the code was not too quick then currently that just checks if there's a library in the OrangeC-lib (and also only if ORANGEC environment variable is set - is that the case [and here] already?) with that name; but olink uses a different approach to find libraries (which includes `-L` and possibly stuff like `LIBDIR` and possibly auto-add .l).
To do this correctly occ needs to do the full parsing and then ask the linker do do the output.

Note: this issue is not necessary to be added soon, if this is too complex; in this case please comment out the current "half code" and come back after the milestone.
