### ISSUE TITLE
olink compatibility options

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#615]
The following options seem to be commonly used with build scripts (currently investigation python distutils) but are not supported yet with olink:

* `-v`; I guess this is possibly a no-go as `-v` means (historically?) the same as `-g` - generate debug info; but _maybe_ `-v` could be seen as `--version` as long as `OCC_LEGACY_OPTIONS` (or `OLINK_LEGACY_OPTIONS` is not set to true)
* `--shared`, maybe that would be reasonable as `/T:DLL32` (and later match whatever the "native shared" variant is)?

**Comment by LADSoft** [comment]
I made the change to -v in the compiler and added --shared.   I also made it so that the print/dump options would not show a header...

**Comment by GitMensch** [comment]
All those are quite fine (--dump with "false" double-hypens shows the header as mentioned in #612) but the `-v` part was only on the compiler (nice work btw), but this issue is about the linker :-)

~~~
>olink.exe -v
olink Version 6.0.50.219 Copyright (C) LADSoft 2006-2021

Usage: olink [options] inputfiles

/Dxxx=val Define something           /Lpath         Set Library Path
/T:xxx    Target configuration       /V, --version  Show version and date
/c+       Case sensitive link        /l             link only
/m[x]     Generate Map file          /oxxx          Set output file
/r+       Relative output file       /sxxx          Read specification file
/v or /g  Pass debug info            /y[...]        Verbose
/!, --nologo   No logo

 --output-def filename    create a .def file for DLLs
@xxx      Read commands from file

Time: 00:36:59  Date: Jul 23 2021
~~~

So `-v` is still "debug" there and `-shared` is not accepted there yet.

**Comment by LADSoft** [comment]
i did change the linker options the other day :)

**Comment by GitMensch** [comment]
`olink.exe -v` does nothing now - so starts the help, only `-V` outputs the help.
Note: I'm happy with `-V` and `--version` in general, it is just that `ld -v` does output the version since years, could we add `-v` to olink for the version header, so output similar as `occ -v` does?

**Comment by LADSoft** [comment]
ok

**Comment by LADSoft** [comment]
i've fixed it now.

**Comment by GitMensch** [comment]
Yes, "works" now in the way that it looks like it should, opening another for the last missing piece...

**Comment by LADSoft** [comment]
you were right i muffed up --shared.   I fixed it but I muffed up the checkin as well, it got added as part of this : 837fbe58d7e5f89de99878f4191f3893cbfd913c

**Comment by LADSoft** [comment]
well, as far as olink -v we could make it different that occ -v, for example to match ld -v.   Looks like that does something similar to the compiler --dumpversion?     Anyway the -v switch is unique to the projects I added it to.   But of -V and --version are shared among the tools so it would be harder to match the same output with those...

**Comment by GitMensch** [comment]
That is an interesting point. and something I did not considered. Just did a quick check now:

~~~
$ ld --version
GNU ld (GNU Binutils) 2.36.1
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ ld -v
GNU ld (GNU Binutils) 2.36.1
~~~

So yes, for `olink -v`, if this is acceptable, we could also limit the output to one line:

~~~
olink Version 6.0.50.222 
~~~

------------------------------------------------------------

As we're already on that - after checking different compilers including MS - what do you think of actually adjusting the **global** `--version` as follows:

~~~
olink Version 6.0.50.222 Copyright (C) LADSoft 2006-2021

Compile date: Jul 29 2021 time: 01:12:00
~~~

to 

~~~
olink Version 6.0.50.222
Copyright (C) LADSoft 2006-2021

Compile date: Jul 29 2021 time: 01:12:00
~~~

or

~~~
olink (OrangeC) Version 6.0.50.222
Copyright (C) LADSoft 2006-2021

Compile date: Jul 29 2021 time: 01:12:00
~~~

or

~~~
OrangeC olink Version 6.0.50.222
Copyright (C) LADSoft 2006-2021

Compile date: Jul 29 2021 time: 01:12:00
~~~

Just as suggestion...

**Comment by LADSoft** [comment]
ok i made both changes :smile:

**Comment by GitMensch** [comment]
I really would like to test those but because of #618 and breaking builds there are no artifacts currently.

**Comment by LADSoft** [comment]
yeah we haven't had a good build since you told me that good builds were really bad lol.   I'll try to get this back on track this afternoon.

**Comment by GitMensch** [comment]
Thanks, all issues mentioned here are solved.

Bonus: `pip install` actually works now (I would have guessed that this isn't the case easily):

```bat
set CC=occ.exe
set "PATH=%PATH%;C:\OrangeC\bin"
python.exe pip install -U pylint --user
```

Quite cool :-)
