### ISSUE TITLE
Add support for Embarcadero Free C++ Compiler

### ISSUE THREAD

**Issue by altPOCA** [LADSoft/OrangeC#620]
The current BCC32 makefile requires RAD Studio. Embarcadero provides their free C++ compiler as a standalone package here:

https://altd.embarcadero.com/download/bcppbuilder/BCC102.zip

One do not need to install the whole RAD Studio to have the C++ compiler.

Please modify your makefile to add support for the standalone free C++ compiler.

Thanks.

**Comment by LADSoft** [comment]
Thanks.   i'll check it out this weekend.

**Comment by LADSoft** [comment]
i had to work around all the bugs in the embarcadero compiler but I did finally get it working.   It is still the 'BCC32' compiler type, I moved radstudio compiles to a new file.

**Comment by GitMensch** [comment]
References: 6e79df709fddb065d6c4f1ca532b59a450da463b b97af6ba9b997fcdd5a3c6cd9f5eb6774c9f61b8 6b6c8802ca597843f25314a3e4833da3bc242695 - @altPOCA Is there something open yet or can this be closed?

**Comment by altPOCA** [comment]
> References: [6e79df7](https://github.com/LADSoft/OrangeC/commit/6e79df709fddb065d6c4f1ca532b59a450da463b) [b97af6b](https://github.com/LADSoft/OrangeC/commit/b97af6ba9b997fcdd5a3c6cd9f5eb6774c9f61b8) [6b6c880](https://github.com/LADSoft/OrangeC/commit/6b6c8802ca597843f25314a3e4833da3bc242695) - @altPOCA Is there something open yet or can this be closed?

You closed it a bit too soon but it's fine. I have a bit trouble figuring out how to build your compiler from source. There are too many makefiles and batch scripts. This is what I tried:

I have C:\BCC32\bin in my PATH then in the src directory of your source tree I run omake -DCOMPILER=BCC32 clean -j:8 and it gives me a bunch of errors. Then I tried omake -f bcc32.mak and omake bcc32.mak both returned immediately to the cmd shell without any errors but a new blank line.

Please pardon my ignorance but how to correctly build your compiler from source anyway? Which batch script to be used or which omake command? Thanks.

**Comment by LADSoft** [comment]
sorry, guess I'm used to people never closing out issues lol...

_omake -DCOMPILER=BCC32 clean -j:8_ will only clean up the directories...

after you've done that try this:

_omake -DCOMPILER=BCC32 fullbuild_   which will build the compiler and the runtime library, and install the executables and libraries in the proper places.

you can also compile it without specifying fullbuild, and it will just build the executables and leave them in the source directories.

Note bcc32.mak expects embarcadero c++ to be installed in c:\bcc102 ...

**Comment by altPOCA** [comment]
> sorry, guess I'm used to people never closing out issues lol...
> 
> _omake -DCOMPILER=BCC32 clean -j:8_ will only clean up the directories...
> 
> after you've done that try this:
> 
> _omake -DCOMPILER=BCC32 fullbuild_ which will build the compiler and the runtime library, and install the executables and libraries in the proper places.
> 
> you can also compile it without specifying fullbuild, and it will just build the executables and leave them in the source directories.
> 
> Note bcc32.mak expects embarcadero c++ to be installed in c:\bcc102 ...

Now it worked. You could close the issue again :smile:
