### ISSUE TITLE
_WIN32 not defined any more?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#624]
I'm quite sure that the following did work previously:

```c
#if defined( _WIN32)
   #include <conio.h>
#else
   #include <sys/select.h>
   #include <unistd.h>
#endif
```

Now it errors with 

> Could not open  <sys/select.h>  for input

(side note: should we add that?)

and the only way to compile now is by explicit adding the define `occ -D_WIN32`.

**Comment by LADSoft** [comment]
I'm not sure how I could have broken this sigh.    Will look into it...

**Comment by LADSoft** [comment]
it seems ok...   but there are ways of turning it off.   For example if you do /Wa it will put it in one of the DOS modes and undefine _WIN32.    There are other variants of /W that will do something similar...

**Comment by GitMensch** [comment]
Command line was:

`occ -! -O2 -Wall -Wextra -pedantic -I.. -DHAVE_VSNPRINTF -DHAVE_VSSCANF -c ..\pdcurses\psdomething.c`

**Comment by LADSoft** [comment]
yeah probably the -Wall broke it...   I'll see what I can do about making them coexist this afternoon...

**Comment by GitMensch** [comment]
Thanks, adding `-Wall` and `-Wextra` is definitely reasonable. Just for reference as it is slightly related: #605.
