### ISSUE TITLE
omake: missing option to override variables

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#626]
Works: `gmake CC=occ all`, does not: `omake CC=occ all`:
> Error: No rule to make target 'CC=occ'

which should override

```make
CC = gcc
```

see GNU make manual under [Overriding](https://www.gnu.org/software/make/manual/html_node/Overriding.html); note that `CC=occ make` is very different from `make CC=occ` (the first one needs a posix shell and does not override, the second one is a make functionality and always overrides).

**Comment by LADSoft** [comment]
there are already two ways of doing this.   I'll add this one too though :smile:

**Comment by LADSoft** [comment]
i think you asked in another issue about 'ORANGEC' with the concern it may not be defined.    However, as part of another issue we wrote a long time ago we define it in every application, at the beginning, if it isn't already defined,

**Comment by GitMensch** [comment]
For some reason my local OrangeC environment does not work; I'll setup it again with next passing CI build...
Meanwhile: I _think_ the commit don't fix that:

scenario 1: `A = B`
scenario 2: `A ?= B`

With `omake -DA=stuff` only the second scenario has A as "stuff", hasn't it (that would be perfectly correct)?
with `omake A=stuff` both should be set (because that _overrides_), but if I understood the referenced commit correctly it just emulates `-D`.

?
