### ISSUE TITLE
ocpp: -Mx options for dependency generation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#628]
Resulting from:

```make
# rule to generate a dep file by using the C preprocessor
# (see man cpp for details on the -MM and -MT options)
%.d: %.cpp
	@$(CPP) $(CFLAGS) $< -MM -MT $(@:.d=.o) >$@
```

found in https://gitlab.cobolworx.com/COBOLworx/cbl-gdb/-/tree/master/cobcd-st (with makefile adjustment to specify CPP).

**Comment by LADSoft** [comment]
@GitMensch:   this is actually a problem with OCC.   Which I'm fixing immediately....   But the -Mx options are supposed to be for OCPP I guess...   also orangec only supports the fundamental -M at the moment and finally the output may not be going to the right place.   I'm wondering how you think this should work?

**Comment by GitMensch** [comment]
> finally the output may not be going to the right place

What do you mean by this?

* It should just go to stdout.
* to be reasonable the banner cannot be included (because that's invalid in make syntax)

> the -Mx options are supposed to be for OCPP I guess

Yes. Can you please move the code to OCPP and let OCC just pass the argument (I think this is what gcc and clang do)?

>  orangec only supports the fundamental -M at the moment

OK, let's make that a feature request then: "Please add the missing options for [dependency generation](https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Preprocessor-Options.html#Preprocessor-Options)".

**Comment by LADSoft** [comment]
@GitMensch,   i spent an evening working on constexpr issues but am back to your issues now...   hope to have something to push later today or tomorrow...   a couple of these are non-trivial so they are taking time :smile:

**Comment by GitMensch** [comment]
Sounds good. Note: I'm unlikely to take time for anything development related in the next three weeks, so don't feel any time pressure for those and keep in mind that testing on my part will take a while.
