### ISSUE TITLE
Is it possible to output the original definition for "ERR_REDEFINITION_OF_TYPE"?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#630]
I've got a compile saying:

> Error( 81)    isinternal.h(88):  Multiple declaration for type 'pid_t'

I _guess_ this is the place where it comes from:
https://github.com/LADSoft/OrangeC/blob/66c8044f84ddc69c449bbceeb3faada1dc645f67/src/occparse/declare.cpp#L6256-L6259

In cases like these it would be good to know:

* where was the original definition
* what was the original definition
* ideally: what is the new definition

I just assume that that if after full preprocessing on the symbol was done and the type is identical (for example: `typedef something int;` and the definition is on one case `int` and in the other `something`) the message would not be raised.

**Comment by LADSoft** [comment]
I don't know if you've found the right code; preverrorsym should at least tell you where the original definition was.   I'll track it down later...

**Comment by LADSoft** [comment]
used to work...  I've at least made it tell you where it was previously defined.
