### ISSUE TITLE
FR: add `_lseeki64` and `_commit`

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#631]
Please add the C runtime library functions [`_lseeki64`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/lseek-lseeki64) (same as `_lseek`, but with different parameter types) and [`_commit`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/commit).

--------------------

original issue where I've thought that those are already implemented

It's been a while since I've tried to use configure scripts and automake generated Makefiles to link, so it is possible that I just do it wrong...

This is what is done:

1. configure; then adjust libtool:
```
# Commands used to build an old-style archive.
old_archive_cmds="olib -! \$oldlib\$oldobjs\$old_deplibs"
```
2. compile all C files to objects
3. link the library objects to a static library:
  `olib -! .libs/libvbisam.lib  libvbisam_la-isdecimal.o libvbisam_la-ishelper.o libvbisam_la-isaudit.o libvbisam_la-isbuild.o libvbisam_la-isdelete.o libvbisam_la-isopen.o libvbisam_la-isread.o libvbisam_la-isrecover.o libvbisam_la-isrewrite.o libvbisam_la-istrans.o libvbisam_la-iswrite.o libvbisam_la-ischeck.o libvbisam_la-vbdataio.o libvbisam_la-vbindexio.o libvbisam_la-vbkeysio.o libvbisam_la-vblocking.o libvbisam_la-vblowlevel.o libvbisam_la-vbmemio.o libvbisam_la-vbnodememio.o`
4. link the executables
   `occ -! -I../.. -I../../libvbisam -O -o vbcheck.exe vbcheck-vbcheck.o  -L/d/dev/vbisam/build_orange/libvbisam /d/dev/vbisam/build_orange/libvbisam/.libs/libvbisam.lib`

Result:
> Error: Undefined External '_commit' in module D:\dev\vbisam\libvbisam\ishelper.c
Error: Undefined External '_lseeki64' in module D:\dev\vbisam\libvbisam\vblowlevel.c
        2 Errors, 0 Warnings
        Errors encountered, not creating output file
        
Where have I gone wrong - how to fix this?

**Comment by LADSoft** [comment]
I'm not finding a reference to _lseeki64 anywhere in the runtime lib, including in the headers.   probably _commit is the same.    Are these new?   Or perhaps in an older build you used some #define to get an alternate code path to compile?

**Comment by GitMensch** [comment]
Thanks for the lookup. They aren't new, guess I used a different code path before.
Let's make it a FR then :-) I'll adjust the issue title and starting post.
