### ISSUE TITLE
long options: make it an array of strings

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#632]
in #627 it was suggested that the options in the switch parser be set up so that you can have multiple long-options for any given switch (e.g. pass an array instead of a string).   At the same time, there are other options that could be added to omake.

**Comment by LADSoft** [comment]
@GitMensch: any problem with me using an initializer-list here instead of specifying an explicit array?

**Comment by GitMensch** [comment]
No, that's completely fine.
