### ISSUE TITLE
Clean up the LSSM file after usage

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#633]
Current compiler work when doing compiles and tests leaves traces of this "LSSM" file absolutely everwhere, I understand that this purpose relates to appveyor in some manner and memory vs disk speed, however there needs to be cleanup such that it doesn't spill absolutely everywhere during compiles and thus necessitates me to run a git clean.

**Comment by LADSoft** [comment]
hm I'm not seeing  that.   And shouldn't, since I think when the file gets opened it gets tagged 'delete on close'...    but I think that that was an evolutionary dead-end anyway so I'll back out of the change in a minute.
