### ISSUE TITLE
orc 6.0.50.1 access violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#638]
~~~
Access Violation:(D:\orangec\bin\orc.exe)
CS:EIP 0023:0048553B  SS:ESP 002B:0019D5F8
EAX: 0000004C  EBX: 0019F120  ECX: 0000004C  EDX: 00000000  flags: 00010202
EBP: 00000001  ESI: 00000000  EDI: 0019F120
 DS:     002B   ES:     002B   FS:     0053   GS:     002B


CS:EIP  8B 00 FF 10 59 8B 44 24 04 50 E8 10 15 FB FF 59
~~~

To reproduce:
* checkout https://sourceforge.net/p/gnucobol/code/HEAD/tree/branches/gnucobol-3.x/
* execute build_windows/maketarstamp.ps1 (or just create/copy tarstamp.h from an older version)
* copy build_windows/config.h.in to build_windows/config.h
* open build_windows/ocide/cobcrun.exe.cpj
* make the project

[as an alternative to doing steps 1+2 it _should_ work to just get a [nightly prepared source zip](https://ci.appveyor.com/api/projects/GitMensch/gnucobol-3-x/artifacts/gnucobol-3.2-dev_win.zip?job=Image:%20Ubuntu2004), but I haven't 

You'll see the access violation (and I've _once_ seen OCIDE crash directly afterwards, on further tests it stayed open).

Is this related to #547?

**Comment by LADSoft** [comment]
ok i got ocide set up again...  the crash is unexpected it should be generating an error.    I will fix that but in the meantime wanted to comment this is related to #547, the error is that it doesn''t like the enumerations you've put in common.h (for example on line 805)
