### ISSUE TITLE
occ -w does not prevent warnings from ocpp

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#642]
~~~
 occ testlink.c -! -I ../.. -lmpir -w
Warning ..\..\mpir.h(48): __need_size_t macro redefinition changes value
~~~

Side questions:

1. How could we suppress that single warning?

2. Why is there a redefinition change? The only occurrences of the macro definition I've found in this repo are to 1, which should be the identical value

```c
#define __need_size_t  /* tell gcc stddef.h we only want size_t */
```

**Comment by LADSoft** [comment]
there were previous isues with redefinition issues which I cleaned up over the last few months...   if it is still an issue you can reopen this.
