### ISSUE TITLE
Could the link phase try both some.l and libsome.l?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#645]
If I remember correctly GCC on Windows will, when `-lsome` is specified first try `libsome`, then fallback to `some`. If both are not found as import/static libraries it will fall back to search for `libsome.dll`, then `some.dll`

It would be nice if OrangeC could also try the "lib"-prefix (if not first, then as a fallback), as it removes the need to rename a bunch of libraries.

Note: this is _different_ from speechifying the name on the command line - for example `some.a` or `some.dll` will only be used "as-is".

Note2: it would be really nice to get the GCC feature "can directly link against dll's", too (internally creating an import library with `oimplib -C` on the fly).

**Comment by GitMensch** [comment]
Friendly ping @LADSoft

**Comment by LADSoft** [comment]
yeah i will look at the main issue...   split the other one out so I can do it later on :smile:
