### ISSUE TITLE
Should we remove STLPort due to not being tested in quite awhile or should some other action be taken related to it?

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#649]
This is just a theoretical question about what should be done, removing STLPort could clean up the repository greatly as I don't think there's been a build using it in years, and since it's so untested there might as well be no support for it....

Any thoughts on the matter?

**Comment by LADSoft** [comment]
good idea, probably should have gotten rid of it a long time ago as frankly it is buggy (that was why I moved to libcxx).   I'll do it here in just a bit...

**Comment by GitMensch** [comment]
Wow, so much deletions :-) Did I understood it correct that this won't save any time on the actual build (so only on the checkout)?

**Comment by chuggafan** [comment]
Ye, this is only a checkout fix, but it does mean that there's less stuff in a git checkout, which is nice.

Might be a like. 0.0000000000000001% speedup on account of not having to parse the makefile for the STLPort info.
