### ISSUE TITLE
tags gone banana, release notes missing

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#653]
v6.0.51.2   21 hours ago   7119d3e
v6.0.51.1  21 hours ago    a50863f
Orange-C-v6.0.51.2   21 hours ago   7119d3e
Orange-C-Orange-C-v6.0.51.2   21 hours ago  7119d3e 
Orange-C-Orange-C-Orange-C-v6.0.51.2    21 hours ago  7119d3e

@LADSoft 
Can you please delete the additional tags "Orange-C-Orange-C-Orange-C-v6.0.51.2" and "Orange-C-Orange-C-v6.0.51.2" and add actual release notes to https://github.com/LADSoft/OrangeC/releases/tag/Orange-C-v6.0.51.2 ?

Thanks!

**Comment by LADSoft** [comment]
I don't know why appveyor was going bananas but I finally shut it down...   I still have to do the release notes manually and just hadn't got there yet lol!    Will look at it now...
