### ISSUE TITLE
Adding __mm_pause to the backend

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#657]
The reason I'm creating this as an issue is that even with the documentation touching the x64.adl system is... interesting...

I specifically know that currently the `pause` instruction is unsupported by the infrastructure, and what I'd like to do is use this to do spin-wait loops in an upcoming job-server patch ever so-slightly more efficient. But I can't add the intrinsic to the code if the instruction quite literally does not exist, after all.

I *THINK* something like `<Opcode Name="pause" mand="" op="0xf3:8 0x90:8" Class="sse2"/>` is *close* to what I want based off of the opcode documentation [here](https://www.felixcloutier.com/x86/pause) but I'm not quite sure

**Comment by LADSoft** [comment]
when you say _class="sse2"_ what you are saying is that it has some set of operands as specified for that class.    But PAUSE doesn't have any operands.   What you want to do for pause is probably use _class="single"_.   Probably you could model it after the code for mfence or sfence...

**Comment by chuggafan** [comment]
I *THINK* your suggestion did the trick but I can't tell because there's a lot more linker pollution around than I thought...

Hopefully the op is correct...

**Comment by LADSoft** [comment]
you can use oasm/b to get a binary file with just the instruction in it...

**Comment by chuggafan** [comment]
Just got around to checking since it was hard to find an easy way to just dump the two bytes:

Seems to work(?) is the answer, so once #658 is merged this issue should be over.

Technically this is also related a bit to #304  so I'll tag that here...
