### ISSUE TITLE
Question re: design of OMAKE

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#659]
I'm trying to do a big redesign of the multithreading for OMAKE, and I keep seeing the processIDSemaphore that exists in the OS system, I know this is used intra-process for the executing process ID list, but I don't see where this gets used outside of being a (somewhat jank) inter-process mutex for an intra-thread item, is there something I'm missing with the design of this or am I able to swap this over to an internal mutex for better compatibility with GNU Make?

**Comment by LADSoft** [comment]
omake spawns itself; there is a named sem shared between all instances of omake that prevent it from starting too many non-omake subprocesses.   So yeah it is used internally, but at the same time it is not used internally because of the multiple running omake instances.

**Comment by chuggafan** [comment]
I meant the processID semaphore, called `processIdSem`, which only seems to guard the static `std::set` of process IDs, this isn't an interprocess communication as far as I can tell, so am I OK to just make `processIdSem` a mutex since it only has a max of 1 user at a time?

**Comment by LADSoft** [comment]
the environment variable .OMAKESEM holds the semaphore name for a recursive set of calls to omake.   It is initialized by the top level omake and passed through the environment to recursive calls to omake.   Line 246 of os.cpp opens a named semaphore with that name (which is shared by the recursive set of calls).   So I think the semaphore is shared by different invocations of omake, and turning it into a local mutex wouldn't work so well.

**Comment by chuggafan** [comment]
Different question this time: I see that the print directory stuffs is handled in the JobInit function, and I can kind of understand that there's a file that's temporarily created (somehow). [_tempnam](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tempnam-wtempnam-tmpnam-wtmpnam?view=msvc-170) is used, so presumably there's a blank directory this temporary file is located? 
Why is this in the JobInit section, what can I do to move it out of the JobInit function, and how can I stop it's reliance on the OMAKE semaphore server name and have it be called something else so that I can begin a move to a more GNU make compatible version?

**Comment by LADSoft** [comment]
tempnam uses the path found in the TMP environment variable if there is one, or else it uses the first argument to tempnam.   In this case if TMP doesn't exist it would use the current directory.   But it makes up a random file name...   I think @GitMensch pointed out there is a better alternative than using tempnam but I haven't looked into that.

it looks like JobInit can be called multiple times...   we could move a lot of stuff out of it though, looks like everything except the semaphore creation is a good candidate for that.   Might even be able to move the semaphores out as well, depending on how much work you want to do.

Meanwhile the print dir stuff also has to share a file between multiple omake invocations, apparently, and it is doing that by reusing the same unique id being used for the semapahore names.    It also is used only once per omake invocation...   I would suggest moving everything except the semaphore creation to right before line 665 in MakeMain.cpp, (the RunCommands line) and passing the unique name created with the rng down into JobInit where the semaphores are created...

**Comment by chuggafan** [comment]
Cool, for now I'll move it out to where you said, the only issue is that I'm currently planning on a massive port for POSIX systems that involves changing out of named semaphores in their entirety, because of the same comments that plague semaphores.h showing that our current system is broken on non-windows
https://github.com/LADSoft/OrangeC/blob/19a572683fd3549ae985fd8e004e14c5c72fafc7/src/omake/semaphores.h#L8-L9
In order to fix this, I'm using the jobserver creation tactic used by [GNU Make, as documented here](https://www.gnu.org/software/make/manual/make.html#Job-Slots).

When switching over to this style of make-system, you can no longer guarantee that there's a "string" that has a valid filename being passed there, as on windows SHORTPATHS that contain commas are invalid, possibly causing issues later down the line.
I *THINK* that the system I'm devising will accept the current JobsInit scheme even if it gets called multiple times due to the fact that I'm switching over to using:

a `std::shared_ptr<JobServer>` that handles everything,
when a new `JobServer` is created, it opens the handle to the Semaphore, since we still keep track of how many jobs we have and how many are left, this is fine since we are just *opening* the semaphore, instead of creating a new one.
so this will be unaffected by the closing and opening since we're still holding onto a reference of the original, just the reference comes from a different place.

My plan also comes with moving the naming scheme out of JobsInit and *into* the JobServer, so that the JobServer can also generate the exact command that we need to pass through to other instances of itself

I should probably open an issue, link this, and close this, but I've been working on this fairly silently to be quite honest, and need feedback in order to determine how my steps to move everything around will continue.
