### ISSUE TITLE
Is there a verbose mode showing different stages of compilation / invoked executables?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#66]
On investigating #64 I wanted to see how `olink` is invoked by `occ`, but I didn't found an option for this in `occ /h

GCC has `-v                       Display the programs invoked by the compiler.`

Note: GCC is *very* verbose when using `-v`, ideally occ has something like "verbose levels", something like

`occ /v                        Display the programs invoked by the compiler.`
`occ /vv                       Display the programs invoked by the compiler and internal specs.`
`occ /vvv                      Display the programs invoked by the compiler and internal specs of compiler and programs invoked.`

(the second and third may be combined in a single "very verbose" option).

**Comment by LADSoft** [comment]
I added -y and -yy for the compiler, all they do though is show what programs are being run.   If you want to leave it open I'll get back to it later when I've gotten through the other issues.

**Comment by GitMensch** [comment]
Request for `-yy`: show return code of invoked process, too.
