### ISSUE TITLE
Add separate demangle program to demangle input

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#664]
#660 for discussion on why this should be done
The way I envision this is two ways:
one is just an input and output, the other way we can also take a file that has a list of inputs and output that, if the input is blank, we just take a stdin until an input termination command (IIRC it's ctrl+d on UNIX) and output the value after that.
IIRC there's programs similar such as C++filt, and their interface we may want to take a look at before continuing with such a project

**Comment by LADSoft** [comment]
So I now put demangled names in the map file, the assembly outputs, etc...   this isn't much needed because of that so I'm closing it.
