### ISSUE TITLE
OMAKE optional -j number

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#665]
Currently with OMAKE using -j without any value after it results in a crash with an... interesting... error code:
`250588109`, which according to microsoft, doesn't exist since `EEFABCD` isn't an error code in their system.
What I want to do is to allow for a default value of hardware_concurrency (aka have the make system select the number of jobs we're allowed).

I'm putting this as a separate issue but will still link in #660 as I will be attempting to debug this whether I like it or not, my only problem is that I do not know how the command system works precisely, so I may need some additional help there.

**Comment by chuggafan** [comment]
Found the cause of the issue: calling stoi with a null string causes big issues, and trying to do -j without an argument gives us an error because there's a required argument, what should be done is a system to create an optional argument, but I don't see that as an option in this command setup...

**Comment by LADSoft** [comment]
well CmdSwitchInt allows specifying a default value in the constructor, apparently, so I think if it doesn't let you do without the value that is a bug.     Likely I introduced it when adding support for using the ':' character...
