### ISSUE TITLE
Can OrangeC utilities like oimplib be used standalone from OrangeC?

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#670]
Could I just extract it from the OrangeC distribution and use it as a standalone tool?

**Comment by GitMensch** [comment]
Yes, but some things will only be useful together with the OrangeC environment - like oimplib that creates an import library for the OrangeC linker - but for extracting other things like a def file - sure.
Just remember that those tools likely use other parts like dlls from the distribution - but you can always copy those, too.

**Comment by LADSoft** [comment]
As it is, none of the files in the distribution rely on other dlls.   Some of them do rely on data files though, for example olink has two data files required for the windows platform.    It also calls into DLPE to make a final executable... and the three occ executables are of course interwoven.   But specifically oimplib doesn't have dependencies other than as GitMensch pointed out it is heavily tied into the object file format...     the only things I can think of that are totally divorced from the rest of the project are ORC, OMAKE, and OGREP.

**Comment by 3oheicrw** [comment]
> As it is, none of the files in the distribution rely on other dlls. Some of them do rely on data files though, for example olink has two data files required for the windows platform. It also calls into DLPE to make a final executable... and the three occ executables are of course interwoven. But specifically oimplib doesn't have dependencies other than as GitMensch pointed out it is heavily tied into the object file format... the only things I can think of that are totally divorced from the rest of the project are ORC, OMAKE, and OGREP.

You could think about making standalone versions of ORC, OMAKE and OGREP.

Does the compiled resource by ORC be compatible with other compilers? I mean MinGW GCC which uses windres and GoRC, too. If it's compatible then it's no reason to not make a standalone version of it. Other project could grab and use this standalone ORC, like they use GoRC.

**Comment by LADSoft** [comment]
yeah ORC makes .RES files, which will work fine at least for 32-bit compilers.   Never looked into what happens with 64-bit ones...

My problem is that while the executables are mostly independent of each other, there are a lot of interdependencies in the source code.   I don't want to make more github projects which are all mostly the same code base....

**Comment by LADSoft** [comment]
i added ORC and OMAKE as separate repositories now
