### ISSUE TITLE
OMAKE: adding target-specific variables

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#671]
https://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html

Target specific variables at first, seem highly situational, but recently I actually ran into a situation where target specific variables are a way for ensuring that targets generate variables correctly, let's take a situation like so:

```Make
Generated_variable_config.cfg:
    Do something

Create_variable_config: Generated_variable_config.cfg

Uses_variable_value: private VALUE=$(shell cat file | grep regex)
Uses_variable_value: export USES_VAL=-DSomething -DUSES_VAL=VALUE
Uses_variable_value: Create_variable_config
# do stuff
```

Something important to note here is that `VALUE`, created as a private variable in Uses_variable_value is generated *AFTER* Create_variable_config, which is extremely useful so that you can generate CFLAGS and the like on the fly from a different script

**Comment by LADSoft** [comment]
yeah that looks like an interesting thing to do... and I don't think it would be too hard either.     Don't know that we should touch it while you've got omake up on blocks though...
