### ISSUE TITLE
Question about '__VERSION__'

### ISSUE THREAD

**Issue by gvanem** [LADSoft/OrangeC#672]
Trying the info at https://orangec.readthedocs.io/en/latest/occ/OCC%20Defining%20Macros/
in a simple program: 
```c
printf ("%d.%d.%d.\n", __ORANGEC_MAJOR__, __ORANGEC_MINOR__, __ORANGEC_PATCHLEVEL__);
printf ("%s.\n", __VERSION__); // always defined, rendition of the major/revision/minor/build as a string
```
gives me:
```
6.51.2.
6.0.51.2.
```

And `occ -V`, also gives `Version 6.0.51.2`.

So where does the `.0` part (revision?) come from? AFAICS, there is no built-in for it.
And IMHO it's strange it's not the value of the minor version.

**Comment by LADSoft** [comment]
the __VERSION__ is compatible with windows version strings....   second octet is always 0 though as orangec only uses major/minor/revision.    It is directly derived from the  constants in "orangec\src\version.h".   I think the other macros are also derived from version.h in a more indirect way...    maybe I should add the missing octect as its own macro...

**Comment by gvanem** [comment]
Ok, fine. Closing.
