### ISSUE TITLE
`omake -nolog`  difference to `nmake -nolog`

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#673]
Obviously no priority at all, just want to report that there's something strange.

```
> nmake -nologo -f test.mk
target executed
> omake -nologo -f test.mk
target executed

> nmake -nolog -f test.mk
target executed
> omake -nolog -f test.mk
> echo %errorlevel%
0
```

its seems that there is an error because of unknown "nolog" options (`omake --help` doesn't show `-nologo` but that seems to be skipped) - and it isn't showed by message + error code.

Tested with omake 6.0.50.246 and  6.0.51.2

**Comment by LADSoft** [comment]
there are several switches that start with 'no' and there is also a -n switch.    So it will display an error now...
