### ISSUE TITLE
omake from stdin does not work (gmake compatibility)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#674]
Rechecked with latest release, the "omake has issues to parse Makefiles from stdin" mentioned in https://github.com/LADSoft/OrangeC/issues/56#issuecomment-455820937 is still the same.

Given the following Makefile.tst:

```Makefile
SHELL = /bin/sh

stuff = a b
$(stuff):
	@echo $@

testme: $(stuff)
```

~~~
$ omake -! -f Makefile.tst testme
a
b
# all fine - same result as GNU make

$ omake -! -f Makefile.tst
a
# no "b" - same result as GNU make

$ cat Makefile.tst | omake -! -f - testme
Error: No rule to make target 'testme'
~~~

As it isn't actually related to the original error and we have now 101 comments in this issue I'm moving it out to a new one.

_Originally posted by @GitMensch in https://github.com/LADSoft/OrangeC/issues/56#issuecomment-1114697728_

**Comment by LADSoft** [comment]
fixed.
