### ISSUE TITLE
Correcting typo in readme (minor)

### ISSUE THREAD

**Issue by PDWhittington** [LADSoft/OrangeC#677]

**Comment by GitMensch** [comment]
Sounds good, which one?

**Comment by PDWhittington** [comment]
I was going to do a PR and link back to the issue but discovered I don't have perms (which is fine).

In readme.md you have "retarged" which should be "retargeted". Sorry -- rather pedantic now I'm forced to articulate it :-)

Great work on this compiler by the way -- I'm excited to try out the compiling of sqlite to .Net :-)
