### ISSUE TITLE
occ: allow values for /o /L /I to be used as separate options

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#68]
Currently working: `occ /oTest.exe test.c`, `occ -oTest.exe test.c`.

Adding support for `occ -o Test.exe test.c` would be good as it allows to be used with existing Makefiles build with GCC as target, too. Currently results in `Fatal error: Cannot open input file Test.exe`

Similar for `/L` (also applies to `olink`) and `/I`.

**Comment by LADSoft** [comment]
I changed various options in the tools that were referring to file names, to allow either behavior.   If a space immediately follows the switch it will use the next argument.

**Comment by LADSoft** [comment]
the libvorbis test tests with a space between /I and include path which is a test of the compiler; the main project make files have been adjusted for each sub-invocation of omake, to have a space between the -f switch and the file name which is a test of the rest of the project.   The latter change did isolate a hard to find bug that was found when compiling with MINGW64
