### ISSUE TITLE
Could people develop commercial/proprietary software with OrangeC?

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#680]
Most compilers out there even though themselves are in GPL have exceptions to make it's possible to use for commercial/proprietary software development (linking exception?). Please correct me if I was wrong, but I think OrangeC is using the vanilla GPL without adding such exceptions? This make any programs compiled by OrangeC (and of course linked with OrangeC runtime) have to be licensed under GPL too (and thus open sourced).

https://en.wikipedia.org/wiki/GPL_linking_exception

**Comment by LADSoft** [comment]
yes there is an exception; the libraries can be freely linked with propriatary code and you can release without releasing the source code.    It is at least in the comments for all the library source code...  I will leave this open to remember to check the licensing documentation to make sure it is spelled out there as well

**Comment by LADSoft** [comment]
I updated the licensing documents to reflect the exception now.

**Comment by GitMensch** [comment]
> I updated the licensing documents to reflect the exception now.

Where? Can you please reference the commit?

**Comment by LADSoft** [comment]
looks like it was done as part of this commit: e33cf9ac4308c4d86309ba6275c9e957b613d3e6
