### ISSUE TITLE
Rewrite OCC symbol tables

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#683]
The OCC Symbol table processing is one of the biggest single remaining uses of CPU time.   It averages between 5 and ten percent of the compile time for typical C++ programs found in the project and is sometimes the biggest single usage outside of new/delete.   It may be that reworking the code to use for example unordered_map instead of iterating through lists speeds it up a bit....  I'm not really sure how much that could be since a lot of the time looking for symbols would be for structure members and there is already a small acceleration for that.   But at least this kind of development would take us down the road of modernizing the source code a bit which is another of the very long-term goals...

@chuggafan you are welcome to work on this if you want.   I can write documentation about the symbol tables and the various use cases for them if you are interested.   It isn't quite as easy as simply plopping in an unordered map everywhere there is currently a symbol table, unfortunately.

But I don't think this is a huge project, given how contained everything related to it is.

**Comment by chuggafan** [comment]
Is this the ocpp symbol table you're talking about or the OCC symbol table or any number of other symbol tables involved in this? The latter is much, much more involved than the former (which is used effectively just for defines)... AKA is this the SymbolManager or the SymbolTable? I think it's possible to modify some of it to provide better stuff (that hash function stuff looks gnarly), I think if we optimized a lot of our string handling more I think we'd see a lot of performance gains as well, mangling is a fiesty process it seems and it's particularly horribly contained.

**Comment by LADSoft** [comment]
I think I wouldn't touch mangling, because, long term we wanna go to the MS mangling/unmangling throughout the projects.   Which I think is another relatively contained & easy project if you want to take it on as I believe there is source code available as part of the libcxx abi library to ease that process...   at least for the unmangling portion...  honestly i wouldn't be surprised though if there was an existing library on github somewhere that we might just be able to appropriate :smile:

anyway I was thinking only occparse.exe would be touched right now,  specifically a rework of the SYMLIST/HASHTABLE workings throughout.   That because occparse is one of the programs that is still way out of date language-wise, and it is also the program in the suite that will most benefit the most from any speed optimizations we can give.

As far as string handling optimizations, I'm open to suggestions.   That one string change I checked in for SetChars() in OASM cut about a minute off the build time of the assembly language build, on my computer...   that was a change of like 5%...   so I'm all for optimizing string stuff just not sure how to go further with it...

**Comment by LADSoft** [comment]
so the symtab branch has the final version of this; along the way I rewrote the inlining support for much better code gen (the compiled code runs faster) and reworked the mechanism for instantiating templates so that the compiler doesn't have to compile as much code to get to an output file...   resulting in faster compiles and smaller object files.
