### ISSUE TITLE
inline function parameters optimization

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#688]
Right now, function parameters are spilled to memory during inlining.   Improve this so that when possible, the values can be kept in temporary registers.

**Comment by LADSoft** [comment]
i took a side trip and did this one.   occ seems faster at least to me...  I do notice that with all the changes that have been made recently OCCIL is noticably faster at compiling the cc386 compiler though.

I forgot to tag what i was doing, so here here are the various checkins that go along with this issue.   It took longer than expected because the more optimized use of registers brought out a lot of other compiler bugs that I had to fix along the way...

5e2f5afa5c2c4687f32c234577a9f8b4ccd1d326
cde6a7b953aafa6b4e2dbc4eb75520435446b40c
973df1fc22fd4e19c45eff279fb94c8e310246fd
57ef509009a01cebddfeb18f77911f04473eab89
150a8273aab63c7de735a9892cc95ccf81e12fc5
07466d73fe49b4022f6169abf300876f303dca3d
d0ac15ff96e24e10a09f92bb496bcaecff972c03

**Comment by GitMensch** [comment]
That sounds like a good time for a new release (last Nov 2021); otherwise: Is there any plan for a release, maybe after #559 is finished?

... maybe inspecting a run of #168 to use another testsuite with the current version before a release? Just asking....

**Comment by LADSoft** [comment]
I had planned to do it after #559 is complete, but, that could be a while yet so maybe you are right maybe we should have a release now as there have been substantial changes over the last ten months...   yeah redoing #168 sounds like a good idea, been quite a while since we've done that one :). 

So after I look at a minor bug I've seen, I'll redirect my efforts to rerun #168 then when that is ready we can have a release.
