### ISSUE TITLE
add option "/V" (version information)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#69]
Using this option currently shows all command line options (likely because it is unknown) - it would be nice to have an option to *only* show the version of the tool call (tested `occ`, `olink`, `omake` - the feature request is about all tools`, even `ocide`).

**Comment by LADSoft** [comment]
Added /V throughout.   It displays the banner, and the time/date of the build.

**Comment by GitMensch** [comment]
Looks very good. Is it confusing/bad to *also* do this when `--version` is used?
Depending on the answer this issue can either directly be closed or after the long option is added.
