### ISSUE TITLE
Does OrangeC able to build itself yet?

### ISSUE THREAD

**Issue by jpgpng** [LADSoft/OrangeC#692]
In other words, does OrangeC self-hosted yet? So far I only see makefiles to use other compilers to build OrangeC.

**Comment by GitMensch** [comment]
I'm nearly sure that the answer is yes.
The CI build on appveyor has the following definition: https://github.com/LADSoft/OrangeC/blob/master/appveyor.yml - it runs [build.bat](https://github.com/LADSoft/OrangeC/blob/master/src/build.bat) which does multiple different compiles using OCC and OCCIL.

**Comment by jpgpng** [comment]
@GitMensch Wait a minute. This build.bat seems have nothing to do with use OCC to build OCC at all. I only see options to build OCC with other compilers. The OCC and OCCIL sections on it seem to be the things to be built not that them were used to build :confused:

**Comment by LADSoft** [comment]
Yes OCC does build itself; it gets tested multiple times on appveyor with every check in.    The way to do it is provide the following define when using omake to run the make script:  /DCOMPILER=OCC.   This will invoke the make rules in occ.mak, which will compile and build occ with itself.   Of course you have to have previously built OCC with another compiler to do that...

If you run build.bat, it will compile OCC (usually with MSVC unless you change the script) then it will use that version of OCC (built with MSVC) to build another version of OCC.   The resulting OCC that is built with itself is then built again with the new binaries so you have an OCC built with itself building an OCC with itself...   And then the binary outputs from steps two and three are compared to make sure the behavior is the same for both versions...

We also perform the same tests when compiling via assembly and compiling with debug info, although the latter tests are running out of time on appveyor right now...
