### ISSUE TITLE
Add OrangeC to cmake compilers collection

### ISSUE THREAD

**Issue by pwd96m4a** [LADSoft/OrangeC#700]
I will not remember the switches for OrangeC and so do many others I think. Just GCC/Clang's switches are more than enough. So adding OrangeC to cmake compilers collection (in other words, add OrangeC support to cmake) will really help the adoption of OrangeC. This work the compiler vendor should do themselves. As I recall, a Pelles C user asked on cmake's forum to add Pelles C support and the cmake guys promised to do so. It's many years now but Pelles C is still not yet supported. There is no Pelles C on this list: https://github.com/Kitware/CMake/tree/master/Modules/Compiler The same will be for OrangeC if you don't do the pull request yourself. BTW, they are on gitlab. The github repo is just a mirror.

**Comment by LADSoft** [comment]
this is basically the same thing as issue #603.   Thank you for the feedback though as it is helpful to know what to prioritize.

I'll work on these early in the next milestone...   timing will depend on how much trouble I have getting through the remainder of #559

**Comment by pwd96m4a** [comment]
I will close this issue as it duplicated with https://github.com/LADSoft/OrangeC/issues/603
