### ISSUE TITLE
trunk/src/dos/infopad/esl.cpp:59:13: error: Mismatching allocation and deallocation

### ISSUE THREAD

**Issue by dcb314** [LADSoft/OrangeC#703]
Source code is

            delete items;
            count = wParam;
            items = new statusItem[count];

Maybe better code

            delete [] items;
            count = wParam;
            items = new statusItem[count];

**Comment by GitMensch** [comment]
All those de-allocation mismatches would be good to have combined as a single PR. Could you do this, please?

Just out of interest: Did you run Orange compiler/runtime with valgrind (that commonly points out those, but not sure about its state on DOS), did you run a static analyzer or "inspected manually"?
