### ISSUE TITLE
add runtime checks

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#708]
use a compiler
OrangeC 6.0.61.1
     occ /O0 (failed)
     occ /O1 (pass)
    occ /O2 (failed)
mingw-w64 8.5
    gcc -O1 (failed)
    gcc -O2 (failed)
    gcc -O3 (pass)

Example from a long time ago when I was learning C
(I'm not a programmer, just enjoy watching)
Poor English, the above is from Google Translate

[test.zip](https://github.com/LADSoft/OrangeC/files/9646580/test.zip)

**Comment by LADSoft** [comment]
I think the way 'c1' is used, it invokes undefined behavior.   I think we are looking at buffer overruns and potentially uninitialized memory...

**Comment by GitMensch** [comment]
... which would also explain why it "may work/break different in different optimization levels".

Ideally the compiler or runtime checks of OrangeC return something reasonable when compiled with debug info.

**Comment by LADSoft** [comment]
well....   that is typically done with a runtime check.   OrangeC doesn't do that though...

**Comment by GitMensch** [comment]
Shouldn't these two options referenced in the changed documentation (or more) be use in the compiler wrappers?

**Comment by LADSoft** [comment]
I couldn't find relevant options for GCC...    are there any?    There are probably options for cl.exe though...

**Comment by chuggafan** [comment]
The relevant similar options in GCC are the sanitizer options, `-fsanitize`, which uses [santiziers](https://github.com/google/sanitizers/wiki/AddressSanitizer), which do a lot of similar functions, I did mention sanitizers in... #572 but that was a while ago.

**Comment by LADSoft** [comment]
the closest thing I see is a sanitizer that checks for uses of a variable once its scope has exited, don't see anything specific about using it without assigning it first or bounds checking on the stack...

**Comment by chuggafan** [comment]
bounds checking on the stack might be `ubsan`, there's like, 10 different sanitizers, most not supported on windows, and they all do different things.
