### ISSUE TITLE
Structure _stat64i32 is not defined

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#711]
@chuggafan

**Comment by 44iCdnz** [comment]
Could workaround by `#define _stat64i32 _stat`

**Comment by GitMensch** [comment]
Shouldn't this be defined in general?

**Comment by LADSoft** [comment]
yeah the workaround should work, although it leaves you with a 32-bit time instead of a 64-bit time.    But orange c doesn't support 64-bit time_t yet...    I'm going to reopen this so I remember to implement this family of functions, and 64-bit time_t.

Thanks!

**Comment by 44iCdnz** [comment]
> yeah the workaround should work, although it leaves you with a 32-bit time instead of a 64-bit time. But orange c doesn't support 64-bit time_t yet... I'm going to reopen this so I remember to implement this family of functions, and 64-bit time_t.
> 
> Thanks!

For MSVC, as the document on MSDN said, _stat is 64 bit, stat without the underscore is 32 bit.

**Comment by 3oheicrw** [comment]
@LADSoft Is this fixed or not? If it's fixed then please close this issue. The OP deleted his account and it seems he no longer care about it.

**Comment by LADSoft** [comment]
this is fixed as of today.
