### ISSUE TITLE
Command line tools: support using - for parameters like other compilers

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#712]
Even MSVC's cl.exe now supports this. But from this screenshot it seems OrangeC still not, it still expecting /

https://github.com/LADSoft/OrangeC/issues/710#issuecomment-1279603984

**Comment by LADSoft** [comment]
Orange C will do it either way.    It supports / because that is a common windows thing, but it also supports -.

**Comment by 3oheicrw** [comment]
> Orange C will do it either way. It supports / because that is a common windows thing, but it also supports -.

What do you think about `-!` option? I think `/!` is more natural. BTW, IMO they are both bad. Why don't just `-nologo` and `/nologo` like MSVC? Using `!` here is a bit awkward. I don't know why you decided to do it like this.

**Comment by 3oheicrw** [comment]
Anyway, this issue should be closed too. The OP already has the answer he wanted, but it seems he no longer care about it.
