### ISSUE TITLE
Emulating popular compilers

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#713]
I know about it from OpenWatcom: https://github.com/LADSoft/OrangeC/issues/710#issuecomment-1279603984

On the binnt folder, you could see various binaries emulating popular compiler (cl.exe for MSVC, owcc for GCC). It really helps adoption, as people no longer have to rewrite their build scripts from scratch. Please consider at least emulating GCC (the binary should be gnucc to not conflict with gcc if both OrangeC and GCC are in PATH).

**Comment by LADSoft** [comment]
@GitMensch suggested this a while back too...   I still haven't gotten there :smile:

**Comment by 3oheicrw-alter-ego** [comment]
> @GitMensch suggested this a while back too... I still haven't gotten there smile

What about something like this https://github.com/swig/cccl used in conjunction with this https://github.com/LADSoft/OrangeC/issues/722?

**Comment by LADSoft** [comment]
there is also https://github.com/rofl0r/pellescc

**Comment by LADSoft** [comment]
this is done now.

**Comment by GitMensch** [comment]
> this is done now.

partly, we don't have a wrapper for cl.exe and link.exe, do we?
