### ISSUE TITLE
Windows API headers?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#714]
It seems, there is none?

**Comment by 44iCdnz** [comment]
Could I take TCC's winapi headers and use it?

http://download.savannah.gnu.org/releases/tinycc/

**Comment by 44iCdnz** [comment]
This seems to be newer: https://github.com/lifenjoiner/MinGW-w64-tcc

**Comment by GitMensch** [comment]
What about the official Windows SDK?

**Comment by 44iCdnz** [comment]
> What about the official Windows SDK?

It's MSVC only? If you could make it work with OrangeC.

**Comment by LADSoft** [comment]
It does have windows headers.    They are derived from a very old GNU project...    a little bit incomplete and they don't quite handle 'UNICODE' the right way, but they are there.

**Comment by 44iCdnz** [comment]
> It does have windows headers. They are derived from a very old GNU project... a little bit incomplete and they don't quite handle 'UNICODE' the right way, but they are there.

What about updating it?

https://github.com/LADSoft/OrangeC/issues/715

**Comment by GitMensch** [comment]
It is only a question of available time.

I'm sure that a PR of yours would be merged and heavily reduce the TTM for this one.

**Comment by 44iCdnz** [comment]
> It is only a question of available time. I'm sure that a PR of yours would be merged and heavily reduce the TTM for this one.

Check this first: https://github.com/LADSoft/OrangeC/issues/715

**Comment by LADSoft** [comment]
we had been thinking about using mingw's version.      Unfortunately I only have so much time and there is a lot that needs doing...   TBH this isn't a high priority compared to a lot of other issues I want to deal with....   I would prioritize it if I were getting a lot of demand for that but really I'm not getting feedback that says anyone cares.   But the current headers work well enough for general use although like I say they are a little out of date and don't conform to the standard microsoft set for 'UNICODE'. 

Thanks

**Comment by 3oheicrw** [comment]
@LADSoft this issue should be closed.

**Comment by LADSoft** [comment]
the pelles windows headers are now being used.
