### ISSUE TITLE
Unable to use obj.h

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#716]
Here is obj.h: https://github.com/small-c/obj.h

I'm trying to compile main.c with occ /1 main.c : https://github.com/small-c/obj.h/tree/master/tests/animal

Error(135) obj.h(278): Lvalue required
1 Errors

**Comment by LADSoft** [comment]
I duplicated the issue with a simple test program.   I'll fix it when I've finished vetting your other issues :)

**Comment by LADSoft** [comment]
so i fixed this at the same time as #718

**Comment by 3oheicrw** [comment]
> so i fixed this at the same time as #718

Does the obj.h examples compiled fine? I'm not at home so I can't test.

**Comment by LADSoft** [comment]
I didn't try this explicitly with the link you gave me...   but it seemed obvious what the problem was (a pointer to a structure was returned and an attempt was made to modify the structure) and I did test a fix for it.

**Comment by 3oheicrw** [comment]
> I didn't try this explicitly with the link you gave me... but it seemed obvious what the problem was (a pointer to a structure was returned and an attempt was made to modify the structure) and I did test a fix for it.

Please have a look at this test: https://github.com/small-c/obj.h/tree/master/tests/win32_app

Other tests compiled fine, this is not.

**Comment by LADSoft** [comment]
I fixed this one now.   It had compiled (with the latest win32 headers) but it didn't run properly.   Had to fix #pragma pack...
