### ISSUE TITLE
So many errors compiling a sample project

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#718]
This is the source: https://github.com/TheRealMichaelWang/cish/tree/main/src

This is my build script:

```
@ECHO OFF

occ /c ast.c
occ /c compiler.c
occ /c compiler.h
occ /c debug.c
occ /c error.c
occ /c ffi.c
occ /c file.c
occ /c hash.c
occ /c machine.c
occ /c machine.h
occ /c postproc.c
occ /c postproc.h
occ /c scanner.c
occ /c scanner.h
occ /c source.c
occ /c stdlibf.c
occ /c type.c
```

**Comment by 3oheicrw** [comment]
I changed build script to compile in C11 and C99 mode, still failed. The most interesting error is "Initialization designator requires C99". As I compiled in both C11 and C99 mode but that error still spits out.

**Comment by LADSoft** [comment]
so i fixed the issues in this project, however, the compiled cish won't compile the examples.    I tried compiling cish with cl.exe and got the same results so I'm done with it for now....

**Comment by 3oheicrw** [comment]
> so i fixed the issues in this project, however, the compiled cish won't compile the examples. I tried compiling cish with cl.exe and got the same results so I'm done with it for now....

cish is an interpreter, how would you expect it to compile examples? The compiler of Cish language is Capote :smile:

**Comment by LADSoft** [comment]
hehehe....   sometimes when I look at other people code I have no idea how it fits into their ecosphere :smile:

**Comment by chuggafan** [comment]
> hehehe.... sometimes when I look at other people code I have no idea how it fits into their ecosphere 😄

You say that like it's normal to just know everything about a project you've seen for all of 15 minutes ;)

**Comment by 3oheicrw** [comment]
It seems this is not simply as modifying headers like https://github.com/LADSoft/OrangeC/issues/717 but it changed compiler code too. I will have to wait for a newer release to test it?

**Comment by LADSoft** [comment]
so yes it was a compiler change.    The checkin got built on appveyor and resulted in an install package; for your reference here is a direct link:

https://ci.appveyor.com/project/LADSoft/orangec/builds/45148254/job/pn664dyb2ooi74md/artifacts

**Comment by 3oheicrw** [comment]
> so yes it was a compiler change. The checkin got built on appveyor and resulted in an install package; for your reference here is a direct link:
> 
> https://ci.appveyor.com/project/LADSoft/orangec/builds/45148254/job/pn664dyb2ooi74md/artifacts

Hi. The page has an Ubuntu icon. So the binaries was cross compiled from Ubuntu I wonder?

**Comment by 3oheicrw** [comment]
Confirmed that it could build now.

**Comment by LADSoft** [comment]
the vm that appveyor uses might be ubuntu...
