### ISSUE TITLE
Failed to bootstrap gobo eiffel

### ISSUE THREAD

**Issue by ruanjiasing** [LADSoft/OrangeC#719]
This issue on the gobo eiffel repo is confirmed: https://github.com/gobo-eiffel/gobo/issues/58

The steps to reproduce:

- Clone gobo eiffel
- Set the `GOBO` environment variable point to the cloned directory
- Add `%GOBO%\bin` to `PATH`
- Create `occ.cfg` file with the content like the linked issue in `%GOBO%\tool\gec\config\c`
- Edit `%GOBO%\tool\gec\bootstrap\bootstrap.bat` to include his changes on the linked issue.
- On `%GOBO%` directory open a command prompt window and run `bin\install.bat occ`, you could run `tool\gec\bootstrap\bootstrap.bat occ` instead.

Update: or more simpler, just try to compile the sources file at `%GOBO%\tool\gec\bootstrap` with `occ`.

**Comment by LADSoft** [comment]
I verified that there are three missing #defines in the headers, I will add them later today :smile:

**Comment by LADSoft** [comment]
so it was easy enough to add the #defines, but unfortunately gobo uses wide character versions of various C functions so it fails on link.   I may not get to implementing them before this weekend...

**Comment by LADSoft** [comment]
this compiles now and the executable at least seems to run.
