### ISSUE TITLE
How to build OrangeC (Windows environment)?

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#724]
I have added MINGW64's bin directory to PATH. This document doesn't clear at all (it seems assumed MSVC):

https://github.com/LADSoft/OrangeC/blob/master/build.md

I followed it but it always resulted in errors (it's not even go to compilation steps, it failed almost immediately).

I found a batch script for MINGW64 (https://github.com/LADSoft/OrangeC/blob/master/src/mingw64compiles.bat), tried to run it but it also failed with errors. The Windows Command Prompt is not easy to copy the output of it here for you to see, doesn't like the MSYS2 Shell or Cygwin Shell (they are both used mintty).

**Comment by LADSoft** [comment]
i haven't tried building orangec itself from within the msys2 environment, maybe I will give it a try after a while.

the build files are designed for win32, as such the batch file eventually uses src/mingw64.mak.   It uses the name 'x86_64-w64-mingw32-gcc' for the compiler which is probably a windows-centric name, you might have to modify the mingw64.mak to use the name of the compiler as it exists on msys2.

**Comment by LADSoft** [comment]
I didn't realize this one was for windows.

There are several build scripts for different compilers.    The ones that get the most use are occ, mingw64, clang, and msvc.    Each has a corresponding .mak file (e.g. mingw64.mak for mingw64)

By default it compiles with msvc, to build the compiler/run time libs with msvc you would do:

        omake fullbuild

assuming the msvc install batch file has been run

To compile with mingw64 you would do:

        omake -DCOMPILER=MINGW64 fullbuild

and that will build the compiler and libraries and set everything up.    For this to work mingw64 must be on the path.

To compile with clang it is:

        omake -DCOMPILER=CLANG fullbuild

if you want to use build.bat, which is the script appveyor eventually runs to build the compiler three times in succession, you just have to know how to configure it.   on line 15 there is a line:

        set BUILD_PROFILE=MS

this selects the microsoft compiler.   If you want to use MINGW64 set it to:

       set BUILD_PROFILE=MINGW64
