### ISSUE TITLE
Build failed with MSYS2's MINGW64

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#729]
MSYS2's MINGW64 added to Windows PATH.

Command used https://github.com/LADSoft/OrangeC/issues/724:

` omake -DCOMPILER=MINGW64 fullbuild`

I can only capture the last errors:

![1s](https://user-images.githubusercontent.com/116574529/198210427-8a181b78-2ba4-4e9c-ad1d-90544aa07995.PNG)

![2s](https://user-images.githubusercontent.com/116574529/198210451-fcd719c0-89e9-4320-a37d-0c9710cda7ac.PNG)

![3s](https://user-images.githubusercontent.com/116574529/198210463-b2b78df2-cda3-4c99-87c1-d86a3a1b74b5.PNG)

**Comment by 3oheicrw-alter-ego** [comment]
I don't care anymore. Gave up.

**Comment by LADSoft** [comment]
in #723, I noted that there seems to be a bug in MINGW64s random header.   I don't see it here mostly because I've not upgraded since 8.1 of MINGW64, precisely because of problems like this.   I'm planning on seeing if I can find a workaround e.g. change #defines or something...

**Comment by 3oheicrw-alter-ego** [comment]
> in #723, I noted that there seems to be a bug in MINGW64s random header. I don't see it here mostly because I've not upgraded since 8.1 of MINGW64, precisely because of problems like this. I'm planning on seeing if I can find a workaround e.g. change #defines or something...

You don't have to play the game chasing latest and greatest. I will test and report since which GCC version the issue started.

**Comment by 3oheicrw-alter-ego** [comment]
MSYS2 is rolling release so will be always latest greatest. I will use this to test instead: https://winlibs.com/

**Comment by 3oheicrw-alter-ego** [comment]
@LADSoft Re-check your makefiles, GCC 7.5.0 compiled OCC fine but since this is a full build then there is the step OCC compiles itself too. It failed exactly at this step. The error is `'occ' is not recognized as an internal or external command, operable program or batch file.`

`OrangeC-master\bin` was created and did have all the OCC utilities compiled but for some reasons omake can't find them, the problems is in the makefiles.

**Comment by 3oheicrw-alter-ego** [comment]
Please fix this then I will continue testing with other MinGW GCC versions.

**Comment by buguorenjian** [comment]
Add `OrangeC-master` directory to `ORANGEC` environment variable and `%ORANGEC%\bin` to `PATH`, don't use a `fullbuild` as it will pull in unrelated nonsense.

`omake -DCOMPILER=MINGW64` is enough.

**Comment by buguorenjian** [comment]
GCC 7.5.0 works.

**Comment by buguorenjian** [comment]
GCC 8.5.0 works.

**Comment by buguorenjian** [comment]
GCC 9.4.0 works.

**Comment by buguorenjian** [comment]
GCC 10.3.0 works.

**Comment by buguorenjian** [comment]
Failed to build with Clang of GCC 10.3.0. On mingw64.mak just replace x86_64-w64-mingw32-gcc with clang.

**Comment by buguorenjian** [comment]
It started to fail exactly at GCC 11.2 @LADSoft

**Comment by buguorenjian** [comment]
Since this is standalone MinGW, so it's something to do with MinGW, not MSYS2. Close. Please open new ticket for the new issue. I'm done with this.

**Comment by LADSoft** [comment]
I made an adjustment so that the latest version of mingw64 can be used in MSYS2

to build it use:

     ./omake fullbuild -DCOMPILER=MINGW64 -DORANGEC_ONLY=YES
