### ISSUE TITLE
How to configure BCC102 to be used to build OrangeC?

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [LADSoft/OrangeC#731]
From bcc32.mak:

`COMPILER_PATH := \bcc102`

What does this mean? I downloaded BCC102.zip from https://altd.embarcadero.com/download/bcppbuilder/BCC102.zip and extracted it to `$(DISTROOT)`. OMake can't find it. I then tried to move it to `$(DISTROOT)\src`, OMake still can't find it!

I ended up changed the above to point to the absolute path of BCC102 directory (without the double quote otherwise it will fail) (to be clear, it's `C:\Active\Pixelitor\BCC102`, I moved it here after previous failed attempts). Finally, the build started.

Update: I used this command `omake -DCOMPILER=BCC32 fullbuild`

Another update: `$(DISTROOT)` is `C:\Active\Pixelitor\OrangeC-master`

**Comment by 3oheicrw-alter-ego** [comment]
No, something is wrong. The makefiles for this free BCC102 compiler and RADSTUDIO are separate. But why it's trying to link with a 64 bit library on a 32 bit compiler?

**Comment by 3oheicrw-alter-ego** [comment]
What? Why it's spamming the parent directory of `$(DISTROOT)` with `libtmp*` files?

**Comment by 3oheicrw-alter-ego** [comment]
I have an impression that `bcc32.mak` is not being maintained well. I will try to compile with OpenWatcom.

**Comment by 3oheicrw-alter-ego** [comment]
I will not try with this BCC102 any further. Too much headache.

**Comment by 3oheicrw-alter-ego** [comment]
Re-read bcc32.mak, realized BCC102 doesn't include an assembler. Has to install NASM. Installed NASM, with NASM.EXE on Windows PATH, still failed to compile. So not my mistake.

**Comment by LADSoft** [comment]
yeah i don't know where we left things with BCC32.    At some point I was battling compiler bugs in the compiler.

BCC102 should have been installed to C:\bcc102  and c:\bcc102\bin should be on the path.

**Comment by 3oheicrw-alter-ego** [comment]
> yeah i don't know where we left things with BCC32. At some point I was battling compiler bugs in the compiler.
> 
> BCC102 should have been installed to C:\bcc102 and c:\bcc102\bin should be on the path.

Hardcoded in makefiles or not? Sorry, I don't really know omake but this line in bcc32.mak is very absurd:

`COMPILER_PATH := \bcc102`

Could you tell me what's the meaning of it or is it just a typo? What does the backslash serve here? And `\bcc102` will be expanded to which path?
