### ISSUE TITLE
Does OrangeC support PASCAL calling convention?

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#737]
I have no idea what PASCAL calling convention is. I only know about stdcall and cdecl. Recently I know a bit more of them (fastcall, vectorcall) by reading the Pelles C help file. If OrangeC doesn't support that PASCAL calling convention, please remove the checks for it on various imported Pelles C Windows headers file. These leftovers only cause confusions.

**Comment by LADSoft** [comment]
As far as the win32 headers goes, PASCAL is a synonym for STDCALL.    It has its roots in ancient history...

**Comment by ruanjiashing** [comment]
> As far as the win32 headers goes, PASCAL is a synonym for STDCALL. It has its roots in ancient history...

Sorry, it's my ignorant.
