### ISSUE TITLE
Does OrangeC has share.h?

### ISSUE THREAD

**Issue by 3oheicrw** [LADSoft/OrangeC#738]
Pelles C doesn't have share.h. That header is documented here:

https://learn.microsoft.com/en-us/cpp/c-runtime-library/sharing-constants?view=msvc-170

It's a fairly simple header. We could take it from MinGW-w64:

https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/share.h

**Comment by LADSoft** [comment]
orange C does have share.h
