### ISSUE TITLE
omake vs gmake

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#739]
Is there a list of differences between omake and gmake? If there is no such a list, there should be documented incompatibilities between them. There should be a list of omake's current quirks too. @LADSoft used to tell me some of omake's current quirks but I can't find his comment.

**Comment by GitMensch** [comment]
As far as I'm aware: the built-in rules are reasonably different (using OrangeC tools) and "only some GNU extensions are supported yet"

**Comment by 3oheicrw** [comment]
> As far as I'm aware: the built-in rules are reasonably different (using OrangeC tools) and "only some GNU extensions are supported yet"

How is it compared to mingw32-make? I want to know more about it. Your answer is very brief in information :smile:

**Comment by ruanjiashing** [comment]
I will try using omake and will ask if needed.
