### ISSUE TITLE
Chatting

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#740]
I can't access the Pelles C forum. It always said I was banned because of spam when I'm not even logged in. I tried to use VPN, but most of the VPN's IP addresses are also banned like my real IP address. Finally, setting the location to Canada granted me access to the forum. But I can't register new account nor login with my existing account. My existing account was already banned for no reason because of spam. C is not my language. I'm very rarely posting on that forum. So it seems the decision to ban me is based solely on my IP address and it's the anti spam software doing it not the moderators of that forum. Many people faced the same issue as me, including a moderator of that forum: https://bcxbasiccoders.com/smf/index.php?topic=662.0

That thread is from February. They said the admin fixed this issue and I confirmed but I think it's come back now. The last post I did on that forum is from May and I didn't visit the forum since then so I don't know what's going on but today both of my existing account and my newly registered account are marked as spam and banned.

It's also since May the developer of Pelles C was disappeared: https://forum.pellesc.de/index.php?topic=10591.0 but it seems to be just his normal habit.

What I hate most about that forum is there is no way for you to contact the admin. There is no links on the website for you to do so. I was wrongly banned from many forums because of my IP address (a dynamic IP address that is generated randomly which I have no control over it). But most of the time a simple email to the admin by the contact info solved the problem. I know that they don't want to be bothered by a random guy on the internet and only want to focus developing that software and enjoying life. But if you are caught in the situation of me you will understand how disappointed it is.

I'm moving out from Pelles C to OrangeC. After the Windows headers importing, OrangeC should be improved enough to use. But OrangeC still lacking the ability to generate 64 bit binaries that Pelles C has since a long time ago.

**Comment by LADSoft** [comment]
I recently juggled the milestones around a bit to move the 64 bit binaries thing closer to the front, but it is still behind the C++17 upgrade.   Maybe I will move the C++17 after that, let me think about it...   but I'm still working on getting through all the tests for libcxx...

**Comment by ruanjiashing** [comment]
> I recently juggled the milestones around a bit to move the 64 bit binaries thing closer to the front, but it is still behind the C++17 upgrade. Maybe I will move the C++17 after that, let me think about it... but I'm still working on getting through all the tests for libcxx...

My opinion is, you will always have to chase and catch up with the latest C++ standard. It's a long term work. The ability to generate 64 bit binaries instead makes your compiler a serious solution and really helps the adoption of it. This is just my own opinion, other people could think different from me.

**Comment by ruanjiashing** [comment]
BTW, since this thread is off-topic, I will close it to give space to more serious tickets.
