### ISSUE TITLE
Threads on OrangeC

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#754]
MinGW uses a port of pthread to Windows called winpthread. MSVC and Pelles C instead have two types of runtime, one single thread and one multi thread that could be specified via switches at compilation. I wonder what about OrangeC?

Pelles C is the first C compiler on Windows implements C11's threads.h, MinGW's threads.h is just a wrapper over pthreads.

**Comment by ruanjiashing** [comment]
I checked the OrangeC source. It does have threads.h but pthread.h is a zero-sized file (the content is indeed empty). Perhaps I should rephrase the question because I put it not clear. How to deal with code link with -pthread? So far they only compiled with MinGW (or Cygwin if you count that heavy compatibility layer).

**Comment by chuggafan** [comment]
C11 threads in OrangeC are probably similar to Pelles C in that we just wrap around the windows APIs, pthreads.h is a holdover from when the original thread implementation from libcxx would yell at you for not having it, now that libcxx isn't linux-only the purpose of it inside of this compiler have been removed. If you want Windows pthreads find a pthread library and use it.
