### ISSUE TITLE
Does it support pragma lib?

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#756]
Pragma lib looks like this:

```
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "gdi32.lib")
```

It's a Pelles C specific extension (is it? as Pelles C mostly mirror MSVC, it's not unexpected if MSVC supports this too). I'm personally against it. If OCC currently doesn't support it then it's for goodness.

**Comment by chuggafan** [comment]
This is actually a good point for implementation in order to be more compatible with MSVC for static linking, @LADSoft any thoughts on this? I might take a crack at this in a couple weeks when I have more time than I do now.

**Comment by LADSoft** [comment]
so there is a `#pragma library (libname)`.    It would be easy to change the syntax...   but I haven't used it in a long while so it would need to be retested...

**Comment by GitMensch** [comment]
Sounds like this is solved. Note: according to MSVC docs https://learn.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp#examples you don't need to specify the ".lib" extension, so it would be useful to if @chuggafan could add the internal alias for it; also nice would be to have the other `#pragma comment` parts supported.

**Comment by LADSoft** [comment]
@chuggafan yes I think it would be nice if you could add the alias for it...    do you want me to write a separate issue for that?

**Comment by chuggafan** [comment]
Sure, I'll get around to it probs in the next 2 weeks as well as set it up so we can do things like add other info into the system that the `comment` pragma supports

**Comment by GitMensch** [comment]
Follow on in #761 (which currently misses the assignment for better planning).
