### ISSUE TITLE
Does it support pragma warn?

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#757]
Pragma warn looks like this:

```
#ifdef __POCC__
	#pragma warn(disable: 2118 2216)	/* disable some warnings				*/
				/* 2118: Parameter {parameter_name} is not referenced.			*/
				/* 2216: The return value from {function_name} is never used.	*/
#endif
```

It's a Pelles C specific extension (is it? as Pelles C mostly mirror MSVC, it's not unexpected if MSVC supports this too). My opinion is if you want to disable a specific set of warnings on a specific set of source files then it's better done on the makefile instead of on the source files like this. But I don't know what you think about it.

**Comment by chuggafan** [comment]
https://github.com/LADSoft/OrangeC/blob/master/doc/occ/OCC%20Pragma%20Directives.md

**Comment by ruanjiashing** [comment]
> https://github.com/LADSoft/OrangeC/blob/master/doc/occ/OCC%20Pragma%20Directives.md
> 
> ```c++
>         if (str == "STDC")
>             HandleSTDC(tk);
>         else if (str == "AUX")
>             HandleAlias(tk);
>         else if (str == "PACK")
>             HandlePack(tk);
>         else if (str == "LIBRARY")
>             HandleLibrary(tk);
>         else if (str == "STARTUP")
>             HandleStartup(tk);
>         else if (str == "RUNDOWN")
>             HandleRundown(tk);
>         else if (str == "WARNING")
>             HandleWarning(tk);
>         else if (str == "ERROR")
>             HandleError(tk);
>         else if (str == "FARKEYWORD")
>             HandleFar(tk);
>         else if (str == "ONCE")
>             HandleOnce(tk);
>         else if (str == "PRIORITYCPP")
>             cppprio++;
>         else if (str == "IGNORE_GLOBAL_INIT")
>             HandleIgnoreGlobalInit(tk);
>         else if (str == "PUSH_MACRO")
>             HandlePushPopMacro(tk, true);
>         else if (str == "POP_MACRO")
>             HandlePushPopMacro(tk, false);
>         else if (catchAll)
>             catchAll(str, tk.GetString());
> ```
> 
> These are an exhaustive list of all pragmas that are supported by OrangeC

So it seems it support pragma warn? How to use it? The syntax seems different from Pelles C.

**Comment by chuggafan** [comment]
> So it seems it support pragma warn? How to use it? The syntax seems different from Pelles C.

https://github.com/LADSoft/OrangeC/blob/master/doc/occ/OCC%20Pragma%20Directives.md

**Comment by ruanjiashing** [comment]
> > So it seems it support pragma warn? How to use it? The syntax seems different from Pelles C.
> 
> https://github.com/LADSoft/OrangeC/blob/master/doc/occ/OCC%20Pragma%20Directives.md

Syntax is like Pelles C, except it's `warning` not `warn`.
