### ISSUE TITLE
How does OCC treat unsupported pragmas?

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#758]
On previous versions of MinGW, it will error if it found unsupported pragmas. I have to wrap these pragmas in ifdefs to have the code compiles. With recent versions of MinGW, it will simply ignore the unsupported pragmas, print a warning about that and keep going.

**Comment by LADSoft** [comment]
I think it is a standard thing to ignore it if you can't parse it lol...   anyway that is what occ does does, if it runs into a parse error while parsing the pragma it just bails and continues processing the file with the next line...
