### ISSUE TITLE
occparse access violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#760]
```
Access Violation:(C:\OrangeC\bin\occparse.exe)
CS:EIP 0023:004DCBBE  SS:ESP 002B:00189E80
EAX: 076A7A4C  EBX: 076A79E0  ECX: 00000000  EDX: 076A7A6C  flags: 00010206
EBP: 00000000  ESI: 076A7A4C  EDI: 07B2DCA0
 DS:     002B   ES:     002B   FS:     0053   GS:     002B


CS:EIP  8B 4F 08 39 4E 08 0F 85 70 01 00 00 8B 4F 04 39

Stack trace:
                        4dcbbe
```

Since I'm feeding occ a wildcard input, it could be very likely it's not crashed at gravity_compiler.c but another source file. But it does crash. I really see gravity_compiler.c printed before it crashed.

_Originally posted by @ruanjiashing in https://github.com/LADSoft/OrangeC/issues/752#issuecomment-1298117622_

**Comment by GitMensch** [comment]
I do wonder if this stack trace is "as it should be", of it is is either trashed or does not show functions because of a new issue.

 @LADSoft Additional I'm suggesting to also print the version output and the command line in any abort case, if possible.

**Comment by ruanjiashing** [comment]
Additional information: if you use the MSVC build then it will give a stack trace about access violation, but if you use the MINGW64 build then it will simply crash.

**Comment by ruanjiashing** [comment]
This latest CI build is very buggy. Not only occparse.exe crashes, omake crashes too: https://github.com/LADSoft/OrangeC/issues/748 then occopt.exe also crashes: https://github.com/thradams/cake/issues/16#issuecomment-1298375924

**Comment by ruanjiashing** [comment]
> stack trace only shows functions if you run a debug version. This because a) there is no debug inforrmation for release builds and b) ebp is optimized out and orangec doesn't do the equivelant of whatever lookaside tables MSVC adds to compensate for that.
> 
> As far as the CI build I'm not sure what is up, I don't believe I've changed much of anything in the compiler itself for a week or so. And even then I was mostly changing c99 declarator initializers... which I don't believe the compiler uses... And the only thing that changed last night was the addition of the gl headers... maybe orange C is having trouble parsing one of the myriads of new headers added over the last week. I will look at it at some point later this week but I'm buried in something else right now.

It's this way before the addition of the gl headers. No one can really sure how long it's like that because almost no one tested building actual source code with it like me. It could be happened long before the Pelles C headers import. But imo I think this is very unlikely, it's definitely that something changed after the Pelles C headers import that caused this.

**Comment by LADSoft** [comment]
i was thinking about this some more, and I had forgotten in my original response that there were runtime library changes as well.    Possibly i muffed something up...   will look at it soon.

**Comment by LADSoft** [comment]
i fixed this specific issue in 1b42fbe9f6c156e2499e1807ba1d4371e7230815

**Comment by LADSoft** [comment]
Additional information: if you use the MSVC build then it will give a stack trace about access violation, but if you use the MINGW64 build then it will simply crash.

The stack trace is part of the runtime library, so, if you don't build occ with itself, you don't get the stack trace when occ crashes because other compilers don't put in stack traces any more.

**Comment by LADSoft** [comment]
on the problem with cake:   the crash is an existing bug with the optimizer; I could see it occuring in various people's source code.   I will push a fix tomorrow when I fix another parse problem that cake brough out...

**Comment by GitMensch** [comment]
I guess there was a fix so the only part missing is a reference and close?

**Comment by LADSoft** [comment]
sure ok.    Looks like we attributed the gravity one already, the one for cake is : e86e5b56028b4d4b56bffd3a4a7e3c1bf373d36e
