### ISSUE TITLE
Rename omake to sth else

### ISSUE THREAD

**Issue by iahun** [LADSoft/OrangeC#762]
It's conflicting with OCalm's `omake`:

https://github.com/ocaml-omake/omake

I think `omk` will be OK.

**Comment by GitMensch** [comment]
lol, renaming it will break all my build scripts and my memory muscle; in the end this is like multiple "make" sharing the same name; the other repo will tell you the same.

To fix same names you may either call it with the full path, prefix its path to PATH as needed, or create a wrapper script that effectively does this then calls your executable with all parameters passed to the wrapper script (this way you can create your `omk` and another `ocm`).

**Comment by iahun** [comment]
OCalm is more famous than OrangeC.

**Comment by GitMensch** [comment]
I see, but still: fame doesn't matter. What _may_ matter more is the age and in this case OrangeC's omake started inn 1994 while OCaml's first release "0.9.2" is dated 2004.

Just call the omake you want with either absolute path, prefix PATH as wanted, or use a wrapper srcipt.

Ideally it also works if you rename OrangeC's omake binary to omg.exe after install/unzip, but I haven't tested if that works (I suggest you to check that, also with "another" omake in PATH).

In any case I'd suggest to close this request as  "won't be done".
