### ISSUE TITLE
omake crashes

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#769]
It has been reported that under some unknown condition omake crashes.   Haven't been able to duplicate it on my windows 11 pc.   This issue it to try it with older versions of windows to see if there is an incompatibility somehow.    Also, might as well see what happens if it is run in powershell.

**Comment by GitMensch** [comment]
Maybe a good reason to run a local analyze + upload to https://scan.coverity.com/projects/ladsoft-orangec, then inspect the defect list.

**Comment by GitMensch** [comment]
Not sure but this is "maybe solved"?

**Comment by LADSoft** [comment]
I'm going to have a release possibly this weekend, I'll plan to update the other repos as well with the latest work.    But I'm closing this.

**Comment by iahunq** [comment]
@LADSoft Should this issue be closed?

**Comment by GitMensch** [comment]
Crash issues should only be closed when the crash is solved.

**Comment by iahunq** [comment]
> Crash issues should only be closed when the crash is solved.

Where are the issues? There is no specific issues, just a remark that `omake` was reported to be crashing under some unknown conditions on some older versions of Windows. There is nothing to debug or to solve.

**Comment by GitMensch** [comment]
@LADSoft wrote:

> I'm closing this.

yes, please do so ... and possibly #792 as well (I _guess_ the "`-j1` is broken" thing is solved)
