### ISSUE TITLE
allow compilation of assembler sources with .s

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#77]
I've just tried to send occ to compile MPIR 3.0.0.
Its configure script fails with "checking how to switch to text section". For doing so it sends different one-line assembler files to the compile `occ -9`.
All files error with `Error(437)    conftest.s(1):  Invalid use of type 'int'` which I *guess* means `occ` tries to process them as C sources.

Just as a note: these are the things the configure script tests - if one of these do compile it seems to assume it has its answer:

```asm
	.text
	.code
	.csect .text[PR]
```

**Comment by LADSoft** [comment]
I added this...

**Comment by GitMensch** [comment]
Doesn't work yet:

~~~
configure:24441: checking how to switch to text section
trying .text
configure:24452: occ -c  -! -IC:\dev\orangec\include -IC:\dev\orangec\include\win32 conftest.s >conftest.out 2>&1
configure:24455: $? = 1
Error(437)    conftest.s(1):  Invalid use of type 'int'
1 Errors
configure: failed program was:
	.text
trying .code
configure:24452: occ -c  -! -IC:\dev\orangec\include -IC:\dev\orangec\include\win32 conftest.s >conftest.out 2>&1
configure:24455: $? = 1
Error(437)    conftest.s(1):  Invalid use of type 'int'
1 Errors
configure: failed program was:
	.code
trying .csect .text[PR]
configure:24452: occ -c  -! -IC:\dev\orangec\include -IC:\dev\orangec\include\win32 conftest.s >conftest.out 2>&1
configure:24455: $? = 1
Error(437)    conftest.s(1):  Invalid use of type 'int'
1 Errors
configure: failed program was:
	.csect .text[PR]
configure:24471: error: Cannot determine text section directive
~~~

Note: a quick grep showed the following files containing `.nas` without any change:
https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/lc.c
https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/ocide/rule/asm.rul
https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/cleanup.c
https://github.com/LADSoft/OrangeC/blob/6d19cad3a341ee00a7e06dcbecdf07e0667116fd/src/omake/MakeMain.cpp

Additional the following files should be considered for this change, too
https://github.com/LADSoft/OrangeC/blob/618d3048ccce688fbc74026deb98462fdb25fa2a/src/ocide/find.c
https://github.com/LADSoft/OrangeC/blob/6d19cad3a341ee00a7e06dcbecdf07e0667116fd/src/ocide/drawedit.c
https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/dos/infopad/ipdedit.cpp
https://github.com/LADSoft/OrangeC/blob/97e35e2f707025007b3312f5d6eeabc51b215364/src/ocide/prjfile.c

**Comment by LADSoft** [comment]
I didn't realize you meant the IDE...   I had fixed the C compiler only.   Should be resolved now.

**Comment by LADSoft** [comment]
should be fixed

**Comment by GitMensch** [comment]
according to MPIR configure script works:

~~~
checking how to switch to text section... .text
checking how to switch to data section... .data
~~~
