### ISSUE TITLE
Compile FOX Toolkit

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#770]
the fox toolkit is a C++ 11 program : http://fox-toolkit.org/

Presently some of the files don't compile.    The common errors are that addresses are taken without '&' and there are some problems with member function pointers (in one case it crashes)

**Comment by iahung2** [comment]
I think you should skip this for now. The latest version of the FOX Toolkit failed to compile even on MSYS2.

**Comment by LADSoft** [comment]
ok thanks for the heads up...
