### ISSUE TITLE
Compile Gravity

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#771]
compile gravity compiler: https://github.com/marcobambini/gravity

The two reasons this won't compile are that is uses '$' in character names and that it uses computed gotos.

**Comment by LADSoft** [comment]
I added the '$' and used an alternate configuration that doesn't enable the computed gotos, but there is a bug in the sources where a macro is called without enough arguments so even with that it won't compile out-of-the-box.

Since this does mostly compile now except for a bug the author left in, (it uses a macro without enough arguments when computed gotos aren't enabled)   I'm going to close it with the caveat that I'll try compiling it with the computed gotos when I add support for computed gotos in #201.

**Comment by GitMensch** [comment]
Can you please create and/or reference a pr (or an issue) in the repo concerning the bad macro usage?

**Comment by LADSoft** [comment]
marcobambini/gravity#394

**Comment by LADSoft** [comment]
the author fixed it and I verified that orange c compiles it ok now.
