### ISSUE TITLE
problem with names of unnamed structures

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#777]
if you declare an unnamed structured in a header file, then include it in two c++ files, it may have different names in the two files.    This isn't good for example if a function argument uses the type and the function is shared across modules.

**Comment by chuggafan** [comment]
Would a good solution to this be to replace the number with a 64 bit hash of the typename + position in the struct + size of type? I think this would be an ez solution here that's repeatable and if we have issues we can just make it a various salted solution with larger hash sizes for this.

**Comment by LADSoft** [comment]
I guess you are saying hash each member together?    I guess that would work....   might be a bit slow though lol...

**Comment by chuggafan** [comment]
Yes, I think it's the only realistic way to use those factors because we need to ensure that there's compatibility between types of the same and position in the type (e.g.:

```c
typedef struct
{
uint32_t a;
uint16_t b;
} mytype_t;
// should be type compatible with assuming a 32-bit system:
typedef struct
{
int a;
short b;
} mytype2_t;
```
Ergo we need to use the size of the system, we can drop the name portion and just make it position in the struct + size of the struct melded together in some sort of key system but I don't need an easy way to do this, we could simply make ridiculously long anonymous type names that are just the sizes of the structure's elements in the order they appear as well, it'll be faster, just might break something along the way...

**Comment by LADSoft** [comment]
if we have two structures like this:

```c++
typedef struct
{
uint32_t a;
uint16_t b;
} mytype_t;
// should be type compatible with assuming a 32-bit system:
typedef struct
{
int c;
short d;
} mytype2_t;
```
it wouldn't work to describe them with the same unique name because they would collide if included in the same translation unit.    So the name of each field has to be added, and we also need position and whether or not it is a bit field/how many bits.

Also if we had two structs which is the same except one member changes from

```
int aa;
```
to
```
char *aa
```

assuming a 32-bit compiler they'd hash the same if you only use position, and we need to differentiate those as well.   So I'm thinking we'd have to traverse the type and hash all the bt_xxx constants (other than bt_typedef), along with the length fields in case it is an array...   and if a bt_xxx is a structure or enumeration of course we'd have to hash in the completely qualified name of the structure/union....

it is a bit of work but it might be ok using the builtin c++ hashing, we'd have to try it and see...   probably not much of an issue in the C++ language since it isn't so usual to typedef structs this way as in C....    I would prefer that to stringing a gazillion ascii characters together because we are definitely going to break buffer sizes if we do that....
