### ISSUE TITLE
false positives for warning 137: '%s' used without prior assignment

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#78]
```c
    WINDOW *win;

    if ( !(win = PDC_makenew(nlines, ncols, 0, 0))    // line 85
        || !(win = PDC_makelines(win)) )
        return (WINDOW *)NULL;
```

raises:

> Warning(137)  C:\dev\PDCurses\pdcurses\pad.c(86):  'win' used without prior assignment in function newpad

If I'm not wrong I think line 85 initializes it to `NULL` when line 86 is reached, doesn't it?

Similar:

```c
    const char *str;
    SP->lines = (str = getenv("LINES")) ? atoi(str) : PDC_get_rows();
```

> Warning(137)  C:\dev\PDCurses\win32\pdcscrn.c(411): 'str' used without prior assignment in function PDC_scr_open

**Comment by LADSoft** [comment]
should be resolved.

**Comment by GitMensch** [comment]
Found another one in GnuCOBOL's cobc:

```c
/* Reverse a list of trees,
   NOTE: changes the passed list directly! */
cb_tree
cb_list_reverse (cb_tree l)
{
	cb_tree	next, last;

	last = NULL;
	for (; l; l = next) {     // line 1541
		next = l->chain;
		l->chain = last;
		last = l;
	}
	return last;
}
```

>Warning(137)  C:\dev\gnucobol\cobc\tree.c(1541):  'next' used without prior assignment in function cb_list_reverse

Actually `next` is only used after the for was processed one time, and therefore: after `next` got a value assigned.

**Comment by GitMensch** [comment]
@LADSoft should be reopened, the second issue is still open
