### ISSUE TITLE
Support compiling to WebAssembly?

### ISSUE THREAD

**Issue by nsgnkhibdk2cls0f** [LADSoft/OrangeC#781]
WebAssembly is pushed very hard and become very viral recently. Especially with the initiative like WASI (https://wasi.dev/) it's already powerful enough to be a serious target. Maybe you could get compiling to WebAssembly done before your compiler can even output 64 bit binaries! WebAssembly is a much simpler instructions set!

**Comment by LADSoft** [comment]
I don't know if I'd want to detour into something like that so soon...

**Comment by LADSoft** [comment]
This is beyond the scope of this project, so I'm closing this issue,.
