### ISSUE TITLE
Unable to use with PLOOC

### ISSUE THREAD

**Issue by tn1997tn** [LADSoft/OrangeC#784]
https://github.com/GorgonMeducer/PLOOC

**Comment by GitMensch** [comment]
... because?

**Comment by tn1997tn** [comment]
> ... because?

It printed too many errors. I have no idea why. You could reproduce it yourself. Copy all of the plooc*.h to example/byte_queue and try to compile byte_queue.c as a static library with occ.

**Comment by GitMensch** [comment]
When creating an issue I'd suggest to show the full output of the compile, along with the command line used (and in this case just use `-I ../..` to find the headers), then there's something to inspect. Creating "doesn't work" without much context doesn't provide that and also does not help when people search for the error messages you have seen either.

**Comment by tn1997tn** [comment]
> When creating an issue I'd suggest to show the full output of the compile, along with the command line used (and in this case just use `-I ../..` to find the headers), then there's something to inspect. Creating "doesn't work" without much context doesn't provide that and also does not help when people search for the error messages you have seen either.

OK here you are:

```
C:\PLOOC-4.6.3\example\byte_queue>occ -c byte_queue.c -I../..
occ (OrangeC) Version 6.0.62.2
Copyright (C) LADSoft 2006-2021
Error .\byte_queue.h(64): Wrong number of arguments in call to macro __PLOOC_CONNECT2
Error( 11)    .\byte_queue.h(64):  Syntax error: ) expected
Error( 11)    .\byte_queue.h(78):  Syntax error: ) expected
Error( 61)    .\byte_queue.h(91):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(96):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(99):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(102):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(105):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(108):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(111):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(114):  Storage class 'extern' not allowed here
Error( 61)    .\byte_queue.h(117):  Storage class 'extern' not allowed here
Error(273)    C:\Active\orangec\include\c\string.h(56):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(58):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(60):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(62):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(68):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(70):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(72):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(73):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(74):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(75):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(76):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(77):  Functions may not be a part of a structure or union
Error(273)    C:\Active\orangec\include\c\string.h(78):  Functions may not be a part of a structure or union
Error(  1)    C:\Active\orangec\include\c\string.h(78):  Too many errors or warnings
```

**Comment by LADSoft** [comment]
So i identified the problem, will look into fixing it perhaps tonite but more likely tomorrow...    basic gist is the __VA_ARGS__ support isn't quite up to par when __VA_ARGS__ is used as an argument to another macro invocation...

**Comment by LADSoft** [comment]
ok so there are no less than 3 GCC extensions in this project lol...  I'm still working through them...

**Comment by LADSoft** [comment]
the version i just pushed compiles this, however, I couldn't generate an exe because there seemed to be missing files...

**Comment by tn1997tn** [comment]
> the version i just pushed compiles this, however, I couldn't generate an exe because there seemed to be missing files...

`byte_queue` is a static library so the is no exe.

**Comment by LADSoft** [comment]
yeah i pretty much compiled all the files in the project(well the ones that weren't designed for ARM anyway), there were some other bugs I fixed beyond what the problem was with byte_queue...   usually after I do that I try to run the results to make sure there are no surprises...   but i couldn't with this one...
