### ISSUE TITLE
occ version output shows 2021?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#785]
as seen in #784

**Comment by LADSoft** [comment]
I'm not sure what is up with this.   'version.h' has the correct date of 2023.    And even if it were somehow cached incorrectly, it should show 2022 like it did last year...   where 2021 is coming from is a mystery.

**Comment by GitMensch** [comment]
Not mystery but magic 😁 🪄

**Comment by LADSoft** [comment]
can't duplicate
