### ISSUE TITLE
What is the equivalent to ranlib on OrangeC?

### ISSUE THREAD

**Issue by tn1997tn** [LADSoft/OrangeC#789]
### Discussed in https://github.com/LADSoft/OrangeC/discussions/787

<div type='discussions-op-text'>

<sup>Originally posted by **tn1997tn** February 23, 2023</sup>
I'm trying to convert a makefile from using GCC to OrangeC. Please help.</div>

It seems no one watching the Discussions section so I converted it to an issue.

**Comment by LADSoft** [comment]
sorry i've been busy with other stuff, will look at PLOOC and make comments on everything tonite...

**Comment by LADSoft** [comment]
you would use arocc....
