### ISSUE TITLE
Does omake support gnu make's .PHONY target?

### ISSUE THREAD

**Issue by tn1997tn** [LADSoft/OrangeC#790]
From my experience I guess it doesn't. Please correct me if I was wrong.

**Comment by GitMensch** [comment]
It definitely should, also see the code https://github.com/LADSoft/OrangeC/search?q=.PHONY&type=code, but it may be not complete, the related issue has a sample: If .PHONY samples are not found, they should be ignored, not error'd on.

**Comment by LADSoft** [comment]
will look at this tonite or tomorrow
