### ISSUE TITLE
Documenting the differences between omake and gnu make

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#791]
There should be a note about the incompatibilities between omake and gnu make. omake is far from a drop-in replacement for gnu make imo. There are plenty of notes about the differences between bsd make (bmake) and gnu make on the internet:

https://alfix.gitlab.io/bsd/gnu/coding/2017/01/28/gnu-make-vs-bsd-make.html

https://mmap.page/dive-into/make/

p/s: You could install bsd make (bmake) on MSYS2 to have a taste of it.

**Comment by GitMensch** [comment]
> There should be a note about the incompatibilities between omake and gnu make.

Patches welcome! Just fork and edit https://github.com/LADSoft/OrangeC/blob/master/doc/omake/OMake.md

**Comment by tn1997tn** [comment]
> > There should be a note about the incompatibilities between omake and gnu make.
> 
> Patches welcome! Just fork and edit https://github.com/LADSoft/OrangeC/blob/master/doc/omake/OMake.md

I have a better solution that works for me: just use `mingw32-make` and ditch `omake`, en voilà assez!

**Comment by iahunq** [comment]
@LADSoft Should this issue be closed?
