### ISSUE TITLE
GNU make Automatic Variables

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#793]
I don't think omake supports the whole set of them and I don't think it should too. But it's good to know the list of supported Automatic Variables.

https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html

**Comment by GitMensch** [comment]
> I don't think omake supports the whole set of them and I don't think it should

Why not?

**Comment by LADSoft** [comment]
sorry this took so long...   looking at the source code it should support all of them.
