### ISSUE TITLE
Missing of GdiPlus.h

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#795]
`Error: Could not open  <GdiPlus.h>  for input`

**Comment by GitMensch** [comment]
We have switched the windows headers to Pelles C. If I understood the small pieces I've checked correctly, then Pelles C does not distribute so neither do we.
It seems that people use this: https://forum.pellesc.de/index.php?topic=733.0 to add it to a Pelles C environment, so you may could try that for OrangeC, too.

@LADSoft: Would it be reaonable to include this part (at least the headers)?

**Comment by tn1997tn** [comment]
Pelles C is a C compiler and GdiPlus.h is a C++ header so it's no points for them to include this header.

**Comment by LADSoft** [comment]
i might add this at some point...   if you have a reference for where I might find one that isn't in the microsoft headers that might make it happen faster though...

**Comment by tn1997tn** [comment]
> i might add this at some point... if you have a reference for where I might find one that isn't in the microsoft headers that might make it happen faster though...

MinGW-w64 project.
