### ISSUE TITLE
Unable to use with win32++

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#797]
Here is win32++: https://win32-framework.sourceforge.net/

It supported many compilers, as old as Borland 5.5 is still supported. But I have no idea why OrangeC doesn't work with it. Try to compile a sample like Scribble and you will see many errors.

**Comment by GitMensch** [comment]
... can you please provide a small example that hows the errors?

**Comment by tn1997tn** [comment]
> ... can you please provide a small example that hows the errors?

I will copy paste from Command Prompt, wait...

**Comment by LADSoft** [comment]
will evaluate tonite or tomorrow...

**Comment by LADSoft** [comment]
I've been slowly making my way through these issues.   A lot of good issues exposed by this project.    I'm working on a bug with the preprocessor right now, it suppresses some non-recursive constructs as if they were recursive...

**Comment by LADSoft** [comment]
I've got it compiling, there are some compiler issues with compiling cast operators though so it doesn't run yet...

**Comment by LADSoft** [comment]
so i compiled and ran the scribble example, and was able to draw some stuff...  the menus are a bit broken though.   I'll try to get it finished up this week...

**Comment by LADSoft** [comment]
the menus are broken due to a bug in libc++ - it passes a 'begin' point where an 'end' pointer should be passed.    Fixing the bug allows the scribble example to work...   later on I will try to find out if this bug has been addressed in later versions of the library and if not maybe I can figure out how to send in a bug report...   but meanwhile I'm closing this issue.

**Comment by LADSoft** [comment]
the workaround for win32xx by the way is disable owner-drawn menus...

**Comment by LADSoft** [comment]
they've rewritten the code, it isn't immediately obvious whether the rewrite would work any better though.    It will be a while before I upgrade the library again...
