### ISSUE TITLE
__CCDL__ stated in help file when it is __ORANGEC__ actually

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#8]
Hi!
The help file orangec/help/chelp.chm, at "C language help"/"Preprocessor"/"Macro Expansion", bottom of the page, it is stated: `__CCDL__` The LADSoft compiler is being used. No value.
After some tests, I found `__CCDL__` was not defined. After some guessing, I found that `__ORANGEC__` was. The doc needs an update, I suppose. And wouldn't occ documentation be a better place for that kind of occ specific information?

**Comment by LADSoft** [comment]
Hi Lionfaith,

I fixed the documentation you referenced, and also added a more complete 
list to the section 'defining macros' in orangec/help/tools.chm.   
Finally, I updated the similar section in the HTML version of the 
documentation to match.

Thanks,

David
lionfaith wrote:

**Comment by lionfaith** [comment]
Thanks for your work! :)
