### ISSUE TITLE
std::function check with equality operators is nonfunctional

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#809]
```cpp
#include <functional>
#include <vector>
std::function<void(std::vector<uint64_t>)> func;

int main()
{
    std::vector<uint64_t> vals = {100, 200};
    if (func != nullptr)
    {
        func(vals);
    }
    return 0;
}
```
This produces:

```
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Error(151)    C:\OrangeC\test.cpp(8):  Invalid structure operation
1 Errors
```

This function should exist, per: https://en.cppreference.com/w/cpp/utility/functional/function/operator_cmp

This is doubly weird because in some circumstances this construct produces a nullptr from detemplate on line 5772 of cpplookup.cpp where it fails an allTemplateArgsSpecified check in template.cpp line 7318 from the current commit of my personal `master` branch, causing a nullptr dereference. I have no idea why, I will make a note of the commit where the crash can be seen in my PR that I will upload later.

**Comment by LADSoft** [comment]
@chuggafan 

the function does exist so this is a compiler bug...   I will get to it tonite or tomorrow...

**Comment by LADSoft** [comment]
I've slowly been making progress on this between other things, but currently it has some other stuff broken...   i'll be working on this next and hopefully we can get it cleaned up.

**Comment by LADSoft** [comment]
i got sidetracked working on #373, which is stalled now waiting on #819.    Meanwhile I have to get serious about #603 again lol...   I'll get to this after #603...

**Comment by LADSoft** [comment]
i got this compiling now, but there is a problem in the inliner where the entire if statement gets elided... sigh...   will fix it tomorrow.

**Comment by chuggafan** [comment]
I mean, if the if statement is always true I do think eliding it is correct. Especially because in this case the inliner is absolutely correct that the function can't execute in my example, what I could do is give an example where the inliner cannot be sure that the if statement is always one way and we can test on that...

**Comment by LADSoft** [comment]
it shouldn't be able to tell, because, 'func' is at a global scope and something else might have modified it...

**Comment by chuggafan** [comment]
Ahhhh, that's reasonable, I forgot I dealt out a global variable.... I mean, that would be nice in a linker optimization but not in a compiler optimization (though good luck with our current linker system from doing that, IIRC the way gcc, clang, and msvc do linker optimization is to dump IR into object files and to collate the references inside of the linker before applying global optimizations with whole-program context).

**Comment by LADSoft** [comment]
yeah i doubt we will to that point lol!    

But I finally figured out operator bool() wasn't being called.   Got it fixed for the present use case, but if you make a declaration like this:

std::function<void(int,int,int)> func;

where there are multiple arguments, it falls flat on its face...
