### ISSUE TITLE
Response-file / command-line issue

### ISSUE THREAD

**Issue by gvanem** [LADSoft/OrangeC#812]
I'm really puzzled on how OrangeC parses a response-file an puts it's arguments into `main (int argc, char *argv[]`).
E.g. if I have a GNU-make generated response-file `build/occ.arg` file with:
```
--nologo
-c
-I.
-9
+v
-O+a
-O+i
```

and compile like `occ.exe @build/occ.arg file.c -o build/file.obj`, the bleeding logo shows up:
```
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2021
```

But if I change my GNU-make rule into `occ.exe --nologo @build/occ.arg file.c -o build/file.obj`,
the logo doesn't show up!

I mean, it doesn't seems the complete `build/occ.arg` file gets expanded before `Utils::banner()` does it's job. Why not?

(I'd prefer a nice compact cmd-line with all arguments in `build/occ.arg`).

**Comment by LADSoft** [comment]
the main reason the banner appears before command line switches are processed, is that with the current design any errors in the command line processing would appear before the banner.

Let me see if I can rectify the situation...   I'll get to this pretty soon as I'm in the process of cleaning up low hanging fruit from the repository and this is a low-hanging fruit.

**Comment by gvanem** [comment]
> Let me see if I can rectify the situation.

OK, good.

**Comment by LADSoft** [comment]
I did fix this...
