### ISSUE TITLE
#include "stdio.h" doesn't work

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#820]
@chuggafan,   I am running orangec through the CMAKE tests associated with clang.   There are some legitimate compiler bugs.

oen if them is, if you include stdio.h, using quotes instead of angle-brackets, you get the following:

```
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Error \orangec\include\stdio.h(107): Could not open using #include_next  <stdio.h>  for input
1 Errors
```

angle brackets work fine...

is this something you could look into?    Or should I just handle it myself?

**Comment by chuggafan** [comment]
I can look into this, but it's likely that it has to do with how many directories were skipped vs not skipped and include ordering...

**Comment by chuggafan** [comment]
Actually, I am having issues related to even starting debugging, it seems that the ocpp.lib generation and ocpp.exe generation (and a lot of files) are having issues where in Visual Studio due to the project rename the incorrect file is being generated causing massive headaches that I'm not sure how to solve, if that's solved I can much more easily debug what's going on.

In the meantime I do have a quick theory that I'll try out without the VS debugger.

**Comment by LADSoft** [comment]
ok no problem.

FWIW when I was having headaches with refactoring destroying my ability to build, one of my coworkers pointed out that the 'clean' or 'rebuild; option in visual studio doesn't clean all the object directories properly.    Which works fine for the normal use cases they designed for, but can get in the way if you are doing wholesale rewrites...

While that was specifically for C# projects, it might apply to C++ as well I suppose.   His solution was to use powershell to recurse through the directory tree and delete everything related to object files and executables.   Which in C# is the bin and object directories and I guess would be the debug and release directories for C++.

Another trick he queued me into when things got really bad, was to delete the hidden **_.vs_** directory that is in the directory with the solution, and let visual studio rebuild it.    But that doesn't seem to be needed as often...

**Comment by chuggafan** [comment]
So it turns out for some reason the depth of traversal for "How far have we actually checked `#include_next`" is off by one it seems, and that is causing the issue only when we are doing a non-system-include, as seen by:

```
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
File existence check: ..\stdio.h
File existence check: .\stdio.h
File existence check: stdio.h
File existence check: c:\ORANGEC\include\stdio.h
File existence check: c:\ORANGEC\include\__config
Path checked: c:\ORANGEC\include name: stdio.h Files skipped: 1 skips needed: 3
Path checked: c:\ORANGEC\include\c name: stdio.h Files skipped: 2 skips needed: 3
Path checked: c:\ORANGEC\include\c\win32 name: stdio.h Files skipped: 3 skips needed: 3
File existence check: c:\ORANGEC\include\c\win32\stdio.h
```

I think this would warrant a rewrite of `FindFile` in order to execute this, I am just not sure how much of it needs to be modified in order to handle it...

Dang edgecases cropping up years later.

**Comment by LADSoft** [comment]
Im not 100% sure how to read the numbers above, but, it seems there *may* simply be a problem where we treat <> differently from "" regardless of where the file is actually found???

**Comment by chuggafan** [comment]
Whoops, I accidentally pushed my instrumentation to my PR for this project, I meant to push it on a separate branch to link it, anyways:

```
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
pushFile name: ..\testembed.cpp dirs traversed: 0
ppFile Directories travelled: 0 name: ..\testembed.cpp
FindFile name: stdio.h dirs skipped: 0 Current ppFile name: ..\testembed.cpp
FindFile name 2: stdio.h dirs skipped: 0 include_files_skipped: 0
File existence check: ..\stdio.h
FindFile name 3: stdio.h dirs skipped: 0 include_files_skipped: 0
File existence check: .\stdio.h
FindFile name 4: stdio.h dirs skipped: 0 include_files_skipped: 0
sysSearchPath is empty between 4 and 5: 0
srchPath is empty between 4 and 5: 1
File existence check: stdio.h
Search Path: 
srchPath 2 is empty between 4 and 5: 1
sysSearchPath 2 is empty between 4 and 5: 0
FindFile name 5: stdio.h dirs skipped: 0 include_files_skipped: 1
File existence check: c:\ORANGEC\include\stdio.h
FindFile name 6: stdio.h dirs skipped: 0 include_files_skipped: 2
pushFile name: c:\ORANGEC\include\stdio.h dirs traversed: 2
ppFile Directories travelled: 2 name: c:\ORANGEC\include\stdio.h
FindFile name: __config dirs skipped: 0 Current ppFile name: c:\ORANGEC\include\stdio.h
File existence check: c:\ORANGEC\include\__config
pushFile name: c:\ORANGEC\include\__config dirs traversed: 1
ppFile Directories travelled: 1 name: c:\ORANGEC\include\__config
FindFile name: stdio.h dirs skipped: 0 Current ppFile name: c:\ORANGEC\include\stdio.h
FindFile name 2: stdio.h dirs skipped: 0 include_files_skipped: 0
FindFile name 3: stdio.h dirs skipped: 0 include_files_skipped: 0
FindFile name 4: stdio.h dirs skipped: 0 include_files_skipped: 0
sysSearchPath is empty between 4 and 5: 0
srchPath is empty between 4 and 5: 1
Search Path: 
srchPath 2 is empty between 4 and 5: 1
sysSearchPath 2 is empty between 4 and 5: 0
FindFile name 5: stdio.h dirs skipped: 0 include_files_skipped: 1
SrchPath Path checked: c:\ORANGEC\include name: stdio.h Files skipped: 1 skips needed: 3 system? 1
SrchPath Path checked: c:\ORANGEC\include\c name: stdio.h Files skipped: 2 skips needed: 3 system? 1
SrchPath Path checked: c:\ORANGEC\include\c\win32 name: stdio.h Files skipped: 3 skips needed: 3 system? 1
File existence check: c:\ORANGEC\include\c\win32\stdio.h
FindFile name 6: stdio.h dirs skipped: 0 include_files_skipped: 4
pushFile name: stdio.h dirs traversed: 4
Error c:\ORANGEC\include\stdio.h(107): Could not open using #include_next  <stdio.h>  for input
1 Errors
```

With the most recent commit from my PR I get this output, I'll probably force-push it back to what it was before and put this on a different branch...

**Comment by LADSoft** [comment]
thanks.   If you can get it on a different branch so I can merge it that would be appreciated.   Then I can get back to the work for cmake...

**Comment by chuggafan** [comment]
I don't have a solution, I have the issue as a thing, I don't know how to solve this easily so it'll take awhile, sorry since it wasn't obvious.

**Comment by LADSoft** [comment]
oh ok sorry I misunderstood...

**Comment by LADSoft** [comment]
@chuggafan - I took a stab at fixing this.   Would you mind reviewing and seeing if you think I've broken something else?

**Comment by chuggafan** [comment]
Looks good as best as I can tell, I don't have a lot of the programs I used to originally test include_next on my desktop, I think I worked on it on my laptop at the time so I currently can't completely verify, but I'm amazed that's the solution.

Things I think of when I'm deep in the problem when trying to solve for the first time vs a year later.

**Comment by LADSoft** [comment]
ok thanks.   Builds are working so I'll close this now...
