### ISSUE TITLE
change archive file extension

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#821]
im looking for feedback as to whether it would be advisable to change the object file extension from .l to .a.

linux/gcc/clang all support .a and as far as I know .l is unique to orangec
.l is also the extension for lex source files so there is and has been a conflict

but there would be a lot of ripple, and I'm not sure how it would affect things like the automake builds if we change it now...

the immediate problem being a lot of the cmake tests for clang are failing because the tests are designed around clang and clang doesn't know .l...

**Comment by chuggafan** [comment]
Personally I think it is nice to differentiate between archive file types, i.e. `.lib` is MSVC, `.a` for ELF in packed form, and `.l` for IEEE OMF. There should be a non-invasive way in cmake to change what the expected static library output is for a specific compiler...

**Comment by GitMensch** [comment]
Agreed.

Am 6. Juli 2023 03:30:09 MESZ schrieb chuggafan ***@***.***>:

**Comment by LADSoft** [comment]
ok sounds good to me.    I really wasn't looking forward to making that kind of invasive change...

the problem though is we are running tests intended for clang, and it is the tests themselves that sets the library extension in each individual test, rather setting global in the cmake config files.    I might try setting it in the orange c cmake config files but I'm not sure whether the code in the tests will overwrite it or append to it...

but we may end up just having to fail these tests since they aren't designed for orange c.

**Comment by GitMensch** [comment]
just minor: should have been closed not as completed, but as "not done"

**Comment by GitMensch** [comment]
> but we may end up just having to fail these tests since they aren't designed for orange c.

I'm confused now, do they test clang or do they also test gcc? Don't they also test MSVC?
The necessary distinction should be the same for OrangeC, if not then the testsuite used possibly can take an update apart from the OrangeC integration.

Just a note: while some tests (the one testing for the extensions) should fail, it may be useful to at least check if some of the MSVC / GCC tests pass with the wrappers oracc and oracl - and if not, then recheck which ones _should_ pass.
