### ISSUE TITLE
FR: add `-fsyntax-only`

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#823]
this came up in https://github.com/LADSoft/OrangeC/commit/16dc88175490e9756a9a346234dce1219a29175f#diff-a50bd0d2d5dde2a491a559d55d6b8a0a5b329794093d943db8061aff69202370 (adding it should needs an update there, too), but is something general useful, so here's the FR for that:

an option to syntax-check only (=compile only, no linking tried, no output files [other than temp files] generated)

**Comment by LADSoft** [comment]
there is an option already to do this.   Apparently I thought it interesting to add when I added gccocc.    The documentation is incorrect about it though so this PR will be about fixing the documentation.

**Comment by LADSoft** [comment]
so while there was an option to do it, it was broken when you put it in a response file so i fixed that as well as updating the docs.
