### ISSUE TITLE
What do you think about using LLVM?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#824]
LLVM has many C++ compiler frontends, not just Clang. For example:

https://github.com/robertoraggi/cplusplus

Your project is still struggling to have 64-bit support and can't generate 64-bit binaries yet. I think LLVM is a perfect match for you. Using LLVM, you could focus on the C++ compiler part and let LLVM take care of the code generation and optimization parts.

**Comment by LADSoft** [comment]
the thing is, the part of the project I like most is the code generation/optimization.   I wouldn't be as interested in the project if I gave those away...
