### ISSUE TITLE
What do you think about changing to a more permissive license?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#825]
Relicensing to a more permissive open source license like MIT, BSD, or even a modified Apache license like LLVM? I think the world doesn't need just another GPL-ed C/C++ compiler. GNU GCC is already enough. The reason why LLVM is widely adopted is not only because it has a more modern architecture than GNU GCC but also because of the permissive license it uses. The BSD operating systems all switched to LLVM Clang as the default C/C++ compiler for this reason, with DragonflyBSD as the exception. They are constantly trying to purge GPL-licensed software from their codebase.

**Comment by GitMensch** [comment]
My opinion: The world don't need another non-gpl compiler, clang/LLVM is enough.
Note: people _do_ ship adjusted LLVM/clang binaries without distributing their code, because the license allows that. The world _really_ does not need a non-copyleft compiler.

**Comment by iahunq** [comment]
> My opinion: The world don't need another non-gpl compiler, clang/LLVM is enough.

This is only true before LLVM changed their license to a modified Apache license. The OpenBSD project used to want to migrate out of LLVM/Clang after the relicensing but finally decided to still embrace LLVM/Clang as they don't have any alternatives. Imagine if Orange C is relicensed to MIT or BSD license, it's very likely they will embrace Orange C instead of stuck with LLVM/Clang.

> Note: people _do_ ship adjusted LLVM/clang binaries without distributing their code, because the license allows that. The world _really_ does not need a non-copyleft compiler.

This is _the reason why_ the world embraced LLVM/Clang.

**Comment by GitMensch** [comment]
> > Note: people _do_ ship adjusted LLVM/clang binaries without distributing their code, because the license allows that. The world _really_ does not need a non-copyleft compiler.
> 
> This is _the reason why_ the world embraced LLVM/Clang.

... and the reason why the world does not have the code of the modified versions.

**Comment by iahunq** [comment]
> > > Note: people _do_ ship adjusted LLVM/clang binaries without distributing their code, because the license allows that. The world _really_ does not need a non-copyleft compiler.
> > 
> > 
> > This is _the reason why_ the world embraced LLVM/Clang.
> 
> ... and the reason why the world does not have the code of the modified versions.

... and there is nothing wrong with it.

**Comment by LADSoft** [comment]
well aside from what we think about whether it should be gnu-licensed or not, the fact is it IS gnu licensed and there have been contributions from people who agree that that is the way it SHOULD BE licensed, and I wouldn't feel comfortable pulling that rug out from under their feet.    So it is going to remain gnu licensed.

Note however we went to some effort to adjust the license for the runtime library, so that you can distribute code compiled with OrangeC without having to give out your source code.   Unless of course the code you are compiling is licensed in a manner that it would itself require you to give out source code.

I think gcc did something similar.

**Comment by GitMensch** [comment]
Just again the note that you have a closed-fixed and a closed-not-done option in GH (and can adjust that after the initial close).
The use is especially when looking through closed issues in the issue tracker to directly see what is changed=relevant and which had no change.

**Comment by LADSoft** [comment]
ok thanks I will bear that in mind going forward.
