### ISSUE TITLE
Unable to build Nana

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#847]
You could get Nana here: http://nanapro.org/en-us/

It's a C++11 application. The website is a bit misleading when it said `LANGUAGE C++11/14/17`. This only means the library is compatible with C++11/14/17. It doesn't require C++14 or C++17 to be built.

Go to `nana/build/makefile` and edit `makefile` to remove all of the unsupported flags by `gccocc` from `CXXFLAGS` (only `-g` is left) and change the compiler from `g++` to `gccocc`. You will have to use GNU Make. I have not tested with OMake, though. My experience with OMake is generally bad. The fact is this `makefile` was written for GNU Make so it's naturally for you to also use GNU Make. I'm building on MSYS2 (MINGW64) environment. This is what I see after I typed `make`:

```
gccocc -o out/objs/any.o -c ../../source/any.cpp -I../../include -I/usr/include/freetype2 -I../../extrlib -g
gccocc (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2021
Error ../../source/any.cpp(15): Could not open  <nana/any.hpp>  for input
Error(229)    ../../source/any.cpp(21):  Qualifier 'any' is not a class or namespace
Error(228)    ../../source/any.cpp(23):  'any' is not a member of 'nana'
Warning(105)  ../../source/any.cpp(24):  Function should return a value
Error(229)    ../../source/any.cpp(26):  Qualifier 'any' is not a class or namespace
Error(228)    ../../source/any.cpp(28):  'any' is not a member of ' (*)(???)'
Error(229)    ../../source/any.cpp(30):  Qualifier 'any' is not a class or namespace
Error( 18)    ../../source/any.cpp(30):  Undefined symbol 'other'
Error( 11)    ../../source/any.cpp(86):  Syntax error: } expected
8 Errors
make: *** [makefile:41: out/objs/any.o] Error 1
```

I'm using the latest released version of Orange C:

```
$ gccocc -V
gccocc (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2021

Compile date: Jun 25 2023 time: 04:27:36
```

Update: you should change `/usr/include` to `/mingw64/include`, too.

**Comment by iahunq** [comment]
```
$ ls ../../include
nana
```

So why can't Orange C `see` it? Does it support relative include paths?

**Comment by LADSoft** [comment]
@iahunq:

it is  currently ok with both MINGW-32 and MING64 as far as your issue goes, at least it is getting past the #includes on my computer......   but there is another problem with returning the results of typeid as a reference that I will look into after I go to dinner...

**Comment by LADSoft** [comment]
so the current omake seems to process this makefile ok now...   in addition to the foreach problem and the crash, I fixed some things related to implicit rules and then it took off.    but I seem to have lost the changes I was making to fix compilation of C++ problems.   I'll get back to that but my priority this weekend is going to be get as far as I can with #603...

**Comment by LADSoft** [comment]
there are some crashes, but the major problem is we don't currently support the 'filesystem' header...   that won't come until we update to C++17...
