### ISSUE TITLE
Does Orange C support POSIX paths?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#849]
For example, `-I/mingw64/include/freetype2`? https://github.com/LADSoft/OrangeC/issues/847

Update: I'm running Orange C on MSYS2 (MINGW64) environment.

**Comment by GitMensch** [comment]
yes, it supports that "per se", but don't be confused here, MSYS2 MinGW64 has an internal mapping of that path, which is not true for _any_ win32 binaries that you run with it.

You have those options:
* specify a windows style path `/d/dev/mingw64` - note: you can just _additional_ specify that, so commonly no need to adjust Makefiles for that (for example during configure with ` configure CPPFLAGS="-Iyourinclude"` or during make with `make CPPFLAGS="-Iyourinclude"` (depending on the makefiles this may override).
* possibly: create a windows symlink to this directory in the drive's root you are working (as `/mingw64` should be identical to `D:\mingw64`, if your current working drive is "D:")
