### ISSUE TITLE
A stress test for the compiler: building Qt5 from source

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#850]
Qt5 is a C++11 application that the compiler is supposed to be able to deal with, and as it's using a `./configure` script to build, you could test how good your GCC and binutils emulators are too. Please note that Qt5 itself will very likely need to be patched. You could have a look at the patches used by MSYS2 here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-qt5-base

Note: a statically linked Qt5 needs another set of patches: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-qt5-static

**Comment by GitMensch** [comment]
Suggestion if you are interested in this: start that (after gccocc ignores warning unknown options) and post updates here., as well as help posts.

Do you have any idea why this huge amount of patches is not included upstream?

**Comment by iahunq** [comment]
Let's focus on Nana. It's small enough and doesn't have any external dependencies.
