### ISSUE TITLE
This `makefile` crashed omake

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#852]
See: https://github.com/LADSoft/OrangeC/issues/847

The `makefile` is taken from that issue, but this issue is about omake and completely unrelated to that issue. The only thing I could see was a stack trace being printed on the terminal emulator (I'm using the MSYS2 (MinGW64) environment).

**Comment by LADSoft** [comment]
Thanks.   One of the things I was going to do when I researched #847 was see what problems I could find with omake but you beat me to it lol!

**Comment by iahunq** [comment]
Fixed with https://github.com/LADSoft/OrangeC/commit/f32d8d4cb1d621d623df4ba1b7f6a3eb3429221c
