### ISSUE TITLE
Unable to build LibAgar

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#854]
You could get LibAgar here: https://github.com/JulNadeauCA/libagar

Currently it failed at the configuration step:

```
$ CC=occ ./configure
BSDBuild 3.2 <https://bsdbuild.hypertriton.com/>
    _       _       _     ___
  / _ \   / _ \   / _ \  |  _ \
 | |_| | | (_| | | |_| | | |_) |
 |_| |_|  \__, | |_| |_| |_| |_|
          |___/
                 v1.7.1 for x86_64 (LARGE)

checking for a C compiler...using occ
checking whether the C compiler works...yes, it outputs .exe files
cc: checking whether compiler is Clang...no
cc: checking whether compiler is cc65...no
cc: checking whether compiler is emcc...no
cc: checking whether compiler is GCC...no
cc: checking for compiler warning options...yes
cc: checking for float and double...yes
cc: checking for long double...yes
cc: checking for long long...yes
checking for Objective-C compiler...yes, /mingw64/bin/clang
checking whether the Objective-C compiler works...yes
objc: checking for compiler warning options...no
checking for byte order...occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2021
Error conftest.c(2): Could not open  <sys/param.h>  for input
1 Errors
Failed to compile test for byte order, code 0
```

**Comment by GitMensch** [comment]
You may want to send a note upstream that this test is nonportable. You could also send a PR upstream that first checks for the heater and it it is missing either do the check with a union or assuming little endian in that case.
... but actually the test with the union is simple and portable.

Am 7. Juli 2023 19:21:02 MESZ schrieb iahunq ***@***.***>:

**Comment by iahunq** [comment]
After I manually added `<sys/param.h>` by copying from MinGW-w64, it's now failing to find `FreeType`:

```
checking for FreeType...yes (26.0.20)
checking whether FreeType works...no
*
* The FreeType library was not found, aborting!
*
* Agar needs FreeType to display vector fonts
* (http://www.freetype.org/).
*
* If you really want to use Agar's built-in
* monospace bitmap font engine (not recommended),
* please use: ./configure --without-freetype
*
```

I then proceed with building without `FreeType`. The build started for a while. I checked Task Manager and saw Orange C is really invoked. But finally it failed mysteriously without any errors being printed on the screen.

**Comment by iahunq** [comment]
Let's focus on Nana. It's small enough and doesn't have any external dependencies.

**Comment by GitMensch** [comment]
Note: for external libraries you'd need to generate import libraries first (see either the docs or the GnuCOBOL testbed issue where that is outlined, too).

**Comment by GitMensch** [comment]
I'd suggest to keep that open, even if possibly until other issues are closed.

**Comment by iahunq** [comment]
> I'd suggest to keep that open, even if possibly until other issues are closed.

Let @LADSoft decide.
