### ISSUE TITLE
Please add an emulator for `gcc -E`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#855]
Configure scripts usually use `gcc -E` as the preprocessor. When you force CC to `occ` or `gccocc`, the configure script will simply substitute `gcc` with this value, so the preprocessor will be `occ -E` or `gccocc -E`. The problem is that these commands are not working, so the test for the preprocessor will fail.

**Comment by GitMensch** [comment]
While I totally support that FR, what about specifying CPP for the configure accept invocation too?

**Comment by iahunq** [comment]
> While I totally support that FR, what about specifying CPP for the configure accept invocation too?

Do you mean `CPP="ocpp --no-logo"`? It doesn't work, too.
