### ISSUE TITLE
gccocc doesn't understand `-pthread`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#861]

**Comment by GitMensch** [comment]
As noted in #892: this is "by design", because OrangeC has no planned pthread support.
What currently happens if that is used? Do we need to "parse and error" or is the current one enough (in which case this issue should be closed as not-planned)?

**Comment by iahunq** [comment]
> As noted in #892: this is "by design", because OrangeC has no planned pthread support. What currently happens if that is used? Do we need to "parse and error" or is the current one enough (in which case this issue should be closed as not-planned)?

Currently `gccocc` will report `Unknown switch '-p'`. My idea is `gccocc` should ignore `-pthread`.

**Comment by GitMensch** [comment]
That option explicit requests to use the library we don't use, from the manpage:

> Adds support for multithreading with the pthreads library. This option sets flags for both the preprocessor and linker.

As we won't do either, it is better to raise an error message (otherwise you'll get a compile/link error).

But it _may_ be reasonable to explicit parse so gccocc (and occ) can report

> Unsupported switch '-pthreads', use xyz instead.

(with or without the xyz part)

**Comment by iahunq** [comment]
Some switches that are irrelevant to Orange C now could become relevant in the future when Orange C supports Linux, e.g: `-pthread`, `-pie`, `-no-pie`, `-static-pie`, `-fpic`, `-fPIC`, `-fpie`, `-fPIE`,... They should be handled by `gccocc`.

**Comment by iahunq** [comment]
Fixed with https://github.com/LADSoft/OrangeC/commit/0e43f6ee8a154a5373ce84804fea3e5ecc3609a6
