### ISSUE TITLE
Missing predefined macros in "OCC Defining Macros.md"

### ISSUE THREAD

**Issue by AlexN-114** [LADSoft/OrangeC#87]
In your doc file `OCC Defining Macros.md` the standard macros  `__FILE__`, `__LINE__`, `__DATE__`, `__DATEISO__` and `__TIME__` are missing. ;-)

**Comment by LADSoft** [comment]
thank you!   I've fixed it now :)

**Comment by GitMensch** [comment]
You may want to include "fixes #number" any time you think a commit fixes something.
Looks like this one can be closed :-)
