### ISSUE TITLE
Coff2ieee Access Violation

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#89]
According to the [new Coff2IEEE docs](http://orangec.readthedocs.io/en/latest/general/Coff2IEEE/) I've did

`Coff2ieee.exe -ogmp.l mpir.lib`

result:

~~~
Coff2ieee Version 6.0.36.1 Copyright (C) LADSoft 2006-2018
converting library file

Access Violation

CS:EIP 0023:00407412  SS:ESP 002B:0019F08C
EAX: 00000000  EBX: 0019F1D0  ECX: 00000001  EDX: 0019F180  flags: 00010202
EBP: 0019F1D0  ESI: 0019F1D0  EDI: 0019F1D0
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

[mpir.lib](https://github.com/LADSoft/OrangeC/files/1974537/mpir.lib.zip)

**Comment by LADSoft** [comment]
hi, I'm having problems with compiling mpir to get a dll/lib pair...   is there some way you can provide it?   Otherwise do you know where I should put the vsyasm configuration files?   I have the 2017 version of vs community and all the instructions I can find for installing yasm don't help...

**Comment by GitMensch** [comment]
I've did this some time ago and can look this up for you. I guess you should be able to check the access violation with the attached [mpir-combo.zip](https://github.com/LADSoft/OrangeC/files/1976698/mpir-combo.zip)

**Comment by GitMensch** [comment]
Note: this happens on all the tested lib files (all produced by VS for 32bit)

**Comment by LADSoft** [comment]
I will fix soon, meanwhile I think I noticed that the latest problem you were having with oimplib was use of the lowercase /c switch instead of the uppercase /C switch.   I did reverify with your example code and it does seem to work...   but I haven't actually run the generated code since I don't know what arguments to use.

**Comment by LADSoft** [comment]
i fixed it.

**Comment by GitMensch** [comment]
Not sure if the libraries will work, but the access violation is fixed.
