### ISSUE TITLE
GCC's stack protection

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#893]
Does Orange C have something equivalent?

https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang

This is only a question and I don't ask you to add such a feature. Btw, `gccocc` should be updated to handle these compiler flags. It currently don't understand them.

**Comment by LADSoft** [comment]
no Orange C doesn't have this.

**Comment by GitMensch** [comment]
FR: please add that "someday"

**Comment by LADSoft** [comment]
lol.   This one actually isn't all that difficult so i might do it now while I'm cleaning up the repository, but, there is a backlog of other stuff I need to get to first.
