### ISSUE TITLE
Orange C doesn't have something equivalent to `-fpermissive`?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#894]
Related to: https://github.com/LADSoft/OrangeC/issues/892

It seems `occ` itself has no equivalent flags to `-fpermissive`.

**Comment by GitMensch** [comment]
clang explicit opted to **NOT** support it, apart from several patches (seemingly even from Intel) to include that option

I totally second [the reasoning about that that](https://github.com/llvm/llvm-project/issues/54120):

> Clang has historically not supported `-fpermissive` and I think the bar for supporting that feature is far higher than "GCC compatibility" because it's effectively a new, unbounded language dialect rather than a simple extension. Right now, our story is very easy to understand: we don't support `-fpermissive`. If we start supporting it, then we get to play catch-up with all of the `-fpermissive` situations GCC accepts, or we're making users have to deal with the divergence, either of which is not a scenario I think we want to enter into lightly.

See https://reviews.llvm.org/D58154 if you want more notes than the above (there are much more on its mailing lists).

Conclusion: I suggest to close this issue as not planed and to explicit say the same as above: OrangeC won't implement that.
Note: OrangeC also doesn't support explicit std's for clang and gcc dialects, and I think that's fine (after all it isn't a COBOL compiler that explicit supports disagreeing dialects ;-)

**Comment by LADSoft** [comment]
We won't support this

**Comment by GitMensch** [comment]
Then  please close as not planned.
