### ISSUE TITLE
How strict is Orange C?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#895]
Could it be used for development? Or should development be done with other more strict compilers like MSVC, GCC, or Clang first, then later use Orange C only to compile? Orange C lacks many useful warning options compared to GCC and Clang. It also lacks something like `-fpermissive` to deal with problematic code. This leads me to the conclusion that either the compiler is so strict that it will refuse to compile any problematic code, or it's expected to have the compiler compile any code thrown at it regardless of how problematic the code is.

**Comment by LADSoft** [comment]
The main problem with using it for development is like you say the warnings aren't as comprehensive as on other compilers.    Another area that needs improvemnt, but, again there is so much to do and so little time.

I wouldn't expect it to be nearly as strict as say GCC, but I wouldn't expect to accept just any old code either...
