### ISSUE TITLE
Does Orange C do static linking by default?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#897]
Maybe related to: https://github.com/LADSoft/OrangeC/issues/896

But as I said, Orange C is even slower than `g++ -static` so we can't blame the static linking. The point of this issue is discussing about dynamic linking of the runtime to reduce the binary size. The binary generated by Orange C, even though being 32 bit, is much larger than a 64 bit binary generated by `g++`.

**Comment by LADSoft** [comment]
you can do dynamic linking, e.g. use -dll or -dynamic on the command line.   Or use -Wcd.

As far as slowness, it is a work in progress.    I've recently made improvements and have an idea what to improve next.

As far as binary size, it is a work in progress.   I've recently made improvements.

But I hope you understand that I am doing the brunt of the work on this project and I can't do everything all at once.    And things take time...

**Comment by GitMensch** [comment]
So the answer to the main question is:

YES, it does static linking by default - and that can be adjusted using the mentioned flags.

**Comment by LADSoft** [comment]
FWIW you can do dynamic linking either against the orange c dynamic lib (which is lscrtl.dll) against msvcrt.dll (in which case some parts of the C language that postdate what went into that dll will still be linked statically) or even against crtdll.dll...
