### ISSUE TITLE
mruby

### ISSUE THREAD

**Issue by letarg0** [LADSoft/OrangeC#90]
Is possible to compile mruby using OrangeC?
is any benchmart to check how fast is it?

**Comment by chuggafan** [comment]
That question entirely depends on how MRuby's build process is, you could probably compile MRuby with OrangeC, OrangeC *SHOULD* be able to compile any C89 to C11 standard of C, so compilation of MRuby should be possible, not that I reccomend it, because that entirely depends on your use-case.

**Comment by letarg0** [comment]
https://github.com/mruby/mruby
can You test this link?

**Comment by GitMensch** [comment]
Why don't you test it on your own?

If there are any issues with the make/compilation part (during `omake CC=occ`) you can report back here - until then I vote for closing this "issue".

**Comment by LADSoft** [comment]
I evaluated and thank you, there are a couple of compiler bugs highlighted by this program.   They will be fixed in the next release.

There is also one file that takes a long time to compile...  I will eventually look into seeing if I can improve that situation...

**Comment by LADSoft** [comment]
the problem with the long compile of one of the mruby files should be fixed as part of #109 when i get to it.    Meanwhile the only thing holding up a release is I want to finish #85 and I'm having issues...

**Comment by letarg0** [comment]
Very good, we waithing.

Mebye next runing a benchmark : OrangeC and other compilers.

**Comment by LADSoft** [comment]
I released the latest version 6.0.37.1 today; it compiles mruby ok now.   

I don't know much about benchmarks...

**Comment by GitMensch** [comment]
I suggest to close this issue (may be reopened if there are any issues with mruby compiled with OrangeC)
