### ISSUE TITLE
Where to download the latest CI build?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#902]
The artifact Binaries.zip from Github Actions, that contains ZippedBinaries.zip, after extracted has a messed up directory structure that is very different from what normally see on an Orange C release.

**Comment by GitMensch** [comment]
Yep, those binaries are currently not that useful...

I personally always go to https://ci.appveyor.com/project/LADSoft/orangec/builds, then take the last "green" build.

**Comment by LADSoft** [comment]
the actions binaries seem to be fixed now, hopefully we can start to stabilize the appveyor and get it working again as well.
