### ISSUE TITLE
Build Orange C with modern MinGW-w64

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#906]
The MinGW-w64 version tested by Orange C is too old. If the information on #729 was correct then Orange C has failed to build since GCC 11.

**Comment by LADSoft** [comment]
yeah that is probably true.   I worked on it a while tonite and got it to compile, now I'm having linker problems though...   I'll get back to it in a bit...   and possibly one of my next projects will be to make it actually work when compiled that way lol
