### ISSUE TITLE
Support building Orange C with MinGW-w64 based Clang

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#907]
`clang.mak` is for MSVC based Clang. We need to add a `llvm-mingw.mak` makefile for MinGW-w64 based Clang. The content of `llvm-mingw.mak` could be adapted from `mingw64.mak`.

You could download a MinGW-w64 based Clang from https://github.com/mstorsjo/llvm-mingw/releases (remember to pick the MSVCRT build).

Related issue: #728

Update: it seems we don't need a separate makefile at all, for building with MinGW-w64 based Clang, simply edit `mingw64.mak` and replace `-lstdc++` with `-lc++` on `COMPLIB`.

**Comment by GitMensch** [comment]
Why would we need a separate one?

The MSYS2 packaging system uses a single definition for all its environments and those use the same makefile, they just pass CC and others as variable into make (which has gcc as most reasonable default, which on the ucrt and similar environments is just a link to the clang compiler).

**Comment by iahunq** [comment]
> Why would we need a separate one? The MSYS2 packaging system uses a single definition for all its environments and those use the same makefile, they just pass CC and others as variable into make (which has gcc as most reasonable default, which on the ucrt and similar environments is just a link to the clang compiler).

Clang will use `libc++` as default even though you could use `-stdlib=libstdc++` to force it to link with `libstdc++` instead. On `mingw64.mak` you could see `-lstdc++` as part of `COMPLIB`. On llvm-mingw distribution or MSYS2 CLANG64, `libstdc++` is not even included.

**Comment by iahunq** [comment]
Simply editing `mingw64.mak` to replace `-lstdc++` with `lc++` doesn't work. So, you can't use `mingw64.mak` as is.

**Comment by iahunq** [comment]
@LADSoft It seems I have wrongly blamed the makefile. Please have a look:

```
In file included from memory.cpp:28:
..\occopt/memory.h:122:31: error: use of undeclared identifier 'beLocalAlloc'
    auto rv = static_cast<T*>(beLocalAlloc(sz * sizeof(T)));
                              ^
..\occopt/memory.h:137:31: error: use of undeclared identifier 'beGlobalAlloc'
    auto rv = static_cast<T*>(beGlobalAlloc(sz * sizeof(T)));
                              ^
```

I have no idea why the same piece of code compiled fine on GCC.

**Comment by iahunq** [comment]
If anyone wanted to ask me why I closed #915 then the reason is I think this is a too trivial hack to do a PR. We are reusing the `mingw64.mak` makefile anyway.

**Comment by LADSoft** [comment]
we won't be using the 'mingw-make' for mingw on clang...   I haven't decided yet whether to give it a new make file for clarity but meanwhile the gcc-linux is what will be used...    because the environment is so different than that for pure windows programs...

**Comment by iahunq** [comment]
> we won't be using the 'mingw-make' for mingw on clang... I haven't decided yet whether to give it a new make file for clarity but meanwhile the gcc-linux is what will be used... because the environment is so different than that for pure windows programs...

I used MinGW-w64 based Clang with a modified `mingw64.mak` to link with `libc++` instead of `libstdc++` and the patch above. I'm able to build and have a working Orange C. Btw, I build using `omake` on Windows Command Prompt.

p/s: What is your problem with `mingw32-make`?

**Comment by LADSoft** [comment]
sorry i meant mingw64.mak.   I have no problem with mingw32-make!  But if you got it working that way that is good :smile:

yeah i found out omake does work under msys2, main problem for me was it doesn't compile itself without the COMPILER=OCC because I defaulted to gcc-linux...
