### ISSUE TITLE
Support using of `mingw32-make` to build Orange C on MSYS2

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#908]
Related issue: #904

**Comment by GitMensch** [comment]
Would you mind inspecting for necessary changes and doing a PR?

**Comment by iahunq** [comment]
> Would you mind inspecting for necessary changes and doing a PR?

If you keep track of the discussion on #904 you should know @LADSoft already done most of the things needed to build Orange C with `mingw32-make`. I closed #904 because it has become too large and created several new issues to continue the discussion.

**Comment by LADSoft** [comment]
yeah mingw32 mostly works at this point...   I'll leave this open until I get it completely build the compiler with the native msys2 compiler..

**Comment by LADSoft** [comment]
ok the compiler builds with mingw32 in msys2, use 'COMPILER=gcc-linux'.   I've set it up to default to that if MSYSTEM is set so you can just run mingw32-make without any arguments.   I also did various cleanup, now 'mingw32-make clean' works...    you won't be able to do a full build yet since this will create executables that don't fully work...

omake still doesn't run under msys2...   I'll look at it...

**Comment by iahunq** [comment]
> ok the compiler builds with mingw32 in msys2, use 'COMPILER=gcc-linux'. I've set it up to default to that if MSYSTEM is set so you can just run mingw32-make without any arguments. I also did various cleanup, now 'mingw32-make clean' works... you won't be able to do a full build yet since this will create executables that don't fully work...
> 
> omake still doesn't run under msys2... I'll look at it...

Which MSYS2 shell you are using? Did you mistake `MSYS2 MINGW64` with `MSYS2 MSYS`?

**Comment by LADSoft** [comment]
yeah i was confused, I made the project build makefiles default to gcc-unix under msystem.   If I use COMPILER=OCC omake works, and it seems to work for other makefiles as well...

**Comment by iahunq** [comment]
> yeah i was confused, I made the project build makefiles default to gcc-unix under msystem. If I use COMPILER=OCC omake works, and it seems to work for other makefiles as well...

Please review your changes to the makefiles. It's becoming a mess now.

**Comment by iahunq** [comment]
Use this command to redirect `stdout` and `stderr` to the file `mingw32-make-msys2.log`:

`mingw32-make fullbuild COMPILER=MINGW64 WITHDEBUG=YES > mingw32-make-msys2.log 2>&1`

**Comment by iahunq** [comment]
> So, please edit your posts in both issues and attach the log you've created that way...

Not needed. Because `mingw32-make` works fine on MSYS2, without the need to use `--no-builtin-rules`. It's really #928. I'm building with `mingw32-make` on Windows Command Prompt to see if it works fine, too.

**Comment by iahunq** [comment]
Update: `mingw32-make` works fine on MSYS2, without the need to use `--no-builtin-rules`.

**Comment by iahunq** [comment]
> So, please edit your posts in both issues and attach the log you've created that way...

[mingw32-make-msys2.log](https://github.com/LADSoft/OrangeC/files/12088266/mingw32-make-msys2.log)

**Comment by iahunq** [comment]
The Orange C version built by `mingw32-make` could compile test code just fine. But there are still incompatibilities in the makefiles as the zipped files are not correctly created. With the command `mingw32-make fullbuild COMPILER=MINGW64 WITHDEBUG=YES > mingw32-make-msys2.log 2>&1` only the zipped binaries file was created (missing zipped sources). With the command `mingw32-make fullbuild ORANGEC_ONLY=YES COMPILER=MINGW64 WITHDEBUG=YES > mingw32-make-msys2.log 2>&1` no zipped files were created at all. For more detail you could investigate the `mingw32-make-msys2.log` file.
