### ISSUE TITLE
Update BUILD.md

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#909]
In the case where the users already have a locally installed version of Orange C and thus have the environment variable `ORANGEC` set to that locally installed version, when building Orange C from source, the `ORANGEC` environment variable should be updated to the source directory. Please correct me if I am wrong.

Update: the option `WITHDEBUG=YES` should be documented on BUILD.md, too.

**Comment by LADSoft** [comment]
yes you are correct.   I will both these comments and some other related stuff.
