### ISSUE TITLE
Remove `-lstdc++` from `COMPLIB` on `mingw64.mak`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#910]

**Comment by GitMensch** [comment]
Why?

In any case, if you want a makefile changed, then please just go ahead and make a PR with that change (giving a short explanation of the "why").

You can do this even in the browser via GH and a PR will run the CI tests on your change, too.

**Comment by iahunq** [comment]
I have no idea why but if I removed `-lstdc++` then Orange C will failed to build.

**Comment by LADSoft** [comment]
I fixed this the other day and it *seems* to build...    I will investigate more closely...

**Comment by iahunq** [comment]
> I have no idea why but if I removed `-lstdc++` then Orange C will failed to build.

I think I know why it failed to build without `-lstdc++`. You are using `gcc` to compile C++ code. If you use `g++` then `libstdc++` will be automatically linked. Please correct me if I'm wrong.

Btw, it seems you have reasons to use `gcc` in the first place. There are various mixed C/C++ code in the codebase. This maybe the reason.
