### ISSUE TITLE
FR: implement strnlen

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#913]
> That's a POSIX extension, not standard C, we can add support for it, but I haven't seen it before.

_Originally posted by @chuggafan in https://github.com/LADSoft/OrangeC/issues/278#issuecomment-1633385255_

**Comment by iahunq** [comment]
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strnlen-strnlen-s?view=msvc-170
