### ISSUE TITLE
[omake] Where does `/c: /c: Is a directory` come from?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#919]
This project is not even building on Windows, but it's the source code level. At least, the makefile is valid and `omake` should work (like `mingw32-make`).

https://github.com/DragonFlyBSD/cpdup

The command I used: `omake -f GNUmakefile`

This is what I see:

```
$ omake -f GNUmakefile
        C:/OrangeC/bin/occ -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 -Wwrite-strings -Wcast-qual -Wcast-align -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 /c: /c: Is a directory -c src/cpdup.c
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Unknown switch '-:'
occparse (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023

Usage: occparse [options] [@response file] files
Error <builtins>(2): commands returned error code 1
```

Where does `/c: /c: Is a directory` come from?

This is what I see when I use `mingw32-make`:

```
$ mingw32-make -f GNUmakefile
cc -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 -Wwrite-strings -Wcast-qual -Wcast-align   -c -o src/cpdup.o src/cpdup.c
In file included from src/cpdup.c:56:
src/cpdup.h:23:10: fatal error: pwd.h: No such file or directory
   23 | #include <pwd.h>
      |          ^~~~~~~
compilation terminated.
mingw32-make: *** [<builtin>: src/cpdup.o] Error 1
```

**Comment by LADSoft** [comment]
it looks like the phrase 'is a directory' comes from an error response from one of the commands being sent to the shell...   I will have to look at it at some point...

**Comment by iahunq** [comment]
> it looks like the phrase 'is a directory' comes from an error response from one of the commands being sent to the shell... I will have to look at it at some point...

Do you mean `pkg-config`? I edited `GNUmakefile` to comment out anything related to it. The error is still the same. `/c: /c: Is a directory` must be something from `omake` itself.

**Comment by LADSoft** [comment]
yeah omake is inserting it, but I Think it originally found it from a command sent to the command shell...     I will look at it...

**Comment by LADSoft** [comment]
i sort of noticed in passing, that it seems to happen when you do 'mkdir -p' when the shell is cmd.exe...   ill look into it later...

**Comment by iahunq** [comment]
> i sort of noticed in passing, that it seems to happen when you do 'mkdir -p' when the shell is cmd.exe... ill look into it later...

But the shell I used is MSYS2 (MINGW64).

**Comment by iahunq** [comment]
@LADSoft Any progress?

**Comment by LADSoft** [comment]
I looked at this briefly today, it appears that my change to omake to make omake work with foxit made the situation much worse...   anyway working on #859 right now.   This is one of the bugs I found when trying to compile NANA.    When I get that done today or tomorrow I will look more closely at trying to get omake to work with this make file.

**Comment by LADSoft** [comment]
You were the one who pioneered the idea that bash does magic, not me.

the reason that BASH could work with occ but not gccocc is simple, gccocc calls occ but occ doesn't call anything.  For things to work properly gccocc has to call occ with EXACTLY THE SAME ARGUMENTS that it itself was originally called with.    And it has to use the same environment - bash - as gccocc was exposed, as you pointed out that it is actually bash that performs the desired functionality you wanted.    

Leaving out either of those steps means that occ won't successfully be called in EXACTLY THE SAME WAY that gccocc was called, and thus it won't be able to properly process that command line.

It was never my intention to fully support msys2 in the way you want me to...   it has seemed like a good fit for the project to do what I've done, but, I'm not going to start making multiple release paths just to support it the way you think is 'proper'.

And I'm not backing out of these changes at this point, either.

**Comment by iahunq** [comment]
OK. Let's accept there will be never a POSIX OMake and OMake itself is always designed to work only on the Windows environment with `cmd.exe` as the shell. I understand your decision. So please remove all of the hacks made to OMake for MSYS2. OMake shouldn't call `sh` or `bash`. Let's decoupling Orange C from MSYS2. Sorry for the mess I have caused.

**Comment by GitMensch** [comment]
actually I've used omake before from boths msys2 environments and mingw, please don't break that...

**Comment by iahunq** [comment]
> actually I've used omake before from boths msys2 environments and mingw, please don't break that...

`mingw32-make` works fine on MSYS2. This means an OMake that uses `cmd.exe` as the shell will also work fine on MSYS2.

**Comment by iahunq** [comment]
> And I'm not backing out of these changes at this point, either.

I understand your decision. BTW, do you have any new progress on this issue? Do you know where `/c: /c: Is a directory` comes from yet?

**Comment by LADSoft** [comment]
@iahunq I took a detour and spent a couple of days working on -fstack-protector and some runtime checks - im going to work on this now...,

**Comment by LADSoft** [comment]
so I *think* some of the fixes I made to omake caused it to properly use sh.exe instead of cmd.exe, at least I am not seeing the original problem anymore.   I did see it at one point, briefly...

I have a version of omake that seems to work ok on the libagar make file now, there were some vagaries around the use of '&&' in commands.   omake uses it as a temporary file marker whereas it is a continuator in sh.exe...

 once I got past that and tried compiling, I found that libagar does some things unsupported by occ though which make it not compile; first it uses gnu style assembly language constructors in the C source code (The gnu-specific #ifs around that make a file not compile), and second it uses 'select' which isn't really supported on windows...   I will push this later maybe tonite but I've got to vet everything again first...   I'm probably going to wrap this one up.   I'm leaving the nana open though because I eventually want to get past the 'filesystem' header problem and see if we can get it completely to compile...

**Comment by iahunq** [comment]
This is what I currently see:

```
$ omake -f GNUmakefile
Error GNUmakefile(36): No rule to make target 'src/cpdup.o'
Error GNUmakefile(36): No rule to make target 'src/hclink.o'
Error GNUmakefile(36): No rule to make target 'src/hcproto.o'
Error GNUmakefile(36): No rule to make target 'src/md5.o'
Error GNUmakefile(36): No rule to make target 'src/misc.o'
```

**Comment by LADSoft** [comment]
i was confused...   you have two issues dealing with the same thing so I concentrated on what the one said about libagar without realizing you were compiling something else entirely here...    I will look at this later...

**Comment by LADSoft** [comment]
I'm improving this in the next push...   problem was the $(shell ...) was only compatible with cmd.exe...

any idea how to install libbsd and openssl in a way that is compatible with this package?   I tried pacman and it installed some binaries, but I'm not sure it installed what I needed, at least I can't find the files needed by pkg-conf...

Thanks...

**Comment by chuggafan** [comment]
For openssl, you should install openssl and `openssl-devel` (openssl-devel is listed as only under `msys` but it should just be headers, install the openssl appropriate for your thing) and libbsd seems to only be for `msys`, with no header files or binaries for non-CYGWIN like systems.

In general if you're unable to compile something in msys you should look and see if there's a `-devel` version, a fast way to check is `pacman -Ss <package>`.

**Comment by iahunq** [comment]
> This is what I currently see:
> 
> ```
> $ omake -f GNUmakefile
> Error GNUmakefile(36): No rule to make target 'src/cpdup.o'
> Error GNUmakefile(36): No rule to make target 'src/hclink.o'
> Error GNUmakefile(36): No rule to make target 'src/hcproto.o'
> Error GNUmakefile(36): No rule to make target 'src/md5.o'
> Error GNUmakefile(36): No rule to make target 'src/misc.o'
> ```

To be more clear. This is the result when I run `omake -f GNUmakefile` on a modified `GNUmakefile` that was edited to remove anything I found could cause problems for `omake` including `$(shell ...)`:

```
PROG=		cpdup
MAN=		cpdup.1
SRCS=		$(wildcard src/*.c)
OBJS=		$(SRCS:.c=.o)
DISTFILES=	GNUmakefile LICENSE README.md src $(MAN)
DISTFILES+=	BACKUPS PORTING

CFLAGS=		-O -pipe -std=c99 -pedantic
CFLAGS+=	-Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 \
		-Wwrite-strings -Wcast-qual -Wcast-align
#CFLAGS+=	-Wduplicated-cond -Wduplicated-branches \
		-Wrestrict -Wnull-dereference \
#CFLAGS+=	-Wconversion

#CFLAGS+=	$(shell pkg-config --cflags openssl)
#LIBS+=		$(shell pkg-config --libs   openssl)

#OS?=		$(shell uname -s)
#ifeq ($(OS),FreeBSD)
#CFLAGS+=	-D_ST_FLAGS_PRESENT_
#else ifeq ($(OS),Linux)
CFLAGS+=	-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64
#CFLAGS+=	$(shell pkg-config --cflags libbsd-overlay)
#LIBS+=		$(shell pkg-config --libs   libbsd-overlay)
#endif

PREFIX?=	/usr/local
MAN_DIR?=	$(PREFIX)/share/man

TMPDIR?=	/tmp
RPMBUILD_DIR?=	$(TMPDIR)/$(PROG)-rpmbuild
ARCHBUILD_DIR?=	$(TMPDIR)/$(PROG)-archbuild

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(PROG) $(OBJS)

.PHONY: all

```

This makefile is very normal, isn't it?

**Comment by chuggafan** [comment]
OHHHHH I think I see what's wrong there, I think we might not support the alternate `patsubst` syntax, https://www.gnu.org/software/make/manual/html_node/Text-Functions.html

I think that can be brought out into its own issue...

**Comment by LADSoft** [comment]
when I run omake on your make file I get this, which is pretty much what I expect.   I will note that the src/ thing was one of the previous bugs that I had fixed...

```
        \orangec\bin\occ -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 -Wwrite-strings -Wcast-qual -Wcast-align -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -c src\cpdup.c
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Error src\cpdup.h(8): Could not open  <sys/file.h>  for input
Error src\cpdup.h(21): Could not open  <dirent.h>  for input
Error src\cpdup.h(23): Could not open  <pwd.h>  for input
Error src\cpdup.h(24): Could not open  <fnmatch.h>  for input
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(66):  Syntax error: ; expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(67):  Syntax error: ; expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(68):  Syntax error: ; expected
Error(101)    C:\OrangeC\src\occparse\temp\cpdup\src\hclink.h(49):  Function parameter expected
Error(101)    C:\OrangeC\src\occparse\temp\cpdup\src\hclink.h(58):  Function parameter expected
Warning(482)  C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(98):  Missing type specifier for identifier 'DIR'
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(99):  Syntax error: ) expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(100):  Syntax error: ) expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(114):  Syntax error: ) expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(115):  Syntax error: ) expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(129):  Syntax error: ) expected
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(130):  Syntax error: ) expected
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(191):  Undefined symbol 'SIGPIPE'
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(194):  Undefined symbol 'opterr'
Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(195):  Call to function 'getopt' without a prototype
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(206):  Undefined symbol 'optarg'
Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(217):  Unreachable code
Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(222):  Type mismatch in parameter 'str' in call to 'getbool'
Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(225):  Type mismatch in parameter 'str' in call to 'getbool'
Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(228):  Call to function 'setlinebuf' without a prototype
Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(229):  Call to function 'setlinebuf' without a prototype
Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(255):  Type mismatch in parameter 'str' in call to 'getbool'
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(273):  Undefined symbol 'optopt'
Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(275):  Unreachable code
Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(279):  Unreachable code
Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(283):  Unreachable code
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(286):  Undefined symbol 'optind'
Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(299):  Call to function 'geteuid' without a prototype
Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(417):  Undefined symbol 'optopt'
Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(419):  Unreachable code
Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(544):  Syntax error: ) expected
Error(147)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(545):  Expression syntax error
Error(111)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(761):  Argument list too long in call to 'xlink'
Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(813):  Call to function 'S_ISLNK' without a prototype
Error(111)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(1166):  Argument list too long in call to 'xrename'
Error(  1)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(1166):  Too many errors or warnings

Error <builtins>(2): commands returned error code 1
``

**Comment by LADSoft** [comment]
@chuggafan I think omake should be able to handle the alternate patsubst syntax

**Comment by iahunq** [comment]
> when I run omake on your make file I get this, which is pretty much what I expect. I will note that the src/ thing was one of the previous bugs that I had fixed...
> 
> ```
>         \orangec\bin\occ -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 -Wwrite-strings -Wcast-qual -Wcast-align -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -c src\cpdup.c
> occ (OrangeC) Version 6.0.70.2
> Copyright (C) LADSoft 2006-2023
> Error src\cpdup.h(8): Could not open  <sys/file.h>  for input
> Error src\cpdup.h(21): Could not open  <dirent.h>  for input
> Error src\cpdup.h(23): Could not open  <pwd.h>  for input
> Error src\cpdup.h(24): Could not open  <fnmatch.h>  for input
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(66):  Syntax error: ; expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(67):  Syntax error: ; expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.h(68):  Syntax error: ; expected
> Error(101)    C:\OrangeC\src\occparse\temp\cpdup\src\hclink.h(49):  Function parameter expected
> Error(101)    C:\OrangeC\src\occparse\temp\cpdup\src\hclink.h(58):  Function parameter expected
> Warning(482)  C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(98):  Missing type specifier for identifier 'DIR'
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(99):  Syntax error: ) expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(100):  Syntax error: ) expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(114):  Syntax error: ) expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\hcproto.h(115):  Syntax error: ) expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(129):  Syntax error: ) expected
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(130):  Syntax error: ) expected
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(191):  Undefined symbol 'SIGPIPE'
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(194):  Undefined symbol 'opterr'
> Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(195):  Call to function 'getopt' without a prototype
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(206):  Undefined symbol 'optarg'
> Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(217):  Unreachable code
> Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(222):  Type mismatch in parameter 'str' in call to 'getbool'
> Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(225):  Type mismatch in parameter 'str' in call to 'getbool'
> Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(228):  Call to function 'setlinebuf' without a prototype
> Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(229):  Call to function 'setlinebuf' without a prototype
> Error(114)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(255):  Type mismatch in parameter 'str' in call to 'getbool'
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(273):  Undefined symbol 'optopt'
> Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(275):  Unreachable code
> Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(279):  Unreachable code
> Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(283):  Unreachable code
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(286):  Undefined symbol 'optind'
> Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(299):  Call to function 'geteuid' without a prototype
> Error( 18)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(417):  Undefined symbol 'optopt'
> Warning(193)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(419):  Unreachable code
> Error( 11)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(544):  Syntax error: ) expected
> Error(147)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(545):  Expression syntax error
> Error(111)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(761):  Argument list too long in call to 'xlink'
> Warning(110)  C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(813):  Call to function 'S_ISLNK' without a prototype
> Error(111)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(1166):  Argument list too long in call to 'xrename'
> Error(  1)    C:\OrangeC\src\occparse\temp\cpdup\src\cpdup.c(1166):  Too many errors or warnings
> 
> Error <builtins>(2): commands returned error code 1
> ``
> ```

Something weird happened. I still got the same error with the latest Orange C from Github Actions:

```
$ omake -f GNUmakefile
Error GNUmakefile(36): No rule to make target 'src/cpdup.o'
Error GNUmakefile(36): No rule to make target 'src/hclink.o'
Error GNUmakefile(36): No rule to make target 'src/hcproto.o'
Error GNUmakefile(36): No rule to make target 'src/md5.o'
Error GNUmakefile(36): No rule to make target 'src/misc.o'
```

But with the Orange C version I compiled myself, I got the same error message as you. Weird, isn't it?

**Comment by iahunq** [comment]
It's even more weird. I got the same error message I posted with both the modified and unmodified `GNUmakefile` if I used the latest Orange C from Github Actions. If I used the Orange C I compiled myself, the error message for the unmodified `GNUmakefile` is:

```
$ omake -f GNUmakefile2
        C:/OrangeC/bin/occ -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2 -Wwrite-strings -Wcast-qual -Wcast-align /c: /c: Is a directory -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 /c: /c: Is a directory -c src/cpdup.c
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Unknown switch '-:'
occparse (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023

Usage: occparse [options] [@response file] files
Error <builtins>(2): commands returned error code 1
```

This is the same error message as what on the opening of this issue.

Btw, do you notice on the command line of `occ` there is `-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64`? They shouldn't be there. They should be added only if the platform is Linux. This means `ifeq ($(OS),Linux)` evaluated to true. This is so wrong!

**Comment by LADSoft** [comment]
ok i'm fixing a problem with an 'if' on the same line as an 'else;' in the next push.

As far as your other problem,    i dug some more and was able to duplicate what you've got; it seems like you are missing a file.    There should be a file 'builtins.mak' in c:\orangec\bin.   It should have been copied there as part of the build...    it defines basic rules omake can use to compile and link when the makefile doesn't have them (and this one doesn't).    if you need to get it manually for some reason take the file 'target.mak' in the omake directory and rename it to 'builtins.mak' in the orangec\bin directory...    but it looks like from the dump you gave me there may be a slight incompatibility in that file so I may make some edits...

**Comment by iahunq** [comment]
With the latest Github Actions build, the only thing I see is still:

```
$ omake -f GNUmakefile2
Error GNUmakefile2(36): No rule to make target 'src/cpdup.o'
Error GNUmakefile2(36): No rule to make target 'src/hclink.o'
Error GNUmakefile2(36): No rule to make target 'src/hcproto.o'
Error GNUmakefile2(36): No rule to make target 'src/md5.o'
Error GNUmakefile2(36): No rule to make target 'src/misc.o'
```

Something is wrong with the Github Actions build? Why don't it have a `builtins.mak` file?

**Comment by iahunq** [comment]
If you look at the distribution of GNU make you will see it doesn't ship with any so-called `builtins`. It works out of the box. Unlike BSD make that is pretty much useless without a collection of `mk-files`. Does the `builtins` get embedded into the GNU make binary itself? I don't know! But I personally against the way BSD make is doing. If you don't know what BSD make is, you could have a taste of it here:

https://packages.msys2.org/package/mingw-w64-x86_64-bmake?repo=mingw64

**Comment by LADSoft** [comment]
hm ok, I think I see what is wrong with the build but I'll just do what you suggested and build it in to omake.    Tomorrow night though :)
