### ISSUE TITLE
Build will fail if the source directory is nested too deep

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#928]
For example, this will fail: `C:\msys64\home\Administrator\OrangeC`.

But this `C:\OrangeC` or `C:\Work\OrangeC` will work.

I'm talking about building with `omake` and Windows Command Prompt. Anyone could reproduce this?

**Comment by GitMensch** [comment]
Haven't checked but when I'm testing for long paths in my project I never test with entries shorter than 256 character positions.

For this issue it would help if you can say **what** actually fails an **how**.

**Comment by chuggafan** [comment]
$5 says fundamentally the issue is nested paths, It's why I place OrangeC in the `C:\` directory, buidpaths for things like the clibs blast past 256 characters.

**Comment by iahunq** [comment]
> Haven't checked but when I'm testing for long paths in my project I never test with entries shorter than 256 character positions.
> 
> For this issue it would help if you can say **what** actually fails an **how**.

This is about building Orange C itself. If the source directory is nested too deep, it will fail to copy something I don't know. Please correct me if I'm wrong but I found `omake` will proceed to the next target even if the current target has errors (and thus considered as failed). GNU make on the other hand will stop if there is error. What is printed on the screen is too fast and too much for me to keep track of what is really failed.

The result is even you will have a look to be normal Orange C distribution with all of the needed binaries placed on `OrangeC\bin` but you can't use this Orange C distribution to compile programs. You will see error message like this:

```
$ occ test.cpp
occ (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023
Error: Input file 'c0xpe.o' does not exist.
Error: Library 'climp.l' does not exist or is not a library
Error: Library 'clwin.l' does not exist or is not a library
Error: Undefined External '_CatchCleanup(void*)' in module test.cpp
Error: Undefined External 'std::__basic_string_common<bool=1>::__basic_string_common()' in module test.cpp
Error: Undefined External 'std::__basic_string_common<bool=1>::~__basic_string_common()' in module test.cpp
Error: Undefined External 'std::basic_ostream<char, char_traits<char>>::sentry::sentry(basic_ostream<char, char_traits<char>>&)' in module test.cpp
Error: Undefined External 'std::basic_ostream<char, char_traits<char>>::sentry::~sentry()' in module test.cpp
Error: Undefined External 'std::basic_string<char, char_traits<char>, allocator<char>>::~basic_string()' in module test.cpp
Error: Undefined External 'std::basic_string<char, char_traits<char>, allocator<char>>::__init(unsigned int, char)' in module test.cpp
Error: Undefined External 'std::basic_string<char, char_traits<char>, allocator<char>>::__rep::__rep()' in module test.cpp
Error: Undefined External 'std::ctype<char>::id' in module test.cpp
Error: Undefined External 'std::cout' in module test.cpp
Error: Undefined External 'std::ios_base::__set_badbit_and_consider_rethrow()' in module test.cpp
Error: Undefined External 'std::ios_base::clear(unsigned int)' in module test.cpp
Error: Undefined External 'std::ios_base::getloc() const ' in module test.cpp
Error: Undefined External 'std::locale::~locale()' in module test.cpp
Error: Undefined External 'std::locale::use_facet(std::locale::id&) const ' in module test.cpp
Error: Undefined External '__cppexceptionhandle' in module test.cpp
Error: Undefined External 'strlen' in module test.cpp
        20 Errors, 0 Warnings
        Errors encountered, not creating output file
```

**Comment by iahunq** [comment]
> $5 says fundamentally the issue is nested paths, It's why I place OrangeC in the `C:\` directory, buidpaths for things like the clibs blast past 256 characters.

Is it a limitation of the operating system or `omake` itself?

**Comment by chuggafan** [comment]
This is a fundamental issue with Windows, the 256 PATH limit dates back to DOS 3.1, it's possible to extend the PATH but I don't think occ or omake fully support it since quite frankly it's off by default.

**Comment by LADSoft** [comment]
yeah the toolchain uses the old path limit of 260 chars...   I've never looked to see what it takes to extend beyond that...

**Comment by chuggafan** [comment]
The truth is that in order to do so you need to do what's in the first link: edit the registry.

For a lot more people it's the default in later editions of windows, but it's still not common.

**Comment by iahunq** [comment]
Please correct me if I'm wrong. But GNU Make and Ninja seem to have no such limitation and I don't have to do any registry hacks. I have compiled projects using CMake with both Ninja generator and "MSYS Makefiles"/"MinGW Makefiles" generator. They are very large projects, much larger than OrangeC, and I have no problems building them. Of course I'm using MSYS2 (MINGW64)/MSYS2(UCRT64) and sometimes MSYS2 (CLANG64) but not the Windows Command Prompt.

**Comment by chuggafan** [comment]
> Please correct me if I'm wrong. But GNU Make and Ninja seem to have no such limitation 

They do, you haven't encountered them yet, "large" does not mean "heavily nested with large folder names".

**Comment by iahunq** [comment]
OK. Let's consider it a limitation of Windows. But it should be documented on BUILD.md @LADSoft

**Comment by iahunq** [comment]
Since `omake` is already working fine on MSYS2, I think I should stop here. Feel free to reopen the issues about using `mingw32-make` to build Orange C if you want to continue to work on it.
