### ISSUE TITLE
Support using of `mingw32-make` to build Orange C on Windows Command Prompt

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#931]
Use this command to redirect `stdout` and `stderr` to the file `mingw32-make-cmd.log`:

`mingw32-make fullbuild COMPILER=MINGW64 WITHDEBUG=YES > mingw32-make-cmd.log 2>&1`

**Comment by iahunq** [comment]
I tried to add `ORANGEC_ONLY=YES` to `mingw32-make` but it doesn't work.

**Comment by LADSoft** [comment]
hm the makefile has a line that checks for the environment variable MSYSTEM, and if it exists that particular part of the build is supposed to be skipped...    seemed to work for me when I tested it..   i will test again...

**Comment by iahunq** [comment]
> hm the makefile has a line that checks for the environment variable MSYSTEM, and if it exists that particular part of the build is supposed to be skipped... seemed to work for me when I tested it.. i will test again...

`MSYSTEM` is only defined on MSYS2. This issue is about building with `mingw32-make` on Windows Command Prompt.
