### ISSUE TITLE
What do you think about adding something like `osed`?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#934]
You already have `ogrep` 😄

**Comment by GitMensch** [comment]
Me neither, but I wouldn't complain if @iahunq provides a PR to add it.

**Comment by iahunq** [comment]
GNU sed has a standalone build for Windows if anyone interested:

https://github.com/mbuilov/sed-windows

**Comment by LADSoft** [comment]
i haven't forgotten this...  i may add gnu sed at some point but not sure yet how to make a .configure script for it so I can get all the sources I need.    Tried using autoconf but it generates errors, and then the script it generates doesn't work...

I also think it may not quite be standalone; it seems to use various unix packages...

**Comment by iahung2** [comment]
> i haven't forgotten this... i may add gnu sed at some point but not sure yet how to make a .configure script for it so I can get all the sources I need. Tried using autoconf but it generates errors, and then the script it generates doesn't work...
> 
> I also think it may not quite be standalone; it seems to use various unix packages...

Why? Why do you need to add gnu sed to Orange C? There is already a standalone version of gnu sed that available for everyone!

https://github.com/mbuilov/sed-windows

Note: `ogrep` is your own implementation of `grep` then `osed` is your own implementation of `sed`, this is what I mean when I suggested you to add `osed`; and other people were right; there is no need for a homegrown implementation of `sed`; `sed` is more complex then `grep` and people can always use gnu sed if they have a need for `sed`.
