### ISSUE TITLE
`HAVE_UNISTD_H` is misleading

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#935]
Yeah, I know we are not using `autotools` so `HAVE_UNISTD_H` will not be defined automatically but it's something hard coded by you on `gcc-linux.mak`. But as I said on #925, MinGW-w64 also has `unistd.h` so `HAVE_UNISTD_H` is really misleading. You should choose a better name.

**Comment by iahunq** [comment]
> It isn't misleading as long as it is _only_ used for the include of unistd.h, which is the actual purpose of that macro, and "ok" if code that needs functions/types defined in there is guarded with that macro, too.
> 
> It should not be used as a way to check for posix-environments, win32, ...
> 
> So... where do you see the problem in it use?

You already got it. The problem is `HAVE_UNISTD_H` is not only used for the include of `unistd.h` but also as a substitute for `__linux__`. Please have a look at https://github.com/LADSoft/OrangeC/blob/923d7110186de05e643511af18226be4d41e60d4/src/clocc/clocc.cpp#L644 and https://github.com/LADSoft/OrangeC/blob/d961b28338c2cedc4925f1d15a4d903d03fa785c/src/gccocc/gccocc.cpp#L422. 

Related issue: #936

**Comment by iahunq** [comment]
My thoughts is `HAVE_UNISTD_H` should be for the include of `unistd.h` only. You should introduce another macro and set that macro manually on makefiles. This will give you more flexibility. Btw, some compilers also defined `WIN32` so you can't use that macro.

**Comment by GitMensch** [comment]
> Btw, some compilers also define `WIN32` so you can't use it.

most (if not all) define `_WIN32` - and for those that don't we could add it on the makefile or from outside (CPPFLAGS). As noted cygwin commonly does not behave anything like win32 and therefore does not define that macro (and you should not define it with Cygwin either), if "one of those" then best use both macros.

**Comment by iahunq** [comment]
> > Btw, some compilers also define `WIN32` so you can't use it.
> 
> most (if not all) define `_WIN32` - and for those that don't we could add it on the makefile or from outside (CPPFLAGS). As noted cygwin commonly does not behave anything like win32 and therefore does not define that macro (and you should not define it with Cygwin either), if "one of those" then best use both macros.

Yes, I know most compilers defined `_WIN32`. But some compilers also defined `WIN32`, `WIN64`, `__WIN32__`,... @LADSoft want to use `WIN32` so I tell him this macro could be already defined by some compilers.

> We could introduce another define like WIN32 that isn't compiler generated

**Comment by LADSoft** [comment]
so it sounds like what I need to do is introduce a new preprocessor macro like WINDOWS_PLATFORM.   HAVE_UNISTD_H would still be used for its intended purpose of including unistd.h, but, if it isn't defined WINDOWS_PLATFORM would be defined, and would take over things like the ones in gccocc, clocc, semaphores.h, and any other place where I'm using HAVE_UNISTD_H to determine the platform rather than the specific header configuration of unistd.h.    Does that sound reasonable?

**Comment by iahunq** [comment]
> so it sounds like what I need to do is introduce a new preprocessor macro like WINDOWS_PLATFORM. HAVE_UNISTD_H would still be used for its intended purpose of including unistd.h, but, if it isn't defined WINDOWS_PLATFORM would be defined, and would take over things like the ones in gccocc, clocc, semaphores.h, and any other place where I'm using HAVE_UNISTD_H to determine the platform rather than the specific header configuration of unistd.h. Does that sound reasonable?

@GitMensch I don't think any compilers out there defined `WINDOWS`? `WINDOWS_PLATFORM` is too verbose.

**Comment by GitMensch** [comment]
https://github.com/cpredef/predef/blob/master/OperatingSystems.md lists only `__WINDOWS__`. But verbosity is not a problem, _if_ a new define is added I'd possibly go with `WINDOWS_PLATFORM` or `TARGET_OS_WINDOWS` or similar.
