### ISSUE TITLE
`src/clibs/platform/win32/makefile`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#937]
`ifndef MSYSTEM` should be replaced with `ifneq "$(ORANGEC_ONLY)" "YES"`. This will fix #931

**Comment by LADSoft** [comment]
yeah if you get to the point you feel comfortable making small non-intrusive edits like this one you can always do a pull request with it, that might make it just a little easier on me.    But don't worry about it if you don't feel like doing that...   I'll get this eventually....

**Comment by iahunq** [comment]
> just insert [skip_ci] in the commit log and appveyor should ignore that

What is the commit log? The commit message by `git -m`?

**Comment by GitMensch** [comment]
yes, or the one that you specify via GH "edit" directly when clicking on ok/suggest change

**Comment by iahunq** [comment]
@LADSoft Please incorporate this tiny change and I will close all issues about using `mingw32-make` to build Orange C. As it's currently working fine and only the zipped files creation part is not working, and it seems you don't want to work on this any further. I agreed with you as a compiler developer it's more interested to work on the compiler itself rather than problems like this.

**Comment by LADSoft** [comment]
Sorry I never commented on this....    when I looked at it I found that using 'ORANGEC_ONLY=YES' on the command line suppresses this, I can't really change that because it would affect the appveyor builds.   But I think you can do  'omake zip' after the build to create them seperately if you really want them...

**Comment by iahunq** [comment]
> Sorry I never commented on this.... when I looked at it I found that using 'ORANGEC_ONLY=YES' on the command line suppresses this, I can't really change that because it would affect the appveyor builds. But I think you can do 'omake zip' after the build to create them seperately if you really want them...

I don't understand what you said. The whole point of this issue is:

> `ifndef MSYSTEM` should be replaced with `ifneq "$(ORANGEC_ONLY)" "YES"`. This will fix #931

`ifndef MSYSTEM` is an ugly hack that will only work on MSYS2. Changing it to `ifneq "$(ORANGEC_ONLY)" "YES"` will work on both MSYS2 and Windows Command Prompt with the option `ORANGEC_ONLY=YES` added to `mingw32-make` command line.

**Comment by LADSoft** [comment]
changing that line the way you want will break the appveyor build as that flag also turns off zip file generation and we don't want the zip files for the first part of the appveyor build but we do want occil support projects to be built ...   leave this open and I will give some thought into restructuring the builds in the near future...

**Comment by iahunq** [comment]
> changing that line the way you want will break the appveyor build as that flag also turns off zip file generation and we don't want the zip files for the first part of the appveyor build but we do want occil support projects to be built ... leave this open and I will give some thought into restructuring the builds in the near future...

OK, I got it.

**Comment by iahunq** [comment]
> changing that line the way you want will break the appveyor build as that flag also turns off zip file generation

Please note that on #938 it failed to correctly create the zipped files even if no `ORANGEC_ONLY=YES` added. See https://github.com/LADSoft/OrangeC/issues/908#issuecomment-1640892500. Summary:

> With the command `mingw32-make fullbuild COMPILER=MINGW64 WITHDEBUG=YES > mingw32-make-msys2.log 2>&1` only the zipped binaries file was created (missing zipped sources).

**Comment by iahunq** [comment]
> changing that line the way you want will break the appveyor build as that flag also turns off zip file generation and we don't want the zip files for the first part of the appveyor build but we do want occil support projects to be built ... leave this open and I will give some thought into restructuring the builds in the near future...

@LADSoft Why don't you add a new option called `WITHOUT_OCCIL`? On `src/clibs/platform/win32/makefile` you simply have to change `ifndef MSYSTEM` to `ifneq "$(WITHOUT_OCCIL)" "YES"`. This will not break the CI builds and will also fix #931.
