### ISSUE TITLE
Decoupling Orange C from MSYS2

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#939]
> It was never my intention to fully support msys2 in the way you want me to...

@LADSoft I'm very sorry because I caused a mess for you. I know Orange C applications are never designed to run on MSYS2. Apart from the `makefiles` that are adapted to allow the building of Orange C itself on MSYS2, the hacks for various Orange C applications for them to work on MSYS2 should be removed. I'm sorry again.

**Comment by LADSoft** [comment]
it is no problem, sometimes I'm a little over eager to make fixes lol...   i did eventually revert the changes related to bash...
