### ISSUE TITLE
omake should handle GNU make's `--jobserver-auth=` switch

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#942]
Related issue: #941

https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html

**Comment by chuggafan** [comment]
It does, I don't think it properly is using it though... This is back when I was moving everything over to the new JobServer implementation.

(P.S. in this case you wanted to link the WINDOWS-Jobserver link, as on MINGW64 it actually uses semaphores because semaphores on windows are much better than on POSIX)

**Comment by iahunq** [comment]
Please see the output of `omake` on #941:

```
$ omake
        gmake -f GNUmakefile -j:1 --jobserver-auth=OMAKE3172
sh: line 1: gmake: command not found

Error makefile(2): commands returned error code 127
```

Do you think the value of `--jobserver-auth` (`OMAKE3172`), that is automatically filled by `omake`, is something valid?

**Comment by iahunq** [comment]
This value changed with each runs of `omake`. So it seems to be the process id of `omake`. This time it's `OMAKE2192`.

**Comment by chuggafan** [comment]
> Do you think the value of --jobserver-auth (OMAKE3172), that is automatically filled by omake, is something valid?

Please read the relevant documentation for the platform, while I understand that GNU make on Linux uses a POSIX jobserver, on Windows, it uses the Windows semaphore based jobserver.
https://www.gnu.org/software/make/manual/html_node/Windows-Jobserver.html

**Comment by iahunq** [comment]
> > Do you think the value of --jobserver-auth (OMAKE3172), that is automatically filled by omake, is something valid?
> 
> Please read the relevant documentation for the platform, while I understand that GNU make on Linux uses a POSIX jobserver, on Windows, it uses the Windows semaphore based jobserver. https://www.gnu.org/software/make/manual/html_node/Windows-Jobserver.html

OK, I got it.
