### ISSUE TITLE
FreeDOS question

### ISSUE THREAD

**Issue by lodhia** [LADSoft/OrangeC#951]
Hello,

I just installed the Orange C Compiler Suite v6.0.17.1 on my FreeDOS 1.3 install. I restarted the computer as the installer requested, and after boot it says HXLdr32 V1.12 Installed, since I allowed the installer to modify my autoexec file.

 Whenever I run occ on a simple test.c file (consisting of just int main() { return(0) };) I get

dpmild32: import not found: Acquire SRWLockExclusive
dpmild32: import not found: Acquire FlsAlloc
...

and  a bunch of other errors like that which concludes with

dpmild32: file KERNEL32.DLL
dpmild32: C:\orangec\bin\dkrnl32.dll: cannot resolve imports

Pardon in advance if this is an obvious error on my part.

**Comment by LADSoft** [comment]
I haven't really been supporting DOS for several years...   it would be very much broken at this point.

**Comment by GitMensch** [comment]
What version of OrangeC should likely work with DOS?
Is DOS support more likely to be restored or to be removed?

**Comment by LADSoft** [comment]
apparently it got broken when I switched the runtime library over to use RPMALLOC...   I don't know what version that switch occurred in though.

I'm likely to remove support at some point, there just isn't any interested in that platform and I've got lots other stuff to do...

**Comment by lodhia** [comment]
Thanks for letting me know!
