### ISSUE TITLE
Request GetThreadDescription, SetThreadDescription (processthreadsapi.h functionality)

### ISSUE THREAD

**Issue by johnsonjh** [LADSoft/OrangeC#954]
* SetThreadDescription(): https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription

* GetThreadDescription(): https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription

* Example: https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2022#set-a-thread-name-by-using-setthreaddescription

[]()
[]()

It would be great if you would consider adding this functionality.

**Comment by LADSoft** [comment]
thanks!   will update the import list for kernel32.dll in the next push.
