### ISSUE TITLE
FR: provide a tool to list symbols from occ generated object files similar to nm

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#97]
Given

```c
int main () {
	return 12;
}
```

and `gcc -c conftest.c` you can do

~~~
$ nm.exe conftest.o
00000000 b .bss
00000000 d .data
00000000 r .eh_frame
00000000 r .rdata$zzz
00000000 t .text
         U ___main
00000000 T _main
~~~

but as `nm` from GNU Binutils doesn't know the format occ uses

~~~
$ occ -! -c conftest.c
$ nm.exe conftest.o
conftest.o: File format not recognized
~~~

I *assume* OrangeC has a similar tool and I just didn't see it when glancing at https://orangec.readthedocs.io/en/latest/Tools/

Please advise how to replace `nm` when using `occ`.

**Comment by LADSoft** [comment]
there is not currently a convenient tool but it isn't too hard to do so I'll see what I can do later on...

**Comment by GitMensch** [comment]
For a new implementation it looks wise to check both the [command line options of `nm`](https://linux.die.net/man/1/nm) and its output format.

**Comment by GitMensch** [comment]
Maybe also provide features of [`ojbdump`](https://linux.die.net/man/1/objdump)...

**Comment by GitMensch** [comment]
Impressive how fast the issue number gets down!

Just wanted to note that this is the missing bit in testing OrangeC with MPIR [building and runnung its test suite with MSYS] (a "piece" of software that already showed more than one compiler bug in the past).

**Comment by LADSoft** [comment]
As per your note that you could use this sooner rather than later I started working on this last weekend...   got the basic skeleton developed.   Just have to add the actual functionality but I don't see that as difficult as the file I/O is already in libraries...   should be able to get something going this weekend if you don't flood me with other issues in the meantime ;)

**Comment by GitMensch** [comment]
FIXME: There is currently no doc entry for `onm.exe`.

**Comment by GitMensch** [comment]
More important: is not part of the CI-build assets, maybe not part of the installer, too (the install script was what pointed me to the "doc" directory for the other tools)
