### ISSUE TITLE
The links on `read the docs` page is broken

### ISSUE THREAD

**Issue by tqo50396** [LADSoft/OrangeC#995]
For example, on the article for OCC: https://orangec.readthedocs.io/en/latest/occ/OCC/

If you click on the `Command Line` link, it will redirect you to:

https://orangec.readthedocs.io/en/latest/occ/OCC/OCC%20Command%20Line.md

This link is invalid.

If you navigate using `Occ` on the navbar, it will redirect you to the correct link:

https://orangec.readthedocs.io/en/latest/occ/OCC%20Command%20Line/

All of the links on `read the docs` are like that.

**Comment by LADSoft** [comment]
yeah they had updated the readthedocs site; I had already made #973 to fix issues with it but hadn't actually done the work yet.   Based on your other feedback I'm likely to switch the whole thing to the github wiki instead though.   I'm closing this as a duplicate.

**Comment by GitMensch** [comment]
actually you did close it as completed, there is another button (pull-down) to mark it as duplicate or unplanned (can be post-adjusted, too)

**Comment by LADSoft** [comment]
fixed as part of #1036
